[베르] 1,2단계 쇼핑 장바구니 제출합니다.
woowacourse/android-shopping-cart pull request #15
Opened 2023-05-11 08:50 UTC by SeongHoonC

안녕하세요. 리뷰어님! 저는 베르입니다.

쇼핑 장바구니 미션 리뷰 잘부탁드립니다!

2023-05-12 05:00 UTC, namjackson commented
테스트 코드를 추가로 작성해주셔도 좋을거같아요!

2023-05-12 05:00 UTC, namjackson requested changes
안녕하세요 베르! 
1~2단계 미션 고생하셨어요! 
잘 구현해주셨네요,
몇가지 고민할법한 포인트들 코멘트로 남겼으니, 확인해주세요!

2023-05-12 13:25 UTC, SeongHoonC commented on app/src/main/java/woowacourse/shopping/presentation/cart/CartAdapter.kt
> +        notifyDataSetChanged()
전체 아이템을 다 변경해주는 것은 비효율적이기 때문에 RecyclerView Adapter 는 다양한 notify 를 제공합니다. 데이터를 갈아끼워주기 위해서  notifyDataSetChanged() 대신에 해당되는 item, range 만 변경하도록 하겠습니다!

2023-05-13 05:12 UTC, SeongHoonC commented on app/src/main/java/woowacourse/shopping/presentation/productlist/ProductListPresenter.kt
> +    }
view 의 adapter 를 초기화 할 때 아이템을 넣어주려고 했습니다. 
상품을 업데이트 하는 것에 차이가 있어서 생각해서 분리하였습니다. 
하지만 adapter 초기화는 view 에서 하고 아이템만 업데이트 해주면 되기 때문에 변경하겠습니다!

2023-05-13 05:15 UTC, SeongHoonC commented on app/src/main/java/woowacourse/shopping/presentation/productlist/ProductListActivity.kt
> +        presenter.updateRecentProducts()
다른 상품 detail 액티비티로 갔다가 돌아오면 최근 본 상품이 업데이트 되어야 한다고 생각했습니다! 그래서 onCreate 에서 하지 않고 onStart 에서 호출하였습니다!

2023-05-13 08:40 UTC, SeongHoonC commented on app/src/main/java/woowacourse/shopping/presentation/cart/viewholder/CartItemViewHolder.kt
> +    private val productModel get() = _productModel!!
deleteItem 람다를 viewHolder 가 create 될 때만 사용하고 이후 bind 할 때는 재사용하기 위해서 저장하고 있습니다!

2023-05-13 09:16 UTC, SeongHoonC commented on app/src/main/java/woowacourse/shopping/presentation/cart/CartAdapter.kt
> +        notifyDataSetChanged()
위와 같이 생각했었지만 페이지를 넘기는 구조에서는 전체 데이터를 바꿔주어야 하지 않을까요? 확인해보니 notifyDataSetChanged 을 사용할 때는 viewHolder 를 5개만 생성하지만 notifyItemRangeChanged 는 10개 정도를 생성합니다. 재사용 관점에서도 notifyDataSetChanged 가 유리하다고 판단됩니다!

2023-05-13 09:23 UTC, SeongHoonC commented on app/src/main/java/woowacourse/shopping/presentation/productlist/product/ProductListAdapter.kt
> +        notifyDataSetChanged()
추가되는 것을 알리기 위해 notifyItemRangeInserted() 를 사용하겠습니다!

2023-05-15 08:31 UTC, namjackson approved these changes
안녕하세요 베르! 
피드백 적용 잘해주셨네요,
몇가지 추가적인 코멘트 남겼으니, 확인해주세요!
코멘트는 다음 미션 진행하면 적용해주세요!

2023-05-15 08:31 UTC, namjackson commented on app/src/main/java/woowacourse/shopping/presentation/cart/viewholder/CartItemViewHolder.kt
> +    private val productModel get() = _productModel!!
productModel 을 들고있기보단, ViewHolder 에서 현재 Position에 접근하면 어떨까요?

2023-05-15 08:31 UTC, merged

2023-05-15 23:26 UTC, SeongHoonC commented on domain/src/main/java/woowacourse/shopping/CartPages.kt
> +        return getCurrentProducts()
3, 4 단계를 구현하면서 고치도록 하겠습니다!

2023-05-15 23:44 UTC, SeongHoonC commented on app/src/test/java/woowacourse/shopping/presentation/productlist/ProductListPresenterTest.kt
> +        every { recentProductIdRepository.addRecentProductId(capture(productIdSlot)) } just runs
fake 는 리턴 결과를 확인할 경우에 사용하는 것, mock 은 중간 과정을 확인할 경우에 사용하는 것이라고 생각합니다.
presenter test 와 같이 반환값이 존재하지 않지만 중간에 인자로 어떤 것이 넘어갔는지 혹은 해당 메서드가 실행되었는지 확인하고 싶을 때 mock 을 써야한다고 생각합니다.

2023-05-15 23:48 UTC, SeongHoonC commented on app/src/test/java/woowacourse/shopping/presentation/productlist/ProductListPresenterTest.kt
> +        every { recentProductIdRepository.addRecentProductId(capture(productIdSlot)) } just runs
fake 를 주입하는 시점과 actual 값을 얻는 사이에 긴 과정이 있어 테스트 결과에 영향을 주는 것이 많아지는 경우.
기능 하나를 확인하기 위함인데 application test 처럼 비대해지는 경우에 중간을 끊어주는 역할로 사용할 수 있을 것 같습니다.