[뽀또] 1, 2단계 쇼핑 장바구니 제출합니다.
woowacourse/android-shopping-cart pull request #22
Opened 2023-05-11 08:53 UTC by hyunji1203

ㅇ

2023-05-12 04:17 UTC, vagabond95 requested changes
미션 진행동안 잘 부탁드려요~!

페이징을 직접 구현해주신 부분이 기억에 남습니다. 👍 
남긴 코멘트는, 해당 코멘트 지점외에도 비슷하게 적용될 수 있는 부분은 같이 확인 부탁드릴게요~!

2023-05-12 04:17 UTC, vagabond95 commented on app/src/main/res/layout/item_recent_viewed.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
중요한 부분은 아니지만 divider 같이 간단한 녀석은 `View` 로 선언해주셔도 무방합니다~!

2023-05-12 04:17 UTC, vagabond95 commented on app/src/main/res/layout/item_recent_viewed_product.xml
> +            type="woowacourse.shopping.model.ProductModel" />
필요한 모델을 잘 바인딩하여 활용해주셨네요 👍

2023-05-12 04:17 UTC, vagabond95 commented on app/src/main/res/layout/item_cart.xml
> +            name="cart_product"
요 녀석만 snake case 로 작성해주신 이유가 있을까요~?

2023-05-12 04:17 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/view/productlist/recentviewed/RecentViewedItemViewHolder.kt
> +        Glide.with(binding.root.context).load(product.imageUrl).into(binding.imgProduct)
image view 에 대한binding adapter 를 제공하고 내부에서  glide 처리를 해주도록 하여,
재사용성을 높혀봐도 좋겠습니다!

2023-05-12 04:17 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/view/productlist/ProductViewHolder.kt
> +sealed class ProductViewHolder(view: View) : RecyclerView.ViewHolder(view) {
seald class 활용 👍

2023-05-12 04:17 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/view/cart/CartActivity.kt
> +        supportActionBar?.title = "Cart"
actionBar 에 대한 로직을 묶는 함수로 제공해봐도 좋겠습니다 ㅎㅎ

2023-05-12 04:17 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/view/cart/CartActivity.kt
> +        binding.recyclerCart.adapter = CartAdapter(
layout manager 와 adapter 는 데이터가 넘어오기 전에 세팅해줘도 괜찮지 않을까요~?

2023-05-12 04:17 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/view/cart/CartActivity.kt
> +    }
어떤 함수를 notify 해줄지는 adapter 에 위임하고, 필요한 데이터만 넘겨주는 것은 어떨까요?

activity 가 adapter 에 대해 많은 것을 알고 있을 필요가 없을 것 같아요!

2023-05-12 04:17 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/view/cart/CartActivity.kt
> +                finish()
이러한 로직도 presenter 로 위임해주는 것은 어떨까요?

아무리 간단해보이는 로직이라도 view 는 ui 이벤트 이후는 책임지지 않는다는 원칙을 지켜보면 좋겠습니다 :)
간단해보이는 로직이 이후에는 간단해지지 않기도 하구요~!

2023-05-12 04:17 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/view/cart/CartItemViewHolder.kt
> +            binding.textPrice.text = binding.root.context.getString(R.string.korean_won, PriceFormatter.format(product.price))
이러한 price 포맷을 처리하는 TextView BindingAdapter 를 제공해봐도 좋겠네요~!

2023-05-12 04:17 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/view/productdetail/ProductDetailActivity.kt
> +    }
로직을 함수 단위로 분리해주면 가독성이 좀 더 확보딜 것 같아요!

2023-05-12 04:17 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/view/cart/CartPresenter.kt
> +        }
해당 코드의 중복을 제거해보는 것은 어떨까요?

2023-05-12 04:17 UTC, vagabond95 requested changes
미션 진행동안 잘 부탁드려요~!

페이징을 직접 구현해주신 부분이 기억에 남습니다. 👍 
남긴 코멘트는, 해당 코멘트 지점외에도 비슷하게 적용될 수 있는 부분은 같이 확인 부탁드릴게요~!

2023-05-13 18:22 UTC, hyunji1203 commented on app/src/main/res/layout/item_cart.xml
> +            name="cart_product"
카멜 케이스로 적었어야 했는데... 급해서 저렇게 적어버렸습니다..! 다시 카멜 케이스로 수정했습니다!

2023-05-13 18:30 UTC, hyunji1203 commented on app/src/main/java/woowacourse/shopping/view/cart/CartActivity.kt
> +        supportActionBar?.title = "Cart"
넵! 해당 로직을 별개의 함수로 분리했습니다~!

2023-05-13 18:35 UTC, hyunji1203 commented on app/src/main/java/woowacourse/shopping/view/productdetail/ProductDetailActivity.kt
> +    }
데이터를 갖고 오는 부분과 뷰에 bind 해주는 부분을 함수 단위로 분리해 적용시켰습니다!

2023-05-13 18:43 UTC, hyunji1203 commented on app/src/main/java/woowacourse/shopping/view/cart/CartPresenter.kt
> +        }
해당 코드를 `updateCartItems`로 묶어 중복을 제거했습니다!

2023-05-13 18:53 UTC, hyunji1203 commented on app/src/main/res/layout/item_recent_viewed.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
아하 넵!

2023-05-14 08:56 UTC, hyunji1203 commented on app/src/main/java/woowacourse/shopping/view/cart/CartActivity.kt
> +        binding.recyclerCart.adapter = CartAdapter(
넵! 맞습니다!
그래서 아예 xml의 RecyclerView 의 속성에 `            app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
`을 추가해 미리 세팅 될 수 있도록 변경하였습니다~!

2023-05-14 09:36 UTC, hyunji1203 commented on app/src/main/java/woowacourse/shopping/view/cart/CartActivity.kt
> +    }
넵 activity가 많은 정보를 알고 있지 않도록 notify를 `CartAdapter` 안으로 넣고 Activity에서 데이터를 받아 작동하도록 수정하였습니다!

2023-05-14 10:00 UTC, hyunji1203 commented on app/src/main/java/woowacourse/shopping/view/cart/CartActivity.kt
> +                finish()
**//CartActivity**
```
override fun onOptionsItemSelected(item: MenuItem): Boolean {
        presenter.handleNextStep(item.itemId)
        return super.onOptionsItemSelected(item)
}

override fun handleBackButtonClicked() {
        finish()
}
```

**//CartPresenter**
``` 
override fun handleNextStep(itemId: Int) {
      when (itemId) {
            android.R.id.home -> {
                    view.handleBackButtonClicked()
            }
      }
}
```

이렇게 해당 로직을 Presenter로 위임을 해주었습니다!
코드를 짜면서 궁금한 점이 생겼습니다! 
제가 짠 코드 처럼 이런 식으로 위임을 하는 것이 맞는 지 궁금했고, `android.R.id.home` 처럼 안드로이드 관련 단어(....?)가 Presenter로 들어와도 되는 것인지 궁금합니다..!
아직까지 완벽하게 MVP 패턴에 익숙해지지 못해 리뷰어님께 여쭤보고 싶습니다!!!

2023-05-15 14:36 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/view/cart/CartActivity.kt
> +                finish()
비슷한 내용으로 다른 분에게 남긴 코멘트가 있는데 참고 부탁드려요!
[코멘트1](https://github.com/woowacourse/android-shopping-cart/pull/2#discussion_r1193904056)
[코멘트2](https://github.com/woowacourse/android-shopping-cart/pull/2#discussion_r1193907162)

2023-05-15 14:53 UTC, vagabond95 requested changes
크게 피드백 드릴 부분이 보이지 않을 만큼, 추가로 잘 구현해주셨네요 👍 

그외에 고민해볼만한 부분에 대해 코멘트를 남겼는데, 확인 부탁드려요!

2023-05-15 14:53 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/util/BindingAdapter.kt
> +    @BindingAdapter("glideImage")
glide 라는 이름은 빠져도 좋을 것 같아요!
이미지 라이브러리는 언젠가 바뀔수도 있으니까요 :)

2023-05-15 14:53 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/view/productdetail/ProductDetailActivity.kt
> +    private lateinit var productData: ProductModel
해당 프로퍼티는 presenter 생성 시 주입받아도 괜찮지 않을까요?

activity 에 상태로 가지고 있을 이유가 크게 없을 것 같아요!

2023-05-15 14:53 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/view/productlist/ProductListActivity.kt
> +                }
요 계산을 presenter 에 위임하는 것은 어색할까요? ㅎㅎ

2023-05-15 14:53 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/view/productlist/ProductListActivity.kt
> +            },
무명 클래스의 객체로 넘겨주는 것도 좋지만,
람다식을 활용하면 좀 더 가독성을 확보할 수 있어보여요!

2023-05-15 14:53 UTC, vagabond95 requested changes
크게 피드백 드릴 부분이 보이지 않을 만큼, 추가로 잘 구현해주셨네요 👍 

그외에 고민해볼만한 부분에 대해 코멘트를 남겼는데, 확인 부탁드려요!

2023-05-15 16:25 UTC, hyunji1203 commented on app/src/main/java/woowacourse/shopping/view/productdetail/ProductDetailActivity.kt
> +    private lateinit var productData: ProductModel
넵! 말씀해주신 대로 해당 프로퍼티를 Presenter 안으로 이동시켜, Activity가 해당  상품 데이터의 상태를 갖지 않도록 수정했습니다!

2023-05-15 16:38 UTC, hyunji1203 commented on app/src/main/java/woowacourse/shopping/view/productlist/ProductListActivity.kt
> +                }
View에 의존성 없이 데이터를 통해 계산을 하는 로직이므로 어색하지 않은 것 같아 , Presenter의 `calculateSpanSize()` 함수에 해당 로직을 위임했습니다!

2023-05-15 17:55 UTC, hyunji1203 commented on app/src/main/java/woowacourse/shopping/view/productlist/ProductListActivity.kt
> +            },
넵! 람다식을 활용하도록 수정했습니다!

2023-05-16 13:33 UTC, vagabond95 approved these changes
추가로 코멘트 드릴 부분이 보이지 않아, 1 / 2단계는 머지하도록 하겠습니다~!
고생 많으셨어요!

2023-05-16 13:34 UTC, merged