[부나] 1, 2단계 쇼핑 장바구니 제출합니다.
woowacourse/android-shopping-cart pull request #25
Opened 2023-05-11 08:53 UTC by tmdgh1592

2023-05-12 07:34 UTC, malibinYun requested changes
1, 2단계 미션 고생 많으셨어요.
DataLayer는 피드백의 대상이 아니기에, 별도로 피드백을 남기지 않았습니다.
위 내용 보다는 요구사항에 더 초점을 맞추어서 미션을 진행해주세요 :)
Presenter에 대한 테스트가 없네요. 꼭 작성 후 리뷰 요청 부탁드립니다 :)
다음 요청때에는 모든 요구사항 및 테스트 코드를 작성 후 요청해주세요!

2023-05-12 07:34 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/ui/basket/BasketPresenter.kt
> +        ).map { it.toUi() }
이후 "다음" 페이지가 아니라, 특정 페이지를 로드해야할 때는 어떤 변경점이 생겨날까요?

2023-05-12 07:34 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/ui/productdetail/ProductDetailPresenter.kt
> +        thread {
어떤 것을 해결하기 위해 thread를 활용하셨나요?
무엇이 해결되었고, 무엇이 해결되지 않았나요?
어떤 특징과 장단점이 있었나요?
다른 것 말고 이 라이브러리를 선택한 이유는 무엇인가요?

2023-05-12 07:34 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/ui/shopping/MoreButtonAdapter.kt
> +    RecyclerView.Adapter<MoreButtonViewHolder>() {
더보기 버튼은 정말 "Recycle" 에 적절했나요?

2023-05-12 07:34 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/ui/shopping/ShoppingActivity.kt
> +        presenter.fetchProducts()
presenter에 한 번만 명령하게 만들어보는 건 어떨까요?

2023-05-12 07:34 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/ui/shopping/ShoppingViewHolderType.kt
> +    MORE_BUTTON(R.layout.item_button_more);
ViewType은 기존에 존재하는 적절한 객체에 응집도있게 합쳐볼 수 있겠네요 :)

2023-05-12 07:34 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/ui/shopping/recentproduct/RecentProductsViewHolder.kt
> +        binding.isVisible = visibility
이 함수의 내용이 "bind" 라기에는 너무 포괄적이라는 생각이 드네요 🙂

2023-05-12 07:34 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/util/BindingAdapter.kt
> +        .into(this)
바인딩 어뎁터를 잘 활용해주셨네요 👍
아래 부분들을 더 고민해보세요

- imgUrl 이 null이 들어오는 경우가 있을까요?
- image 라는 단어는 file 일 지 url 일 지 xml attibute를 통해 바로 알 수 있을까요?

2023-05-12 07:34 UTC, malibinYun commented on app/src/main/res/layout/activity_basket.xml
> +    </data>
binding 할 data가 없을 때는 불필요한 코드라고 생각해요 :)

2023-05-12 07:34 UTC, malibinYun commented on app/src/main/res/layout/item_recent_products.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
visible에 대한 내용도 bindingAdapter로 풀어내어보세요 :)

2023-05-12 07:37 UTC, malibinYun commented
어떤 부분들을 구현하지 못했는 지 리스트업 한 후, 스스로의 체크리스트로 활용하시면 좋겠어요 :)
저도 리뷰 중 어떤 요구사항이 지켜지지 않았는 지 파악하기가 쉽지 않아서요!

2023-05-14 18:16 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/shopping/ui/basket/BasketActivity.kt
> +        binding = DataBindingUtil.setContentView(this, R.layout.activity_basket)
제가 알고 있는 선에서는

DataBindingUtil을 사용하면 바로 setContentView()를 사용할 수 있다는 장점이 있습니다.
또한 layout을 알지 못하는 상황에서도 인자로 전달받아 사용할 수 있습니다!

반면, ActivityBasketBinding은 명시적으로 binding 인스턴스를 만든다는 특징이 있습니다.
공식문서에서는 layout Id를 알고 있는 경우에는 type safe을 위해 후자를 택하라고 하지만 아직 장점을 크게 느끼지 못하여서 DataBindingUtil을 사용하였습니다 😃

2023-05-14 18:17 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/shopping/ui/basket/BasketActivity.kt
> +            finish()
각 View에 대한 네이밍을 명확히 하도록 하겠습니다!

2023-05-14 18:22 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/shopping/ui/basket/BasketPresenter.kt
> +        ).map { it.toUi() }
그렇게 되면 코드에 많은 수정이 필요할 것 같습니다..!
무조건 이전, 다음 페이지가 아니라, 특정 페이지를 Presenter에서 관리하고 필요한 페이지를 불러오도록 변경하였습니다!

2023-05-14 18:25 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/shopping/ui/productdetail/ProductDetailPresenter.kt
> +        thread {
안드로이드에서 database 접근을 UI Thread에서 수행하면, 무거운 작업의 경우 ANR이 발생할 수 있다고 알고 있습니다.
그래서 페어와 협의한 결과 별도의 Thread를 통해 비동기적으로 하고자 하였습니다!
하지만 thread를 사용하니 테스트 코드를 작성을 어떻게 해야 할 지 모르겠습니다.. 😅

Coroutine, Flow, Rx 등 다양한 라이브러리가 있지만 아직 정확히 알지 못하기에 간단해보이는 thread { } 를 사용하였습니다!

2023-05-14 18:25 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/shopping/ui/shopping/ShoppingActivity.kt
> +        }
코드가 길어지는 것 같아 별도로 분리하는 작업을 하였습니다 : )

2023-05-14 18:27 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/shopping/ui/shopping/recentproduct/RecentProductsViewHolder.kt
> +        binding.isVisible = visibility
다시 살펴보니, visibility와는 거리가 있어보이기도 합니다.
해당 함수는 제거하였습니다 👍

2023-05-14 18:29 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/shopping/util/BindingAdapter.kt
> +        .into(this)
> imgUrl 이 null이 들어오는 경우가 있을까요?

이후에 서버와 통신하는 경우에, 여러 상황이 생길 것에 대비해야 할 것 같습니다.
fallback(), error() 를 활용하여 예외 처리하였습니다!

> image 라는 단어는 file 일 지 url 일 지 xml attibute를 통해 바로 알 수 있을까요?

현재로서는 image가 url인지, xml resource인지 알기 어려워보입니다.
`bind:imageUrl` 로 변경하여 네이밍을 명확하게 변경하였습니다.

2023-05-14 18:43 UTC, tmdgh1592 commented on app/src/main/res/layout/item_recent_products.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
LiveData이나 Delegates.Observable을 통해 해결할 수 있을 것이라고 생각했습니다.
그런데 이 방법을 사용하기엔 Presenter에서 값을 외부에 노출해야 하는 문제가 있어서 아직 고민을 하고 있습니다.
우선, 아래 방법으로 구현하였습니다!
혹시 말리빈께서 생각해두셨던 구현법이 있으실까요..?!

RecentProductWrapperAdapter.kt
```kotlin
@SuppressLint("NotifyDataSetChanged")
private fun updateRecentProductWrapperVisible(recentProductList: List<UiRecentProduct>) {
    container.clear()
    if (recentProductList.isNotEmpty()) container.add(Any())
    notifyDataSetChanged()
}
```

2023-05-14 18:48 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/shopping/ui/shopping/ShoppingViewHolderType.kt
> +    MORE_BUTTON(R.layout.item_button_more);
ViewType을 적절한 객체에 응집도있게 합치는 것이
`RECENT_PRODUCTS`, `PRODUCT`, `MORE_BUTTON`과 같은 타입을 각 ViewHolder로 옮기는 것을 의미하신 걸까요?!
만약 그렇다면 enum의 장점을 활용할 수 없지 않나요?? 🤔

2023-05-14 18:52 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/shopping/ui/shopping/ShoppingActivity.kt
> +        presenter.fetchProducts()
`fetchAll()` 메서드를 만들어서 한 번만 명령하도록 변경하였습니다 : )

2023-05-15 06:53 UTC, tmdgh1592 commented
안녕하세요 말리빈 😃
저번 리뷰요청 때 구현하지 못한 기능을 모두 구현하였습니다.
domain, presenter 테스트 코드 또한 모두 작성 완료하였습니다!

리뷰 남겨주신 부분에 대해 제가 잘 이해하지 못한 부분에 대해 코멘트를 남겨놨습니다!
괜찮으시다면 답변 부탁드립니다! 🙏😀

2023-05-16 04:14 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/ui/productdetail/ProductDetailPresenter.kt
> +        thread {
ANR이 발생하기 이전에 어떤 현상이 생겨날까요?
ANR은 어떨 때에 발생할까요?

스레드 간 이동을 수행하는 것은 Presenter의 일일까요?
이후에는 thread 이동에 대해 어떻게 더 잘 활용할 수 있을 지 고민해보셨으면 좋겠어요 :)

지금은 스레드간 이동을 하는 경우 고려해야할 것들이 매우 많은데요,
그렇기에 해당 문제를 인지하고 따로 공부해보시고, 지금은 MVP 아키텍처와 레벨 1 내용을 안드로이드에 지속적으로 적용해보는 것을 연습해보셨으면 좋겠어요.

2023-05-16 04:28 UTC, malibinYun approved these changes
1, 2단계 미션 고생 많으셨어요!
다음 미션을 위해 머지할게요.
피드백은 다음 미션에 반영해주세요!

2023-05-16 04:28 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/ui/shopping/ShoppingActivity.kt
> +    override val presenter: Presenter by lazy { createShoppingPresenter(this, shoppingDatabase) }
https://github.com/woowacourse/android-shopping-cart/pull/25#discussion_r1191964195
여전히 View에서 ShoppingDatabase를 알고있네요!
ShoppingDatabase의 생성도 분리된 곳에서 수행해보는 것은 어떨까요?

2023-05-16 04:28 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/ui/shopping/recyclerview/adapter/loadmore/LoadMoreAdapter.kt
> +) : RecyclerView.Adapter<LoadMoreViewHolder>() {
이 버튼 친구는 따로 Adapter를 선언하기보다, 다른 Adapter의 ViewType으로 넣어보는 건 어떨까요?

2023-05-16 04:28 UTC, malibinYun commented on app/src/test/java/woowacourse/shopping/basket/BasketPresenterTest.kt
> +        verify(exactly = 1) { view.updateNavigatorEnabled(any(), any()) }
모든 값을 any()로 검증하기 보다 의도된 특정 값이 들어왔는 지 검증해보는 건 어떨까요?

2023-05-16 04:29 UTC, merged

2023-05-16 04:40 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/shopping/data/datasource/recentproduct/RecentProductDataSource.kt
> +        fun add(product: DataRecentProduct)
`getPartially()`, `add()` 만으로는 무엇을 대상으로 동작하는 함수인지 파악하기 어렵겠군요!
`getRecentProductsPartially()`, `addRecentProduct()` 로 변경하였습니다!

2023-05-16 04:44 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/shopping/data/model/PageNumber.kt
> +data class PageNumber(val value: Int, val sizePerPage: Int) {
각 레이어별로 model이 존재하는데, IDE 패키지에서 봤을 때 DataXxx, UiXxx, DomainXxx 와 같이 Prefix가 붙어 있는 것이 읽기 힘들다고 느껴졌습니다!
그래서 코딩을 할 때에는 모델의 이름을 그대로 사용하고, 사용할 때에는 typealias의 이름을 사용하도록 하였습니다.

2023-05-16 04:49 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/shopping/ui/basket/BasketActivity.kt
> +    override fun updateNavigatorEnabled(previous: Boolean, next: Boolean) {
다시 보니 코드를 작성한 본인조차도 헷갈리네요 🤔
조금 더 구체적으로 작성해보겠습니다!

2023-05-16 05:11 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/shopping/ui/basket/BasketActivity.kt
> +        binding = DataBindingUtil.setContentView(this, R.layout.activity_basket)
아..! DataBindingUtil.setContentView()가 반환하는 타입을 보니 이제야 조금 이해했습니다.
특정 액티비티나 프래그먼트의 XxxBinding 타입이 아니라, ViewDataBinding의 서브 타입 파라미터군요! 😃

그렇기 때문에 아래와 같은 코드에서 type safe를 보장하지 못한다는 것 같습니다.
```
private val binding: ABinding = DataBindingUtil.setContentView(R.layout.not_a)
`
``

말리빈 덕분에 새로운 사실을 알게 되었네요~! 감사합니다 👍

2023-05-16 05:33 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/shopping/ui/productdetail/ProductDetailPresenter.kt
> +        thread {
제가 알고 있는 내용으로는 ANR은 UI Thread에서 5초 이상 응답하지 않으면 자동으로 os가 앱을 종료시키는 것으로 알고 있습니다!
예를 들어, UI Thread에서 DB에 한 번에 100,000 개의 데이터를 넣는다면, 사용자가 느끼기에 앱이 마치 멈춘 것처럼 느껴질 수 있습니다.
이러한 상황을 고려하고 별도로 thread를 생성하였던 것입니다.

2023-05-16 05:34 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/shopping/ui/productdetail/ProductDetailPresenter.kt
> +        thread {
> 스레드 간 이동을 수행하는 것은 Presenter의 일일까요?

이 질문은 잘 모르겠습니다.. 🥲
말리빈 말씀처럼 우선은 MVP에 대해 공부하고 이후 필요한 상황에서 익히도록 하겠습니다!

2023-05-16 05:47 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/shopping/ui/basket/BasketPresenter.kt
> +    }
이 코드도 마찬가지군요!
이전, 다음보다는 fetchBasket() 메서드에 page 인자를 전달받는 것이 여러 면에서 사용하기 좋아 보입니다!
이로 인해 위 두 함수는 필요 없어져서 지웠습니다 : )

2023-05-16 06:38 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/shopping/ui/shopping/ShoppingActivity.kt
> +    override val presenter: Presenter by lazy { createShoppingPresenter(this, shoppingDatabase) }
ShoppingDatabase 생성 또한 별도로 분리하여 주입받도록 변경하였습니다!

2023-05-16 08:01 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/shopping/ui/shopping/recyclerview/adapter/loadmore/LoadMoreAdapter.kt
> +) : RecyclerView.Adapter<LoadMoreViewHolder>() {
우선 3, 4단계를 진행하고 시간이 되면 리팩토링을 진행해보겠습니다!
감사합니다 : )

2023-05-16 14:33 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/ui/shopping/ShoppingViewHolderType.kt
> +    MORE_BUTTON(R.layout.item_button_more);
enum의 장점을 활용해볼 수 있는 방법도 있겠지요.
ViewHolder를 sealed로 변경해보는 방법도 있겠네요 :)
여러 방법에 대해 많은 고민해보시면 좋겠어요! 🙂