[아크] 3, 4단계 쇼핑 장바구니 제출합니다.
woowacourse/android-shopping-cart pull request #28
Opened 2023-05-18 08:06 UTC by re4rk

안녕하세요 레아!
3단계에서 중점적으로 말씀해주셧던 Val Mutable List로 적용하여 Adapter들을 구현하였습니다!
추가로 4단계에서는 최신 목록과 장바구니는 로컬로만 사용한다고 가정하고 상품 목록만 Okhttp를 적용시켜보았습니다! 어느 방향으로 미션을 수행해야 할지 모르겠어서 빠르게 제출합니다!
이번 단계도 잘부탁드립니다!

2023-05-19 08:02 UTC, woowahan-leah commented on app/src/main/java/woowacourse/shopping/ui/cart/CartActivity.kt
>          }
매번 리스너를 재초기화하는 것이 좋은 방향일까요? presenter와 view에 대해 이해도가 높지 않은 이상 다른 개발자들이 잘못 이해하고 사용할 가능성이 높아보입니다.

2023-05-19 08:04 UTC, woowahan-leah commented on app/src/main/java/woowacourse/shopping/ui/cart/CartPresenter.kt
> +    }
개발자들마다 의견이 다를 수 있겠지만 CartPresenter의 인스턴스를 생성하자마자 Repository를 호출하는 코드가 생긴다는 것이 예상치 못한 부수 효과라고 느껴질 수 있을 것 같아요. 이 이유로 Presenter의 init 블럭에 초기화 구문을 넣는 것을 지양하는 편입니다. 아크의 의견은 어떠신가요?

2023-05-19 08:04 UTC, woowahan-leah commented on app/src/main/java/woowacourse/shopping/ui/cart/CartPresenter.kt
> +    override fun moveToPagePrev() { index -= 1; setUpCarts() }
꼭 한줄에 작성할 필요가 있을까요?

2023-05-19 08:05 UTC, woowahan-leah commented on app/src/main/java/woowacourse/shopping/ui/cart/CartPresenter.kt
>      }
bottom -> Presenter가 View를 너무 잘 알고 있다는 생각이 들어요. 수업시간에도 나온 질문을 다시 드릴게요.
1. presenter가 view 관심사를 들고 있음
2. view가 presenter 관심사를 들고 있음

각각을 관심사 분리의 입장에서, 유지보수하기 쉬운 관점에서 어떤 장단점이 있을지 고민해보세요.

2023-05-19 08:06 UTC, woowahan-leah commented on app/src/main/java/woowacourse/shopping/ui/cart/cartAdapter/CartAdapter.kt
> +    }
notifyDataSetChanged가 꼭 필요한 로직이라고 판단하셨나요?

2023-05-19 08:06 UTC, woowahan-leah commented on app/src/main/java/woowacourse/shopping/ui/cart/cartAdapter/viewHolder/CartProductViewHolder.kt
> +        binding.listener = cartListener
view holder에서 리스너를 초기화하는 다양한 방법 중에 이 방법을 선택하신 이유가 있으신가요?

2023-05-19 08:09 UTC, woowahan-leah commented on app/src/main/java/woowacourse/shopping/ui/cart/cartAdapter/viewHolder/CartProductViewHolder.kt
> +        if (data !is CartItemType.Cart) return
뷰타입을 사용하는 뷰홀더마다 이 코드를 작성해야 할까요? CartItemType.Cart임을 알 수 있는 다른 방법이 있나요?

2023-05-19 08:10 UTC, woowahan-leah commented on app/src/main/java/woowacourse/shopping/ui/cart/cartAdapter/viewHolder/CartProductViewHolder.kt
> +        }
bind함수가 호출될때마다 setOnClickListener가 초기화되지 않도록 개선해보면 좋을 것 같습니다.

힌트: 커스텀뷰에도 클릭 리스너를 전달할 수 있습니다.

2023-05-19 08:11 UTC, woowahan-leah commented on app/src/main/java/woowacourse/shopping/ui/cart/cartDialog/CartDialog.kt
> +@SuppressLint("SetTextI18n")
`@Suppress`가 왜 필요한가요?

2023-05-19 08:12 UTC, woowahan-leah commented on app/src/main/java/woowacourse/shopping/ui/customView/ProductCounter.kt
> +    var maxCount: Int = 99
외부에서 값을 수정할 수 있나요?

2023-05-19 08:13 UTC, woowahan-leah commented on app/src/main/java/woowacourse/shopping/ui/detailedProduct/DetailedProductActivity.kt
> +                flags = FLAG_ACTIVITY_CLEAR_TOP
👍 getIntent의 구현을 숨겨서 flag값을 노출하지 않아도 됩니다.

하지만 다른 개발자들도 getIntent를 호출할 때 FLAG_ACTIVITY_CLEAR_TOP가 설정된다는 것을 알 수 있을까요?

2023-05-19 08:17 UTC, woowahan-leah commented
@re4rk 오늘 수업에서의 개념을 적용하고 싶으실 수도 있을 것 같은데요, 빠르게 리뷰 요청을 하신 만큼 핑퐁이 자주 있으면 좋겠습니다! 일단은 Mocked된 Web 데이터를 실제 로컬 앱에서도 사용하는 구조로 변경하시는 것이 우선일 것 같아요.

2023-05-21 18:44 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/utils/LiveDataUtils.kt
> +}
Nullable한 LiveData를 Not Null로 사용하기 위해서 랩핑하여 사용하고 있습니다!

2023-05-21 18:44 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/utils/LiveDataUtils.kt
> +}
추가로 postValue는 현재 사용하고 있지 않아서 제거 했습니다!

2023-05-21 18:45 UTC, re4rk commented on domain/src/main/java/woowacourse/shopping/repositoryImpl/RemoteProductRepository.kt
> +class RemoteProductRepository(baseUrl: String) : ProductRepository {
어플에서도 사용되도록 MockWebServer랑 RemoteProductRepository 모두 수정했습니다!

2023-05-21 19:03 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/ui/detailedProduct/DetailedProductPresenter.kt
> +    }
따로 setUp함수로 분리하고 호출 하였습니다!

2023-05-21 19:13 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/ui/detailedProduct/DetailedProductActivity.kt
> +                flags = FLAG_ACTIVITY_CLEAR_TOP
필요한 곳에서만 호출되도록 변경하였습니다!

2023-05-21 19:15 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/ui/customView/ProductCounter.kt
> +    var maxCount: Int = 99
```xml
<resources>
    <declare-styleable name="ProductCounter">
        <attr name="count" format="integer" />
        <attr name="minCount" format="integer" />
        <attr name="maxCount" format="integer" />
    </declare-styleable>
</resources>
```
의도한 내용입니다! attrs.xml을 수정해서 밖에서 수정할 수 있게 바꿔놨었습니다!
이런식으로 값을 변경하도록 하는 것이 좋지 못한 방향인지 궁금합니다!

2023-05-21 19:18 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/ui/cart/cartDialog/CartDialog.kt
> +@SuppressLint("SetTextI18n")
코드 수정중에 잘못 들어간 것같습니다! 바로 반영하였습니다!

2023-05-21 21:56 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/ui/cart/CartPresenter.kt
> +    override fun moveToPagePrev() { index -= 1; setUpCarts() }
전체적으로 Presenter의 구조를 변경하였습니다!

2023-05-21 23:26 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/ui/cart/CartPresenter.kt
> +    }
사실 아직 MVP 구조에서 View와 Prestener 역할을 어떻게 나누는 것이 좋을지 고민입니다! 처음에는  View와 Presenter는 1:1 대응이라 Presenter가 초기화 될 때 한번에 호출하도록하는 것이 어떠냐는 피드백을 예전에 받았습니다!
둘 다 장단점이 있다고 생각하고 지금은 저도 View에서 Presenter의 초기화 할 때 같이 넣어주는 것이 맞다고 생각해서 View의 영역으로 이동시켰습니다!

2023-05-21 23:26 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/database/cart/CartConstant.kt
> +            "WHERE $TABLE_COLUMN_ID = $id"
적용시켜서 가독성을 높이도록 했습니다!

2023-05-21 23:27 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/ui/cart/CartPresenter.kt
>      }
아직 어떤 MVP 구조가 유지보수성이 좋을지 더 고민해볼 필요가 있다고 느끼게 되었습니다!
피드백 반영을 위해 최대한 신경써서 변경해보았습니다!

2023-05-21 23:32 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/ui/cart/cartAdapter/CartAdapter.kt
> +    }
RecyclerView에서 페이지 방식의 리사이클러 뷰를 구현할 때에는 DataSetChanged가 꼭 필요하다고 생각합니다!
해당 페이지를 반영할 때 다른 notify~ 함수들을 모두 활용해서 반영해보았습니다!
예시로는 첫페이지는 5개 다음페이지가 3개의 아이템을 가지고 있다고 생각한다면 5->3과 3->5 개수 변환을 모두 반영할 필요가 있습니다!
이때 다른 notify~를 활용한다면 notifyItemChanged와 notifyItemDeleted 두개 모두 필요하게 될 것입니다!
따라서 해당 DataSetChanged가 필요하다고 생각합니다!

2023-05-21 23:36 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/ui/cart/cartAdapter/viewHolder/CartProductViewHolder.kt
> +        }
해당 기능 구현할 때 bindingAdapter를 학습하기 위해 시간을 많이 할당한 것같습니다!

```Kotlin
object CustomBindingAdapter {
...
    fun interface OnCountChangeListener {
        fun onCountChange(productId: Int, count: Int)
    }

    @BindingAdapter("productId", "listener", requireAll = true)
    @JvmStatic
    fun onCountChange(view: ProductCounter, productId: Int, listener: OnCountChangeListener) {
        view.setOnCountChangeListener { listener.onCountChange(productId, it) }
    }
}
```

```xml
        <woowacourse.shopping.ui.customView.ProductCounter
            ...
            listener="@{listener.onItemUpdate}"
            productId="@{product.id}"
            ...
        />
```
다음과 같이 구현을 하게 되었는데 이 구조에 대해서 어떻게 생각하시는지 궁금합니다!

2023-05-21 23:42 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/ui/cart/cartAdapter/viewHolder/CartProductViewHolder.kt
> +        binding.listener = cartListener
이 방법 외에 2가지를 추가로 총 3가지 방법이 있다고 생각합니다!

1. listener 전달
  -  listener를 전달 할 경우 on~으로 전달하여 어떤 행위일 때 실행 할 지 알 수 있습니다.
  - presenter 함수들을 wrapping 하여 추가 기능을 구현 할 수 있습니다.
  - 필요 이상의 함수들을 xml에서 알 수 있게 됩니다.
3. presenter 전달
  - 마찬가지로 필요 이상의 함수들을 xml에서 알 수 있게 됩니다.
5. Function* 을 이용한 전달
  - 필요한 함수들만 전달하게 됩니다.
  - 한 아이템의 역할이 많아질 수록 코드의 길이가 길어질 것입니다.

이 때 유지보수성을 더 좋게 만들기 위해서 listener로 전달하는 것이 좋다고 생각을 했습니다!
혹시 제가 생각치 못한 부분이 있으시다면 알려주시면 감사하겠습니다!!

2023-05-21 23:50 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/ui/cart/cartAdapter/viewHolder/CartProductViewHolder.kt
> +        if (data !is CartItemType.Cart) return
3가지 방법이 있다고 생각합니다!

1. Adapter에서 캐스팅을 거친 후에 전달합니다!
2. Adapter의 Items을 일급 컬렉션으로 만들어서 타입을 반환하도록합니다!
3. ViewHolder마다 바인딩을 합니다!

이 중에서 3번이 Adapter의 코드를 가장 단순하게 만들 수 있는 방법이라고 생각이 들어서 선택하게 되었습니다!
레아는 어떤 방식을 가장 선호하시는지 궁금합니다!

2023-05-22 00:04 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/ui/cart/CartActivity.kt
>          }
하나가 변경중일 때에는 나머지가 변경되지 않도록 Presenter 내부적으로 처리하도록 변경하였습니다!

2023-05-23 03:06 UTC, woowahan-leah requested changes
안녕하세요 아크! 먼저 리뷰가 늦어서 죄송합니다 😭  
리뷰 반영을 잘 해주셨습니다 💯 

고민하시던 내용에 대한 코멘트를 달았으니 확인해주시면 감사하겠습니다.
이미 훌륭하지만 조금 더 개선하면 좋을 부분이 있습니다.
아키텍쳐에 대한 고민은 이정도면 충분하다고 생각해요! 상태 관리에 대한 피드백이 많습니다.

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏 💪

2023-05-23 03:06 UTC, woowahan-leah commented on app/src/main/java/woowacourse/shopping/ui/cart/CartPresenter.kt
> +    private fun fetchCartProducts() {
저는 개인적으로 private 함수보다는 override 함수를 먼저 위치시키는 것을 선호합니다. 다른 개발자들이 이 클래스의 역할을 파악할 때 override되어 외부에 드러난 함수를 먼저 보고, 그 다음에 숨겨진 함수를 보는 것이 자연스럽다고 느껴질 것 같아요.

2023-05-23 03:06 UTC, woowahan-leah commented on app/src/main/java/woowacourse/shopping/ui/cart/CartPresenter.kt
>      }
지금의 Presenter는 LiveData의 영향으로 MVP와 MVVM 구조가 조금은 혼용되어있습니다.
정확한 설명은 아니지만 이 둘의 차이를 간단히 나눠보자면 이런 모습일 것 같아요.

매번 이렇게 변경사항이 생길 때마다 초기화, 뷰 세팅을 해주는 구조(presenter가 뷰를 직접 알고 있음) -> MVP
LiveData로 변경사항을 트래킹하여 뷰에서 알아서 그 책임을 갖는 구조(viewmodel이 뷰를 직접 알고 있지 않음) -> MVVM

이번 미션에서 아키텍쳐에 대한 고민은 이정도면 충분해보여요!

2023-05-23 03:06 UTC, woowahan-leah commented on app/src/main/java/woowacourse/shopping/ui/shopping/productAdapter/viewHolder/ProductsViewHolder.kt
> +                binding.btnAddToCart.visibility = View.VISIBLE
```suggestion
                binding.btnAddToCart.isVisible = true
```
한 단계 추상화되어있습니다!

2023-05-23 11:32 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/ui/cart/CartActivity.kt
> +    private lateinit var mockWeb: MockWeb
ServerURLSingleton이라는 오브젝트를 만들어서 관리하도록 변경하였습니다!

2023-05-23 17:28 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/ui/cart/CartPresenter.kt
> +    private fun fetchCartProducts() {
위에서 아래로 읽을 수 있는 코드를 만들도록 노력해보겠습니다!

2023-05-23 17:29 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/ui/cart/CartPresenter.kt
>      }
MVP와 MVVM의 차이를 와닿게 구분 할 수 있는 말씀인 것같습니다!

2023-05-23 19:08 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/ui/cart/cartAdapter/CartAdapter.kt
> +    }
ListAdapter로 변경하였습니다!

2023-05-23 19:11 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/ui/cart/cartAdapter/CartAdapter.kt
> +    }
ListAdapter로 변경하였습니다!

2023-05-23 19:34 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/ui/cart/cartAdapter/viewHolder/CartProductViewHolder.kt
> +        if (data !is CartItemType.Cart) return
제네릭으로도 시도를 해보았지만 1번과 비교했을 때 코드상의 깔끔함이 덜하다고 판단하여 1번으로 진행해보았습니다!

2023-05-24 05:30 UTC, woowahan-leah approved these changes
안녕하세요 아크! 리뷰 반영을 잘 해주셨습니다 💯 

참고하시면 좋을 내용을 코멘트로 달았으니 다음 단계 미션 진행하며 한번 읽어봐주세요!
아크의 PR을 리뷰하며 즐거웠습니다 🙂 

다음 미션도 응원할게요 🙏

2023-05-24 05:30 UTC, woowahan-leah commented on app/src/main/java/woowacourse/shopping/CustomBindingAdapter.kt
> +    @BindingAdapter("productCounterListener", requireAll = true)
명시적 네이밍 변경 👍 
참고로 저는 이 바인딩 어댑터가 개발자가 임의로 생성한 커스텀 어댑터임을 강조하기 위해, 또 코드 네임스페이스를 관리하기 위해
```suggestion
    @BindingAdapter("bind_productCounterListener", requireAll = true)
```
위와 같이 bind prefix를 붙이기도 합니다. 이렇게 작성하면 bind로 시작하는 네임스페이스에서 한눈에 볼 수 있어요.
<img width="438" alt="image" src="https://github.com/woowacourse/android-shopping-cart/assets/112997521/baa54044-c066-4f49-85ff-3c83e9ac6e07">


이 스타일은 참고만 해주세요 🙂

2023-05-24 05:30 UTC, woowahan-leah commented on app/src/main/java/woowacourse/shopping/ui/cart/cartAdapter/CartAdapter.kt
> +            }
areItemsTheSame에서 viewType으로 비교하는 것은 적절하지 못한 사용법인 것 같아요 🤔 

https://developer.android.com/reference/androidx/recyclerview/widget/DiffUtil.ItemCallback#areItemsTheSame(T,T)

> Called to check whether two objects represent the same item.
For example, if your items have unique ids, this method should check their id equality.

2023-05-24 05:30 UTC, woowahan-leah commented on app/src/main/java/woowacourse/shopping/ui/shopping/recentProductAdapter/RecentProductsAdapter.kt
> +                return oldItem === newItem
주소값을 비교하는 것이 areItemsTheSame을 사용하는 적절한 방법일까요? 🤔 
> areItemsTheSame() 함수가 먼저 실행이 되고 해당 함수의 결과로 true 가 반환됐을 경우에만 areContentsTheSame() 이 호출됩니다.

2023-05-24 05:30 UTC, woowahan-leah commented on app/src/main/java/woowacourse/shopping/utils/ServerURLSingleton.kt
> +}
싱글톤에서 이와 같은 가변 값을 관리하게 된다면 언제 데이터가 초기화될지 알 수 없고, 프로그램 중간에 값이 변경되지 않는 것을 보장할 수 없어 예상치 못한 부수 효과로 이어질 수 있습니다.

지금은 MockWeb을 사용하기 때문에 URL 초기화 로직을 관리하기 위한 방법으로 사용하셨다고 이해했습니다. 협업 미션을 진행하실 때 이러한 로직은 걷어내시게 되겠지만 싱글톤이 위험하다는 것은 꼭 이해하고 넘어가셨으면 좋겠어요!

비슷한 로직의 코드를 이전 회사에서 리팩터링한 경험이 있는데, 관련 경험을 블로그 포스팅으로 작성했어서 도움이 될 것 같아 공유해요.
- https://spoqa.github.io/2020/11/02/android-dependency-injection-with-koin.html

Koin 라이브러리 소개 전까지만 보시면 될 것 같아요!

2023-05-24 05:30 UTC, woowahan-leah commented on app/src/main/java/woowacourse/shopping/ui/shopping/recentProductAdapter/RecentProductsAdapter.kt
> +) : ListAdapter<RecentProductItem, RecentProductViewHolder>(DiffCallback()) {
ListAdapter를 잘 적용해주셨어요 👍 

시간이 된다면 내부에서 사용하고 있는 AsyncListDiffer에서 어떤 알고리즘을 구현하고 있는지 보시는 것도 재밌습니다. (아크가 좋아하실 것 같아요ㅋㅋㅋ)
https://developer.android.com/reference/androidx/recyclerview/widget/AsyncListDiffer

2023-05-24 05:30 UTC, woowahan-leah commented on app/src/main/java/woowacourse/shopping/ui/shopping/recentProductAdapter/RecentProductsAdapter.kt
> +                return oldItem === newItem
참고로 지금은 areItemsTheSame과 areContentsTheSame만 구현하고 있지만 상황에 따라 getChangePayload를 구현하고 싶을 수도 있습니다. getChangePayload는 areItemsTheSame는 true, areContentsTheSame는 false인 경우에 호출됩니다.

참고만 해주세요!

2023-05-24 05:31 UTC, merged