[수달] 3, 4단계 쇼핑 장바구니 제출합니다.
woowacourse/android-shopping-cart pull request #31
Opened 2023-05-21 13:28 UTC by otter66

안녕하세요 제리! 
step1,2 피드백 도움이 많이 되었습니다!

이번에는 어찌어찌 기능은 만들었으나 리펙터링은 많이 진행하지 못하였네요!
로직들을 관리하는곳을 정하는 것이 조금 어려운 것 같습니다.
이번에도 피드백 잘 부탁드리겠습니다! 

(이전에 남겨주신 피드백에 대한 내용입니다!!)
> concatAdapter 를 사용해주시는 이유는 무엇일까요?
> concatAdapter 를 사용하지 않는다면, 어떤 방식으로 구현할 수 있을까요?   

⇒ concat외에는 view type, nested를 사용하는 방법 등이 있는 것 같습니다.
- view type: 하나의 어뎁터에 다양한 역할을 하는 어댑터를 담아 구현이 가능합니다. 변경이 생길 경우 대응에 불리할 것 같다고 생각합니다. 단순히 하나의 리스트를 가지며 하나의 리스트 내부에서 다른 뷰들을 사용할 경우 view타입을 이용한 방법이 적절한 방법인 것 같습니다.
- nested: 구현이 간단하다는 장점이 있습니다. 하지만 재사용이 불가하다는 단점이 있습니다. 현재 미션처럼 서버로부터 값을 가져올 때는 어느정도의 데이터가 들어올지 알 수 없기 때문에 아이템이 많을 수 있어 부적절한 것 같습니다. 
- 지금과 같이 아이템이 많을 수 있고, 하나의 리스트 안에 또다른 리스트가 있는 경우에는 concat이 적절하다고 생각하였습니다!

> 매번 notifyDataSetChanged() 를 호출 할 경우, 성능상 문제가 생기지는 않을까요?
> 좀 더 효율적으로 notify 하는 방법은 무엇이 있을까요?   
- 최근 상품의 경우 새로운 아이템이 추가될 때 기존의 최근 상품 목록에 있던 것을 다시 볼 때 아이템의 위치가 변경되는 경우가 있기도 합니다. 
   이 경우 삭제되는 아이템의 위치를 찾고, 교체하는 과정이 관리하는 아이템의 개수(10개)에 비해 복잡할 것이라 생각해 notifyDataSetChanged를 이용해 전체를 다시 셋팅하도록 하였습니다.

2023-05-22 05:01 UTC, vagabond95 requested changes
3, 4단계 구현하시느라 고생 많으셨습니다~!

구현해주신 내용을 바탕으로 코멘트 남겼는데, 확인 부탁드릴게요!

2023-05-22 05:15 UTC, otter66 commented on app/src/main/java/woowacourse/shopping/feature/product/detail/ProductDetailActivity.kt
> +        dialog.dismiss()
dismiss를 먼저 호출하지 않을 경우 기존 다이어그램을 지우라는 에러메세지와 함께 앱 크래시가 발생하기 때문입니다. 
첫 호출임에도 불구하고 해당 에러가 발생하는 이유는 찾지 못하였습니다 🥲

2023-05-22 07:25 UTC, otter66 commented on app/src/main/java/woowacourse/shopping/data/cart/CartDao.kt
> +    private val productRepository: ProductRepository =
월요일 6시 이전까지 리뷰요청을 하기 위해 우선 CartDao와 CartRepositoryImpl에만 적용하였습니다. 
확인해주시면 감사하겠습니다!

2023-05-22 07:34 UTC, otter66 commented on app/src/main/java/woowacourse/shopping/feature/product/MainActivity.kt
> +        runOnUiThread {
UI를 변경하는 작업을 UI 스레드에서 하지 않을 경우 앱 크래시가 나는 오류가 있어 runOnUiThread를 사용하였습니다.

2023-05-22 08:11 UTC, otter66 commented on app/src/main/java/woowacourse/shopping/feature/product/detail/ProductDetailPresenter.kt
> +        if (MAX_COUNT_VALUE < count) count--
페이징 부분, 장바구니 제품의 개수를 선택하는 부분에 coerceAtLeast, coerceAtMost 적용하였습니다!! 감사합니다!!

2023-05-22 08:30 UTC, otter66 commented on app/src/main/java/woowacourse/shopping/feature/product/detail/ProductDetailActivity.kt
> +        dialog.dismiss()
이제 오류가 안나고 있습니다...🫠 제거하였습니다...

2023-05-22 08:48 UTC, otter66 commented on app/src/main/java/woowacourse/shopping/feature/cart/CartProductViewHolder.kt
> +        }
이 부분은 CounterView에 Listener를 등록하여 수정해보도록 하겠습니다!

2023-05-23 08:13 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/feature/product/MainActivity.kt
> +        runOnUiThread {
이러한 사항을 view 에서는 신경을 쓰지 않도록 하기 위해서는 어떻게 개선해볼 수 있을까요?

view 입장에서는 이러한 부분이 보장되지 않으면 불편함이 크지 않을까요 ㅎㅎ

2023-05-23 08:37 UTC, vagabond95 requested changes
추가로 구현해주신 내용을 바탕으로 코멘트 남겼습니다 ㅎㅎ

마지막까지 화이팅이십니다~!

2023-05-23 08:37 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/feature/product/MainActivity.kt
> +    private val cartRepository: CartRepository by lazy {
repository 를 activity 에서 멤버로 가지고 있을 필요가 있을까요?

2023-05-23 08:37 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/feature/product/MainActivity.kt
> +            cartProductStates = cartRepository.getAll().map(CartProduct::toUi),
presenter 가 있으므로, repository 를 바로 참조하는 것은 지양해야할 것 같아요. 다른 코멘트에 남겼지만, 이처럼 멤버로 가지고 있을 경우 참조가 쉽기 때문에 아키텍처 규칙에서 쉽게 벗어나는기 가능합니다.

2023-05-23 08:37 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/feature/product/MainActivity.kt
> +            cartProductAddFab = { Thread { presenter.storeCartProduct(it) }.start() },
쓰레드를 activity 에서 컨트롤 하는 것이 적절할까요?

2023-05-23 08:37 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/feature/product/MainPresenter.kt
> +        val cartProduct: CartProduct? = cartRepository.getCartProduct(productState.id)
한번 가져온 product 는 재사용할 수 있게 캐싱해보는 것은 어떨까요?

2023-05-23 08:37 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/feature/product/ProductViewHolder.kt
> +            cartProductCountMinus(productState)
카운트의 증감 등 상태관리는 presenter 에서 처리해주는 것이 어떨까요?

상태 관리를 한 곳에서 하지 않으면 디버깅이 어려울 수 있어요.

single source of truth 에 대해 같이 공부해봐도 좋겠습니다 ㅎㅎ

2023-05-23 08:37 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/feature/product/MainPresenter.kt
> +        val cartProduct: CartProduct? = cartRepository.getCartProduct(productState.id)
캐싱을 한다면, 추가로 신경써줘야할 부분은 무엇이 있을까요?

2023-05-23 08:37 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/feature/cart/CartProductViewHolder.kt
> +            홀더 또한 뷰이기 때문에 값을 더하거나 빼는 등의 로직은 presenter와 같은 위치에 있는 것이 좋을 것 같으나
2가지 접근 방법이 있을 것 같아요.

- 변경될 만한 값을 observable 한 형태로 다룬다.
- 변경이 생기는 아이템을 업데이트하고 해당 아이템 index 를 이용하여 notify 해준다.

2023-05-23 08:37 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/data/product/MockProductRemoteService.kt
> +            val request = Request.Builder().url(url).build()
http 모듈은 mocking 클래스와 분리되어야 하지 않을까요?

real web server 을 붙힐 때, http 를 이용하고 싶을 경우
현재는 재사용이 어려우니까요 ㅎㅎ

2023-06-07 10:31 UTC, otter66 commented on app/src/main/java/woowacourse/shopping/data/product/MockRemoteProductRepositoryImpl.kt
> +        Thread {
스레드를 생성하고 시작하는 비용이 많이 들 수 있다는 것 외에는 아직 잘 모르겠습니다... 🥲

2023-06-07 17:10 UTC, otter66 commented
제리님! 의존성, 코드 분리 등에 대해 피드백 자세하게 주셔서 도움이 많이 되었습니다!!
여전히 불필요하게 notifyDataSetChanged()를 호출하고 있거나, 테스트 코드가 없는 점 등 보완하고 싶은 부분은 많습니다... 
하지만, 시간이 부족한 관계로 제출합니다...🫠 
MVP에 대해 생각해보고 구조를 잡는데 많은 도움이 되었습니다! 리뷰 감사드립니다!!

2023-06-08 15:40 UTC, vagabond95 commented
view 레벨에서 처리되던 비즈니스 로직이 많이 줄어든 것 같아요 👍 
MVP 패턴은 한번에 감을 익히기는 쉽지 않으므로, 많은 프로젝트의 예시를 살펴보는 것을 권장 드립니다. ㅎㅎ

2023-06-08 15:41 UTC, vagabond95 approved these changes
끝까지 놓치지않고 미션 마무리해주셨네요 👍 

아마 현시점에는 마지막 미션까지 마무리하신 상황이실텐데,
고생 많으셨습니다!

성장에 좋은 밑거름이 되는 미션이 되셨길 바랍니다 :)

2023-06-08 15:42 UTC, merged