[글로] 3, 4단계 쇼핑 장바구니 제출합니다.
woowacourse/android-shopping-cart pull request #35
Opened 2023-05-21 19:22 UTC by ippnsj

안녕하세요! 페로로님~! 😊

3단계를 진행하면서 recyclerview의 데이터가 변경될 때마다(수량, 체크 여부) 다시 bind 해주고 있는데 이렇게 하면 해당 아이템만 깜빡이더라구요 ^-^;;; 

4단계의 경우, 일단 상품에 대해서만 mock 서버로부터 데이터를 받아오게 하였습니다!
기존에 상품 테이블과 다른 테이블이 foreign key 관계로 연결되어 있어서 최초에만 mock 서버로부터 20개씩 데이터를 받아오고 받아온 데이터는 상품 테이블에 저장하고 추후 접근 시에는 테이블에서 데이터를 가져오도록 하였습니다!

3, 4 단계 리뷰도 잘 부탁드립니다~😉

2023-05-22 03:15 UTC, laco-dev requested changes
3, 4단계 미션 고생 많으셨습니다.

이후 미션에서 서버 구현에 따라 변경될 수 있는 영역과, 인터페이스를 중심으로 피드백을 남겼습니다.

관련해서 다음 미션은 진행 속도도 중요하기 때문에 UI 관련 피드백은 꼭 반영하지 않아도 되겠습니다.

2023-05-22 03:15 UTC, laco-dev commented on app/src/test/java/woowacourse/shopping/cart/CartPresenterTest.kt
> +    fun 카트의_사이즈보다_현재_페이지와_페이지당_사이즈의_곱이_작다면_캐싱되어_있는_카트를_가져온다() {
"캐싱되어 있는 데이터를 가져온다" 는 프레젠터가 해야할 테스트가 맞을까요?

2023-05-22 03:15 UTC, laco-dev commented on app/src/test/java/woowacourse/shopping/cart/CartPresenterTest.kt
> +    }
프레젠터 입장에서는 레포지터리의 함수를 호출했다는 것도 한가지 중요한 테스트 기준이기는 합니다.
하지만 결과적으로는 레포지터리를 거쳐서 만들어진 결과로 View가 업데이트 되는지가 더욱 구체적인 기준이 되어야 합니다.

예를 들어 위 테스트는 상품의 수량이 감소되었을 때 프레젠터에서 개수를 잘못 넣어도 테스트는 성공합니다.

아래 테스트 이름과 작성한 테스트를 비교해보고 한번 고민 해보세요.
```
> Test: 카트의 상품 수량이 3개일 때 상품을 감소시키면, 전체 상품 수량은 2개로 변경된다
```

2023-05-22 03:15 UTC, laco-dev commented on app/src/main/res/layout/dialog_add_cart_product.xml
> +            app:layout_constraintTop_toTopOf="@id/dialog_cart_product_amount" />
강의 자료에는 아래와 같은 내용이 있는데요.
답변을 적어주세요

> 반복되는 뷰(상품 수량 선택)를 재활용할 수 있는 방법을 고민해본다.

2023-05-22 06:41 UTC, ippnsj commented on app/src/main/java/woowacourse/shopping/cart/CartContract.kt
> +        fun updateCartTotalAmount(amount: Int)
현재는 전체 장바구니 정보를 저장하여 관리하고 있습니다!
그래서 처음 접근하는 페이지의 카트 정보는 db에서 값을 가져오고 이미 접근했던 페이지의 카트 정보는 저장되어 있는 전체 장바구니 객체에서 가져오도록 하였습니다!
그 이유는 상품 선택 여부는 카트 화면에서만 유효하기 때문입니다.

저 또한 총 가격과 수량을 관리하는 객체가 있으면 좋겠다고 생각했고, 다음과 같은 가정을 해보게 되었어요!

1. 전체 장바구니를 유지하며 선택된 장바구니 객체도 관리하는 경우
이 경우에는 상품 선택 여부는 전체 장바구니에서 관리되고 있고, 총 가격과 수량은 선택된 장바구니에서 관리되고 있지만
만약 상품 수량이 변경되거나 한다면 전체 장바구니와 선택된 장바구니 모두에서 상품의 정보를 갱신해주어야 합니다.

2. 전체 장바구니를 없애고 선택된 장바구니 객체만 관리하는 경우
이 경우에는 정보 갱신은 한 번만 해주면 되지만 페이지를 이동할 때마다 db에서 카트 정보를 가져오고 선택된 장바구니를 토대로 선택 정보를 업데이트 해주어야 합니다.

3. 선택되지 않은 장바구니와 선택된 장바구니로 분리하여 관리하는 경우
정보 갱신은 하나의 객체에서만 해주어도 괜찮지만 2번과 마찬가지로 페이지를 이동할 때마다 db에서 카트 정보를 가져오고 선택 정보를 업데이트 해주어야 합니다.

위 세 방식 중에 어떤 방식이 더 적절할지 고민이 많이 되는 것 같습니다!
그런데 고민하다보니 1번처럼 페이지를 이동할 때마다 db에서 데이터를 받아오지 않으면 상품 정보가 바뀌어도 알 수 없겠다는 생각을 했습니다. 하지만 페이지를 이동했을 때 상품이 삭제되어 카트 상품이 유저 모르게 삭제되어 있다면 그것도 문제이지 않을까 하는 생각도 드네요... 이런 경우에는 상품이 삭제되어도 며칠 동안은 데이터를 유지한채로 유저가 삭제된 상품을 주문하려고 할 때 삭제된 상품임을 알리고 카트에서 삭제하는 것이 좋지 않을까 하는 생각까지 하게 되었습니다 😅

리뷰어님의 생각은 어떠신가요? 🤔
저는 상품의 가격이 변동되었을 경우에는 카트 정보도 업데이트 되어야 하기 때문에 페이지 이동시마다 db에서 정보를 가져오는 것이 낫다고 생각했습니다!
또한 굳이 선택되지 않은 장바구니까지 관리할 필요가 있을까 하는 생각이 들어 2번 방법이 가장 적절하지 않을까 생각했어요! 😄

2023-05-22 06:53 UTC, ippnsj commented on app/src/main/java/woowacourse/shopping/cart/CartContract.kt
> +        fun updateCartTotalAmount(amount: Int)
하지만 2번처럼 하게 되면은 처음 카트 화면을 들어갔을 때 모든 카트 상품이 선택된 상태일 수 있도록 하려면 init에서 모든 카트 상품을 가져와서 선택 장바구니에 넣어야 할 것 같습니다..!
초기에만 전체 카트 상품을 가져오더라도 페이지 이동 시에는 페이지에 해당하는 카트 상품만 가져오니까 pagination에 어긋나지 않는다고 생각해도 괜찮을까요...? 🥲

2023-05-22 07:03 UTC, ippnsj commented on app/src/main/java/woowacourse/shopping/cart/CartContract.kt
> +        fun updateCartTotalAmount(amount: Int)
아니면 초기에 전체 카트 상품을 가져오는 대신 3번처럼 선택되지 않은 장바구니도 관리해서 db에서 데이터를 가져왔을 때 선택 여부를 업데이트할 수도 있을 것 같아요! (db에서 처음 데이터를 가져온 순간에는 모두 선택되어 있다고 보고 선택되지 않은 장바구니에 존재할 경우 선택 안됨으로 변경)

2023-05-22 08:31 UTC, ippnsj commented on app/src/main/java/woowacourse/shopping/cart/CartContract.kt
> +        fun updateCartProduct(prev: CartProductModel, new: CartProductModel)
DiffUtil을 말씀하시는 건가요??

2023-05-22 08:54 UTC, ippnsj commented on app/src/main/java/woowacourse/shopping/cart/CartContract.kt
> +        fun updateCartProductCheckedInPage(isChecked: Boolean)
updateAllChecked() 는 전체 선택이 되어있는지 아닌지 확인해서 전체 선택 체크박스를 업데이트 하는 역할을 합니다.
updateCartProductCheckedInPage(isChecked: Boolean) 는 전체 선택 체크박스를 클릭했을 때, 페이지 내의 모든 카트 상품의 선택 여부를 업데이트 하는 역할을 합니다.

함수명만 보았을 때는 둘의 차이가 잘 드러나지 않는 것 같아요...!
updateAllChecked 대신 determineAllChecked 는 어떨까요...? 😅
저도 저만의 함수명 컨벤션을 구축하면 좋을 것 같네요ㅠㅠ 🥲

2023-05-22 14:09 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/cart/CartContract.kt
> +        fun updateCartTotalAmount(amount: Int)
제 의도는 도메인 레벨에서 선택된 장바구니를 관리하는 것은 아니였습니다.
선택된 장바구니의 상태는 UI의 상태이기 때문에 프레젠테이션 레이어에서 결정이 필요합니다.

결론적으로 선택 개수와 총 가격등은 장바구니라는 데이터 안에서 결정이 되기 때문에 별도의 객체로 만드는 대신 이런 식으로도 사용을 해 볼 수 있지 않을까 합니다.

```
class Cart {
   fun getSelectedProducts(): Products
}

// presenter
fun foo() {
   val selectedProducts = cart.selectedProducts()
   val totalPrice = ...
   val totalCount = ...
   view.updateXXX(totalPrice, totalCount)
}
```

2023-05-28 13:13 UTC, ippnsj commented on app/src/main/java/woowacourse/shopping/cart/CartActivity.kt
> +            }
카트 상품이 레포지토리에서 처음 온 상태 그대로 저장해 두었다가 액티비티가 finish 될 때 비교하여 다르다면 변경되었음을 뷰에 알리도록 변경하였습니다!
즉, 최종적으로 상품의 수량이 변화하지 않는다면(상품 개수를 하나 늘리고 다시 하나 줄이는 경우 등) 뷰에 알리지 않습니다! 😊

2023-05-28 14:08 UTC, ippnsj commented on app/src/main/java/woowacourse/shopping/cart/CartAdapter.kt
> +    private val onPlusAmountButtonViewClick: (Int) -> Unit = { onPlusAmountButtonClick(cartProducts[it]) }
리스너가 많아지면서 어댑터 생성자가 복잡해진 것 같아서 '카트 상품 리스너' 와 '카트 네비게이션 리스너' 객체를 생성하여 생성자로 넘겨주도록 수정하였습니다!

2023-05-29 03:40 UTC, ippnsj commented on app/src/main/java/woowacourse/shopping/cart/CartContract.kt
> +        fun updateCartTotalAmount(amount: Int)
**변경된 점** : 말씀대로 선택된 장바구니의 상태는 UI의 상태라고 판단하여 프레젠터에서 해당 데이터인 cart를 관리하도록 하였습니다!

**변경되지 않은 점** : 다만, cart에 저장되는 cartProduct는 사용자가 접근한 페이지의 상품만 이어서 사용자가 접근하지 않은 페이지의 cartProduct는 가지고 있지 않습니다! (장바구니 접근 시 모든 카트 상품을 가져오는 대신, 각 페이지에 해당하는 카트 상품만 가져와서 저장하다보니 그렇습니다!)
하지만 totalPrice나 totalCount는 모든 카트 상품에서의 총 가격과 총 수량을 의미하기 때문에 위 코드에서 보여주신 것처럼 현재 저장된 cart에서 selectedProducts를 가져오더라도 접근하지 않은 페이지의 상품은 없기 때문에 총 가격과 총 수량 계산이 불가합니다!ㅠㅠ (접근하지 않은 페이지의 상품은 B마트와 동일하게 모두 선택되어 있다고 가정했어요!)
그래서 totalPrice와 totalCount는 장바구니 접근 시 SUM과 COUNT sql 함수를 사용하여 가져오고 수량이 변경될 때마다 값을 변경하도록 하였습니다!

**커밋** :

2023-05-29 05:35 UTC, ippnsj commented on app/src/main/java/woowacourse/shopping/cart/CartPresenter.kt
> +        if (currentPage == 0) view.updateNavigationVisibility(determineNavigationVisibility())
Page 라는 객체를 만들어서 값이 0보다 작은지 확인하도록 하였습니다!
프레젠터에서는 Page 가 첫 페이지인지 확인하고 첫 페이지가 아니라면 이전 페이지로 이동하는 로직을 수행하도록 하였습니다!
PageTest 에서는 페이지의 값이 0보다 작을 수 없다는 것을 예외 처리 발생 여부를 통해 확인했고,
CartPresenterTest 에서는 Page가 첫 페이지일 때 이전 페이지 이동 로직이 실행되지 않고, 첫 페이지가 아닐 때 이전 페이지 이동 로직이 실행되는지를 확인하였습니다! 😊

커밋 :

2023-05-29 05:41 UTC, ippnsj commented on app/src/main/java/woowacourse/shopping/cart/CartPresenter.kt
> +        view.updateAllChecked(isAllChecked)
상품들에 대한 목록도 데이터에 해당한다고 생각하여 Repository에서 관리하고 있었습니다!
리뷰어님 말씀처럼 상품 체크 여부는 UI의 영역이라고 생각합니다!
그래서 프레젠터가 상품들에 대한 목록을 가지고 있도록 하였고 프레젠터에서 전체 체크 여부를 확인하도록 하였습니다! ^-^

2023-05-29 06:10 UTC, ippnsj commented on app/src/main/java/woowacourse/shopping/cart/CartPresenter.kt
> +        view.updateCartTotalAmount(cartTotalAmount)
현재는 상품들의 목록에 접근한 페이지에 해당하는 상품들만 존재하기 때문에 총 가격과 총 개수를 구할 수 없다고 판단하였습니다!
그래서 서버로부터 초기에 총 가격과 총 개수를 받아와서 수량이 변경되거나 선택이 취소될 때 값을 변경하도록 하였습니다! 🤗
상품 목록이 전체 상품을 가지고 있지 않은 이유는 pagination을 구현하는데 장바구니 화면으로 이동 시 전체 상품을 모두 한 번에 가져오면 pagination의 의미가 없다고 생각하여 페이지를 이동할 때 각 페이지에 필요한 상품만 받아오도록 구현하였기 때문입니다~!

2023-05-29 06:33 UTC, ippnsj commented on app/src/main/java/woowacourse/shopping/cart/CartPresenter.kt
> +        val cartCount = cartRepository.getAllCount()
판매자에 의해 상품 자체가 삭제되면서 카트 상품이 삭제되어 전체 개수가 변경될 수 있다고 판단하여 매번 서버에서 전체 개수를 가져오도록 했던 것 같습니다!
현재로서는 판매자에 의한 상품 삭제 기능이 없으므로 매번 서버로부터 전체 개수를 가져올 필요는 없습니다!

2023-05-29 07:17 UTC, ippnsj commented on app/src/main/java/woowacourse/shopping/cart/CartPresenter.kt
> +        val productTotalPrice = cartProduct.product.price * cartProduct.amount
CartProduct 가 스스로 반환하도록 수정하였습니다! 🥲

2023-05-29 07:20 UTC, ippnsj commented on app/src/main/java/woowacourse/shopping/cart/CartPresenter.kt
> +        cartRepository.replaceCartProduct(prev, new)
리팩토링 이전에 상품 목록을 repository에서 관리하면서 db에 상품 정보를 수정해야할 경우 modify, 저장된 상품 목록을 교체해야 하는 경우 replace를 호출했습니다 😅
상품 목록을 프레젠터에서 관리하면서 replace 함수는 삭제하였습니다!

2023-05-29 07:41 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/cart/CartPresenter.kt
> +        view.updateCartTotalAmount(cartTotalAmount)
넵, 페이지가 구현이 되어있다면 현재 목록으로부터 전체를 도출하기 어려울 수 있겠네요.

2023-05-29 08:12 UTC, ippnsj commented on app/src/main/java/woowacourse/shopping/common/model/ShoppingProductModel.kt
> +package woowacourse.shopping.common.model
app 모듈 안에 있어서 app 모듈 안에서는 어디서든 접근 가능하다는 의미로 common.model 패키지로 두었는데 오해의 소지가 있겠네요!
ui 패키지를 추가하고 model 및 ui 관련 패키지를 모두 하위 패키지로 이동하였습니다! 😊

2023-05-29 08:26 UTC, ippnsj commented on app/src/main/java/woowacourse/shopping/data/cart/CartRepositoryImpl.kt
> +    private var cart: Cart = Cart(emptyList())
상품 목록을 관리하고자 했는데 그렇다 하더라고 굳이 생성자로 받을 필요는 없을 것 같아요!
해당 프로퍼티는 프레젠터가 상품 목록을 관리하도록 수정하면서 삭제했습니다! 😊😊

2023-05-29 08:46 UTC, ippnsj commented on app/src/main/java/woowacourse/shopping/data/product/ProductRepositoryImpl.kt
> +import woowacourse.shopping.server.ProductRemoteDataSource
서버도 데이터를 가져오는데 주 목적이 있으므로 데이터 레이어에 포함될 수 있겠다는 생각이 듭니다!
.data.server 로 수정하였습니다~!

2023-05-29 09:13 UTC, ippnsj commented on app/src/main/java/woowacourse/shopping/productdetail/ProductDetailActivity.kt
> +    private var recentProductModel: ProductModel? = null
extra로 넘어온 값을 확인하고 존재하면 저장해 두었다가 프레젠터로 넘겨주기 위해 가지고 있게 했습니다.
프레젠터에 넘겨준 이후에는 불필요한 데이터이기 때문에 프레젠터를 init할 때 extra를 체크하도록 하였습니다!

2023-05-29 11:36 UTC, ippnsj commented on app/src/main/java/woowacourse/shopping/productdetail/dialog/CartProductDialogPresenter.kt
> +        }
데이터베이스의 역할일수도 있을 것 같다는 생각이 들어 반영하였습니다!

2023-05-29 16:13 UTC, ippnsj commented on app/src/main/java/woowacourse/shopping/shopping/ShoppingPresenter.kt
> +        updateCartAmount()
변경된 상품과 변화된 수량을 장바구니 페이지와 상품 상세 페이지에서 받아와서 업데이트 하도록 수정하였습니다!
상품이 삭제되지 않는 한 다른 변경점은 없다고 판단하여 변경된 상품을 서버에서 새로 가져오지 않았습니다.
만약 판매자가 상품을 삭제하여 변경된 상품이 없어진다면 변경된 상품만 서버에서 다시 불러오는 것보다는 모든 상품 목록을 다시 불러오는 것이 낫다고 판단하여 판매자가 상품을 삭제하는 경우는 배제하고 생각하였습니다.

커밋 : [d500a26](https://github.com/woowacourse/android-shopping-cart/pull/35/commits/d500a262ac0d8730673ffa1dc4d22d30173facd9)

2023-05-29 16:21 UTC, ippnsj commented on app/src/main/java/woowacourse/shopping/shopping/ShoppingPresenter.kt
> +        return cartProduct
서버에 데이터가 없으면 repository 에서 데이터를 생성해서 반환하는 것이 적절하다고 생각하여 수정하였습니다!

2023-05-29 17:16 UTC, ippnsj commented on app/src/main/java/woowacourse/shopping/server/ProductRemoteDataSource.kt
> +class ProductRemoteDataSource {
RemoteDataSource 인터페이스를 만들어 클래스 내부 구현을 수정하는 대신 새로운 구현체로 교체할 수 있도록 수정하였습니다!

2023-05-29 18:03 UTC, ippnsj commented on app/src/main/res/layout/dialog_add_cart_product.xml
> +            app:layout_constraintTop_toTopOf="@id/dialog_cart_product_amount" />
반복되는 뷰 레이아웃 파일을 만들고 필요한 부분에 include 태크를 사용하여 뷰를 재활용할 수 있도록 하였습니다!

2023-05-29 23:58 UTC, laco-dev approved these changes
장바구니 미션 고생 많으셨습니다.

끝까지 마무리하려고 열심히 해주시는 모습이 보기 좋았습니다.
배우고 경험하신 것들을 남은 미션 그리고 앞으로도 잘 활용 해보셨으면 좋겠습니다.

2023-05-29 23:58 UTC, merged