[멧돼지] 3, 4단계 쇼핑 장바구니 제출합니다.
woowacourse/android-shopping-cart pull request #36
Opened 2023-05-22 03:37 UTC by 2chang5

안녕하세요 페로로님!!! 
페로로님의 귀한리뷰를 많이 받고싶었는데 제실력이 부족해서 빠르게 마무리하지 못해 리뷰 핑퐁이 안되어서 슬프네요 ㅠㅠ
페로로님의 리뷰는 정말 딱딱 꽂히는게 피와살이 되는것 같습니다!!

이번미션을 진행하면서 급하게 진행하다보니 중간에 DB저장로직을 잘못짰다는 생각이 들었지만 들어내지 못했습니다. 
DB로직이 잘못되었다고 생각하는부분은 최초에 장바구니 아이템을 ID를 부여하여 관리하려고 설계하였지만 구조상 장바구니에는 ID가 필요없음을 느꼈습니다.
상품 ID를 통해서 CRUD를 하게되더라고요. 한가지 로직만 장바구니 아이템 ID 를 사용하고있는데 이 마져도 상품 ID를 통해 대체할수 있었습니다. 물론 빠르게 들어내는게 좋겠지만 DB를 다루는 실력이 미숙하여 중간에 들어내지 못하고 우선 구현에 초점을 맞췄습니다.
궁금했던점이 분명 모든 최초설계와는 다르게 돌아가는 경우가 분명 있을텐데 실무에서도 이런 상황이 있어 고치지 못하는경우가 더러있나요?
설계에 분명 많은 시간을 투자했는데 이렇게 중간에 문제가 생기는것을 보고 좀더 설계에 진지하게 임해야  하나 라는 생각이 들어서 질문드립니다.

이번미션을 진행하며 많은 고민을 해봤지만 풀리지않는 고민이 2가지 있었습니다.
1. 비동기처리시 Repository 혹은 DataSource가 어떤 형태를 취해야하는가?
기존에 안드로이드 프로젝트를 진행할때는 자세하게 학습하지는 못하였지만 코루틴과 레트로 핏을 사용하고 라이브데이터를 사용하여 화면을 업데이트 하는 형태를 취했습니다.
레트로핏에서 suspend 를 지원하는것을 통해 retrofit에서 사용할 service interface의 Http 통신 함수를 suspend로 놓고 함수의 반환을 통신을 통해 받아올 자료형으로 놓았습니다. 이후 datasource나 Repository 함수들도 다 suspend 로 처리였습니다. 뷰모델에서 뷰모델 스코프를 열어서 안에서 비동기적으로 데이터를 받아온후 그것으로 라이브데이터를 업데이트 하는 형태를 취해서 스레드를 블록하지않고도 처리할수 있는 형태를 띄었던것 같습니다. 
이런형태를 생각하고 현재 ShoppingCart 로직을 작성하였는데 Thread혹은 OkHttp에서 제공하는 Callback을 통해서 처리하려니 구조가 잘못된것 같다고 생각하였습니다. 현재 ShoppingCart 로직 또한 DataSource에서 부터 통신을 통해 불러오려는 자료형을 반환하도록 작성하였습니다.
하지만 Okhttp의 enqeue 를 사용하려고 시도하였을때 반환되는 response값을 Datasource에서 return 할수가 없었습니다.
로직이 비동기적으로 처리가 되는데 DataSource에 변수를 만들고 그안에 서버통신의 결과값을 담는다 한들 비동기처리가 끝날때까지 Block해서 막지 않는이상 DataSource에서 return을 통해 데이터를 받아 올길이 없었습니다.(비동기 처리가 끝나 반환할 변구에 데이터를 담기전 이미 datasource의 함수가 이미 return 하게됨)
이는 Thread를 사용해도 마찬가지였는데 비동기처리를 위해 Thread를 열어준다 한들 Datasource에 있는 함수들에서 List<Product> 이런형식으로 반환받으려면 Thread를 블록해놓고 데이터를 받아서 반환하는 형태를 띄어야했습니다.
이러면 비동기 처리에대한 이점이 1도 없고 비동기 처리가 길어지면 Block이 오래걸려 문제가 생각수 있다고 생각하였습니다.

그래서 callback으로 처리해줄 함수를 인자로 전달받는 형태를 취하여 Repository에서 처리해주는 형태로 개선해야하나 생각을 해보았습니다
```Kotlin
//현재 코드
fun getPartially(size: Int, lastId: Int): List<Product>

//개선 코드
fun getPartially(size: Int, lastId: Int, callBack: (List<Product>) -> Unit)
```
이렇게 한다면 Thread관련 로직들도 다 repository로 빠지므로 테스트도 수월해진다고 생각하였습니다.

하지만 callback또한 callback지옥을 맛볼수있고 문제가 있을수있다고 생각해서 선뜻 기존구조를 바꾸는게 손이안가서
리뷰어님께 조언을 들어보고 수정하고 싶었습니다.

코루틴의 장점으로 콜백을 없애고 동기적인 시선으로 비동기처리를 할수있다는 장점이 항상 명시되어있었던것 같은데 혹시 이런부분을 말하는것일까요?코루틴 이전의 비동기처리의 일반적인 형태가 이런형태가 맞는지 궁금합니다.

아니라면 Thread를 반환한다던지 다른 형태를 취함으로서 현재와 같은 구조와 비슷하게 개선할수 있을까요?

현재 코드의 형태는 통신을 main 쓰레드에서 금지한것을 우회하지만 작업이 끝날때까지 Thread를 블록하는 형태라 무조건 개선해야한다고 생각합니다.
조언부탁드립니다!!!

2. 상단(최근본상품) 리사이클러뷰 추가시 스크롤 조절 불가
리사이클러뷰의 구조가 복잡하다보니 상단 리사이클러뷰(최근본상품)가 여러 어댑터및 뷰홀더(RecentProductWrapperAdapter,RecentProductAdapter)에 둘둘 둘러쌓여있어 접근하는 방법이 떠오르지 않았습니다.
SmoothScroll을 호출해줘야하는 트리거는 ShoppingActivity의 activityResultLauncher에 있습니다.
어떤방식을 통해 상단 리사이클러뷰에 접근해야 깔끔하게 접근할수있는지 조언부탁드립니다.

긴 글 읽어주셔서 감사합니다!!!!

2023-05-22 10:22 UTC, laco-dev commented
> 궁금했던점이 분명 모든 최초설계와는 다르게 돌아가는 경우가 분명 있을텐데 실무에서도 이런 상황이 있어 고치지 못하는경우가 더러있나요?
설계에 분명 많은 시간을 투자했는데 이렇게 중간에 문제가 생기는것을 보고 좀더 설계에 진지하게 임해야 하나 라는 생각이 들어서 질문드립니다.

고치지 못하는경우? 가 이정도 규모의 앱에서는 발생하면 안되죠ㅎㅎ
프로그램을 개발하는데있어 최초 설계는 일부분에 불과합니다. 대부분의 경우 유지보수를 하는데 많은 시간을 할애합니다.
실제로 기능이 추가되는 것도 기존의 기능에 무언가가 추가되는 일입니다.

최초 설계부터 모든것을 고려하고 잘만드는 것은 불가능합니다.
그렇기 때문에 우리가 지금까지 해오는 것들이 필요한 것입니다.
객체지향 프로그래밍, 모듈 분리, 테스트 코드 등 모든것은 유지보수를 위해서입니다.

2023-05-22 10:25 UTC, laco-dev commented
> 1.비동기처리시 Repository 혹은 DataSource가 어떤 형태를 취해야하는가?

욕심을 부리지 말라고 했는데, 결국 욕심을 부리셨군요
지금은 위 질문에 대해 답변을 드리지는 않으려고 합니다.  왜냐하면 서버와 통신하기 위해서는 반드시 비동기 통신으로 구현을 해야 하기 때문입니다.

비동기 통신을 구현하는 방법은 Callback, 리액티브, 코루틴 등 여러가지 방법과 역사가 있습니다.
각각 어떻게 구현하는지 예제를 통해 학습을 해야 하지만, 단시간에 익히기는 어렵습니다.

2023-05-22 10:31 UTC, laco-dev commented
> 2.상단(최근본상품) 리사이클러뷰 추가시 스크롤 조절 불가

최대한 단방향으로 UI 로직의 흐름이 이뤄질 수 있도록 하면 좋습니다.
이 과정으로 의도한 구현이 될 지는 모르겠지만,

스크롤을 발생시키는 상태를 정의하고, 그 상태를 바라보고 있는 뷰가 단순히 어댑터에 접근해서 스크롤을 변경하도록 합니다.
이펙트를 발생시키지 않고 각자의 역할만 할 수 있도록 할 수 있습니다.

이 내용은 지금은 이해가 안되실 수도 있어요.
LiveData라면 SingleLiveData를 참고 해 볼 수 있습니다.

2023-05-22 10:39 UTC, 2chang5 commented
> > 1.비동기처리시 Repository 혹은 DataSource가 어떤 형태를 취해야하는가?
> 
> 욕심을 부리지 말라고 했는데, 결국 욕심을 부리셨군요 지금은 위 질문에 대해 답변을 드리지는 않으려고 합니다. 왜냐하면 서버와 통신하기 위해서는 반드시 비동기 통신으로 구현을 해야 하기 때문입니다.
> 
> 비동기 통신을 구현하는 방법은 Callback, 리액티브, 코루틴 등 여러가지 방법과 역사가 있습니다. 각각 어떻게 구현하는지 예제를 통해 학습을 해야 하지만, 단시간에 익히기는 어렵습니다.
![image](https://github.com/woowacourse/android-shopping-cart/assets/54737136/7b81f4b3-af4c-4255-b5f5-242208707609)
좀더 본질에 집중해 보겠습니다 ㅠㅠ

2023-05-22 12:49 UTC, laco-dev requested changes
3, 4단계 미션 고생 하셨습니다.

질문주신 내용은 커멘트로 따로 남겼습니다.
다음 서버와의 협업을 위해서 인터페이스와 관련된 내용을 위주로 리뷰를 남겼습니다.

마감 기한이 다가오면서 스스로 잘 알고 있던 내용도 다시 잘못 짜는 듯한 느낌을 조금 받았습니다.
다시 한번 강조하지만 욕심을 부리기 보다는 스스로 잘 하고 있는 내용부터 집고 넘어가는게 좋겠습니다.

다음 서버 미션에 대해서는 진행 속도가 중요하기 때문에 UI나 다음 미션중에 충분히 변경될 수 있는 내용은 생략하셔도 됩니다.

2023-05-22 12:49 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/ui/basket/BasketContract.kt
> +import woowacourse.shopping.domain.Product
UI 모델만 사용하기로 하지 않았나요?
View에서 도메인 모델도 알고있게 만들어진 이유가 무엇일까요?

2023-05-22 12:49 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/ui/basket/BasketActivity.kt
> +        setResult(Activity.RESULT_OK, ShoppingActivity.getResultIntent())
setResult의 Data 담는 올바른 방법이 아닙니다.
BaseketActivity를 실행한 화면에 결과를 돌려주는데, ShoppingActivity를 접근하는게 맞을까요?

이 화면을 실행한 곳이 ShoppingActivity가 실행 될 것을 고려하고 했을까요?

2023-05-22 12:49 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/ui/basket/BasketActivity.kt
> +            presenter::updateBasketProductCheckState
콜백 함수가 늘어나면, 인터페이스 리스너를 사용해보세요

2023-05-22 12:49 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/ui/basket/BasketContract.kt
> +        fun fetchTotalCheckToCurrentPage(totalIsChecked: Boolean)
함수에 의미를 부여하다보면, 오히려 불필요한 내용이 섞여서 길어지는 경우가 있어요.
저라면 이런식으로 지어볼 것 같아요.
```kotlin
fun checkAllProducts(checked: Boolean)
```

2023-05-22 12:49 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/ui/basket/BasketContract.kt
> +        fun updateNextPage()
다음 페이지와 이전 페이지를 이동하는 역할 같은데, update라는 의미와 맞을까요?

2023-05-22 12:49 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/ui/basket/BasketPresenter.kt
> +        basket.getSubBasketByStartId(startId, BASKET_PAGING_SIZE).products.none { !it.checked }
장바구니에 있는 상품들이 모두 선택되어있는지를 확인하는 로직인 것 같네요.

레벨 1에서 자주 들었던 내용 기억하시죠?
Basket에게 메시지를 보내서 협력하도록 만들어보세요

2023-05-22 12:49 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/ui/basket/BasketPresenter.kt
> +    }
updateCurrentPage(boolean)으로 이어지는 로직이 단순히 코드 중복을 피하기 위해 분리한 것 같지만,
실제로는 updateCurrentPage라는 이름과 잘 매치가 되지 않는 것처럼 느껴집니다.
아래 스닙핏을 한번 참고 해보세요

```kotlin
override fun updatePreviousPage() {
   val previousPage = currentPage.previous()
   updatePage(previousPage)
}

override fun updateNextPage() {
   val nextPage = currentPage.next()
   updatePage(nextPage)
}

private fun updatePage(page: ...) {
   if (currentPage == page) return
   currentpage = page
   fetch(...)
   view.xxx()
}
```

2023-05-22 12:49 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/ui/model/BasketProduct.kt
> +    val checked: Boolean
코틀린의 프로퍼티는 자바로 컴파일이 될때 기본적으로 getXXX() setXXX() 형태로 만들어지고는 합니다.
그런데 Boolean 타입인 경우 isXXX 형태로 시작하면 자바 코드는 isXXX() setXXX() 형태로 만들어집니다.

그래서 Boolean 타입의 경우 일반적으로 isXXX 형태로 작성을 합니다.

확인하는 방법은 코틀린을 자바로 변환하는 방법을 찾아보시면 됩니다

2023-05-22 12:49 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/ui/productdetail/ProductDetailContract.kt
> +        fun setBasketDialog()
프레젠터 입장에서 View가 다이얼로그를 띄울지, 토스트를 띄울지, 새 화면을 띄울지를 알 필요가 있을까요?
이것은 구현하는 View의 책임으로 봐야 하지 않을까요?

지금 구현에서는 이후 다이얼로그가 아닌 화면을 띄워야 한다면, 인터페이스도 모두 수정이 불가피합니다

2023-05-22 12:49 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/ui/productdetail/ProductDetailContract.kt
> +        )
MVP 패턴에서 콜백 형태로 로직을 주고받는 것은 잘못된 사용 방법입니다.

필요에 따라 다시 프레젠터의 인터페이스를 호출해서 흐름을 이어가야 합니다

2023-05-22 12:49 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/ui/productdetail/ProductDetailPresenter.kt
> +        }
var의 경우 변수로 할당함으로써 불필요한 null 체크를 피할 수 있습니다.
아래 내용과 비슷한 것 같네요?
https://woowacourse.slack.com/archives/C04JY0TMESZ/p1684572629180279

2023-05-22 12:49 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/ui/productdetail/ProductDetailPresenter.kt
> +        currentProduct = previousProduct ?: throw IllegalStateException(NO_PREVIOUS_PRODUCT_ERROR)
데이터가 없으면 "앱을 죽여야" 할까요?
흐름상 충분히 발생할 수 있는 것이라면, 비즈니스 오류로 봐야 할 문제일지 고민을 해야 합니다.

필요에 따라 View에게 오류를 "전파" 해야 할 수도 있습니다

2023-05-22 12:49 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/ui/shopping/ShoppingActivity.kt
> +                presenter.fetchRecentProducts()
함수를 두번 나눠서 호출하지 않고 하나의 함수로 의미를 대신할 수 있지 않을까요?
```kotlin
presenter.refresh()
```

2023-05-22 12:49 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/ui/shopping/ShoppingContract.kt
> +import woowacourse.shopping.domain.Product
요기서도 domain을 사용하고 있네요.

2023-05-22 12:49 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/ui/shopping/ShoppingPresenter.kt
> +    private var lastId: Int = -1,
이 값이 생성자로 주입해서 얻는 장점이 무엇일지 궁금하네요.

마지막 페이지의 여부와 마지막 아이디는 Repository로부터 가져온 데이터에 의해 결정이 되는게 아닐까요?

2023-05-22 12:49 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/ui/shopping/ShoppingPresenter.kt
> +        view.updateProducts(totalProducts)
var를 이용해서 구현을 하신다면 주의해야 할 점이 있습니다.
만약 Repository로 요청한 minus() 요청이 실패한다면 어떻게 될까요?
그리고 오류가 즉시 발생하지 않고 아래의 코드가 이어서 호출한다면 어떻게 될까요?

UI를 업데이트 하는 것은 비즈니스 로직을 호출한 결과에 의해 만들어진 다음 상태가 되어야 합니다.

위 내용에 대해서는 MVP 보다는 이후 학습하게 되실 MVVM 패턴에서 다시 고민 해 보시면 좋겠습니다.
오늘 남겨드린 피드백에도 이와 비슷한 힌트가 있습니다

2023-05-22 12:49 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/util/ListExtension.kt
> +fun <T> Iterable<T>.secondOrNull(predicate: ((T) -> Boolean)? = null): T? {
2번째 엘리먼트를 가져와야 하는 상황이 어떤 상황인가요?

2023-05-22 12:49 UTC, laco-dev commented on app/src/test/java/woowacourse/shopping/ui/basket/BasketPresenterTest.kt
> +    fun `전체 선택 토글 버튼을 눌러 전체 체크가 활성화되면 그에 반영하여 체크 값과 총가격,선택개수 가 업데이트된다(true 로 설정)`() {
프레젠터 입장에서는 어떤 버튼을 눌러 체크 상태로 바뀌고 그에 반영한다는 관심사를 알 필요가 있을까요?

어떠한 행동 그리고 기대되는 결과를 그대로 작성해도 좋습니다.
프레젠터는 비즈니스 로직을 수행하는 만큼 UI 입장 보다 도메인 입장의 이름을 작성해야 합니다.
필요하다면 테스트를 여러번 나눠서 작성해야겟죠?

```kotlin
> Test: 10,000원짜리 서로 다른 상품이 2개인 경우, 전체 선택을 하면 총 가격은 20,000원이다.
```

2023-05-22 12:49 UTC, laco-dev commented on app/src/test/java/woowacourse/shopping/ui/basket/BasketPresenterTest.kt
> +    fun `장바구니에 물품을 추가하면(물품 단일 추가버튼을 누르면) 화면(장바구니 물품 counter갯수,paging navigation 상태)정보와 장바구니 db 값 업데이트가 일어난다`() {
마찬가지로 데이터베이스를 업데이트를 실제로 했는지 확인하는 것도 중요하지만,
결과적으로 View에 어떠한 변화가 발생했는가를 추적하는게 더 중요하고는 합니다.

```kotlin
> Test: 장바구니에 상품이 하나도 없는 경우, 10,000원 짜리 상품을 장바구니에 담으면 전체 가격은 XX이다.
> Test: 장바구니에 10,000원짜리 상품이 하나 담겨있는 경우, 이 상품을 장바구니에서 삭제하면 ~ XXX
```

2023-05-22 12:49 UTC, laco-dev commented on domain/src/main/java/woowacourse/shopping/domain/Basket.kt
> +        else Basket(products + basketProduct)
매우 매우 깊군요... 무엇이 깊을까요?

2023-05-22 12:49 UTC, laco-dev commented on domain/src/main/java/woowacourse/shopping/domain/BasketProduct.kt
> +        if (product != other.product) return false
개수나 선택 상태가 다르면 equals()가 true를 반환하는게 맞을까요?

2023-05-29 02:23 UTC, 2chang5 commented on app/src/main/java/woowacourse/shopping/data/database/dao/basket/BasketDao.kt
> +    fun minus(basketProduct: DataBasketProduct)
이부분에 대해서 두가지 궁금한점이 있습니다!!!
1. Repository,presenter 와 datasource,dao같은 하위 구현체중 어디에서 복잡한 로직을 가져갈것인가? 
다음미션인 order 미션 진행하면서 네이밍과 api에 일치시키는 문제로 repository를 서버 api에 맞도록 단순화시켰습니다. 

그에 따라 LocalDao또한 단순화 시킨다면 조언해주신대로 add, minus, removebyProductId, getByProductId 이런 쓸데없이 난잡한 함수들을 제거할수 있다고 생각합니다.
하지만 사실상 복잡한 Dao 를 단순화 시킴으로써 상위의 presenter 혹은 Repository의 로직이 비효율적이고 난잡해지는 경향이 나타났습니다. 
제 개인적인 의견으로는 이런 데이터 관련된 복잡한 로직들을 presenter혹은 Repository에서 갖고있는것보다. 
db를 접근하거나 아니면 서버에서 접근하는 쪽에서 어느정도 가공해서 올려줘야 한다고 생각합니다.(만약 서버가 api를 만들어줄수 있다면 서버측에서 만들어주는것이 제일 이상적이라 생각합니다.)
-> 프리젠터는 이미 화면을 처리하고 그것을 제외한 도메인 로직을 처리하는것 만으로도 비대화 되어있을 뿐더러
데이터를 제공하는 쪽에서 데이터를 어느정도 가공해서 준다면 관심사 분리로 인해서 각각의 책임이 확실해지고 로직의 복잡성 역시 내려간다고 생각합니다. 
repository에서는 데이터를 어느정도 가공할수 있겠지만 각각의 데이터 저장소 별로 같은 api를 갖고있을거라는 보장이 없기 때문에 repository에서 그 다른 api들을 일치시키는 처리한다면 복잡성이 올라간다고 생각하여 repository보다 하위에서 Repository에서 요구하는 데이터에 맞도록 처리해줘야한다고 생각합니다.
repository에서는 데이터에 대한 일괄적인 처리 정도의 로직이 적당하지않나 생각합니다.

예를들어 getProductById가 있습니다. 
상품id를 통해서 상품객체를 불러와야하는 일이 종종 있어서 이 로직을 Dao에 추가하고 상대적으로 낮은 레벨에서 복잡한 구현을 해주고 
repository혹은 presenter 에서는 가져다 쓰게끔만 하였습니다.
하지만 서버를 붙이며 상품을 가져오는 api 가 getall 밖에 없어서 getProductById를 사용하는 사용처(presenter)에서 getAll을 한 이후에 id를 통해서 검색해서 product를 가져오도록 로직을 수정하였습니다.
하지만 이런 행위들은 상위의 로직을 복잡하게 한다고 생각합니다. 
물론 이 질문을 하면서 드는 생각이 애초에 presenter에서 처리할것이 아니라 getAll을 하고 productId를 통해 뽑아내는 로직을 DataSource에서 했어야했다는 생각이 듭니다.
이렇게 presenter를 복잡하게 유지하게 만드는것보다 datasource의 기능(함수)를 많이 늘려서 datasource는 복잡해지겠지만 presenter등 상위것들은 가볍게 유지하는 방향이 맞을까요?  

2. 기능을 짤때 서버관점으로 생각해야하는가?.
이부분 같은경우도 qpi를 정리하면서 서버에 맞게 정리하다보니 자연스럽게 정리된 경향이 있습니다. 하지만 다른것들을 짤때 같은 고민을 할것같아서 질문드립니다. 
우선 리뷰어님은 서버에서 생각하는 api 느낌으로 구조를 작성하시나요? -> 이번에 제공된 api명세가 서버의 관점으로 작성된 api라고 들었습니다.

서버에 맞추면 add는 최초 물품이 없을때 초기화 하고 update로 수량조절 remove로 아예 제거 이런식으로 사용하게 된것같습니다.

저는 처음에 생각항때 add같은경우 물건의 갯수를 더해주는것(만약 그 품목이 없다면 초기화해주고 갯수를 1로 만들어줌)
minus 같은경우 물건의 갯수를 빼주는것(만약 물품의 갯수가 0이 되면 물품 항목을 삭제해줌)
update 물건의 갯수를 한번에 조절할때 사용
remove 물건의 항목자체를 없애버림
이런식으로 생각하였습니다.
 
근데 이런식으로 생각하다보니 단순 add인데 중간에 뭐 삭제도하고 더해주기도하고 막 복잡한 로직이 섞여 들어간것 같습니다.

> add 내부에서 remove를 하는것이 의도한 동작이 맞을까요?

다른 사람이 봤을 때 왜??? 라는 의문이 계속해서 들지 않을까요?

이 리뷰에서도 마찬가지 상황이였습니다. 이렇게 add가 복잡해지는 상황을 피해야할까요? 
일반적으로 개발자가 생각하는 방향으로 맞춰야한다고 생각합니다.
저만 이런 방식으로 생각하고 일반적으로는서버가 생각하는 방식처럼 생각하는게 대부분일까요? 경험이 많으신 리뷰어님의 조언이 필요합니다.

2023-05-29 02:25 UTC, 2chang5 commented on app/src/main/java/woowacourse/shopping/data/database/dao/basket/BasketDao.kt
> +    fun overWriteUpdate(basketProduct: DataBasketProduct)
네이밍 자체가 익숙하지 않았던것 같습니다!!! 수정하였습니다

2023-05-29 02:30 UTC, 2chang5 commented on app/src/main/java/woowacourse/shopping/data/mockserver/ShoppingCartMockServer.kt
> +    val gson = Gson()
https://github.com/2chang5/android-shopping-order/blob/step1/app/src/main/java/woowacourse/shopping/data/remote/OkHttpModule.kt

다음미션에서 이런식으로 수정하여 사용하도록 변경하였습니다!!!

2023-05-29 02:32 UTC, 2chang5 commented on app/src/main/java/woowacourse/shopping/data/repository/BasketRepositoryImpl.kt
> +
이부분이 단순 구현에 치중하다보니 꼬여버린것같습니다. 장바구니를 페이지네이션 하지않고 관리하는 방법으로 변경하여 더이상 사용하지않아 제거하였습니다.

2023-05-29 02:38 UTC, 2chang5 commented on app/src/main/java/woowacourse/shopping/data/database/dao/recentproduct/RecentProductDaoImpl.kt
> +        removeByProductId(recentProduct.id)
이 부분에 있어서 제가 의도한것은
최근 본 상품은 겹치면 안되니 일단 최근 본 상품 목록에 현재 본 상품이 있다면 제거하고
추가하여 최근본 상품에는 해당상품이 하나만 있도록 유지하려 하였습니다. 
근데 이런부분에서 리뷰어님이 말씀해주신대로 다른 개발자가 와서 보면 무슨행위를 하고있는지 이해하지 못하겠다는 생각이 듭니다.
이런문제를 해결하려면 네이밍을 add가 아닌 nonDuplicateAdd 이런식으로 변경해줘서 해결할수 있을까요?

2023-05-29 02:40 UTC, 2chang5 commented on app/src/main/java/woowacourse/shopping/ui/basket/BasketContract.kt
> +import woowacourse.shopping.domain.Product
바보같이 실수를 한것같습니다. 의도에 맞지않아 수정하였습니다

2023-05-29 05:14 UTC, 2chang5 commented on app/src/main/java/woowacourse/shopping/ui/basket/BasketActivity.kt
> +        setResult(Activity.RESULT_OK, ShoppingActivity.getResultIntent())
말씀해주신 부분에 대해서 이해했습니다. 다른 크루원들의 코드를 살펴보니 애초에 데이터를 전달할 이유조차 없겠다 싶어서 전달하는데이터를 없애버렸습니다. 하지만 만약 데이터를 전달해야하는 상황이 반대로 상수값관리와 intent를 생성하는 행위를 결과를 돌려주는 Activity에서 해야겠다는 생각이 들었습니다.

2023-05-29 05:30 UTC, 2chang5 commented on app/src/main/java/woowacourse/shopping/ui/productdetail/ProductDetailContract.kt
> +        )
궁금한 점이있습니다 현재 minusProductCount, plusProductCount, updateBasketProduct 이 세 함수를 콜백을 통해서 받고있습니다. 
콜백을 통해서 받음으로 함수들을 private로 놓을수있어 캡슐화에 도움이 된다고 생각하였습니다. 
또한 세함수 모두 단순 presenter 의 데이터를 최신화시키는 로직이라 외부로 노출할필요가 없다고 생각합니다. 
이부분에서 콜백형태로 로직을 주고받지않고 외부로 노출했을때 얻을수있는 이점은 무엇인가요? 
한꺼번에 테스트 하는것보다 각각이 테스트 가능해짐으로써 테스트가 용이해질것 같다는 생각이 듭니다만 테스트이전에 캡슐화가 가장 우선순위가 높다고 생각이들어 콜백을 이용하면 안되는 이유를 여쭤보고 싶습니다

2023-05-29 05:31 UTC, 2chang5 commented on app/src/main/java/woowacourse/shopping/ui/basket/BasketActivity.kt
> +            presenter::updateBasketProductCheckState
감사합니다!!! 좋은방법을 생각조차 못했네요 ㅎㅎㅎ

2023-05-29 06:06 UTC, 2chang5 commented on app/src/main/java/woowacourse/shopping/ui/productdetail/ProductDetailContract.kt
> +        fun setBasketDialog()
수정하였습니다!!!

2023-05-29 06:16 UTC, 2chang5 commented on app/src/main/java/woowacourse/shopping/ui/basket/BasketContract.kt
> +        fun updateNextPage()
move라고 이름 지을수도 있겠지만 presneter에서는 data를 다루는것이라 생각하여 다음 페이지로 이동보다는 다음페이지로 데이터의 변화 라고 생각하여서 이름을 이렇게 지었는데 부자연스럽다면 수정해보겠습니다.

2023-05-29 06:37 UTC, 2chang5 commented on app/src/main/java/woowacourse/shopping/ui/basket/BasketPresenter.kt
> +    }
참고해서 수정해봤습니다. 단순 함수의 분리만으로는 가독성이 떨어질수도 있다는 생각이 들었습니다. 가독성은 오묘하네요

2023-05-29 06:46 UTC, 2chang5 commented on app/src/main/java/woowacourse/shopping/ui/model/BasketProduct.kt
> +    val checked: Boolean
방금 자바로 Decompile 해보았는데 

```
@Parcelize
data class BasketProduct(
    val id: Int,
    val count: UiCount,
    val isProduct: UiProduct,
    val isChecked: Boolean
) : Parcelable
```

```
  private final int id;
   @NotNull
   private final Count count;
   @NotNull
   private final Product isProduct;
   private final boolean isChecked;
   public static final Parcelable.Creator CREATOR = new Creator();

   public final int getId() {
      return this.id;
   }

   @NotNull
   public final Count getCount() {
      return this.count;
   }

   @NotNull
   public final Product isProduct() {
      return this.isProduct;
   }

   public final boolean isChecked() {
      return this.isChecked;
   }
```
변수앞에 is 가 붙으면 Boolean 이 아니더라도 getter의 이름이 isXXX라고 붙는걸 확인하였습니다.
Boolean 앞에는 is를 붙여주고 다른 타입에는 붙여주면 안되겠다고 판단했습니다!!

2023-05-29 07:00 UTC, 2chang5 commented on app/src/main/java/woowacourse/shopping/ui/productdetail/ProductDetailPresenter.kt
> +        }
가장 겉에있는 if문으로 있는 null check가 필요없으시단 말씀이신가요? Repository 의 getByProductId의 인자가 Nullable 하지않아서 if문으로 감싼것인데 어떻게 개선해야하는지 감이 오지않습니다 ㅠㅠㅠ

2023-05-29 07:10 UTC, 2chang5 commented on app/src/main/java/woowacourse/shopping/ui/productdetail/ProductDetailPresenter.kt
> +        currentProduct = previousProduct ?: throw IllegalStateException(NO_PREVIOUS_PRODUCT_ERROR)
앱이 동작할때 최초로 어떤 아이템을 상세조회 한다면 최근본상품이 존재하지않아 previousProduct값이 null 일수있고 이럴경우 previous product에  null 이 들어오며 null 이 들어온다면 이 함수가 불리지 않도록 사전처리를 하였습니다.
이 함수를 호출하기위한 버튼이 previousProduct값이 null 이라면 누르지못하게 Visible.Gone처리를 해서 만약 previousProduct값이 null 인데 버튼이 눌려 이함수에 진입한다면 논리적 오류라고 생각하여 개발자가 문제를 해결할수있도록 throw를 던지게 만들어놓았습니다.
정상적으로 앱이 동작한다면 previousProduct값이 null인 상태로는 이함수가 불려서는 안된다고 판단하였고 이 함수가 호출되었으면 설계결함이라고 생각하였는데 혹시 좀 더 유연하게 대처하는 방법이 있을까요?

2023-05-29 07:14 UTC, 2chang5 commented on app/src/main/java/woowacourse/shopping/ui/shopping/ShoppingContract.kt
> +import woowacourse.shopping.domain.Product
자꾸 실수하네요 ㅠㅠㅠ

2023-05-29 07:16 UTC, 2chang5 commented on app/src/main/java/woowacourse/shopping/ui/shopping/ShoppingPresenter.kt
> +    private var lastId: Int = -1,
처음에는 저도 생성자로 받지 않았는데 수업시간에 생성자를 통해서 이런값을 받으면 테스트하기 쉬울수있다는 이야기가 나와서 물론 이걸 테스트에 활용하지는 않았지만 일단 생성자로 빼놔봤습니다. 근데 생성자로 넣음으로 상황을 부여하는데는 더 편리하다고 생각합니다.

2023-05-29 07:30 UTC, 2chang5 commented on app/src/main/java/woowacourse/shopping/ui/shopping/ShoppingPresenter.kt
> +        view.updateProducts(totalProducts)
call back 를 통해서 성공시 로직을 변경한다던지 MVVM이라면 Basket자체를 옵저빙하여 ui를 업데이트 하는 방향으로 가져가야겠군요?

2023-05-29 07:32 UTC, 2chang5 commented on app/src/main/java/woowacourse/shopping/util/ListExtension.kt
> +fun <T> Iterable<T>.secondOrNull(predicate: ((T) -> Boolean)? = null): T? {
상품상세페이지로 진입시 최근본상품을 previous 상품으로 가져가는데 가장 최근 본 상품을 한번더 선택해서 상품 상세페이지로 진입시 두번째로 최근본 상품을 previous 상품으로 들고가기위해서 만들었습니다!!

2023-05-29 08:35 UTC, 2chang5 commented on domain/src/main/java/woowacourse/shopping/domain/Basket.kt
> +        else Basket(products + basketProduct)
indentation deep dive ..... 😢🙏

2023-05-29 08:49 UTC, 2chang5 commented on domain/src/main/java/woowacourse/shopping/domain/BasketProduct.kt
> +        if (product != other.product) return false
그냥 단순 product를 기준으로 겹치지 않도록하려고 로직을 작성했는데 잘못된것같네요. 근데 이로직은 직접 함수의 사용처를 찾아갈수도 없고 일단 보이는곳을 다 고쳐도 안고쳐진 부분에서 로직이 문제가 생기는경우가 있을것같은데 이런경우에 현명하게 equals를 제거하는 방법은 계속 테스트해보는 방법을 제외하고 없을까요?

2023-05-29 09:32 UTC, 2chang5 commented on domain/src/main/java/woowacourse/shopping/domain/BasketProduct.kt
> +        if (product != other.product) return false
테스트의 중요성을 느끼는것 같습니다

2023-05-29 09:36 UTC, 2chang5 commented on domain/src/main/java/woowacourse/shopping/domain/BasketProduct.kt
> +        if (product != other.product) return false
도메인의 equals를 설정할때는 굉장히 신중해야함을 느꼈습니다 프로젝트의 크기가 크거나 기준이 명확해야하는 앱이였다면 진짜 아찔합니다

2023-05-29 23:26 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/data/database/dao/basket/BasketDao.kt
> +    fun minus(basketProduct: DataBasketProduct)
오,,, 이건 지극히 경험에 기반한 답변이 될 것이라서,
앞으로 비슷한 구현을 수도 없이 많이 해보면 어느 정도 생각이 더 잘 잡히실 거라 생각됩니다.
팀마다 컨벤션이 다른 경우도 있어서 결론은 매번 달라요!

보통은 레포지터리 까지는 도메인 레이어이지만 데이터를 표현하는 이름으로 작성하고 데이터소스에서는 CRUD 형태로 작성하고는 합니다. 
다만 리모트 데이터소스는 서버 API에 맞게 도메인처럼 작성이 되고는 해요

```kotlin
val isLoggedIn: IsLoggedInUseCase()
class IsLoggedInUseCase {
   operator fun invoke(): Boolean = reposisotry.getUserHashId().isNotEmpty()
}

```

2023-05-29 23:27 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/data/database/dao/recentproduct/RecentProductDaoImpl.kt
> +        removeByProductId(recentProduct.id)
주석으로도 충분할 것 같네요?

2023-05-29 23:52 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/ui/productdetail/ProductDetailContract.kt
> +        )
꼭 사용하지 않아야 되는 건 아닙니다.
다만 private으로 숨기는 이점보다, View, Presenter가 스스로해야할 역할을 콜백에서 대신하는 것으로 잘못 해석될 수 있습니다.

단순히 Item에서 처리하는 정도라면 공식문서에서도 소개하고 있는 정도로 종종 사용은 되고는 하는데요.
https://developer.android.com/jetpack/guide/ui-layer/events?hl=ko#recyclerview-events

만약, View에서 어떤 화면을 띄우고 화면의 결과로 콜백을 전달하는 구조라면 문제가 발생할 수 있습니다.
메모리가 부족해서 프로세스가 재시작 한다면 어떻게 될지 상상해 보시면 됩니다.
(어려운 내용이라, 이해가 안될 수도 있습니다. 😢 )

또한 테스트가 용이해 질 것 같다는 부분에는 동의하지 않는데요.
각 콜백 함수는 뷰에서 호출하는 것인데 어떻게 테스트를 할까요?

2023-05-29 23:52 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/ui/productdetail/ProductDetailPresenter.kt
> +        }
변수로 할당

2023-05-29 23:53 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/ui/productdetail/ProductDetailPresenter.kt
> +        currentProduct = previousProduct ?: throw IllegalStateException(NO_PREVIOUS_PRODUCT_ERROR)
저는 아이템 타입을 만들어서 사용합니다
```kotlin
sealed class UiState{
   data class Loading(...)
   data class Success(...)
}
```

2023-05-29 23:54 UTC, laco-dev approved these changes
장바구니 미션 고생 많으셨습니다.

배우고 경험하신 것들을 남은 미션 그리고 앞으로도 잘 활용 해보셨으면 좋겠습니다.
남겨주신 질문에는 답변 남겨두었습니다.

2023-05-29 23:54 UTC, merged

2023-05-30 01:32 UTC, 2chang5 commented on app/src/main/java/woowacourse/shopping/ui/productdetail/ProductDetailContract.kt
> +        )
> 또한 테스트가 용이해 질 것 같다는 부분에는 동의하지 않는데요.
각 콜백 함수는 뷰에서 호출하는 것인데 어떻게 테스트를 할까요?

이런부분에 의해 콜백을 걷어낸다면 테스트가 용이해진다고 생각했습니다