[스캇] 3, 4단계 쇼핑 장바구니 제출합니다.
woowacourse/android-shopping-cart pull request #39
Opened 2023-05-22 07:13 UTC by chws0508

안녕하세요 토리! 스캇입니다!
저번 1,2 단계 리뷰 정말 많은 도움이 되었습니다! 감사합니다!

이번 미션에서는 LiveData를 이용한 상태관리와, Repository 패턴을 이용하는 것에 많은 집중을 하였습니다.
이번 리뷰에서는 Repository 패턴이 잘 적용 되었는지에 대해 리뷰를 받고싶고, LiveData와 ViewBinding을 이용하면서 도메인과 VIew 부분이 많이 혼용된 느낌이 드는데, 이것에 대해서도 리뷰를 받고싶습니다. 
또한, 많은 화면에서 사용되는 Counter 에대해서 CounterView 라는 Custom Layout 을 적용하였습니다. CounterView의 CounterPresenter는 숫자를 올리고 내리는 책임만 가지게 해놓았고, 다른 Activity Presenter 와 서로 협력하는 구조로 작성해 보았습니다.
이 부분에 대해서도 어떤 문제가 있을지 궁금합니다!

이번 리뷰도 잘 부탁드립니다!!

2023-05-22 22:00 UTC, galcyurio requested changes
미션 잘 진행해주셨네요 👍️
Custom View에서도 MVP를 적용해주시고 Presenter에 대한 테스트 코드도 잘 작성해주셨어요!
코멘트를 남겨두었으니 확인 후 다시 요청해주세요!

2023-05-22 22:00 UTC, galcyurio commented on app/src/main/java/woowacourse/shopping/data/mapper/Mapper.kt
> +fun JSONObject.toProduct(): Product {
혹시 json 직렬화 라이브러리를 쓰면 안된다는 제약 조건이 있었나요?
아니라면 하나씩 mapper를 만들면 힘드므로 gson, jackson, moshi와 같은 라이브러리를 써보면 어떨까요?

2023-05-22 22:00 UTC, galcyurio commented on app/src/main/java/woowacourse/shopping/data/product/ProductRepositoryImpl.kt
> +) : ProductRepository {
> 이번 리뷰에서는 Repository 패턴이 잘 적용 되었는지에 대해 리뷰를 받고싶고

모든 Repository 코드들을 잘 살펴보았는데 아래와 같은 관점에서 잘 구현되었네요 👍️

- Repository 내부에서 local, remote source를 구분해서 데이터를 가져온다.
- Repository 외부에서는 local, remote source에서 가져오는지 상관하지 않는다.

2023-05-22 22:00 UTC, galcyurio commented on app/src/main/java/woowacourse/shopping/data/product/ProductService.kt
> +    }
개인적으로는 Executor를 이용하여 직접 고정된 Thread Pool을 만들어 보는 것도 공부하는 단계에서는 굉장히 큰 도움이 될 거라 생각합니다.
이 방식은 이제 현업에서는 legacy로 여겨지지만 OkHttp와 라이브러리의 내부 코드에서는 위와 같이 Thread Pool을 만들어서 Thread를 재사용하기 때문에 내부 동작 방식을 이해하는데 도움이 될 수 있기 때문이에요.

2023-05-22 22:00 UTC, galcyurio commented on app/src/main/java/woowacourse/shopping/presentation/binding/ViewBinding.kt
> +    }
visibility에 대한 BindingAdapter는 Int 보다는 Boolean에 엮어주시는게 추후 확장성에 좋습니다.

2023-05-22 22:00 UTC, galcyurio commented on app/src/main/java/woowacourse/shopping/presentation/cart/CartPresenter.kt
> +    override val pageProducts: SafeLiveData<CartProductInfoList> get() = _pageProducts
`observe()`를 호출하지 않으므로 LiveData로 선언할 필요가 없습니다. 단순히 `var`로 선언하는 것으로도 충분하지 않을까요?

또한 MVP 이기 때문에 View에서 해당 값들을 참조하는 대신 Presenter에서 사용하여 View에 어떤 것을 그릴지를 명령해야 합니다.
Contract에서 `loadedCartProducts`, `pageProducts`를 제거해보고 View에 명령하도록 만들어보세요.

-------

아마 현재 구현된 방식이 더 편하고 가독성이 좋다고 느껴지실텐데요. (저도 그렇긴 합니다 😅)
그 이유는 LiveData와 DataBinding을 활용하는 방식은 MVVM 패턴이기 때문이에요.
MVP를 구현하시다가 더 편하고 좋은 방법을 찾다가 자연스레 MVVM으로 구현하시게 된 것 같아요.

하지만 이번 미션에서는 MVP로 구현하는게 목표이므로 가독성이 안좋아지더라도 MVP로 변경해보고 MVP에 대한 단점을 마음속에 깊이 기억해두시면 좋겠어요.

2023-05-22 22:00 UTC, galcyurio commented on app/src/main/java/woowacourse/shopping/presentation/common/CounterView.kt
> +}
> 많은 화면에서 사용되는 Counter 에대해서 CounterView 라는 Custom Layout 을 적용하였습니다. CounterView의 CounterPresenter는 숫자를 올리고 내리는 책임만 가지게 해놓았고, 다른 Activity Presenter 와 서로 협력하는 구조로 작성해 보았습니다.
이 부분에 대해서도 어떤 문제가 있을지 궁금합니다!

Custom View 구현 👍️
별도로 Custom View에서도 MVP 패턴으로 구현해주신 것도 좋습니다.

다만 이 코드 이외에서 다른 화면에서까지 CounterPresenter를 사용하는 것은 좋지 않습니다. 해당 화면에도 Presenter가 있을텐데 해당 Presenter의 역할을 침범하고 View에서는 어떤 Presenter를 사용해야할지 알고 있어야하기 때문이에요.

2023-05-27 15:56 UTC, chws0508 commented on app/src/main/java/woowacourse/shopping/presentation/cart/CartPresenter.kt
> +    override val pageProducts: SafeLiveData<CartProductInfoList> get() = _pageProducts
이번에 순수 MVP로 구현하면서 느낀점은, MVP 로 구현하면 테스트가 편해지고, 비즈니스 로직,데이터영역과 뷰 영역을 완전히 분리한다는 점에서 추후 리팩토링이나 확장성에 대해서는 이점이 있을 것 같습니다. 하지만 View 하나당 Presenter와 Contract 가 필요해서 클래스 양이 많아지고, 불필요한 코드가 많아지는 느낌을 받았고, 특히 RecyclerView의 ViewHolder의 뷰를 접근하고자 할 때 상당히 불편했던 것 같습니다...(LiveData 를 이용하면 편했었는데 말이죠...)

2023-05-27 15:57 UTC, chws0508 commented on app/src/main/java/woowacourse/shopping/presentation/common/CounterView.kt
> +}
한 화면당 하나의 Presenter만 사용해야 한다 라는 규약도 MVP 의 단점인 것 처럼 느껴지네요 ㅠ

2023-05-27 15:58 UTC, chws0508 commented on app/src/main/java/woowacourse/shopping/presentation/binding/ViewBinding.kt
> +    }
Boolean 이 확장성 뿐만 아니라 가독성도 더 좋다고 느껴지네요!

2023-05-27 16:17 UTC, chws0508 commented on app/src/main/java/woowacourse/shopping/presentation/binding/ViewBinding.kt
ViewBinding 은 단순히 뷰에 대한 참조를 얻는 것으로, 보통 findViewByID 를 대체하는데에 사용되고, 널 안정성과 타입 안정성을 보장해준 다는 점에서 findViewByID 보다 좋습니다. DataBinding은 xml layout 에서 직접 모델을 참조시키는 방식으로, 더 동적인 프로그래밍을 지원하고, 양방향 데이터 바인딩도 지원합니다. ViewBinding 이 DataBinding 보다 컴파일도 빠르고, 사용하기 쉬운 장점이 있지만, DataBinding이 지원하는 기능이 많기 때문에, 이 둘을 적절히 사용하는 것이 좋아보입니다!

2023-05-27 16:37 UTC, chws0508 commented on app/src/main/java/woowacourse/shopping/presentation/cart/CartPresenter.kt
> +    override val pageProducts: SafeLiveData<CartProductInfoList> get() = _pageProducts
추가적으로, CustomView에 대해 MVP를 적용한 것 처럼, ViewHolder에 대한 ViewHolderPresenter 를 만들어서 관리하는 건 MVP 패턴에서 어긋나는 부분일까요?

2023-05-28 07:29 UTC, chws0508 commented on app/src/main/java/woowacourse/shopping/data/product/ProductService.kt
> +    }
별도의 스레드를 생성하지 않고, Retrofit 이나 OkHttp 가 자체적으로 스레드를 생성하려면, enqueue 를 활용하여 비동기적으로 작업을 수행을 해야 하는데, 이 때 콜백을 어떻게 처리해야 할지 감이 안잡히네요...  지금 구조에서는 동기적으로 Repository 에서 바로 Domain 객체를 반환하여, 그 객체를 Presenter 가 이용하는 방식입니다. 하지만 비동기 방식으로 짜게되면, Repository에서 Call<List<Product>>를 반환하고, 그 반환 값을 Presenter 가 enqueue 를 통해 처리해야 구조로 바뀌게 되는 것일까요?? 그런데 이렇게 되면, 모든 View 코드에서 runOnUiThread 가 추가되어야 하고, Repository가 객체를 전달하는것이 아니라 Call로 감싼 객체를 전달하는 것이 옳은가에 대해서도 의문이 드네요. 다른 좋은 방법이 있을까요??

2023-05-28 07:32 UTC, chws0508 commented
https://github.com/woowacourse/android-shopping-cart/pull/39#discussion_r1208402956

2023-05-28 11:00 UTC, galcyurio requested changes
피드백 반영하느라 고생하셨어요! 👏 👏 
질문해주신 부분은 코멘트로 답변을 남겨두었습니다!

2023-05-28 11:00 UTC, galcyurio commented on app/src/main/java/woowacourse/shopping/data/product/ProductService.kt
> +    }
여러가지 방법이 있습니다!

1. 콜백함수를 넘겨서 처리
2. ExecutorService, Future API를 활용하여 Call 대신 Future or 직접 만든 객체를 반환
3. RxJava 활용
4. kotlinx.coroutines 활용

여러 방법을 써놓았는데 1번에서 4번까지 모두 조금씩 개선되었던 안드로이드의 역사입니다.
1번에서 일일히 콜백을 넘겨서 처리하다가 불편하니 값이 추후에 가지게 되는 Future를 쓰게 됩니다.
그러다가 좀 더 본격적으로 옵저버 패턴으로 구현한 RxJava가 나오고 reactive programming 패러다임이 인간의 사고방식과 많이 달라서 기존의 절차형 프로그래밍으로 돌아간 coroutines이 나온 것까지가 현재 상황입니다.

현재는 연습하는 단계이니 1번인 콜백함수를 직접 넘겨서 불편함을 느껴보시는 것도 좋을 것 같아요!

2023-05-28 11:00 UTC, galcyurio commented on app/src/main/java/woowacourse/shopping/presentation/cart/CartPresenter.kt
> +    override val pageProducts: SafeLiveData<CartProductInfoList> get() = _pageProducts
> 이번에 순수 MVP로 구현하면서 느낀점은, MVP 로 구현하면 테스트가 편해지고, 비즈니스 로직,데이터영역과 뷰 영역을 완전히 분리한다는 점에서 추후 리팩토링이나 확장성에 대해서는 이점이 있을 것 같습니다. 하지만 View 하나당 Presenter와 Contract 가 필요해서 클래스 양이 많아지고, 불필요한 코드가 많아지는 느낌을 받았고, 특히 RecyclerView의 ViewHolder의 뷰를 접근하고자 할 때 상당히 불편했던 것 같습니다...(LiveData 를 이용하면 편했었는데 말이죠...)

정확히 이해해주셨네요 👍 

> 추가적으로, CustomView에 대해 MVP를 적용한 것 처럼, ViewHolder에 대한 ViewHolderPresenter 를 만들어서 관리하는 건 MVP 패턴에서 어긋나는 부분일까요?

ViewHolder는 말그대로 View를 Hold하고 있는 객체입니다.
단순히 메모리를 아끼기 위해 View를 재활용하기 위한 객체이기 때문에 ViewHolder에서 Presenter를 쓰게 되면 객체의 역할을 넘어서게 됩니다.

2023-05-29 09:59 UTC, chws0508 commented on app/src/main/java/woowacourse/shopping/data/product/ProductService.kt
> +    }
일일이 콜백함수를 넘기는 과정... 상당히 힘들었네요! 그래도 이 과정이 앞으로 많은 도움이 될 것 같습니다!

2023-05-30 11:41 UTC, galcyurio approved these changes
피드백 반영하느라 고생하셨습니다 👍 
한 가지 코멘트를 남겨두었으니 확인해주세요!

다른 미션들이랑 병행하느라 힘들었을텐데 끝까지 잘 해주셨네요.
이번 미션은 여기서 마무리하도록 할게요!
다음 미션도 힘내세요!

2023-05-30 11:42 UTC, merged