[멘델] 1, 2단계 쇼핑 장바구니 제출합니다.
woowacourse/android-shopping-cart pull request #4
Opened 2023-05-11 08:31 UTC by rhthrhrl0

안녕하세요 제임스! 멘델입니다. 코치님들에게 처음 리뷰 받게 되었는데 잘부탁드립니다!
바쁘신 와중에도 리뷰해주셔서 감사합니다 :)

2023-05-12 03:15 UTC, woowajames requested changes
멘델 안녕하세요!
1, 2단계 기능 정말 잘 구현해주셨네요! 💯 
전반적으로 많은 고민을 했다는 것이 느껴져서 좋았습니다. 👍 
몇 가지 코멘트 남겼으니 확인하시고 다시 리뷰 요청 부탁드릴게요.

2023-05-12 03:15 UTC, woowajames commented on app/src/main/java/woowacourse/shopping/feature/main/recent/RecentAdapter.kt
> +        notifyDataSetChanged()
항상 전체를 갱신하는 방법 말고 다른 방법은 없을지 고민해보면 어떨까요?

2023-05-12 03:24 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/shopping/feature/main/MainActivity.kt
> +            presenter.loadProductsFromCache()
우선, 가장 큰 이유는 현재 앱 수준에서 뷰모델같이 액티비티이 생명주기보다 긴 객체가 존재하지 않아서입니다. 화면을 회전했을때 지금까지의 스크롤 상태를 유지하기 위해 ,기존에 스크롤했던 아이템들이 있어야 하기때문에 이걸 위해 만들었습니다. 
두번째 이유로는, 사용자의 사용관점을 위해 만들었습니다. 만약 화면 회전 전에, 지금까지 얻어왔던 개수의 정보만 복구해서 가져오고 이만큼 다시 디비에서 불러오려고 한다면.... 문제가 발생가능하다고 생각합니다. 예를 들어서, 사용자가 상품을 추가로 로드해서 상품a를 목록창에서 보고 있었는데 회전 하는 사이에 상품a가 사라지고 상품b로 교체되었다고 생각해보면, 사용자 입장에서는 단순히 화면 회전만 했는데 목록에서 보이던 상품a가 사라지고 상품b가 갑자기 보이는 문제가 발생가능합니다. 일단 보이는 것은 사용자 세션이 유지되는 동안 동일하게 해주는것이 맞다고 생각합니다. 대신 그 아이템을 클릭했을때에 대한 예외 처리는 필요하다고 생각합니다 :)

2023-05-13 15:03 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/shopping/feature/main/MainActivity.kt
> +            presenter.loadProductsFromCache()
캐싱과 관련된 책임을 ProductRepository에게 위임했습니다

2023-05-14 05:05 UTC, rhthrhrl0 commented
글을 늦게 올려서 죄송합니다 제임스!! 이번에 변경 사항은 아래와 같습니다.
# 변경사항
1. 프레젠터 내에서 데이터 관리, 어댑터는 프레젠터가 관리하는 데이터를 받아서 화면에 뿌려주는 용도로만 사용하도록 수정
2. 캐싱 객체를 레포지토리 객체 안에 위치시켰습니다. 이로인해 레포지토리 패턴에 좀 더 맞게 프레젠터는 해당 데이터가 어디서 왔는지 모르게 하도록 수정했습니다.
3. notifyItemDataSetChanged 지양하도록 로직 수정. 
4. 데이터 바인딩 가능하다고 지적 받은 부분들 적용.

# 미션을 진행하면서 생긴 궁금증
1. 현재 저는 도메인 모델과 매핑된 ui모델이 존재하고, 이 ui모델이 어댑터에 들어가기 위해 필요한 클릭 람다들을 자신이 소유해서 관리하고 있느느  ItemModel 이라는 개념이 존재합니다. 
페어 피드백에서 이 부분을 지적 받아서 고민이 생겼습니다. 만약 ItemModel이라는 개념이 없다면, 어댑터의 생성자에서 그 어댑터에 들어갈 수 있는 모든 뷰타입들에 대한 클릭 람다들을 주입 받아야 합니다. 이로인해 만약 새로운 뷰타입이 해당 어댑터에 들어오게 된다면, 어댑터의 생성자 부분에서 클릭 이벤트를 주입받는 부분에도 불가피한 변경이 발생 가능하다고 생각했습니다(해당 뷰타입들의 모든 람다를 모은 리스너 객체가 존재하더라도 그 리스너 내부에서 코드 수정이 발생하게 됩니다). 
그래서 저는 보통 ItemModel이라는 인터페이스로 어댑터에 들어가게될 모든 아이템들을 추상화 시키고, 뷰홀더의 bind 메소드 안에서 뷰홀더의 xml파일과 아이템모델을 이어줘서 xml 안에서 데이터바인딩을 활용해서 자체적으로 람다 연결을 해결하는 식인데,,, 제임스는 평소 어떤 방법을 사용하시나요?? 
아이템 모델이라는 추상화 개념이 오히려 너무 복잡한 코드 구조를 불러일으키는 것일까요??

2023-05-15 09:28 UTC, woowajames requested changes
멘델 안녕하세요.
피드백 반영 잘해주셨습니다. 추가적으로 수정해주신 부분도 좋았습니다. 👍 
따라서 소소한 코멘트 몇 가지 남겼으니 확인 부탁드릴게요.
질문은 오프라인에서 이야기 나눠보시죠!

2023-05-15 09:28 UTC, woowajames commented on app/src/main/java/woowacourse/shopping/util/BundleExtension.kt
> +inline fun <reified T : Parcelable> Bundle.getParcelableCompat(key: String): T? {
사용하지 않는 클래스 같네요!

2023-05-15 09:28 UTC, woowajames commented on app/src/test/java/woowacourse/shopping/feature/cart/CartPresenterTest.kt
> +    fun `처음 5개를 가져와 화면에 띄운다`() {
given when then 으로 나눠보면 좋겠습니다.

2023-05-15 09:28 UTC, woowajames commented on app/src/test/java/woowacourse/shopping/feature/cart/CartPresenterTest.kt
> +        verify { cartRepository.deleteProduct(any()) }
any() 보다는 가능한 기대하는 타입을 명시하면 어떨까요?

2023-05-15 09:28 UTC, woowajames requested changes
멘델 안녕하세요.
피드백 반영 잘해주셨습니다. 추가적으로 수정해주신 부분도 좋았습니다. 👍 
따라서 소소한 코멘트 몇 가지 남겼으니 확인 부탁드릴게요.
질문은 오프라인에서 이야기 나눠보시죠!

2023-05-15 11:46 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/shopping/feature/detail/DetailActivity.kt
> +            }
프레젠터 거치도록 수정했습니다!

2023-05-16 06:23 UTC, woowajames approved these changes
안녕하세요 멘델!
피드백 반영 잘해주셨네요! 👍 
다음 단계 진행을 위해 머지하도록 하겠습니다!
수고하셨습니다! 😄

2023-05-16 06:23 UTC, merged