[부나] 3, 4단계 쇼핑 장바구니 제출합니다.
woowacourse/android-shopping-cart pull request #45
Opened 2023-05-22 08:41 UTC by tmdgh1592

안녕하세요  말리빈 😃
지난 1, 2단계에서 주신 피드백을 다 반영하고 싶었지만 시간 관계상 `더 보기 버튼`에 대한 피드백은 아직 반영하지 못했습니다.. 😥
또한 Dao에서 사용하지 않는 메서드를 다 제거하지 못하고 리뷰를 요청하여 해당 코드는 피드백을 반영하면서 함께 정리하겠습니다!

바쁘신 와중에 리뷰해주셔서 감사합니다 😃
이번 리뷰도 잘 부탁드립니다~!!

2023-05-23 01:51 UTC, malibinYun requested changes
rebase 등을 활용해서 먼저 컨플릭을 제거하신 뒤 다시 리뷰 요청 부탁드릴게요 :)

2023-05-23 15:06 UTC, malibinYun approved these changes
3, 4단계 미션 고생 많으셨어요.
다음 미션 진행을 위해 바로 머지하겠습니다.
다음 미션엔 시간에 쫓기지 않게 관리를 잘 해 가며 완수해보셨으면 좋겠어요 :)
마지막 미션까지 잘 수행하시길 응원할게요 💪

2023-05-23 15:06 UTC, malibinYun commented on app/src/test/java/woowacourse/shopping/ui/cart/CartPresenterTest.kt
> +        assertEquals(currentPage.captured, Pagination(page + 1))
currentPage에 캡쳐되는 행위가 없는 것 같은데, 어떤 것을 검증한 것일까요?_?
또, 이 테스트에서는 slot을 활용하지 않고 테스트를 충분히 작성할 수 있어요. slot 없이 작성해보시길 바라요 :)

2023-05-23 15:06 UTC, merged

2023-05-24 15:54 UTC, tmdgh1592 commented
말리빈 피드백주셔서 감사합니다 : )
해당 피드백은 다음 미션을 진행하면서 함께 반영하겠습니다!

2023-06-02 05:55 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/shopping/ui/cart/CartContract.kt
> +    abstract class Presenter(protected val view: View) {
view와 presenter가 1:1 관계라고 생각해서 abstract로 선언하였습니다.
크게 차이가 없다고 생각하였는데, 지금 interface로 바꿔보니 View와 Presenter간의 Contract를 더 보기 편해서,
모두 interface로 변경하였습니다!

2023-06-02 05:57 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/shopping/data/datasource/product/RemoteProductDataSource.kt
> +            }
각각 동기 / 비동기 차이라고 알고 있습니다!
비동기로 구현하려고 했는데, 사실상 동기적으로 구현해버렸네요..!
현재는 callback으로 변경하였습니다!

2023-06-02 05:58 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/shopping/data/datasource/product/RemoteProductDataSource.kt
> +        val countDownLatch = CountDownLatch(1)
Main Thread가 block 된다고 생각합니다.
만약 계속해서 block된다면 심각한 경우 ANR로 이어질 수 있을 듯 합니다..!

2023-06-02 05:59 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/shopping/ui/cart/CartPresenter.kt
> +        view.updatePageNumber(currentPage.toUi())
View의 추상 메서드를 하나로 줄이고 Activity에서 별도로 분리해서 사용하도록 변경하였습니다!

2023-06-02 06:01 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/shopping/ui/detail/ProductDetailActivity.kt
> +        )
DB에서 바로 가져오도록 변경하였습니다!
화면 간 전달할 필요없이 최근 본 상품 데이터를 가져오는 것은 ProductDetail 관련 클래스의 역할이겠군요 🤔
또한, 데이터 불일치가 발생할 여지를 더 줄일 수 있을 것 같습니다!

2023-06-02 06:03 UTC, tmdgh1592 commented on app/src/test/java/woowacourse/shopping/ui/cart/CartPresenterTest.kt
> +    internal fun 종료하면_화면을_닫는다() {
테스트 코드가 실패하지 않도록 해보겠습니다!

2023-06-02 06:15 UTC, tmdgh1592 commented on app/src/main/java/woowacourse/shopping/ui/cart/CartPresenter.kt
> +    }
제가 아는 지식으로, MVP 아키텍처 패턴에서는 View에서 Presenter의 데이터를 직접적으로 접근해서 화면을 갱신하는 것이 아니라,
Presenter가 View에게 상태를 쥐어주고 변경을 요청하는 것으로 알고 있습니다!
즉, View가 가능한 passive 해야 하는데, 위 구조는 온전한 MVP가 아닌 듯 합니다.

Observer 패턴을 쉽게 활용할 수 있는 LiveData는 MVP보다는, MVVM에서 많이 활용된다고 알고 있습니다.
View가 ViewModel의 Observable한 State에 접근해서 화면을 자동으로 갱신할 수 있기 때문입니다.

위 코드를 MVP에 적절하게 변경해보겠습니다!

2023-06-04 14:53 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/ui/detail/ProductDetailActivity.kt
> +        )
제안드린 방법이 반드시 정답은 아니니, 원하는 방법을 취사선택하면 좋겠어요 :)

2023-06-04 14:56 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/util/inject/DataSourceInject.kt
> +    LocalCartDataSource(dao)
Koin 라이브러리가 비슷한 형태로 되어있지요.
어디서든 koin 스코프 내에서 get()을 호출하면, 메모리 트리에서 적절한 인스턴스를 찾아내어서 원하는 인스턴스를 가져오게 만들지요.
하지만 get()을 부르기 위해 사용자가 직접 get 메서드를 구현할 필요는 없습니다.
이런 것처럼 만들어보려 했던 걸로 이해했어요! 

DI 구현은 굉장히 고려해야할 게 많다고 생각이 들어서... ㅋㅋㅋ 라이브러리 들여다보는 정도만 해도 충분하지 않을까~ 하는 생각이 있어요 :)
물론 구현해보시고 싶다면, 말리진 않겠읍니다 💪