[쇼핑 장바구니] 올리브 1, 2단계 미션 제출합니다.
woowacourse/android-shopping-cart pull request #54
Opened 2024-05-16 04:54 UTC by kimhm0728

안녕하세요 페로로! 올리브입니다. 🫒
레벨1 로또 미션 이후로 다시 뵙네요 😊 
너무 반갑습니다!! 이번 미션도 잘 부탁드립니다.

### 질문
메인 화면의 더보기 버튼을 RecyclerView 아래에 Button을 넣어서 구현했습니다. 
ConstraintLayout 제약 조건을 맞게 설정했음에도, 버튼이 제대로 나타나지 않고 버벅거리는 현상이 있습니다.
이런 더보기 버튼의 경우 RecyclerView의 ViewType을 사용해서 구현하는 것이 일반적인가요?
Multi-ViewType 말고 다른 방식으로 구현할 수는 없는지 궁금합니다 😢

### 시연 영상
<video src="https://github.com/woowacourse/android-shopping-cart/assets/70271235/a899618f-c9b6-4809-82f7-aa171605f147" />

2024-05-16 12:52 UTC, laco-dev requested changes
뷰모델과 친해지기 위해서 이번 미션에서는 도메인 로직에 대한 피드백은 제외하였습니다.

뷰모델의 역할은 프레젠터와 마찬가지로 데이터(UI 상태)를 관리하고, 비즈니스 로직을 수행하는 컴포넌트입니다.

그렇기에 현재 UI에서 비즈니스 로직을 수행하고 있는 것은 아닌지?
뷰모델의 테스로 검증을 해야 하는 것은 아닌지?
와 같은 고민이 필요합니다.

남겨드린 것 처럼, 화면 과 1:1 구조를 가지는 뷰모델로 명확히 만든 다음
각 케이스에 대한 로직의 뷰모델 테스트를 작성하는 도전 과제를 드리겠습니다.

2024-05-16 12:52 UTC, laco-dev commented on app/src/androidTest/java/woowacourse/shopping/feature/cart/CartActivityTest.kt
> +    }
UI 테스트 환경에서 Repository를 공유하는방법이 마땅치 않아서 object로 만들어진 것 같네요.

아래 내용은 수정하지 않아도 됩니다.
저도 좋은 방법이 떠오르지 않아서 개인적으로 코드만 남겨봅니다.
```kotlin
interface CartRepository {
  companion object {
    private var insatnce: CartRepository? = null

   fun setInstance(repository: CartRepository) { ... }
  }
}

fun setup() {   
  CartRepository.setInsatnce(FakeCartRepository(...))
}

// given
CartRepository.setInsatnce(...)

// when
..
// then
..
```

이 내용은 지금은 이정도로 고민 해 주신 것으로 충분하고, 
다음 미션들을 하면서 어떻게 UI 테스트에서 뷰모델 더블을 사용할 수 있을까? 로 이어집니다.

2024-05-16 12:52 UTC, laco-dev commented on app/src/androidTest/java/woowacourse/shopping/feature/cart/CartActivityTest.kt
> +            .check(RecyclerViewItemCountAssertion(1))
단위 테스트와 비슷하게 짜본다면 확장함수로 이렇게 만들어 볼 수 있겠네요.
```kotlin
onView(...)
  .hasSize(expected)
```

매번 RecyclerViewItemCountAssertion을 만들고 넣어줘야 한다는 사실이 매우 귀찮을 것...

2024-05-16 12:52 UTC, laco-dev commented on app/src/main/res/layout/activity_main.xml
> +            tools:visibility="visible" />
> ConstraintLayout 제약 조건을 맞게 설정했음에도, 버튼이 제대로 나타나지 않고 버벅거리는 현상이 있습니다.
이런 더보기 버튼의 경우 RecyclerView의 ViewType을 사용해서 구현하는 것이 일반적인가요?
Multi-ViewType 말고 다른 방식으로 구현할 수는 없는지 궁금합니다 😢

리스트의 최하단에 이 버튼이 노출되기를 기대한 것 같은데요.
지금 코드를 보면 이미 Multi-ViewType이 아닌 다른 방법을 사용하신 것 아닌가요?
질문의 의도가 궁금합니다.

일반적으로는 기획, 디자인적인 요구사항에 따라 다르게 구현하지만 아래 기준을 따릅니다.
1. 아이템이 스크롤에 포함되어야 하면 멀티 뷰 타입을 사용한다.
2. 아이템이 리스트 컨텐츠와 독립적으로 그려진다면 별도로 그린다.

또한 2번의 경우, 화면 하단에 플로팅 형태로 만들고 리사이클러뷰가 버튼의 높이만큼 여백을 주어서 해결하고는 합니다.

2024-05-16 12:52 UTC, laco-dev commented on app/src/main/res/layout/item_see_more.xml
> +    <androidx.appcompat.widget.AppCompatButton
`<androidx.appcompat.widget.AppCompatButton` 과 `<Button`은 어떤 차이가 있나요?

채널에서 다른 크루가 이 주제에 대한 해답을 공유한 적이 있어요

2024-05-16 12:52 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/feature/main/MainActivity.kt
> +    }
강의자료에 있는 ktx 를 활용하지 않은 이유가 있나요?

```kotlin
viewModel by viewModels(...)
```

2024-05-16 12:52 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/feature/main/MainActivity.kt
> +        }
화면이 회전하면 어떤 현상이 발생할까요?
구체적으로 page 값이 어떻게 바뀌는지 관찰할 필요성이 있습니다.

그렇다면 페이지는, 액티비티가 가지고 있는것과 뷰모델이 가지고 있는것. 누가 맞을까요?

2024-05-16 12:52 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/feature/main/MainActivity.kt
> +    }
같은 맥락으로, 더보기 버튼의 노출 여부를 판단하고 결정하는 것을 뷰모델이 하도록 위임 할 수도 있을 것 같네요!
모든 데이터를 관리하고 가지고 있는 것은 뷰모델이니까요

```kotlin
val lastPosition = ...
viewModel.determineLoadMoreVisibility(lastPosition)

// viewModel
val showLoadMore: LiveData<Boolean> ...

// <Button
       android:visibility="@{vm.showLoadMore}"
```

2024-05-16 12:52 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/feature/main/adapter/ProductAdapter.kt
> +    }
단순히 updateProducts() 라는 메소드로 볼 때, 내부적으로 아이템이 뒤에 추가될 것이다 라고 확신할 수 있을까요?
삭제될지도, 아예 전부 교체될지도 이름만 봐서는 모르지 않을까요?

2024-05-16 12:52 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/viewmodel/CartViewModel.kt
> +package woowacourse.shopping.viewmodel
viewmodel 패키지에 모두 모아지게 된 배경이 있을까요?

제가 추측하기로는, 뷰모델을 재사용 하려고 이곳에 모인 것 같습니다.
하지만 흔히 화면 단위의 ViewModel은 액티비티와 1:1 대응 구조를 가지고는 합니다.

예를 들어 ProductViewModel 이라는 것을 2개의 화면에서 사용하고 있습니다.
그런데 실제로 두 화면이 뷰모델의 모든 기능을 사용하지 않습니다.
즉 재사용이 아닌 SuperViewModel의 성격을 가지고 있습니다.

`MainViewModel` `ProductDetailViewModel` 두개로 나뉘지 않은 이유를 들어 저를 설득시켜 주세요. 🙇🏻

2024-05-16 12:52 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/viewmodel/ProductViewModel.kt
> +    val products: LiveData<List<Product>> get() = _products
💣  3페이지 목록을 보는 중에 화면이 회전하면 어떤 현상이 벌어질지 확인 해보시면 좋겠습니다. 💣 

흔히 뷰모델이 가지고 있는 상태는 단일 데이터소스라고도 할 수 있습니다.
즉 데이터(UI 상태)를 관리하는 주체가 뷰모델이 되어야 한다는 의미인데요.

가령 현재 가지고 있는 아이템의 전체 수량을 알거나, 특정 페이지의 특정 아이템을 알기 위해서는 어댑터의 아이템에 의존해야 합니다.
결과적으로 비즈니스 로직을 UI가 수행한다는 것으로 볼 수 있고, 뷰모델에 작성해야할 테스트가 UI 테스트로 넘어가게 되는 문제가 발생합니다.

아래 시나리오를 통과 할 수 있다면 성공입니다.
*3페이지까지 보이는 상태에서 화면을 회전한 경우 다시 3페이지까지의 목록이 그대로 노출되어야 합니다.

2024-05-16 12:52 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/viewmodel/ProductViewModel.kt
> +    val product: LiveData<Product> get() = _product
메인 화면 입장에서는 이 product는 아무 필요가 없겠죠?

2024-05-16 12:52 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/viewmodel/CartViewModel.kt
> +    val cartSize: LiveData<Int> get() = _cartSize
`5개 이상일 때 다음 페이지를 노출해야 한다.`는 UI에서 구현할 역할일까요? 뷰모델에서 구현할 역할일까요?

뷰모델에서 테스트를 작성해야 하지는 않았을까요?

```kotlin
val showPageController: LiveData<Boolean>
val hasPreviousPage: LiveData<Boolean>
val hasNextPage: LiveData<Boolean>
```

2024-05-16 12:52 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/viewmodel/CartViewModel.kt
> +    }
수량이 변경되었는데 수량을 가지고 있는 상태 변경하는 코드가 안보이네요~? 어디있을까요?

> 아이템 A의 수량이 3개일 때 수량을 증가시키면 4개가 된다.

2024-05-17 06:08 UTC, kimhm0728 commented on app/build.gradle.kts
> +    implementation("androidx.test.espresso:espresso-contrib:3.5.1")
안드로이드 테스트에 대한 의존성이니 `androidTestImplementation`를 사용하는 것이 맞을 것 같습니다. 수정했습니다! [2091d89](https://github.com/woowacourse/android-shopping-cart/pull/54/commits/2091d89017514ecfd44a02c477f2ab2a27432120)

2024-05-17 06:16 UTC, kimhm0728 commented on app/src/androidTest/java/woowacourse/shopping/feature/cart/CartActivityTest.kt
> +            .check(RecyclerViewItemCountAssertion(1))
말씀해주신 방식으로 수정해보았습니다! 어떤 걸 테스트하려는지도 더 명확해졌네요. 감사합니다! [b8f80b7](https://github.com/woowacourse/android-shopping-cart/pull/54/commits/b8f80b7c30a1dc10dbfe28fa37f0fc84cad0f28d)

2024-05-17 08:34 UTC, kimhm0728 commented on app/src/main/res/layout/activity_main.xml
> +            tools:visibility="visible" />
앗 제가 질문을 너무 모호하게 적었나요?! 지금은 Multi-ViewType을 사용하지 않았고, 그래서 더보기 버튼이 버벅거리는 현상이 나타났습니다. Multi-ViewType을 사용하지 않고도 이러한 버벅임 현상을 해결할 수 있는 방법은 없는지, 일반적으로는 어떤 방식으로 구현했는지가 궁금해서 질문드렸습니다. 

말씀하신대로 "화면 하단에 플로팅 형태로 만들고 리사이클러뷰가 버튼의 높이만큼 여백"을 주어서 해결했습니당 [50497c2](https://github.com/woowacourse/android-shopping-cart/pull/54/commits/50497c24d7d15a301104351ee6539f5eaabd9db1)

추후 시간이 나면 Multi-ViewType으로도 리팩터링해보고 싶은데 괜찮을까요? 코드가 많이 바뀌면 페로로가 리뷰하기 힘드실까봐 여쭤봅니다.

2024-05-17 09:09 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/feature/main/MainActivity.kt
> +    }
처음엔 `by viewModels`로 생성을 했었는데, ProductViewModelFactory를 사용하면서 위와 같은 방식으로 변경했습니다. 그런데 `by viewModels`로도 ProductViewModelFactory를 주입해줄 수 있군요!! 수정했습니다. [5891cb4](https://github.com/woowacourse/android-shopping-cart/pull/54/commits/5891cb4b859dcf36a608b8c820f3e3b835fb67e8)

2024-05-17 13:38 UTC, kimhm0728 commented on app/src/main/res/layout/item_see_more.xml
> +    <androidx.appcompat.widget.AppCompatButton
페어에게 AppCompatButton는 이전 버전과 호환성을 제공하고, 더 많은 속성을 사용할 수 있다고 들어 처음으로 사용해보았습니다. 처음 사용해보는데도 제대로 찾아보지 않고 사용을 했네요.. 


<img width="870" alt="스크린샷 2024-05-17 오후 5 37 44" src="https://github.com/woowacourse/android-shopping-cart/assets/70271235/62ae8181-90a3-40c4-93e4-625de6e85972">

지금 다시 찾아보니, backgroundTint, backgroundTintMode, fontFamily의 속성을 사용할 수 있다고 하네요. 그리고 AppcompatActivity와 AppCompatDialog 에서 Button을 사용하면, 내부적으로 AppCompatButton를 사용한다는 것을 알게 되었습니다.. Button으로 수정했습니다. (케이엠이 채널에 공유한 내용을 읽었음에도 AppCompatButton을 사용한 것에 반성합니다.. 😢) [68f5333](https://github.com/woowacourse/android-shopping-cart/pull/54/commits/68f5333b8cb03ee277bcdc82ba6991ade057fdbc)

2024-05-17 13:38 UTC, kimhm0728 commented on app/src/main/res/layout/item_see_more.xml
> +    <androidx.appcompat.widget.AppCompatButton
\+ 페이지 이동 버튼에 Button을 사용하니 selector가 제대로 적용되지 않았습니다. [해당 글](https://velog.io/@hyemdooly/Button%EC%97%90-background%EA%B0%80-%EC%A0%81%EC%9A%A9%EB%90%98%EC%A7%80-%EC%95%8A%EC%95%84%EC%84%9C-AppCompatButton%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%98%EC%85%A8%EB%82%98%EC%9A%94)을 참고하여, Button을 사용하면 "MaterialButton → AppCompatButton → Button" 순으로 타고 들어가는데, MaterialButton에서 자체적인 Drawable을 background로 지정하고 있기 때문임을 알게 되었습니다. `app:backgroundTint="@null"`속성을 추가하여 해결했습니다. 이런 경우에는 AppCompatButton을 사용해도 될 것 같네요!!

2024-05-17 13:47 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/viewmodel/CartViewModel.kt
> +package woowacourse.shopping.viewmodel
화면 별로 뷰모델을 만들다가, 동일한 repository에서 데이터를 불러오는 코드가 있길래, repository 별로 하나의 뷰모델을 만들었습니다..... 저랑 페어 모두 ViewModel / MVVM을 제대로 사용해본 적이 없어서, 어떤 방식이 일반적인지 잘 몰랐습니다.

또한 강의 시간에 Presenter와 다르게 ViewModel은 하나의 ViewModel이 여러 View에서 쓰일 수 있다는 내용을 배웠습니다. 그런데 강의 시간에 말한 ViewModel은 AAC의 ViewModel이라, 개념적으로 가능하다는 말씀을 하신 것 같은데 저는 "(MVVM 구조 상으로) 여러 뷰가 하나의 뷰모델을 사용할 수 있다~"라고 이해한 것 같네요. 
 
아직 MVVM을 제대로 배우지 않은 상태에서 ViewModel과 LiveData를 적용하려다보니, 코드의 기준이 명확히 잡히지 않은 것 같습니다!! 화면과 ViewModel이 1:1 대응되도록 수정해보겠습니다.

2024-05-17 14:49 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/viewmodel/ProductViewModel.kt
> +    val product: LiveData<Product> get() = _product
맞습니다.. 화면 별로 뷰모델을 생성하면, 화면들이 뷰모델의 모든 기능을 사용하지 않는 경우가 발생하지 않을 것 같습니다. 
MainViewModel을 생성하고, 필요한 LiveData만 갖도록 수정했습니다! (커밋이 너무 커질까봐 일단 ViewModel을 분리만 해서 커밋했습니다. 추후 다른 코멘트에 뷰모델 리팩터링한 커밋도 남기겠습니다~!) [aace1c4](https://github.com/woowacourse/android-shopping-cart/pull/54/commits/aace1c4b4ddc29e6d27fd6a39ee29d940937acd6)

2024-05-17 15:32 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/feature/main/MainActivity.kt
> +    }
헉!!!!!! 말씀하신 방식으로 수정해보았습니다. visibility를 Boolean으로 변경하는 android 속성이 없어서, 바인딩 어댑터를 따로 구현해서 visibility를 변경했습니다. [d2c99c8](https://github.com/woowacourse/android-shopping-cart/pull/54/commits/d2c99c8d5136acda700da62550a5137a26c71a98)

이 코멘트 하나로 액티비티 코드가 비교적 정말 가벼워졌네요...... 기존 제 코드는 MVVM + dataBinding의 이점을 하나도 활용하지 않은 코드였음을 깨닫는 중입니다 🫠 감사합니다!

2024-05-17 16:29 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/viewmodel/ProductViewModel.kt
> +    val products: LiveData<List<Product>> get() = _products
뷰모델을 어떻게 활용할지에 대해 제대로 알지 못하고 코드를 작성해서, 서툰 점이 정말 많이 보이네요. MainViewModel을 따로 분리하고 page 변수를 ViewModel로 이동했습니다. 

그런데 ViewModel에서 로드된 모든 Product를 가지고 있는 것이 아닌, 가장 최근에 로드된 페이지의 Product만 가지고 있었기 때문에 화면 회전 시 제대로 목록이 노출되지 않았습니다. (ex: Product가 총 26개고 더보기 버튼을 한 번 누르면 6개의 products를 가지고 있음) 로드된 모든 Product를 가지도록 수정해서, 화면 회전 시에도 기존 페이지가 유지되도록 수정했습니다! [4a826cd](https://github.com/woowacourse/android-shopping-cart/pull/54/commits/4a826cd276fb29bab83b63467cd388f855ced33f)

\+ 가로 모드 전환 시 아이템 전체가 보이지 않아서 `GridLayoutManager.findLastCompletelyVisibleItemPosition()`이 -1이 반환되었고, 더보기 버튼이 활성화되지 않는 오류가 있었습니다. landscape에 대한 activity_main.xml를 따로 생성해 RecyclerView의 padding을 주어서 아이템 전체가 보이도록 수정했습니다.

2024-05-17 16:38 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/feature/main/MainActivity.kt
> +        }
화면을 회전하면 액티비티를 소멸시켰다가 다시 생성하기 때문에, page가 0으로 초기화되겠군요..!!!! 
반면에 뷰모델은 화면 회전 시에도 데이터가 유지되고, 액티비티에서 finish()를 호출하거나 사용자가 백버튼을 눌렀을 때만 소멸됩니다. 화면 회전 시에도 페이지를 유지하기 위해서는 뷰모델에서 page를 관리해야 할 것 같습니다!! 관련 내용과 커밋 링크는 [이 코멘트](https://github.com/woowacourse/android-shopping-cart/pull/54#discussion_r1605275896)에 남겨두었습니다.

2024-05-18 09:25 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/viewmodel/CartViewModel.kt
> +    val cartSize: LiveData<Int> get() = _cartSize
액티비티에 너무 많은 로직을 넣었던 것 같네요! 액티비티에 있는 ui 상태 프로퍼티들을 뷰모델로 이동시켰습니다. [eb7b064](https://github.com/woowacourse/android-shopping-cart/pull/54/commits/eb7b0647be1b0766edac440688525208dd0c2fdf)

2024-05-18 09:40 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/viewmodel/CartViewModel.kt
> +    }
음.. 이렇게 구현했던 이유는 뷰모델을 화면 별로 나누지 않고 재활용했기 때문인 것 같습니다. 예를 들어 상품 상세 화면에서 장바구니에 상품을 담아도, 장바구니의 수량을 변경할 필요가 없습니다. 장바구니 수량은 장바구니 화면에서만 쓰이기 때문입니다....

뷰모델을 재활용하면서 한 화면에서 뷰모델의 모든 기능을 쓰지 않았고, 읽는 사람이 의문을 갖게 되는 코드를 작성한 것 같네요 😢 화면 별로 뷰모델을 작성하고, 한 화면에 필요한 기능만 모아두도록 수정했습니다.

2024-05-18 09:41 UTC, kimhm0728 commented
@laco-dev 
안녕하세요 페로로! 리뷰 반영해서 다시 요청드립니다.
제 의견과 리뷰 반영 사항들은 코멘트 답변으로 남겨두었으니 확인 부탁드립니다. 🙂
말씀하신대로, 화면과 1:1 대응되도록 뷰모델을 작성하고, 각 화면의 로직을 테스트할 수 있는 뷰모델 테스트를 작성했습니다.

- 상품 목록 화면 뷰모델 테스트 [a29097a](https://github.com/woowacourse/android-shopping-cart/pull/54/commits/a29097afc27551199391561e98243fd00dc7e401)
- 상품 상세 화면 뷰모델 테스트 [490ac61](https://github.com/woowacourse/android-shopping-cart/pull/54/commits/490ac610e440eac927a81e65bc075595363288f0)
- 장바구니 화면 뷰모델 테스트 [a2606d8](https://github.com/woowacourse/android-shopping-cart/pull/54/commits/a2606d86a3619efca9debd74138b38022500cb63)


### 리뷰 외 구현 사항
- 장바구니가 비어있는 경우 빈 화면이 아닌, "장바구니가 비어있습니다"와 같은 문구가 뜨도록 수정했습니다. [925f85d](https://github.com/woowacourse/android-shopping-cart/pull/54/commits/925f85d355029a17a12c8e294d595843db7d0ccc)
- 화면 회전 시 동일한 페이지가 보이는지에 대한 ui 테스트를 작성했습니다. [b5b9147](https://github.com/woowacourse/android-shopping-cart/pull/54/commits/b5b91478809a007c2506bd3e92d5e1586e886414)

2024-05-19 03:24 UTC, laco-dev commented on app/src/main/res/layout/activity_main.xml
> +            tools:visibility="visible" />
구체적인 요구사항이 없다고 들었는데요.
페이지네이션 방법에 따라 다르겠지만, "더보기" 버튼이 스크롤에 같이 끌려올라와야 하는가? 에 대한 의문으로 생각해본다면 어색하지 않을까요?

유저가 이 앱을 사용한다고 했을 때, 다음 페이지를 보고 싶을때 어떤 버튼이 누르기 편할까? 좋을까?
에 대한 UX적인 고민을 해봐야 해요.
무조건 디자이너가 "이렇게 해주세요" 라고 했을 때 더 좋은, 더 나은 유저 경험을 제공한다면 충분히 반론을 하고는 합니다.

---

요기까지는 제 개인적인 의견이구요.
연습을 위한 목적이라면, 적용 해보셔도 괜찮습니다.

2024-05-19 03:25 UTC, laco-dev commented on app/src/main/res/layout/item_see_more.xml
> +    <androidx.appcompat.widget.AppCompatButton
이것은 머티리얼과 테마에 대한 이해가 더 되어야 하기 때문에, 이정도로 충분합니다.
테마 시스템과 머티리얼과 AppCompat의 관계에 대해서...

2024-05-19 03:35 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/viewmodel/CartViewModel.kt
> +package woowacourse.shopping.viewmodel
아하, 너무나도 자연스럽게 처음이라는 것을 간과했군요

흔히 착각하기 쉬운 것 중 하나로 뷰모델 하나로 여러개의 View를 재사용 한다는 맥락은
하나의 기능을 담당하는 화면에 대한 재사용을 의미하는 것이기 때문에, 여러개의 화면은 곧 여러개의 뷰이기도 합니다.

아래 2번의 상황이라면 재사용이 가능할수도 있겠네요
1. 상품 목록 / 상품 상세
2. 상품 목록 A / 상품 목록 B / 상품 목록 C

2024-05-19 03:43 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/viewmodel/ProductViewModel.kt
> +    val products: LiveData<List<Product>> get() = _products
잘 모르기 때문에 알아가는 과정이라, 전혀 잘못한 것은 아니고 자연스러운 과정입니다.

지금은 단순히 아이템을 추가하는 동작만 있기 때문에 어댑터의 복잡도가 그리 높지 않았을거에요.
또한 데이터를 가지고 있는 곳이 두개다 보니까 그만큼 관리가 어렵습니다.

1, 2단계에서는 ListAdapter를 금지한 이유도 이것을 경험하기 위함인데요.
이후 3, 4단계에서 요구사항에 맞춰 어댑터를 어떻게 구현할 것인가? 가 가장 큰 어려움으로 발생합니다.

2024-05-19 03:46 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/viewmodel/ProductViewModel.kt
> +    val products: LiveData<List<Product>> get() = _products
가로 모드에 대한 기능 구현은 요구사항이 아니지만, 대응을 해보셨군요.

깊게 들어가면 고민할 부분이 너무 많지만, activity_main가 통채로 2개가 만들어지면, 아마 보일러 플레이트부터 불필요한 코드가 많이 늘어날 수도 있어서요.

아이템을 어떻게 배치하고 그리는 등의 로직에 따라 굳이 레이아웃 2개가 아니어도 가능할 수도 있기는 합니다.
이것은 여러번 경험 해보고 연습을 해봐야 하는 영역이긴 하네요

2024-05-19 04:51 UTC, laco-dev requested changes
피드백 반영 고생하셨습니다.

MVVM에 처음 학습하는 과정이기 때문에 잘못 했다라는 표현이 아닌 배워가는 자연스러운 과정이라고 생각하고 부담갖지 않으셔도 괜찮습니다.
다음에 점점 더 좋아지면 되니까요.

한번 더 각 세개의 화면 중심으로 로직에 대해 피드백을 남겼습니다.
또한 뷰모델의 단위테스트를 이용할 때 레포지터리를 어떻게 테스트 가능하게 구현할 것인가에 대한 의문도 같이 해결해보면 좋을 것 같아요.

다음 번에는 머지하고 다음 미션 진행할 수 있도록 하겠습니다.

2024-05-19 04:51 UTC, laco-dev commented on app/src/test/java/woowacourse/shopping/feature/products/ProductsViewModelTest.kt
> +        }
쇼핑 앱에서 "상품"을 만드는 기능은 요구사항에서 없을거에요.
하지만 save()라는 기능이 생긴 이유는, 테스트 환경에서 아이템을 만들기 위함이겠지요.

그렇다면, 이는 테스트를 위해서 생긴 기능이라고 볼 수 있습니다.
이전 미션들에서 테스트에 쓰기 위해 프로덕션의 코드를 만드는 것은 좋은 설계가 아니다 라는 얘기를 한 적이 있을거에요.
이 경우, 인터페이스를 활용해 생성자를 응용하도록 연습을 해 왔지요.
그렇다면, 뷰모델 테스트에서는 인터페이스와 테스트 더블을 충분히 활용하고 있나요?

repeat와 DummyRepository + save를 쓰는 것이 최선일까? 라는 궁금증입니다.

2024-05-19 04:51 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/feature/cart/CartActivity.kt
> +        viewModel.loadCart()
이것도 화면 회전에 영향을 받는 고민 포인트중 하나입니다.

현재 1페이지를 보고 있는 상황에서, 화면이 회전하면 뷰가 다시 초기화 되지만, 뷰모델은 기존의 인스턴스를 사용하게 됩니다.
그리고 이어서  `viewModel.loadCart()`가 다시 호출이 됩니다.

정책과 요구사항에 따라 다르지만 뷰모델의 생성자에서 loadCart()를 한번만 호출하도록 해서 이 문제를 해결할 수도 있고, 데이터 상태를 통해 문제를 해결할 수도 있습니다.
오히려 회전할 때 마다 매번 새로 초기화 하는 것이 기획적인 결정사항 일수도있습니다.

2024-05-19 04:51 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/feature/cart/adapter/CartViewHolder.kt
> +typealias OnClickExit = (cartItem: CartItem) -> Unit
별명으로 고차 함수에 의미를 부여 👍🏻

2024-05-19 04:51 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/feature/cart/viewmodel/CartViewModel.kt
> +    }
단순히 보고있는 아이템을 삭제하는데 페이지를 새로 불러올 필요가 있나요?
현재 _cart에서 해당하는 아이템만 삭제할 수 있습니다.
*물론 레포지터리로 요청하는 것은 선행으로 필요합니다.

삭제한 이후, 현재 페이지 상태에 따라 이전 페이지로 이동한다거나 다른 액션을 취할 수 있겠네요.

2024-05-19 04:51 UTC, laco-dev commented on app/src/test/java/woowacourse/shopping/feature/cart/CartViewModelTest.kt
> +    }
요기도 마찬가지로 내가 원하는 레포지터리 인터페이스를 테스트 환경에서 만들 수 있다면 좋겠네요

2024-05-19 04:51 UTC, laco-dev commented on app/src/test/java/woowacourse/shopping/feature/cart/CartViewModelTest.kt
> +        assertThat(actual).isEqualTo(cartRepository.findRange(0, pageSize))
앞선 의견을 이어서 작성하면, 현재 보고 있는 페이지가 일치하는지 여부를 판단하기 위해서 굳이 로직을 호출하지 않고도 간단하게 판단이 가능하게 됩니다.

```kotlin
// given
val items = List(8) { ... }
val repository = MockCartRepository(items)
...

// when
viewModel = ViewModel(...) (만약 생성자에서 초기화를 한다면, 그렇지 않다면 함수)

// then
assertThat(actual).isEqualTo(items.take(5))
```

2024-05-19 04:51 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/feature/products/ProductsActivity.kt
> +                    super.onScrolled(recyclerView, dx, dy)
`super.onScrolled(recyclerView, dx, dy)` 코드가 어떤 동작을 하고있는지 살펴보세용

2024-05-19 04:51 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/feature/products/adapter/ProductsAdapter.kt
> +    private var products: List<Product> = mutableListOf()
List를 비어있는 것으로 초기화 하는 것은 listOf(), emptyList() 를 사용하면 됩니다.

2024-05-19 04:51 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/feature/products/adapter/ProductsAdapter.kt
> +    }
insertXXX는 현재 아이템에 파라미터로 전달받은 값을 추가로 더한다. 라는 의미로 해석이 됩니다.
그런데 더하는 것은 밖에서 하고 안에서는 replace만 하고 있어서 혼란이 발생합니다.

이 문제를 근본적으로 해결하려면 내부에서 아이템이 실제로 추가되는지, 삭제되는지 바뀌는지 등등에 대한 알고리즘이 필요하게 되고 이를 제공하는게 이전에 사용 해 봤을 수도 있는 ListAdapter와 DiffUtil입니다.

이 기능을 사전에 사용하지 못하도록 했기 때문에 이 문제를 해결하려면 나름 머리가 많이 아파지는데요.
이 문제는 3, 4단계에서 이어서 풀이 해보기로하고, DiffUtil을 사용하지 않는 경우는 일반적으로

UI 이벤트를 이용해 처리하고는 합니다.
`SingleLiveData, LiveData<Event>` 라고 부르는 키워드를 이용합니다.

강의에서 다룰 수도 있는데, 지금 당장은 찾아보고 학습하는 정도로 봐주시면 됩니다.

2024-05-19 04:51 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/feature/products/viewmodel/ProductsViewModel.kt
> +    }
지금 로직대로라면, 레포지터리에서 더이상 내려줄 데이터가 없어도 항상 더보기 버튼이 노출되겠군요.
일반적인 페이징 처리에서는 현재 페이지가 "마지막 페이지" 인지 여부에 대한 데이터 로직도 같이 들어가게 됩니다.

2024-05-19 04:51 UTC, laco-dev commented on app/src/test/java/woowacourse/shopping/feature/products/ProductsViewModelTest.kt
> +    }
이 테스트가 "더보기" 버튼이 보인다라는 것을 테스트하기에 적합한 이름일까요?
더 불러올 수 있는지 여부가 어떤 시나리오에 의해 보이는지 잘 매칭이 되지 않아 보이는데요.

> 페이지마다 5개의 크기를 가지는지 사전에 테스트 하고,

> 상품이 25개이고 1페이지를 보고 있을 때, 마지막으로 보고있던 위치가 4라면 더보기 버튼이 보여야 한다.

2024-05-19 04:51 UTC, laco-dev commented on app/src/test/java/woowacourse/shopping/feature/products/ProductsViewModelTest.kt
> +    private fun lastPosition(): Int = viewModel.products.getOrAwaitValue().size - 1
결론적으로 테스트 코드에 가급적 로직을 포함하지 않는게 좋아요

그냥 직관적으로 1페이지 4번째 아이템이다. 라고 하드코딩을 하는 것이 테스트를 이애하는데 더 도움이 될 수도 있습니다.

2024-05-19 04:51 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/feature/detail/viewmodel/ProductDetailViewModel.kt
> +package woowacourse.shopping.feature.detail.viewmodel
일반적으로는 뷰모델을 굳이 패키지로 나누지는 않습니다.
이미 MVVM 아키텍처를 하고 있으므로 액티비티랑 같은 위치에 두면 됩니다.

2024-05-19 04:51 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/feature/detail/viewmodel/ProductDetailViewModel.kt
> +    }
상품 상세에서 프로덕트 아이디가 달라질 일이 없지 않을까요?
그렇다면 뷰모델의 생성자로 같이 받을 수 있지 않을까요?

2024-05-19 04:51 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/feature/detail/ProductDetailActivity.kt
> +    }
이 내용도 UI 이벤트와 연관이 있는 내용이라, 당장은 반영하지 않아도 됩니다.
만약 addCartProduct() 동작이 비동기로 동작하여 유효성 검사나 다른 이유에 의해 실패한다면 어떻게 될까요?

장바구니에 담기 다이얼로그가 뜨겠죠?
그러면 이 로직은 어떻게 짜야 하는가?  😱

2024-05-19 04:51 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/feature/detail/ProductDetailActivity.kt
> +    }
마찬가지로 뷰모델이 실패하는 상황을 뷰가 핸들링 하는 것은 잘못되었어요.

뷰모델의 동작이 비동기로 될 수도 있으며, 실제 어떤 오류 처리를 할지도 비즈니스 로직으로 뷰모델이 해야할 역할이니까요.

이런 경우는 UI 이벤트 외에도 `_errorMessage: LiveData<String?>` 같은 처리를 통해 상태로 만들어서 해결할 수도 있습니다.
https://developer.android.com/topic/architecture/ui-layer/events#consuming-trigger-updates

2024-05-19 10:13 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/feature/detail/viewmodel/ProductDetailViewModel.kt
> +package woowacourse.shopping.feature.detail.viewmodel
앗 그렇군요! 넵 수정했습니다. [a9c0137](https://github.com/woowacourse/android-shopping-cart/pull/54/commits/a9c013790fcf8a2239a7d4173b1a6e5c031a707f)

2024-05-19 10:33 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/feature/detail/viewmodel/ProductDetailViewModel.kt
> +    }
헉 그렇네요! 수정했습니다. [15ce943](https://github.com/woowacourse/android-shopping-cart/pull/54/commits/15ce943ed60f61e9f6b5d56c5629c5be163ea123)

위에 남겨주신 코멘트에 이어서, 상품 상세 화면에서도 Activitiy onCreate에서 `loadProduct()`를 호출하고 있습니다. 즉 화면이 회전되는 경우, product가 이미 로드 되었는데도 다시 loadProduct()가 불필요하게 호출되는 문제가 있었습니다.

현재는 뷰모델의 생성자로 productId를 받아주기 때문에, 추후 뷰모델의 `init {}` 내부에서 `loadProduct()`를 호출하고 Activity에서는 product의 로드 결과만 받을 수도 있을 것 같습니다!! (현재는 Actvitiy에서 `loadProduct()`의 예외 처리를 해주기 때문에, 이렇게 리팩터링하는 경우 뷰모델의 `_product` 타입을 `UiState<Product>` 등으로 변경해야 할 것 같네요.)

2024-05-20 05:17 UTC, kimhm0728 commented on app/src/test/java/woowacourse/shopping/feature/products/ProductsViewModelTest.kt
> +        }
FakeRepository를 따로 구현해서, 테스트에서는 해당 구현체를 사용하도록 수정했습니다. [9c109c4](https://github.com/woowacourse/android-shopping-cart/pull/54/commits/9c109c4c607e5d933ffaeb20652644a3c55fbac9)
ProductRepository의 `save()`, `deleteAll()`, CartRepository의 `deleteAll()` 모두 테스트를 위해 생성된 코드이기 때문에, 모두 삭제했습니다. 

그런데 Ui 테스트에서는 실제 프로덕션 코드에서 선언된 Repository의 데이터를 접근하여 테스트하기 때문에, 테스트 시나리오 별로 Repository의 데이터를 다르기 하기 위해서는 프로덕션 코드 Repository의 데이터를 직접 변경해주어야 합니다..
이 문제를 해결하기 위해 [이전 코멘트](https://github.com/woowacourse/android-shopping-cart/pull/54#discussion_r1603225740)에서 말씀해주신 방식을 적용해보았습니다. [932dcff](https://github.com/woowacourse/android-shopping-cart/pull/54/commits/932dcff90cb745799394e965ee14372a07c6768b)

`Repository.setInstance()`를 생성해 Application onCreate()에서는 프로덕션 코드에 실제 사용되는 Repository를 지정해주고, Ui 테스트에서는 테스트 시나리오에 맞는 데이터들이 담겨있는 FakeRepository를 지정해주었습니다. 그런데 `ProductRepository.setInstance(DummyProductRepository.getInstance())
`와 같은 코드가 적절한 방식인지 잘 모르겠습니다..

2024-05-20 05:18 UTC, kimhm0728 commented on app/src/test/java/woowacourse/shopping/feature/cart/CartViewModelTest.kt
> +    }
네! [해당 코멘트](https://github.com/woowacourse/android-shopping-cart/pull/54#discussion_r1606258218)에 반영 내용 남겨두었습니다.

2024-05-20 05:19 UTC, kimhm0728 commented on app/src/test/java/woowacourse/shopping/feature/cart/CartViewModelTest.kt
> +        assertThat(actual).isEqualTo(cartRepository.findRange(0, pageSize))
헉 isEqualTo 내에서 repository의 함수를 매번 호출하는 것이 마음에 들지 않았는데.. 이렇게 할 수도 있군요! 수정했습니다~! [9c109c4](https://github.com/woowacourse/android-shopping-cart/pull/54/commits/9c109c4c607e5d933ffaeb20652644a3c55fbac9)

2024-05-20 05:20 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/feature/products/adapter/ProductsAdapter.kt
> +    private var products: List<Product> = mutableListOf()
앗 val MutableList로 바꿨다가 다시 var List로 돌아왔는데, 초기화하는 부분은 깜빡하고 다시 바꾸지 못했네요.. 감사합니다!! 수정했습니당 [c66f20a](https://github.com/woowacourse/android-shopping-cart/pull/54/commits/c66f20ad42bad9b266ee8fdf456c063dd586f09b)

2024-05-20 05:22 UTC, kimhm0728 commented on app/src/test/java/woowacourse/shopping/feature/products/ProductsViewModelTest.kt
> +    private fun lastPosition(): Int = viewModel.products.getOrAwaitValue().size - 1
last Position을 나타내는 9, 24 등의 숫자가 어떤 의미인지 잘 표현되지 않아서, 함수를 따로 작성했었는데요.
테스트명을 명시적으로 변경해주면서 last Position도 하드 코딩하는 방식으로 수정했습니다! [1c74dc6](https://github.com/woowacourse/android-shopping-cart/pull/54/commits/1c74dc6b7f3e2b249d64fc3c88fad85244828bb0)

2024-05-20 05:23 UTC, kimhm0728 commented on app/src/test/java/woowacourse/shopping/feature/products/ProductsViewModelTest.kt
> +    }
[해당 코멘트](https://github.com/woowacourse/android-shopping-cart/pull/54#discussion_r1606261265)에 반영 내용 남겨두었습니다! (바로 아래 코멘트)

2024-05-20 05:44 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/feature/cart/CartActivity.kt
> +        viewModel.loadCart()
ProductsActivity에서도 `initializeView()`에서 `viewModel.loadPage()`를 호출했었습니다. 이때는 `loadPage()`에서 새로운 다음 페이지를 로드하기 때문에, 화면 회전을 하면 더보기 버튼을 누르지 않아도 다음 페이지가 로드되었습니다.. 그래서 ViewModel init {} 내에서 `loadPage()`를 호출하는 방식으로 변경했는데요. 

`loadCart()`는 기존 페이지를 다시 로드하기 때문에 볼 때는 딱히 이상한 점이 없어서.. 변경하지 않았던 것 같네요 ㅎㅎㅠㅠ `CartViewModel`에서도 init {} 내에서 `loadCart()`를 호출하도록 수정했습니다. [45ef8f0](https://github.com/woowacourse/android-shopping-cart/pull/54/commits/45ef8f0df7337c77c9c9b2a2d6acd81b271896ad)

그런데 저는 사실 이러한 방식을 선호하지는 않는데요.. 이유는 아래와 같습니다. 
페로로는 이에 대해 어떻게 생각하시는지 궁금합니다!!

1. 생성자를 호출하면, 객체에 필요한 프로퍼티만 셋팅해야 함. 다른 객체로부터 메시지를 받을 때만 어떠한 작업을 수행함 ([엘레강트 오브젝트 1.3](https://github.com/woowacourse-study/2024-elegant-object/blob/main/Chapter-1/kimhm0728/3.%20%EC%83%9D%EC%84%B1%EC%9E%90%EC%97%90%20%EC%BD%94%EB%93%9C%EB%A5%BC%20%EB%84%A3%EC%A7%80%20%EB%A7%88%EC%84%B8%EC%9A%94.md))
2. loadCart()를 명시적으로 호출해서 의미를 더 드러낼 수 있음.

2024-05-20 05:45 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/feature/cart/CartActivity.kt
> +        viewModel.loadCart()
그리고 "데이터 상태를 통해 문제를 해결할 수도" 있다고 하셨는데, 혹시 어떤 방식인지 조금 더 구체적으로 말씀해주실 수 있을까요?? 👀

2024-05-20 07:14 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/feature/products/adapter/ProductsAdapter.kt
> +    }
음... 안에서는 var List를 교체만 해주지만,`notifyItemRangeChanged(positionStart, itemCount)`를 통해서 실제 추가된 item들만 RecyclerView에게 변경사항을 알리고 있습니다. 

그래도 `insertProducts`라는 함수명과 `products = insertedProducts`는 조금 맞지 않는 것 같아서, products의 타입을 val MutableList로 변경하고, products의 뒤에 변경사항 데이터들을 추가해주는 방식으로 수정했습니다! [74656bc](https://github.com/woowacourse/android-shopping-cart/pull/54/commits/74656bc14296e301d9bc8f25a345f2818567255a)

말씀해주신 `SingleLiveData, LiveData<Event>`에 대해 학습해보았는데요. 액티비티의 구성 변경이 일어나서 소멸 후 다시 생성되었을 때, 이미 뷰모델의 LiveData에 데이터가 존재한다면 동일한 이벤트가 다시 발생하기 때문에, 이를 방지하기 위해 주로 사용되는 것 같습니다. 

그런데 RecyclerView.Adapter는 액티비티가 다시 생성될 때 빈 리스트를 가진 새로운 어댑터 인스턴스를 생성하기 때문에, products를 로드하는 동일한 이벤트가 다시 호출되어도 괜찮을 것 같습니다.. `RecyclerView.Adapter`와 `SingleLiveData, LiveData<Event>`를 함께 사용하는 경우는 어떤 경우인가요?? 제가 잘못 이해하고 있는 걸까요 🙄

2024-05-20 16:07 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/feature/detail/viewmodel/ProductDetailViewModel.kt
> +    }
`loadProduct()`의 예외 처리를 뷰모델 내부로 옮기면서, `loadProduct()`를 뷰모델의 `init {}`에서 호출하도록 수정했습니다! [603273b](https://github.com/woowacourse/android-shopping-cart/pull/54/commits/603273b57635b3e06a05bb1d08690913e230b6ce)

2024-05-20 16:15 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/feature/detail/ProductDetailActivity.kt
> +    }
`loadProduct()`의 예외 처리를 뷰모델에서 하도록 수정했습니다. `_productLoadError`라는 LiveData를 하나 더 만들어서, `loadProduct()`에서 상품을 불러오는 것에 실패한다면 `_productLoadError`를 true로 변경했습니다. 그리고 `_productLoadError`를 옵저빙하는 액티비티 쪽에서는 `true`가 되면 `showErrorSnackBar()`를 호출하도록 수정했습니다! (`_productLoadError`가 Boolean 타입이기 때문에 `isError~~~`와 같은 네이밍이 더 명시적일 것 같네요.. 추후 수정하겠습니당) [f1255d7](https://github.com/woowacourse/android-shopping-cart/pull/54/commits/f1255d742041c5b1d35f0f00594986370b24b68a)

2024-05-20 16:20 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/feature/detail/ProductDetailActivity.kt
> +    }
\+ 다른 코멘트에서 `SingleLiveData, LiveData<Event>` 키워드를 말씀해주셔서 학습하다가, 현재와 같은 코드에서는 액티비티 구성 변경 시 다이얼로그/토스트가 중복되어 띄워진다는 문제점을 알게 되었습니다.

`LiveData<Boolean>`을 `LiveData<Event<Boolean>>`으로 wrapping해서, 이벤트가 처음으로 발생한 경우에만 다이얼로그/토스트를 띄울 수 있도록 수정했습니다! [5be6622](https://github.com/woowacourse/android-shopping-cart/pull/54/commits/5be6622727a52a1e55e72d14e2b0871ca189c498)

새로 막 학습하고 코드에 무작정 적용을 해본 거라 제대로 적용한 건지는 모르겠습니다.. 페로로가 생각하신 방향이 맞는지 피드백 부탁드립니다!! (그래도 리팩터링하는 동안 재밌었네요. ㅎㅎ)

2024-05-20 16:26 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/feature/cart/CartActivity.kt
> +        viewModel.loadCart()
아 코멘트 반영하면서 이해했습니다!!!!!!!! 생성자에 로직이 들어가는 걸 선호하지 않는다고 말씀드렸는데,, 데이터 상태를 적용하면 되겠군용. 개인적인 스타일 차이가 아닐까 싶네요 🤔

2024-05-20 16:54 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/feature/products/viewmodel/ProductsViewModel.kt
> +    }
헉 이 부분은 완전히 간과하고 있었습니다.... 너무 꼼꼼하십니다.. ㅋㅋ 

`ProductRepository`에서 `totalCount()` 함수를 생성하고, 이를 기반으로 뷰모델에서 `maxPage`를 계산했습니다. 그리고 현재 페이지가 `maxPage`보다 작다면 더보기 버튼을 노출시키도록 수정했습니다. [5722380](https://github.com/woowacourse/android-shopping-cart/pull/54/commits/5722380684832736a52ee460370e4366e1be771d)

그리고 궁금한 점이 있는데요!! 서버에서 데이터를 내려주는 경우, 보통 제가 구현한 방식처럼 `totalCount()`를 받아오나요? 아니면 다음 데이터가 있는지 없는지에 대한 여부를 받아오나요? 페이지네이션을 구현할 때, 어떤 방식이 더 일반적인지 궁금합니다!

2024-05-20 17:20 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/feature/products/ProductsActivity.kt
> +                    super.onScrolled(recyclerView, dx, dy)
음.... 혹시 코드를 개선하라는 의미로 찾아보라고 하신 걸까요?? 🤔

> This callback will also be called if visible item range changes after a layout calculation. In that case, dx and dy will be 0.

스크롤할 때만 호출되는 줄 알았는데, 레이아웃 계산 후 보여지는 아이템 범위가 변경될 때도 호출된다고 하네요.. 
로그를 찍어보니 화면 회전할 때나 notifyXXX()를 통해 어댑터 아이템을 변경해주었을 때는 스크롤하지 않아도 (dx=0, dy=0)으로 호출되는 것을 알 수 있었습니다!! 그런데..... 어떤 의미로 코멘트를 남기신 건지는 이해하지 못했습니다 😭 혹시 힌트를 더 주실 수 있나요?! 

(이 외에도 여러가지 학습했지만 내용이 너무 길어질 것 같아, 코멘트 의도에 가장 맞을 것 같은 내용만 작성해봅니다...ㅎㅎ)

2024-05-21 04:07 UTC, laco-dev commented on app/src/test/java/woowacourse/shopping/feature/products/ProductsViewModelTest.kt
> +        }
네,, 저도 좋은 방법은 아니라고 봐요.
꽤 나중에 되어서야 이 문제를 해결하기 위한 개념들을 학습할 수 있어서 고민은 이정도로 충분할 것 같습니다.

2024-05-21 04:10 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/feature/products/ProductsActivity.kt
> +                    super.onScrolled(recyclerView, dx, dy)
아뇨 super.onScrolled()를 들어가면 아무 동작을 하지 않고 있는 것을 볼 수 있습니다.

```kotlin
public void onScrolled(@NonNull RecyclerView recyclerView, int dx, int dy) {
}
```

2024-05-21 04:11 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/feature/products/adapter/ProductsAdapter.kt
> +    }
지금은 페이지 단위로 아이템을 불러오고 갱신하고 있어서 아마 문제가 없어보일 것 같아요.
무한 스크롤 형태의 페이지네이션을 구현한다면 이슈가 발생할 수 있습니다.

2024-05-21 04:12 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/feature/products/viewmodel/ProductsViewModel.kt
> +    }
REST API의 Header 정보에 들어있는 경우도 있구요.
Body에 담아서 내려주기도 합니다.

이는 서버 개발자 성향마다 달라서, 무엇이 일반적인지는 확신이 들지 않네요!

2024-05-21 04:23 UTC, laco-dev approved these changes
피드백 반영 고생하셨습니다.

2번의 수정으로 많은 부분 개선이 이뤄져서, 다음 단계에서 이어서 확인해도 좋을 것 같아요.
질문주신 내용은 답변 남겨두었습니다. 🐈 🐕 🐬 🐦

2024-05-21 04:23 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/data/cart/FakeCartRepository.kt
> +    private val cart: MutableList<CartItem> = savedCartItems.toMutableList()
Fake는 테스트에서 사용하기 위한 클래스이니 test 소스셋으로 옮겨볼까요?

2024-05-21 04:23 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/feature/cart/CartViewModel.kt
> +        totalCartCount.value = totalCartCount.value?.minus(1)
아이템을 제거하기 위해 MutableList 타입을 사용했지만 실제로 _cart 타입이 MutableList일 필요는 없을 거에요
List 타입도 remove를 지원하기 때문이죠

```kotlin
_cart.value = _cart.value?.remove(cartItem)
```

2024-05-21 04:23 UTC, laco-dev commented on app/src/main/java/woowacourse/shopping/feature/detail/ProductDetailActivity.kt
> +            }
Event를 이용할 때는 여러방법이 있고 선택의 문제이지만 trure, false로 나누는 대신 명확하게 하나의 이벤트로 처리하는게 효과적일 때가 많습니다.
```kotlin
addCartSuccessEvent.observe { ... }
addCartFailureEvent.observe { ... }
```
이 떄 위 이벤트 타입들은 Unit으로 사용하면 됩니다.

아래 내용은 지금 이해하기에는 조금 어렵지만 참고로 남겨봅니다.
https://medium.com/prnd/mvvm%EC%9D%98-viewmodel%EC%97%90%EC%84%9C-%EC%9D%B4%EB%B2%A4%ED%8A%B8%EB%A5%BC-%EC%B2%98%EB%A6%AC%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95-6%EA%B0%80%EC%A7%80-31bb183a88ce

2024-05-21 04:23 UTC, merged