[쇼핑 장바구니] 빙티 1, 2단계 미션 제출합니다.
woowacourse/android-shopping-cart pull request #55
Opened 2024-05-16 05:01 UTC by s6m1n

안녕하세요 제리! 이번 1, 2단계 잘 부탁드립니다 ㅎㅎ

2024-05-17 06:17 UTC, vagabond95 requested changes
빙티 안녕하세요~! 
미션 기간동안 잘 부탁드립니다 :)

UiState 를 sealed class 로 분리해주는 시도가 인상 깊었습니다. 다만, 구조적으로 조금 고민이 필요해보여요!
안드로이드 코드 위주로 리뷰를 진행했어요, 확인 후 리뷰 요청 부탁드릴게요~!

2024-05-17 06:17 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartViewModel.kt
> +    var offSet: Int = 0
maxOffset, offSet 는 private 으로 선언해도 괜찮지 않을까요~?

2024-05-17 06:17 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartViewModel.kt
> +    var offSet: Int = 0
네이밍은 자유도가 높고, 프로젝트마다 성격이 다르겠지만
보통은 각 페이지를 지칭하는 값은 offset 보다는 `page` 라는 네이밍을 더 많이 사용합니다 :)

바꿔야한다는 것은 아니고, 참고만 부탁드려요~!

2024-05-17 06:17 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartViewModel.kt
> +        cartRepository.load(offSet, 5).onSuccess {
페이지 사이즈 (가져오는 데이터의 수) 는 자주 바뀔 수 있는 값이고, 여러 곳에서 재사용할 여지가 있으므로 상수로 관리해보는 것은 어떨까요?

2024-05-17 06:17 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartViewModel.kt
> +            }
똑같은 처리를 하고 있어 굳이 분기를 태우지 않아도 될 것 같아요~!

2024-05-17 06:17 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/data/remote/DummyCartRepository.kt
> +            ((cartMap.size + 4) / 5 - 1).coerceAtLeast(0)
각 숫자가 무엇을 의미하는지 이해가 너무 어렵습니다!

상수화 해보는 것은 어떨까요?

2024-05-17 06:17 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/presentation/ui/shopping/ShoppingHandler.kt
> +}
현재 loadMore 함수는 동작을 명령하고 있고, onClick 함수는 콜백처럼 특정 상황이 발생했음을 알리고 있는데요.

함수의 네이밍 정책을 맞춰야 할 것 같아요.

2024-05-17 06:17 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/presentation/ui/shopping/ShoppingHandler.kt
> +}
만약 콜백 형식으로 네이밍을 지은다면, onClick 함수는 무엇이 클릭되었는지 좀 더 구체적으로 명시가 되어야 할 것 같습니다.

2024-05-17 06:17 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartViewModel.kt
> +    }
- get 함수인데, 값을 반환하지 않고 있어요.
- get 의 대상은 ItemCount 인데, 실제 값은 maxOffset 를 가져오고 있어요.

실제 함수가 동작하는 내용에 맞게 개선해볼 수 있을까요~?

2024-05-17 06:17 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/presentation/ui/shopping/ShoppingViewModel.kt
> +                _products.value = UiState.Finish((_products.value as UiState.Finish).data + it)
product List 를 이런식으로 전달할 경우, recyclerView 는 항상 notifyDataSetChanged() 를 호출할 수 밖에 없는 구조가 돼요.

몇가지 공부할만한 키워드를 남겨볼게요.
- notifyDataSetChanged 를 호출했을 때, 주의해야 할 점은 무엇일까?
- 현재 구조는 잠재적으로 어떤 문제점이 있을까? (hint : 새로 추가된 데이터만 업데이트 해줄 수 는 없을까?)

2024-05-17 06:17 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/presentation/ui/UiState.kt
> +sealed interface UiState<out T : Any> {
sealed interface 활용 👍

2024-05-17 06:17 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/presentation/ui/UiState.kt
> +sealed interface UiState<out T : Any> {
그런데 현재 구조는 치명적인 단점이 있어요.

제가 당장 떠오르는 문제는 다음과 같아요.

- LiveData<UiState> 일때, Error 가 한번 set 되면 이전 데이터는 날라간다.
- Finish 와 Error 는 근본적으로 성격이 다르다.
    - Error 는 일회성으로 발생한 이벤트이지만, Finish 가 담고있는 데이터는 계속 유지가 되어야 합니다.

그리고, Finish 라는 이름은 개선이 필요해보여요. 기본적으로 데이터를 전달하고자 할때 활용이 되는 것으로 보이는데,
Android 내에서 Finish 라는 네이밍은 Activity / Fragment 를 종료할 때 주로 사용되므로 현 상황에서는 적절하지 않을 것 같습니다!

2024-05-17 08:58 UTC, s6m1n commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartViewModel.kt
> +        cartRepository.load(offSet, 5).onSuccess {
반영했습니다!

2024-05-17 09:00 UTC, s6m1n commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartViewModel.kt
> +            }
아앗 그러네요 😅 수정했습니다!

2024-05-17 16:35 UTC, s6m1n commented on app/src/main/java/woowacourse/shopping/data/remote/DummyCartRepository.kt
> +            ((cartMap.size + 4) / 5 - 1).coerceAtLeast(0)
CartViewModel.kt에서 사용된 [PAGE_SIZE](https://github.com/woowacourse/android-shopping-cart/pull/55#discussion_r1604390893)와 관계되어 있어 파라미터로 주입하도록 수정했습니다!

2024-05-17 16:42 UTC, s6m1n commented on app/src/main/java/woowacourse/shopping/presentation/ui/shopping/ShoppingHandler.kt
> +}
사용자에게 혼란을 줄 것 같은 이름이네요! 아래처럼 콜백 형식으로 통일해 구체화했습니다 :)
```
interface ShoppingHandler {
    fun onProductClick(productId: Long)
    fun onLoadMoreClick()
}
```

2024-05-17 16:44 UTC, s6m1n commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartViewModel.kt
> +    }
maxOffset을 갱신한다는 의미를 담아 updateMaxOffset로 수정했습니다!

2024-05-17 17:35 UTC, s6m1n commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartViewModel.kt
> +    var offSet: Int = 0
> maxOffset, offSet 는 private 으로 선언해도 괜찮지 않을까요~?

```
is UiState.Finish -> {
    cartAdapter.updateList(it.data)
    with(binding) {
        layoutPage.isVisible = viewModel.maxPage > 0
        btnRight.isEnabled = viewModel.currentPage < viewModel.maxPage
        btnLeft.isEnabled = viewModel.currentPage > 0
        tvPageCount.text = (viewModel.currentPage + PAGE_OFFSET).toString()
    }
}
```
제리! 지금은 위의 CartActivity 코드 처럼, activity에서 viewModel의 maxOffset과 offSet 변수를 직접 꺼내어 검사하기 위해 private 키워드를 붙이지 않았는데, 혹시 아래 코드처럼 로직을 viewModel로 옮기라는 의도이신 걸까요?.? 제가 잘 이해한 건지 모르겠습니다..!
```
// viewModel에 위치
fun isPageControllerVisivle() = maxPage > 0
fun isRightButtonEnabled() = currentPage < maxPage
fun isLeftButtonEnabled() = currentPage > 0

 // activity에 위치
layoutPage.isVisible = viewModel.isPageControllerVisivle()
btnRight.isEnabled = viewModel.isRightButtonEnabled()
btnLeft.isEnabled = viewModel.isLeftButtonEnabled()
```


> 보통은 각 페이지를 지칭하는 값은 offset 보다는 page 라는 네이밍을 더 많이 사용합니다 :)

그리고 바꾸지 않아도 된다고 하셨지만 offset이란 단어를 page로 대체하니 변수명이나 메서드명이 더 직관적인 것 같아 변경해보았습니다ㅎㅎ 아래는 단순 궁금증입니다!
페이지네이션에는 `오프셋 기반 방식`과 `커서 기반 방식`이 있다고 알고 있습니다.
저와 페어는 `오프셋 기반 방식`으로 구현해서 offset(시작점)이란 단어를 사용했는데, 이 방식을 사용할 때에도 page라는 네이밍이 더 보편적일까요? page는 왠지 1부터 시작해야할 것 같아서, 지금처럼 값이 0부터 시작하는 경우에는 offset이 더 자연스럽게 느껴집니다! (index 처럼요..)

2024-05-17 17:36 UTC, s6m1n commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartViewModel.kt
> +    var offSet: Int = 0
> maxOffset, offSet 는 private 으로 선언해도 괜찮지 않을까요~?

```
is UiState.Finish -> {
    cartAdapter.updateList(it.data)
    with(binding) {
        layoutPage.isVisible = viewModel.maxPage > 0
        btnRight.isEnabled = viewModel.currentPage < viewModel.maxPage
        btnLeft.isEnabled = viewModel.currentPage > 0
        tvPageCount.text = (viewModel.currentPage + PAGE_OFFSET).toString()
    }
}
```
제리! 지금은 위의 CartActivity 코드처럼 activity에서 viewModel의 maxOffset과 offSet 변수를 직접 꺼내어 검사하기 위해 private 키워드를 붙이지 않았는데, 혹시 아래 코드처럼 로직을 viewModel로 옮기라는 의도이신 걸까요?.? 제가 잘 이해한 건지 모르겠습니다..!
```
// viewModel에 위치
fun isPageControllerVisivle() = maxPage > 0
fun isRightButtonEnabled() = currentPage < maxPage
fun isLeftButtonEnabled() = currentPage > 0

 // activity에 위치
layoutPage.isVisible = viewModel.isPageControllerVisivle()
btnRight.isEnabled = viewModel.isRightButtonEnabled()
btnLeft.isEnabled = viewModel.isLeftButtonEnabled()
```


> 보통은 각 페이지를 지칭하는 값은 offset 보다는 page 라는 네이밍을 더 많이 사용합니다 :)

그리고 바꾸지 않아도 된다고 하셨지만 offset이란 단어를 page로 대체하니 변수명이나 메서드명이 더 직관적인 것 같아 변경해보았습니다ㅎㅎ 아래는 단순 궁금증입니다!
페이지네이션에는 `오프셋 기반 방식`과 `커서 기반 방식`이 있다고 알고 있습니다.
저와 페어는 `오프셋 기반 방식`으로 구현해서 offset(시작점)이란 단어를 사용했는데, 이 방식을 사용할 때에도 page라는 네이밍이 더 보편적일까요? page는 왠지 1부터 시작해야할 것 같아서, 지금처럼 값이 0부터 시작하는 경우에는 offset이 더 자연스럽게 느껴집니다! (index 처럼요..)

2024-05-18 07:42 UTC, s6m1n commented on app/src/main/java/woowacourse/shopping/presentation/ui/shopping/ShoppingViewModel.kt
> +                _products.value = UiState.Finish((_products.value as UiState.Finish).data + it)
notifyDataSetChanged는 어댑터에게 아이템 리스트가 전부 변경되었다고 알려, 모든 뷰를 새로 그리도록 하기 때문에 비용이 높습니다! 변경된 아이템만 알 수 있도록 notifyItemRangeInserted을 사용하도록 리팩터링 해주었습니다!

### 질문
어댑터 items의 타입으로 var list와 val mutableList 중 어떤 게 더 적절할지 판단이 서지 않습니다..😅
Adapter가 참조하는 items의 주소가 변경되느냐, 내용이 변경되느냐의 차이 같은데 제리는 어떤 방식을 더 선호하실까요?

2024-05-18 12:40 UTC, s6m1n commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartAdapter.kt
> +            .into(binding.ivCart)
textFormattedCurrency라는 BindingAdapter 메서드로 분리해 상품 목록과 장바구니 목록에서 재사용 가능하도록 수정했습니다! 👍

2024-05-18 12:42 UTC, s6m1n commented on app/src/main/java/woowacourse/shopping/presentation/ui/UiState.kt
> +sealed interface UiState<out T : Any> {
미처 생각하지 못했는데 안드로이드 생명주기의 Finish와 혼동될 수 있을 것 같네요..ㅎㅎ
Finish -> Success로 수정해주었습니다. 알려주셔서 감사합니다!

그리고 말씀하신 'Error 상태에서의 데이터 손실' 문제를 개선하고자 [블로그](https://medium.com/@laco2951/android-ui-state-modeling-%EC%96%B4%EB%96%A4%EA%B2%8C-%EC%A2%8B%EC%9D%84%EA%B9%8C-7b6232543f25)를 참고해 **Boolean 타입을 갖는 LiveData**로 에러 여부를 전달해 처리하도록 수정했습니다.
기존 코드에서는 아이템을 끝까지 불러온 뒤 더보기를 클릭하면 Error가 set 되면서 이전 데이터가 날아가, 화면 회전 시 빈 리스트가 보여지는 버그가 있었는데 이를 개선할 수 있었습니다 👍

다만 한 화면에 여러 유형의 error가 있는 경우 각 분기를 어떻게 처리할 수 있을지가 고민입니다!
예를 들어 ShoppingActivity에서는 `loadInitialProductByPaged에서 초기 데이터 로드에 실패`와, `addProductByPage에서 추가 데이터 로드에 실패`하는 두 가지 경우를 에러로 간주하는데요.
이럴 때는 각 케이스마다 initLoadError, addProductError를 따로 만들어주어야 할까요?

2024-05-18 14:46 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/presentation/ui/UiState.kt
> +sealed interface UiState<out T : Any> {
에러별로 LiveData 를 만들면, 에러 케이스마다 코드가 추가되어 관리가 어려워질 것 같아요!

Error 에 대한 enum 을 만들어 분류해보는 것은 어떨까요?
추가로, Enum 으로 분류한다고 가정했을 때 다음과 같은 고민이 남는데, 빙티의 선택이 궁금합니다.

1. Error Type enum 을 넘기고, View 에서 Error 별 처리를 한다.
2. Error Type enum 으로 구분하되, 에러별 별도 view 동작이 필요할 경우 (ex/ toast 노출) 해당 동작을 view 에게 명력한다.

빙티는 어느 방식이 더 적절하다고 생각하실까요?

2024-05-18 14:49 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/presentation/ui/shopping/ShoppingViewModel.kt
> +                _products.value = UiState.Finish((_products.value as UiState.Finish).data + it)
빙티 말대로, list 의 내용을 변경할 수 있는 것은 모두 같으나 저는 var list 를 더 선호하는 것 같습니다.

이유는, 전자는 List 를 참조하는 쪽에서는 변경이 불가능 하지만 후자는 (MutableList 타입을 그대로 넘긴다면) 참조하는쪽에서도 변경이 가능하기 때문에 상태 추적이 좀 더 어려워져져서 선호하지 않습니다!

2024-05-18 14:55 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartViewModel.kt
> +    var offSet: Int = 0
> activity에서 viewModel의 maxOffset과 offSet 변수를 직접 꺼내어 검사하기 위해 private 키워드를 붙이지 않았는데

앗 이부분은 IDE 상으로 참조가 안되서 코멘트를 남겼는데, 제가 빌드를 안하고 확인해서 참조가 안되는 부분이었네요 😿 무시해주셔도 좋습니다. 혼동 드려 죄송합니다~~!

> 페이지네이션에는 오프셋 기반 방식과 커서 기반 방식이 있다고 알고 있습니다.
저와 페어는 오프셋 기반 방식으로 구현해서 offset(시작점)이란 단어를 사용했는데, 이 방식을 사용할 때에도 page라는 네이밍이 더 보편적일까요? 

이 부분은 보통 서버의 정책에 네이밍이 따라가곤 합니다. page / cursor ... etc
저도 일반적이라고 했지만, 적고보니 일반적이지 않네요 ^^;

다만, `page는 왠지 1부터 시작해야할 것 같아서, 지금처럼 값이 0부터 시작하는 경우에는 offset이 더 자연스럽게 느껴집니다!` 이 경우 제가 경험했던 프로젝트의 페이지네이션의 단위는 0 부터 시작했던 것 같습니다. 물론 서버의 정책에 따라 달라질 수는 있지만요 ㅎㅎ

이 부분은 너무 깊게 집중하기보다는 팀/서버 와의 정책을 맞추는 부분으로 봐주시면 좋을 것 같습니다~!

2024-05-18 15:09 UTC, vagabond95 requested changes
전반적으로 코드를 깔끔하게 개선해주셔서 크게 피드백 드릴 부분이 없었네요 👍 

추가로 고민해볼만한 점에 대해 코멘트 남겼는데 확인 부탁드릴게요~!
(Error LiveData 에 대한 내용은 너무 깊게 고민하지 않으셔도 괜찮습니다.)

2024-05-18 15:09 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartActivity.kt
> +        }
이러한 상태도 viewModel 에서 관리하고, view 에서는 상태를 표현하는데만 집중해보면 어떨까요?

2024-05-18 15:09 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartViewModel.kt
> +    val error: LiveData<Boolean> = _error
error 를 별도로 분리하는 시도 👍 
사실 기존의 Fail 은 UiState 와는 속성이 무관했죠 :)

2024-05-18 15:09 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartViewModel.kt
> +            _error.value = false
그런데, 항상 반복적으로 false / true 처리를 해야하는 보일러 플레이트가 생겼어요.

이러한 작업을 해야하는 근본적인 이유와 이를 개선한 방법에 대해 추후에 학습하게 되실 텐데, 미리 고민해볼 주제를 살짝 남겨드립니다 :)

2024-05-18 15:09 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/presentation/ui/detail/ProductDetailActivity.kt
> +            .show()
토스트 내용은 에러 내용을 담고 있으므로, 함수 내용이 좀 더 구체적으로 변하거나 메세지 내용을 전달받을 수 있어야 할 것 같아요!

2024-05-18 15:09 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/presentation/ui/detail/ProductDetailActivity.kt
> +            .into(binding.ivProduct)
이 부분도 BindingAdapter 를 활용해보면 좋겠네요 :)

2024-05-20 07:20 UTC, s6m1n commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartViewModel.kt
> +            _error.value = false
제리가 이전 리뷰에서 언급하셨던 것처럼, error는 지속적인 상태가 아니라 일시적인 이벤트로 처리되어야 합니다!
따라서 성공 시 다시 value를 false로 직접 바꿔주는 보일러 플레이트 코드가 생겼습니다.
여기에 더해, 상태를 다시 false로 바꿔주기 전에 화면 회전 등 액티비티 재생성이 될 시 error = true가 반복적으로 observe되며 토스트 메시지가 나타나는 버그가 있었습니다.
중복 처리로 인한 문제를 개선하기 위해 `이벤트 처리 여부를 확인해주는 Event 클래스`를 만들어 이를 개선할 수 있었습니다!

2024-05-20 07:21 UTC, s6m1n commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartViewModel.kt
> +            _error.value = false
제리가 이전 리뷰에서 언급하셨던 것처럼, error는 지속적인 상태가 아니라 일시적인 이벤트로 처리되어야 합니다!
따라서 성공 시 다시 error를 false로 직접 바꿔주는 보일러 플레이트 코드가 생겼습니다.
뿐만 아니라, false로 바꿔주기 전에 화면 회전 등 액티비티 재생성이 될 시 error = true가 반복적으로 observe되며 토스트 메시지가 나타나는 버그가 있었습니다.
중복 처리로 인한 문제를 개선하기 위해 `이벤트 처리 여부를 확인해주는 Event 클래스`를 만들어 이를 개선할 수 있었습니다!

2024-05-20 07:22 UTC, s6m1n commented on app/src/main/java/woowacourse/shopping/presentation/ui/detail/ProductDetailActivity.kt
> +            .show()
토스트를 띄우는 함수를 BindingActivity로 옮기고 에러 메세지 내용을 전달받을 수 있도록 했습니다!

2024-05-20 08:26 UTC, s6m1n commented on app/src/main/java/woowacourse/shopping/presentation/ui/UiState.kt
> +sealed interface UiState<out T : Any> {
Error 처리에 대한 책임을 어떻게 부여하는지에 따라 달라질 것 같아요!
저는 도메인/데이터 처리 결과에 따라 에러 종류를 정의하는 것 까지가 ViewModel의 책임이고 이 상태들을 UI에 어떻게 표현할지는 Activity의 책임이라고 생각했습니다 🤔
그래서 Error Type enum을 추가해 뷰모델에서 Activity로 전달하고 View에서 각 타입에 따른 동작을 처리해주도록 수정해보았어요~
현재는 에러 발생 시 Toast만 띄워주고 있는데, 추후 에러 이미지나 기타 동작들이 세분화 되면 onEventUnhandledContent에 분기를 추가해서 처리할 것 같습니다!

2024-05-20 09:31 UTC, s6m1n commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartActivity.kt
> +        }
제리! 상태를 ViewModel로 옮기기 위해 기존 뷰바인딩을 사용하던 구조에서 데이터 바인딩으로 수정하려고 하는데, 이 부분을 비롯해 다른 뷰바인딩까지 3, 4단계를 구현하며 한번에 수정해도 될까요? 바꾸고 내려면 PR 제출이 너무 늦어질 것 같아서요!!😂

2024-05-21 00:38 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartActivity.kt
> +        }
네 괜찮습니다~!

2024-05-21 00:41 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/presentation/ui/UiState.kt
> +sealed interface UiState<out T : Any> {
좋은 방향이네요!
저는 2번을 선호하지만, 또 1번을 선호하는 팀원분들도 계시더라구요.
빙티 말 처럼 에러처리에 대한 책임을 어떻게 부여하느냐의 차이라고 생각해요.

제일 중요한 점은 코드 전반적으로 이러한 정책이 일관되게 구현되는 것 같습니다.
결국은 코드를 이해하고 변경하기 쉽게 만드는 것이 목표니까요~!

2024-05-21 00:44 UTC, vagabond95 approved these changes
LiveData 는 구조적으로 이벤트를 보내기에는 적합하지 않은 구현체인데, 빙티는 스스로 개선 방안을 잘 구현해주셨네요 👍 

UI 에서 다루는 에러 타입의 경우 현 구조에서는 확장성의 한계가 있는데, 한번 고민해보면 좋을 것 같아요.

1,2단계는 여기서 마무리하겠습니다. 고생 많으셨습니다!

2024-05-21 00:44 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/presentation/util/Event.kt
> +class Event<T>(private val content: T) {
보일러 플레이트를 제거할 수 있게 되었네요~!

2024-05-21 00:44 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/presentation/ui/Error.kt
> +}
에러를 잘 세분화해주셨네요 👍 
그런데 프로젝트가 커질수록 다음과 같은 요구사항이 발생할 수 있어요.

`AllProductsLoaded 에러가 발생했을 때, A 화면에서는 "에러" / B 화면에서는 "오류" 라고 노출해주세요.`
그때는 현재처럼 에러가 하나의 메세지를 가지고 있다면 대응이 어려운데요, 어떻게 해결해볼 수 있을지 고민해보면 좋을 것 같습니다 :)

2024-05-21 00:45 UTC, merged