[쇼핑 장바구니] 팡태 1, 2단계 미션 제출합니다.
woowacourse/android-shopping-cart pull request #57
Opened 2024-05-16 05:12 UTC by Hevton

안녕하세요 두루!! 1, 2 단계 미션 잘 부탁드립니다 !!

https://github.com/woowacourse/android-shopping-cart/assets/86276828/15b65519-444f-4813-8a43-fc441547de4f

2024-05-16 15:52 UTC, Gyuil-Hwnag requested changes
팡태 안녕하세요!
레벨1에 이어 레벨2 장바구니 미션을 함께하게 된 두루라고 합니다. 잘부탁드립니다!

해당 미션 구현 고생 많으셨습니다!
미션 구현을 너무 잘 해주셨습니다 💯

고민해보시면 좋을만한 내용들 코멘트를 달았으니 확인해주시면 감사하겠습니다.
남겨주신 질문에 대한 답변 코멘트 남겨두었습니다! 추가적으로 아직 BindingAdapter에 대한 적용이 많이 어려우실 것 같아서 예시와 함께 남겨두었으니 살펴보시면 좋을 것 같다는 생각이 듭니다!💪

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏 
화이팅입니다💪

2024-05-16 15:52 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/data/remote/DummyCartRepository.kt
> +        }
해당 함수에서 사용하는 값들을 유의미한 네이밍으로 상수화를 해보는 것도 좋을 것 같다는 생각이 듭니다~💪

2024-05-16 15:52 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/ViewModelFactory.kt
> +}
ViewModelFactory 를 만들어주셨네요~👍

2024-05-16 15:52 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartActivity.kt
> +                        tvPageCount.text = (viewModel.offSet + OFFSET_BASE).toString()
해당 내용을 BindingAdapter를 사용하도록 한다면, Activity 내의 구현을 줄여볼 수 있겠다는 생각이 듭니다~💪

2024-05-16 15:52 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartActivity.kt
> +                }
`UiState`의 활용 좋습니다~👍

2024-05-16 15:52 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartActivity.kt
> +        }
해당 내용도 BindingAdapter로 뽑아볼 수 있겠다는 생각이 듭니다!!💪
약간의 힌트를 첨가하겠습니다😀
~~~kotlin
interface CartActionHandler {
    fun onNextButtonClicked()
    fun onPreviousButtonClicked()
}

// activity_cart.xml
    <data>
        <variable
            name="eventListener"
            type="woowacourse.shopping.presentation.ui.cart.CartActionHandler">
        </variable>
    </data>
...
<androidx.appcompat.widget.AppCompatButton
                android:id="@+id/btn_left"
                android:layout_width="42dp"
                android:layout_height="wrap_content"
                android:layout_marginStart="115dp"
                android:background="@drawable/background_button"
                android:text="@string/left_arrow"
                android:textColor="@color/white"
                android:textStyle="bold"
                android:onClick="@{() -> eventListener.onNextButtonClicked()}"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintStart_toStartOf="parent" />

            <androidx.appcompat.widget.AppCompatButton
                android:id="@+id/btn_right"
                android:layout_width="42dp"
                android:layout_height="wrap_content"
                android:layout_marginEnd="115dp"
                android:background="@drawable/background_button"
                android:text="@string/right_arrow"
                android:textColor="@color/white"
                android:textStyle="bold"
                android:onClick="@{() -> eventListener.onPreviousButtonClicked()}"
                app:layout_constraintBottom_toBottomOf="parent"
                app:layout_constraintEnd_toEndOf="parent" />

// CartViewModel.kt
class CartViewModel(private val cartRepository: CartRepository) : ViewModel(), CartActionHandler {
...
    override fun onNextButtonClicked() {
        if (offSet == maxOffset) return
        offSet++
        loadProductByOffset()
    }

    override fun onPreviousButtonClicked() {
        if (offSet == 0) return
        offSet--
        loadProductByOffset()
    }

// CardActivity.kt
        binding.eventListener = viewModel
~~~

2024-05-16 15:52 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartActivity.kt
> +    }
해당 내용도 위의 내용을 참고한다면, Activity 내의 구현을 줄여볼 수 있겠다는 생각이 듭니다~💪

2024-05-16 15:52 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartAdapter.kt
> +        binding.tvPrice.text = binding.root.context.getString(R.string.won, item.product.price)
BindingAdapter를 사용한다면, 해당 구현도 줄여볼 수 있을 것 같다는 생각이 듭니다!💪

2024-05-16 15:52 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartViewModel.kt
> +        get() = field.coerceAtMost(maxOffset)
해당 내용들이 외부에 공개되도록 구현이 된 이유가 있을까 궁금합니다🤔

2024-05-16 15:52 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/detail/ProductDetailActivity.kt
> +        }
해당 내용을 함수로 분리를 해보는 것도 좋을 것 같다는 생각이 듭니다!💪
`observeProducts()`

2024-05-16 15:52 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartViewModel.kt
> +        }
> 1. 현재 제가 구현한 UiState에서는 , 20개의 데이터를 불러와서 Finish 상태가 된 뒤에 추가 로드가 실패한다면 State가 Error로 이동하기에, 갖고 있는 20개 데이터마저 모두 날아가게 됩니다. 그러므로 단일성에 가까운 방법입니다. 이러한 로직에 대해서 현업에서는 보통 어떤 방식으로 구현하는지 평소에도 궁금했는데.. 이 기회에 여쭤볼 수 있을까요? [참고 문서](https://medium.com/@laco2951/android-ui-state-modeling-%EC%96%B4%EB%96%A4%EA%B2%8C-%EC%A2%8B%EC%9D%84%EA%B9%8C-7b6232543f25)

질문 남겨주신 내용이 있어서 코멘트 남겨두었습니다!
(`|| _carts.value is UiState.Error` 에러인 상황에도 Cart 리스트를 업데이트 해주고 계신 것 같습니다🥲)
아래처럼 작성을 한다면, `a`는 1일까요?? 0일까요??😅
- 예시
~~~kotlin
var a = 1
a = 0
~~~

추가적으로 현업에서는 회사마다 컨벤션에 따라서 좀 다르긴 합니다!
남겨주신 레퍼런스의 1, 2, 3, 4 모두 사용할 수 있어서 팡태가 각각을 비교해보고 어떤 것이 좀 더 좋을지 의견을 남겨주셔도 좋을 것 같다는 생각이 듭니다!💪

2024-05-16 15:52 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/shopping/ShoppingActivity.kt
> +        }
수정이 필요한 것은 아니며, 도움이 될만한 내용인 것 같아서 코멘트 남겨두었습니다!
해당 내용은 아래와 같이 넣어줄 수도 있어서 팡태가 보기에 어떤 것이 가독성 측면에서 이점을 주는지 고민을 해봐도 좋을 것 같다는 생각이 듭니다~💪
~~~kotlin
    private fun initAdapter() {
        val layoutManager = GridLayoutManager(this, GRIDLAYOUT_COL)
        layoutManager.spanSizeLookup = spanManager
        binding.rvShopping.layoutManager = layoutManager
        binding.rvShopping.adapter = adapter
    }

    private val spanManager = object : GridLayoutManager.SpanSizeLookup() {
            override fun getSpanSize(position: Int): Int {
                return if (adapter.getItemViewType(position) == ShoppingViewType.Product.value) {
                    ShoppingViewType.Product.span
                } else {
                    ShoppingViewType.LoadMore.span
                }
            }
        }
~~~

2024-05-16 15:52 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/shopping/adapter/ShoppingViewType.kt
> +    }
> 2. ShoppingAdapter의 onCreateViewHolder() 함수에서 분기문을 else 없이 처리하기 위해 ViewType을 별도의 enum class로 관리하고 있는데, 이게 맞는지 싶습니다.. ㅜㅜ 

질문 남겨주신 내용이 있어서 코멘트 남겨두었습니다!
1. onCreateViewHolder() 에서의 else 처리랑 enum class 내에서 else 처리한 것이랑 어떤 차이점이 있을까요??
2. onCreateViewHolder() 에서 else 부분을 없애려고 하는 이유가 있을까요??

2024-05-16 15:52 UTC, Gyuil-Hwnag commented on app/src/main/res/layout/activity_cart.xml
> +                />
xml 에서 다음 명령어를 사용하여 코드를 포맷해보는 것은 어떨까요?🤔
Ctrl + Alt + L (Windows/Linux)
Option + Cmd + L (Mac)

2024-05-17 05:45 UTC, Hevton commented on app/src/androidTest/java/woowacourse/shopping/presentation/ui/cart/CartActivityTest.kt
> +    }
감사합니다 두루! 이에 대한 테스트도 필요할 것 같아서 적용했습니다!

2024-05-17 06:00 UTC, Hevton commented on app/src/androidTest/java/woowacourse/shopping/presentation/ui/detail/ProductDetailActivityTest.kt
> +class ProductDetailActivityTest {
두루! 감사합니다. 이 부분도 진행해 보았는데요, 이러한 테스트로 괜찮은지 여쭤볼 수 있을까요?
``` kotlin
    @Test
    fun `장바구니에_담으면_상품이_데이터에_추가된다`() {
        onView(withId(R.id.tv_add_cart)).perform(click())
        DummyCartRepository.load(0, 1).onSuccess {
            it.size shouldBe 1
        }.onFailure {
            throw IllegalStateException()
        }
    }
```

2024-05-17 06:16 UTC, Hevton commented on app/src/androidTest/java/woowacourse/shopping/presentation/ui/shopping/ShoppingActivityTest.kt
> +    val activityRule = ActivityScenarioRule(ShoppingActivity::class.java)
감사합니다 이 부분도 테스트 하니까 너무 좋네요!

2024-05-17 06:33 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/data/remote/DummyCartRepository.kt
> +
혹시 다른 추천해주실 방법이 있으셨을까요??!

2024-05-17 06:37 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/data/remote/DummyCartRepository.kt
> +        }
놓치고 있었네요 ㅜㅜ 감사합니다!

2024-05-17 06:40 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/data/remote/DummyCartRepository.kt
> +        }
두루! 여기서 페이지 사이즈인 5를 PAGE_SIZE로 상수화시켰는데, 이를 갖고 있는 곳이
CatViewModel이어야 할지 DummyCartRepository이어야 할지 고민이 있습니다!

2024-05-17 06:55 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartViewModel.kt
> +        get() = field.coerceAtMost(maxOffset)
뷰바인딩을 쓰면서 Activity에서 maxOffset과 offset에 따라 View의 비지블 처리를 해주어야 해서 그렇게 진행하게 되었습니다.
데이터 바인딩으로 변환하면서 해당 부분을 개선해보도록 하겠습니다!

2024-05-17 07:03 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/presentation/ui/shopping/ShoppingActivity.kt
> +        }
앗 제가 이 방식으로 구현을 하려고 했는데 함수형으로 작성했었네요.. 저도 이 방식을 많이 봐서 가독성이 더 좋다고 생각합니다.

2024-05-17 07:04 UTC, Hevton commented on app/src/main/res/layout/activity_cart.xml
> +                />
너무 좋은 방법 알려주셔서 감사합니다..!

2024-05-21 04:38 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartActivity.kt
> +        }
감사합니다! 이를 적용했습니다

2024-05-21 04:38 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartActivity.kt
> +    }
감사합니다! 적용했습니다!

2024-05-21 04:57 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartAdapter.kt
> +        binding.tvPrice.text = binding.root.context.getString(R.string.won, item.product.price)
감사합니다 이 부분도 데이터바인딩으로 변경하였습니다!

2024-05-21 04:57 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartViewModel.kt
> +        get() = field.coerceAtMost(maxOffset)
Activity에서 maxOffset과 offset에 따라 View의 비지블 처리를 해주어야 해서 그렇게 진행하게 되었습니다!

2024-05-21 05:08 UTC, Hevton commented
안녕하세요 두루, 질문드릴 내용을 정리해보았습니다!


1. 
> 해당 내용을 BindingAdapter를 사용하도록 한다면, Activity 내의 구현을 줄여볼 수 있겠다는 생각이 듭니다~💪
```
when (it) {
                is UiState.None -> {}
                is UiState.Success -> {
                    cartAdapter.updateList(it.data)
                    with(binding) {
                        layoutPage.isVisible = viewModel.maxOffset > 0
                        btnRight.isEnabled = viewModel.offSet < viewModel.maxOffset
                        btnLeft.isEnabled = viewModel.offSet > 0
                        tvPageCount.text = (viewModel.offSet + OFFSET_BASE).toString()
                    }
                }
            }
```
코멘트를 남겨주신대로, 프로젝트 전반적으로 데이터바인딩으로 변경하는 과정을 가졌습니다.
하지만 위 코드에서 DataBinding & BindingAdapter로 적용하는 커밋을 남겼다가, 이를 다시 제거하는 커밋을 남겼는데요..!

먼저 xml에서 뷰에 바인딩을 할 때, 자동으로 변경 감지가 필요할 경우엔 LiveData같은 상태를 넘겨줘야만 변경이 감지가 되는 것을 알게 되었습니다.
```
text: "@{viewModel}" 로 정의하고 bindingAdapter에서 처리해줬다가, 처음에는 데이터가 매핑되지만 변경 감지가 안되는 것을 파악했습니다.
```

그렇게 되면 maxOffset과 offset 모두 LiveData로 변경하면 되겠지만, btnRight의 enable 처리는 offSet과 maxOffset 두 변경에 대해서 모두 감지해야 하는데 어떻게 처리해야 할지 난감하더라구요..!

또한 위 코드에서 cartAdapter의 updateList같은 처리는 어떻게 데이터바인딩으로 적용하는지에 대한 의문도 있어서 다시 뷰바인딩으로 변경해놓았습니다..


2.
ProductDetailActivity 에서도 뷰바인딩을 데이터바인딩으로 변경하는 과정을 고민하던 중
```
binding.tvAddCart.setOnClickListener {
    finish()
    viewModel.saveCartItem(state.data)
}
```
위와 같은 로직에서 finish를 수행하기 위해서 어떻게 처리해야 하는지도 궁금합니다..!

3.
UiState에서 Error 처리는 별개로 존재해야 한다고 느껴서 따로 뺐으며, 이벤트성으로 처리되는게 적절하다고 생각하여 그렇게 구현했습니다!

2024-05-21 10:17 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/data/remote/DummyCartRepository.kt
> +        }
만약 Ui마다 A 에서는 10개씩, B 에서는 5개씩 이렇게 나눠질 수도 있으니 ViewModel 에서 가지고 있는 것도 나쁘지 않을 것 같다는 생각이 들기는 합니다!💪
그러나 이렇게 된다면 cartRepository를 사용하는 모든 ViewModel 에서 전부 페이징의 기준을 들고 있게 되니 어떤 방식이 좋을지 팡태의 의견도 남겨주시면 좋을 것 같습니다!

2024-05-21 10:47 UTC, Gyuil-Hwnag approved these changes
해당 미션 너무 고생 많으셨습니다! 
리뷰 반영 정말 잘 해주셨네요💯

해당 미션은 다음 미션 진행을 위하여 머지하도록 하겠습니다.
도움이 될만한 코멘트 달았으니 확인하여 다음 미션에서 반영해주셔도 좋을 것 같습니다.
코멘트 남긴 내용들에 대해서는 3, 4단계를 진행하기 전에 적용을 해는 것도 좋을 것 같습니다!💪

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏
다음 미션도 화이팅입니다💪

2024-05-21 10:47 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartViewModel.kt
> +        get() = field.coerceAtMost(maxOffset)
질문 남겨주신 내용이 있어 해당 내용에 코멘트 남겨두었습니다!
현재 구조를 보면 Respository 에서 최대 Page 수를 받아오도록 설정이 되어 있는데, 이를 Response 에서 받아오도록 해보는 것은 어떨까 하는 생각이 듭니다!
아래처럼 Response 로 받아온 값들을 LiveData + DataBinding을 활용한다면, Fragment 에서 넣어주는 부분도 사라질 수 있겠다는 생각도 들기는 합니다!
~~~kotlin
data class CartResponse(
    val hasNext: Boolean,
    val hasPrevious: Boolean,
    val carts: List<Cart>
)

    private val _hasPrevious: MutableLiveData<Boolean> = MutableLiveData()
    val hasPrevious: LiveData<Boolean> = _hasPrevious

    private val _hasNext: MutableLiveData<Boolean> = MutableLiveData()
    val hasNext: LiveData<Boolean> = _hasNext
~~~

2024-05-21 10:47 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/detail/ProductDetailActivity.kt
> +                    }
- 질문 2번에 대한 코멘트 입니다!
~~~kotlin
// ViewModel
    private val _navigateToPrevious: MutableLiveData<ErrorEventState<Unit>> = MutableLiveData<ErrorEventState<Unit>>()
    val navigateToPrevious: LiveData<ErrorEventState<Unit>> = _navigateToPrevious

    fun saveCartItem(product: Product) {
        productCartRepository.save(product)
            .onSuccess { _navigateToPrevious.value = ErrorEventState(Unit) }
    }


// Activity
        viewModel.navigateToPrevious.observe(this) {
            finish()
        }
~~~

2024-05-21 10:47 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/ErrorEventState.kt
> +    fun peekContent(): T = content
- 3번에 대한 답변입니다!
과연 Event 는 에러만 있는 것일까 라는 생각이 듭니다🤔
(클릭등도 이벤트가 아닐까 라는 생각이 듭니다!💪)

2024-05-21 10:47 UTC, Gyuil-Hwnag commented on app/src/androidTest/java/woowacourse/shopping/presentation/ui/cart/CartActivityTest.kt
> +    }
더보기에 대한 테스트 좋습니다~ 👍

2024-05-21 10:47 UTC, Gyuil-Hwnag commented on app/src/androidTest/java/woowacourse/shopping/presentation/ui/shopping/ShoppingActivityTest.kt
> +    }
더보기에 대한 기능 테스트 좋습니다~👍

2024-05-21 10:47 UTC, Gyuil-Hwnag commented on app/src/androidTest/java/woowacourse/shopping/presentation/ui/shopping/ShoppingActivityTest.kt
> +        }
해당 내용에 대해서는 함수로 만들어서 사용을 해볼 수도 있겠다는 생각도 듭니다💪

2024-05-21 10:47 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/data/remote/DummyProductCartRepository.kt
> +        }
위의 1번 질문에 대한 코멘트를 참고하면 좋을 것 같다는 생각이 듭니다!
모든 함수에서 페이지를 Load 할때마다 해당 함수를 호출하지 않도록 수정을 해보는 것도 좋을 것 같다는 생각이 듭니다!💪
Response로 묶는 다면, 파라미터로 받은 pageSize를 활용하여, 마지막 페이지인지에 대해서 유용하게 사용할 수 있겠다는 생각이 듭니다!

2024-05-21 10:47 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartActivity.kt
> +                        tvPageCount.text = (viewModel.offSet + OFFSET_BASE).toString()
해당 내용에 대해서는 1번에 남겨둔 내용을 참고한다면, 사라질 수도 있겠다는 생각이 듭니다💪

2024-05-21 10:47 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/cart/CartViewModel.kt
> +    }
Response에 현재 페이지값을 추가하는 방식으로 Offset 이라는 지역 변수도 없애볼 수 있겠다는 생각이 듭니다!
사실 지역 변수로 나누어져 있는 것들을 Response로 묶고 이를 Repository 에서의 로직을 통해서 판별하도록 책임을 넘기는 것이 중요한 키워드 입니다!

2024-05-21 10:47 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/detail/ProductDetailBindingAdapter.kt
> +    }
BindingAdapter의 활용 좋습니다!
ViewModel 을 직접 받을 필요가 있었을까 라는 생각이 듭니다 `products`를 받아서 처리해도 괜찮을 것 같다는 생각이 듭니다!
BindingAdapter 에서 해당 처럼 ViewMdoel 에 대한 의존성을 가지고 있게 되면, 추후 BindingAdapter에 대한 재사용이 어려울 것 같습니다🥲

2024-05-21 10:47 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/detail/ProductDetailViewModel.kt
> +    }
LiveData의 활용 정말 좋습니다!👍

2024-05-21 10:47 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/detail/ProductDetailViewModel.kt
> +    }
`save()`는 Result 객체를 반환하니 Result 객체의 장점을 활용한다면 저장을 하다 오류가 발생한 경우등에 대해서도 처리가 가능할 것 같다는 생각이 듭니다!💪
(현재 구현상으로는 발생할일이 없겠지만, 실제 서버와 통신한다는 느낌으로 처리를 하도록 해보는 것도 좋을 것 같다는 생각이 듭니다)

2024-05-21 10:47 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/presentation/ui/shopping/adapter/ShoppingViewHolder.kt
> +            }
해당 내용도 기존처럼 DataBinding을 활용하도록 해보는 것도 좋을 것 같다는 생각이 듭니다!💪

2024-05-21 10:48 UTC, Gyuil-Hwnag commented
@Hevton 
팡태 안녕하세요~
질문 남겨주신 내용들에 대해서 리뷰를 하면서 코멘트로 남겨두었습니다!!
고민 공유해주신 것들 정말 좋습니다ㅎㅎ😆
다음 3, 4단계 미션도 화이팅입니다!!

2024-05-21 10:48 UTC, merged

2024-05-27 07:59 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/presentation/ui/ErrorEventState.kt
> +    fun peekContent(): T = content
감사합니다! 이에 대해 확장했습니다!

2024-05-27 07:59 UTC, Hevton commented on app/src/main/java/woowacourse/shopping/presentation/ui/shopping/adapter/ShoppingViewHolder.kt
> +            }
감사합니다!