[크롱] 1, 2단계 쇼핑 장바구니 제출합니다.
woowacourse/android-shopping-cart pull request #6
Opened 2023-05-11 08:45 UTC by krrong

안녕하세요 커트! 처음 뵙는 것 같아요 저는 안드로이드 크롱이라고 해요:) 
이번 미션은 월요일에 극장선택 3, 4단계 미션을 제출했고, 이번주에는 테코톡 준비까지 함께 하느라 정말 정말 어려움이 많았어요. 그래서 많은 고민을 하지 못하고 어렵사리 기능만 구현하도록 만든 것 같아요.
지난번 극장 선택 3, 4단계 미션에서 MVP에 대한 리뷰에 대해 고민해 볼 시간이 적어서 이번 미션에도 MVP를 제대로 적용하지 못한 것 같기도 하구요.🥲

여러모로 아쉬움과 속상한 미션이었던 것 같습니다. 그치만 리뷰 주시면 최대한 적용해보도록 할게요 :) 
좋은 하루 되시길 바랍니다🙃!

2023-05-11 14:09 UTC, BeokBeok requested changes
쇼핑 장바구니 1,2단계 미션하시느라 고생하셨습니다. 👍 
고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪 
앱 실행 시 Crash가 발생하여, 코드만 보고 코맨트를 작성하였습니다.

2023-05-11 14:09 UTC, BeokBeok commented on app/src/main/java/woowacourse/shopping/feature/list/viewholder/CartProductViewHolder.kt
> +        binding.cartProductPriceTv.text = "${DecimalFormat("#,###").format(cartItem.productPrice)}원"
View에 보여줘야할 문구들은 strings.xml을 활용해보면 어떨까요? (이하 관련 내용 동일)

2023-05-11 14:09 UTC, BeokBeok commented on app/src/main/java/woowacourse/shopping/feature/list/viewholder/ProductViewHolder.kt
> +class ProductViewHolder(binding: ViewBinding) : ItemHolder(binding) {
ProductViewHolder와 CartProductViewHolder는 거의 유사한 코드로 작성되어 있습니다.
중복 코드를 개선해보면 어떨까요?

2023-05-11 14:09 UTC, BeokBeok commented on app/src/main/java/woowacourse/shopping/feature/main/ViewType.kt
> +            if ((position + 1) % 20 == 0) return ADD
숫자 20은 어떤 것을 의미할까요?

2023-05-11 14:09 UTC, BeokBeok commented on app/src/main/res/layout/activity_cart.xml
> +    <LinearLayout
ConstraintLayout을 활용하여 Layout의 Depth를 줄여보면 어떨까요?

2023-05-11 14:09 UTC, BeokBeok commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_width="match_parent"
ConstraintLayout의 자식뷰는 match_parent 대신 0dp 사용을 권장합니다.

ref. https://developer.android.com/develop/ui/views/layout/constraint-layout#adjust-the-view-size

2023-05-12 05:14 UTC, krrong commented on app/src/main/java/woowacourse/shopping/data/cart/CartDbHelper.kt
> +        const val DATABASE_NAME = "cart.db"
반영했습니다 :)

2023-05-12 09:02 UTC, krrong commented on app/src/main/java/woowacourse/shopping/feature/cart/CartActivity.kt
> +        // 페이지 버튼 클릭 이벤트들
반영했습니다!

2023-05-13 04:20 UTC, krrong commented on app/src/main/java/woowacourse/shopping/feature/cart/CartActivity.kt
> +    private lateinit var carts: List<CartProductListItem>
코드리뷰 요청 당시에는 시간이 부족하여 MainActivity만 MVP 구조를 가지고 있었습니다. CartActivity도 MVP구조로 변경해보았습니다!

2023-05-14 08:57 UTC, krrong commented on app/src/main/java/woowacourse/shopping/feature/list/adapter/CartProductListAdapter.kt
> +    private val onXClick: (ListItem) -> Unit
장바구니 목록 아이템의 X버튼을 클릭했을 때 발생하는 이벤트입니다! 가독성을 높이기 위해 onDeleteItem으로 변경했습니다!

2023-05-14 09:27 UTC, krrong commented on app/src/main/java/woowacourse/shopping/feature/list/adapter/CartProductListAdapter.kt
> +        val binding = ItemCartProductBinding.inflate(inflater, parent, false)
inflate를 각각의 ViewHolder에서 진행하도록 수정했습니다!

이러한 방식의 이점을 제 나름대로 생각해봤는데요. 뷰를 관리하는 것(생성 or bind)은 ViewHolder에서만 하도록 하고, 어댑터에서 하지 않도록 해서 adapter는 단순히 데이터가 어떤 방식으로 출력되는지만 관리하는 역할을 주는 것이다. 입니다. 혹시 제가 생각한 이점이 올바른지, 추가적인 이점이 있는 것인지 커트의 생각을 묻고 싶어요 🙃

2023-05-14 09:46 UTC, krrong commented on app/src/main/java/woowacourse/shopping/feature/list/viewholder/CartProductViewHolder.kt
> +        binding.cartProductPriceTv.text = "${DecimalFormat("#,###").format(cartItem.productPrice)}원"
반영했습니다 :)

2023-05-15 07:29 UTC, krrong commented on app/src/main/java/woowacourse/shopping/feature/list/viewholder/ProductViewHolder.kt
> +class ProductViewHolder(binding: ViewBinding) : ItemHolder(binding) {
같은 뷰홀더를 상속받게 하여 중복 코드를 줄이는 방법도 생각해보았지만 데이터 바인딩이 적용되어 있기 때문에 BindingAdapter를 활용하여 코드를 개선해보았습니다!

2023-05-15 08:14 UTC, krrong commented on app/src/main/res/layout/activity_cart.xml
> +    <LinearLayout
반영했습니다 :)

2023-05-15 08:16 UTC, krrong commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_width="match_parent"
반영했습니다 :)

2023-05-16 07:26 UTC, krrong commented
앱이 Crash났던 이유는 상품 데이터 정보를 DB에 저장할 때 생성될 때 저장되는 것이 아니라 수동으로 필요한만큼 데이터를 넣어주었기 때문입니다. 현재는 DB가 생성될 때 데이터를 넣어주도록 하여 Crash가 나지 않도록 수정했습니다! :)

2023-05-16 12:53 UTC, BeokBeok commented on app/src/main/java/woowacourse/shopping/feature/list/adapter/CartProductListAdapter.kt
> +        val binding = ItemCartProductBinding.inflate(inflater, parent, false)
잘 이해하고 계시네요! 👍

2023-05-16 13:16 UTC, BeokBeok requested changes
피드백 반영하시느라 고생하셨습니다. 👍 
추가로 고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪

2023-05-16 13:16 UTC, BeokBeok commented on app/src/main/java/woowacourse/shopping/feature/cart/CartActivity.kt
> +    }
Activity는 View 없이 존재하는 경우는 없어서, 굳이 _binding 변수를 null로 초기화하실 필요가 없어요. (이하 관련 내용 동일)

2023-05-16 13:16 UTC, BeokBeok commented on app/src/main/java/woowacourse/shopping/feature/product/detail/ProductDetailActivity.kt
> +            }
View에서 데이터베이스를 조작하고 있네요.
MVP에서 Presenter는 어떤 역할을 할까요?

2023-05-16 13:16 UTC, BeokBeok commented on app/src/main/java/woowacourse/shopping/feature/util/GlideBindingAdapter.kt
> +    @BindingAdapter("app:imageUrl")
`app:` prefix는 바인딩어뎁터에서의 사용을 권장하지 않아요.
왜냐하면, 기본적으로 제공해주는 속성인지 바인딩어뎁터에서 제공해주는 속성인지 모르기 때문이에요.

2023-05-16 13:16 UTC, BeokBeok commented on app/src/main/res/layout/activity_cart.xml
> +            android:layout_width="match_parent"
```suggestion
            android:layout_width="0dp"
```

2023-05-20 06:47 UTC, krrong commented on app/src/main/java/woowacourse/shopping/feature/cart/CartActivity.kt
> +    private val db: CartDbHandler by lazy {
기존 구조가 MVP가 아니었기 때문에 db를 멤버변수로 가지도록 했습니다.
MVP구조로 변경하면서 수정했습니다 :)

2023-05-20 07:05 UTC, krrong commented on app/src/main/java/woowacourse/shopping/feature/cart/CartActivity.kt
> +    }
확인해보니 프래그먼트에서만 위와 같은 방식을 사용하는 것을 확인했고, 수정했습니다!

2023-05-20 07:56 UTC, krrong commented on app/src/main/java/woowacourse/shopping/feature/list/viewholder/CartProductViewHolder.kt
> +        binding.cartClearImageView.setOnClickListener { onClick(cartProductItem) }
각 뷰홀더의 init 블럭 안에서 클릭리스너를 초기화 하는 방식으로 개선해보았습니다!

2023-05-20 08:03 UTC, krrong commented on app/src/main/java/woowacourse/shopping/feature/util/GlideBindingAdapter.kt
> +    @BindingAdapter("app:imageUrl")
바인딩 어댑터의 속성명을 변경해주었고, 바인딩 어댑터를 사용하지 않고 있던 ProductDetailActivity에서도 사용하도록 변경했습니다!

2023-05-20 08:07 UTC, krrong commented on app/src/main/res/layout/activity_cart.xml
> +            android:layout_width="match_parent"
height만 신경썼네요..🥲 반영했습니다 :)

2023-05-20 08:31 UTC, krrong commented on app/src/main/java/woowacourse/shopping/feature/product/detail/ProductDetailActivity.kt
> +            }
MVP 패턴을 적용하여 Presenter가 해당 역할을 하도록 변경했습니다 :)

2023-05-20 08:50 UTC, krrong commented on app/src/main/java/woowacourse/shopping/feature/cart/CartActivityContract.kt
> +        fun setUpRecyclerView(cartItems: List<CartProductItem>)
반영했습니다! 

MVP 구조에서는 View가 반드시 Presenter를 가져야 하는 이유는 단방향 흐름을 강제하기 위함이라고 생각하는데 다른 이유가 또 있을지 궁금해요🙃

2023-05-20 09:35 UTC, krrong commented on app/src/main/java/woowacourse/shopping/feature/cart/CartActivity.kt
> +        }
해당 로직을 presenter가 관리하도록 변경했습니다!

2023-05-21 09:58 UTC, BeokBeok commented on app/src/main/java/woowacourse/shopping/feature/cart/CartActivityContract.kt
> +        fun setUpRecyclerView(cartItems: List<CartProductItem>)
Contract 자체가 규약을 의미해요.
그래서, 하나의 View에는 반드시 하나의 Presenter를 갖도록 하는 것을 강제하는 것이에요.
그 외 다른 이유는 없습니다. 😄

2023-05-21 10:09 UTC, BeokBeok approved these changes
피드백 반영하시느라 고생하셨습니다. 👍 
추가로 고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요. 💪 
다음 미션을 진행하시면서, 추가로 작성된 코맨트들도 반영해주세요. 🙏

2023-05-21 10:09 UTC, BeokBeok commented on app/src/main/java/woowacourse/shopping/feature/cart/CartActivityPresenter.kt
> +        if (cartItems.isEmpty()) return 1
숫자 1은 어떤 것을 의미할까요?

2023-05-21 10:09 UTC, BeokBeok commented on app/src/main/java/woowacourse/shopping/feature/list/adapter/ProductsAdapter.kt
> +        notifyDataSetChanged()
notifyDataSetChanged 함수를 보면 warning이 뜰 텐데요.
왜 warning이 뜨는지 확인해보면 어떨까요?

2023-05-21 10:09 UTC, BeokBeok commented on app/src/main/res/layout/item_more.xml
> +    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
ViewHolder에 View가 하나밖에 없다면(Button) ViewGroup(LinearLayout)으로 감싸지 않으셔도 됩니다.

2023-05-21 10:09 UTC, merged

2023-05-21 10:09 UTC, BeokBeok commented
추가로 Presenter에 테스트 코드가 없는데, 테스트 코드를 작성해보면 더 좋을 것 같아요!

2023-06-01 02:54 UTC, krrong commented on app/src/main/res/layout/item_more.xml
> +    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
그렇군요! 감사합니다 :)
그리고 더이상 해당 레이아웃을 사용하지 않아 삭제했습니다!

2023-06-01 02:57 UTC, krrong commented on app/src/main/java/woowacourse/shopping/feature/cart/CartActivityPresenter.kt
> +        if (cartItems.isEmpty()) return 1
CartActivityPresenter에서 관리하는 장바구니 아이템의 리스트가 비어있는 경우 보여줄 수 있는 최대 페이지입니다!
매직넘버를 상수화하여 관리하도록 변경했습니다!

이외에도 로직을 위해 +1 혹은 -1 해주는 값들이 많은데 모든 것들을 상수화하여 관리하는 것이 좋은 것인지 잘 모르겠어요🥲
커트는 어떻게 생각하시나요?

2023-06-01 03:15 UTC, krrong commented on app/src/main/java/woowacourse/shopping/feature/list/adapter/ProductsAdapter.kt
> +        notifyDataSetChanged()
데이터 변경 이벤트는 항목 변경과 구조 변경 두 가지가 있고, 항목 변경은 단일 항목의 데이터는 업데이트되었지만 위치 변경은 발생하지 않은 경우를, 구조변경은 데이터 내에 항목이 삽입, 삭제, 이동되는 경우를 말합니다.

notifyDataSetChanged는 위에서 언급한 데이터 내의 변경이 어떤 위치에서 발생하였는지 명시하지 않기 때문에 모든 뷰를 다시 바인딩하고 그려야하기 때문에 비효율적입니다. 따라서 notifyItem~~ 의 함수를 사용하는 것이 더 효율적이라고 생각하지만

`notifyItemRangeChanged(0, items.size)`처럼 사용하면 `Inconsistency detected. Invalid view holder adapter positionViewHolder`와 같은 에러가 발생했습니다. 정확한 원인을 잘 모르겠어서 일단 notifyDataSetChanged 함수를 사용했는데 혹시나 에러를 해결하기 위해 찾아보면 좋을 키워드 같은 것들이 있을까요?
ෆ