[쇼핑 장바구니] 하디 1, 2단계 미션 제출합니다.
woowacourse/android-shopping-cart pull request #61
Opened 2024-05-16 07:37 UTC by ii2001

잘 부탁드립니다!!

차근차근 알려주시면 감사하겠습니다!

잘 못한 부분이 있다면 따끔하게 말해주세요!!

🚀 미션완료
👀 잘모르겠음..

2024-05-17 08:02 UTC, vagabond95 requested changes
첫 미션 이후 다시 뵙게 되었네요 :)

BindingAdapter 를 활용하여 Glide 코드를 재사용하는 부분은 놓치기 쉬운데, 잘 구현해주셔서 기억에 남습니다 👍

그외에 고민해보면 좋을 부분들에 대해 코멘트 남겼는데 확인 부탁드릴게요~!

2024-05-17 08:02 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productList/ProductRecyclerViewAdapter.kt
> +        notifyDataSetChanged()
notifyDataSetChanged 를 호출할 경우, 다음과 같은 waring 이 나오고 있습니다.

![Screenshot 2024-05-17 at 4 36 31 PM](https://github.com/woowacourse/android-shopping-cart/assets/27072782/92905a99-8e7c-4a13-801c-21d02673830b)

해당 waring 은 왜 나오는 것이고, 어떻게 개선해볼 수 있을까요?

2024-05-17 08:02 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/ui/setImageViewResource.kt
> +    Glide.with(imageView.context)
BindingAdapter 를 활용하여 glide 재사용 코드를 잘 만들어주셨네요 👍

2024-05-17 12:47 UTC, ii2001 commented on app/src/main/java/woowacourse/shopping/cart/CartFragment.kt
> +            adapter.updateData(viewModel.itemsInShoppingCartPage.value ?: emptyList())
저 함수부분을 아예 삭제하고 itemsInShoppingCartPage 만 가지고 작동할 수 있게끔 바꾸었습니다!

2024-05-17 12:54 UTC, ii2001 commented on app/src/main/java/woowacourse/shopping/cart/CartViewModel.kt
> +        })
외부 변수로 바꾸어주었습니다

2024-05-17 13:00 UTC, ii2001 commented on app/src/main/java/woowacourse/shopping/cart/CartViewModel.kt
> +                ?: _itemsInShoppingCartPage.postValue(it.toMutableList())
만약 데이터가 UI상으로 보여주기전에 내용이 먼저 로딩이 된후에 보여주려면 이런 방법을 해야한다고 알고있습니다!

2024-05-17 13:01 UTC, ii2001 commented on app/src/main/java/woowacourse/shopping/repository/DummyProductStore.kt
> +    override fun load20Data(currentIndex: Int): List<Product> {
어,,, 들어가도 된다고 알고있었는데 제가 잘못알고있었네요 수정하였습니다!!

2024-05-17 13:07 UTC, ii2001 commented on app/src/main/java/woowacourse/shopping/cart/CartViewModel.kt
> +            _itemsInShoppingCartPage.value?.addAll(it)
subList방식으로 수정해서 변경하였습니다!

그런데 사실 변경사항이 외부로 전파되지 않는다는부분이 잘 이해가 안가는데
외부가 어떤 곳일까요??

2024-05-17 13:17 UTC, ii2001 commented on app/src/main/java/woowacourse/shopping/productList/ProductRecyclerViewAdapter.kt
> +        notifyDataSetChanged()
그 부분은 데이터가 추가되는 부분이기때문에 알맞은 함수로 수정했습니다!

그런데 CartItemViewAdapter내부에 있는 부분은 제거가 된 후에 위치까지 이동을 하기때문에 그대로 사용하려고 하는데 괜찮을까요?

2024-05-17 13:56 UTC, ii2001 commented on app/src/main/java/woowacourse/shopping/productList/ProductListFragment.kt
> +        }
너무 좋은것같아요!! 그렇게 수정하겠습니다!

2024-05-18 13:27 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/cart/CartViewModel.kt
> +                }
좋은 고민인 것 같습니다.

하디의 의견이 더 설득력 있어보이네요 👍 
보통 실제 프로젝트에서는 물건/장바구니 물건 모두 서버에서 관리가 되고 싱크가 보장되는게 일반적이므로 id 만 들고 있어도 괜찮다고 생각을 했는데,
현 프로젝트에서는 로컬에서 가져오고 있으므로 하디의 의견이 좀 더 적합한 것 같습니다~!

2024-05-18 13:30 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/repository/DummyProductStore.kt
> +    override fun load20Data(currentIndex: Int): List<Product> {
단순히 된다/안된다기보다, 변경에 취약한 구조로 보여 코멘트를 드렸습니다.

아마도, 20개의 데이터를 가져오기 때문에 20이라는 숫자를 넘겨주신 것 같은데요.
데이터를 가져오는 숫자는 언제든지 바뀔 수 있고 그럴때마다 함수의 네이밍이 변경되어야 합니다.

더 큰 문제는 데이터를 10개를 가져오는 요구사항과 20개를 가져오는 요구사항이 동시에 있을 때, 현재의 방식이라면 함수를 또 추가해주어야겠죠 ㅎㅎ

재사용성 및 변경의 유연함 측면에서 함수의 아주 구체적인 내용은 드러내지 않는게 더 좋은 것 같습니다~!

2024-05-18 13:32 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productList/ProductRecyclerViewAdapter.kt
> +        notifyDataSetChanged()
우선 notifyDataSetChanged 함수를 사용했을때, **발생할 수 있는 문제점**이 무엇인지에 대해 먼저 이야기 해보면 좋을 것 같아요.

이 부분에 대한 이야기가 되면 하디가 질문해주신 내용에 대해 자연스럽게 이어나갈 수 있을 것 같아요 :)

2024-05-18 13:38 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/cart/CartViewModel.kt
> +            _itemsInShoppingCartPage.value?.addAll(it)
내용이 조금 추상적이었네요 ^^; 좀 더 풀어서 이야기해볼게요 :)

LiveData 를 observe 하는 곳에서 데이터를 전달받으려면,
setValue 혹은 postValue 함수를 통해 데이터를 업데이트 해줘야해요.

그런데 이전의 하디의 구현에서는 setValue 가 아닌, getValue 로 가져온 데이터에 addAll 을 호출해줬고, 이러한 변경사항은 observe 를 하는 곳에서 전달받을 수 없게 돼요.

이러한 구현은 LiveData 를 사용하는 목적 (데이터를 업데이트하고, 어디선가 이를 구독하여 전달받는다.)을 온전히 달성하기 어렵다고 할 수 있죠 ㅎㅎ

2024-05-18 13:44 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/cart/CartViewModel.kt
> +                ?: _itemsInShoppingCartPage.postValue(it.toMutableList())
postValue 는 Handler 를 통해 값 업데이트를 요청하므로, 백그라운드 스레드에서 호출해도 안전하게 메인 UI 스레드에 값을 반영할 수 있습니다. 또한 비동기로 값이 반영되구요.

하디가 만약 이러한 사실을 의도하고 사용하셨다고 말씀해주신 것이라면 👍 
아니라면, 이번 기회에 학습 포인트로 가져가면 좋겠네요 :)

2024-05-18 14:02 UTC, vagabond95 requested changes
빠르게 코드를 개선해주셨었네요 ㅎㅎ

장바구니에 대한 코멘트는 하디의 의견이 더 설득력 있다고 생각됩니다 👍 

RecyclerView 의 아이템을 업데이트 하는 함수는 notifyDataSetChanged 외에도 여러 종류가 있는데요, Android 팀은 왜 이렇게 구현을 했던 것일까요? :)
이 부분을 좀 더 깊게 파보면 좋을 것 같습니다~!

2024-05-18 14:02 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productList/ProductRecyclerViewAdapter.kt
> +        notifyItemChanged(0, newData.size)
개선을 시도한 것은 좋습니다 👍 

그런데, notifyDataSetChanged 와 결과적으로는 큰 차이가 없을 것 같습니다 ^^;

조금 더 힌트를 드려보면,
1. product 는 조금씩 새로 불러옵니다.
2. 조금씩 새로 불러오는 product viewHolder 에 대해서만 notify 를 호출해주면 되지 않을까요?

2024-05-19 03:00 UTC, ii2001 commented on app/src/main/java/woowacourse/shopping/productList/ProductRecyclerViewAdapter.kt
> +        notifyDataSetChanged()
화면이 깜빡거리는 불편함과
사용자로 하여금 어떤 부분이 바뀌었는지 확실히 모르는 점이 있는 것 같습니다

2024-05-19 03:21 UTC, ii2001 commented on app/src/main/java/woowacourse/shopping/productList/ProductListViewModel.kt
> +            dummyProductStore.loadDataAsNeeded(currentIndex).toMutableList()
함수 분리를 통해서 수행해보았는데 잘 했는지 모르겠네요 ㅎㅎ..

2024-05-19 03:28 UTC, ii2001 commented on app/src/main/java/woowacourse/shopping/cart/CartViewModel.kt
> +    private var _currentPage: MutableLiveData<Int> = MutableLiveData(1)
라이브 데이터로 감싸지 않으면 Xml파일 내부에서 호출중인데 계속해서 값이 바뀌지 않지 않나요..?
그러면 함수로 감싸서 값을 불러오는 식으로 만들어야 하는건가요?

2024-05-19 08:17 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/cart/CartViewModel.kt
> +    private var _currentPage: MutableLiveData<Int> = MutableLiveData(1)
아이고 IDE 에 참조가 찍히지 않아서, ViewModel 내부에서만 참조되고 있다고 착각했네요 ^^;

해당 코멘트는 무시해주시면 됩니다!

2024-05-19 08:18 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productList/ProductListViewModel.kt
> +            dummyProductStore.loadDataAsNeeded(currentIndex).toMutableList()
잘 개선해주셨습니다!

2024-05-19 08:21 UTC, vagabond95 approved these changes
처음보다 구조적으로 많이 개선되었네요!
중간에 LiveData 에 대한 코멘트는 무시해주셔도 됩니다. 혼동을 드렸네요 ^.ㅜ

추가로 코멘트 드릴 부분이 보이지 않아, 1/2단계는 머지하도록 하겠습니다.
3/4 단계에서 뵙겠습니다~!

2024-05-19 08:21 UTC, merged