[쇼핑 장바구니] 심지 1, 2단계 미션 제출합니다.
woowacourse/android-shopping-cart pull request #62
Opened 2024-05-16 07:53 UTC by sh1mj1

안녕하세요. 두루! 이번 미션 잘 부탁드립니다!!

이번 미션 기한동안 페어와 일정이 많이 안 맞아서 절대적으로 시간을 많이 투자 못했습니다.
그렇다고 따로 구현을 하는 것은 취지에 안 맞는 것 같아 하지 않았습니다.

그래서 먼저 기능 구현만을 목표로 작업을 해서 테스트 코드도 없습니다.
그리고 테스트를 하기 위한 뷰모델에 생성자를 넣도록 하는 팩토리도 만들지 못했습니다.

아래는 시연 영상입니다.
[shopping_cart_video.webm](https://github.com/woowacourse/android-shopping-cart/assets/90040304/34ff38c6-c5f8-46a3-b97c-925c04156a5b)

이번 깃 커밋 메시지는 [gitEmogi](https://gitmoji.dev/) 를 사용해보았습니다.

앞으로의 계획은 이렇습니다.
- 뷰모델에 생성자 주입을 할 수 있도록 변경
- Repository 에 들어갈 것들을 interface 분리
- ViewModel 에서의 LiveData 로직을 더 개선하고 공부

2024-05-16 16:31 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/productDetail/ProductDetailFragment.kt
> +    private val binding get() = _binding!!
non-nullable 하다고 지정을 하는 !! 부분은 자칫 많은 오류를 발생시킬 수 있어서 사용에 주의를 해야 합니다!
해당 내용을 좀 더 안전하게 구현을 하려면 어떻게 수정을 할 수 있을지 고민해보면 좋을 것 같다는 생각이 듭니다~💪

2024-05-16 16:33 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/productDetail/ProductDetailViewModel.kt
> +        get() = productStore.findById(productId)
`LiveData`라는 키워드를 배웠으니 이를 활용해보는 것은 어떨까 라는 생각이 듭니다!💪

2024-05-16 16:34 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/productDetail/ProductDetailViewModel.kt
> +    }
`ShoppingCart` 객체를 직접 참조하지 않고, 함수를 통해서 넣어보도록 수정을 해보는 것도 좋을 것 같다는 생각이 듭니다!💪

2024-05-16 16:36 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/productList/ProductListFragment.kt
> +        }
`onViewCreated()` 에서 너무 많은 기능을 하고 있다는 생각이 듭니다!
이를 함수로 분리를 해보는 것도 좋을 것 같다는 생각이 듭니다!💪

2024-05-16 16:37 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/productList/ProductRecyclerViewAdapter.kt
> +) : RecyclerView.Adapter<ProductRecyclerViewAdapter.ViewHolder>() {
Adapter 내에서 callback 이 아닌 DataBinding을 활용하여, 클릭 이벤트를 감지하도록 하는 것은 어떨까 라는 생각이 듭니다!💪

2024-05-16 16:39 UTC, Gyuil-Hwnag commented on app/src/main/res/layout/fragment_cart_list.xml
> +                android:text="장바구니"
해당 내용을 android resource를 활용해보도록 하는 것은 어떤가 라는 생각이 듭니다!💪

2024-05-16 16:40 UTC, Gyuil-Hwnag commented on app/src/main/res/layout/fragment_cart_list.xml
> +            android:text="@string/previous_arrow"
OnClick 을 ViewModel 에서 처리하도록 한 내용 정말 좋습니다~👍

2024-05-16 16:40 UTC, Gyuil-Hwnag commented on app/src/main/res/layout/fragment_cart_list.xml
> +            app:layout_constraintBottom_toBottomOf="parent"
LiveData 와 DataBinding의 활용 좋습니다~👍

2024-05-16 16:42 UTC, Gyuil-Hwnag commented on app/src/main/res/layout/holder_cart.xml
> +            android:layout_margin="10dp"
사이즈에 대해서 하드코딩을 하는 방법도 있지만 Android Resource의 dimen을 활용하는 방법도 있습니다!
이를 활용해보면 어떨까 하는 생각이 듭니다!💪

(심지가 회사에 갔는데 어떻게 구현되어 있어야, 심지가 좀 더 유지보수가 쉬울 것 같은지를 생각하면서 하면 좀 더 의미있게 와닿을 것 같다는 생각이 듭니다!💪)
~~~kotlin
 <dimen name="cart_product_delete_size">16dp</dimen>

android:layout_height="@dimen/cart_product_delete_size"

2024-05-17 05:06 UTC, sh1mj1 commented on app/src/main/java/woowacourse/shopping/cart/CartFragment.kt
> +        }
넵 함수로 더 분리해서 가독성있게 만들어보겠습니다

2024-05-17 05:08 UTC, sh1mj1 commented on app/src/main/java/woowacourse/shopping/cart/CartViewModel.kt
> +        })
viewmodel 이 아닌 다른 곳에서 이러한 책임을 갖도록 수정해보겠습니다!

2024-05-19 20:47 UTC, sh1mj1 reviewed
피드백 주신 사항 반영했습니다

2024-05-19 20:47 UTC, sh1mj1 commented on app/src/main/res/layout/fragment_cart_list.xml
> +                android:text="장바구니"
넵 국제화를 빼먹은 것들이 많네요 모두 적용하겠습니다!

2024-05-19 20:47 UTC, sh1mj1 commented on app/src/main/java/woowacourse/shopping/productDetail/ProductDetailFragment.kt
> +    private val binding get() = _binding!!
이 부분이 조금 고민이네요.

제 생각에는 아래처럼만 해두면 되지 않을까 생각이 듭니다.
```kotlin 
private val binding get() = _binding ?: throw IllegalStateException("FragmentCartListBinding is not initialized") 
```

물론 이렇게 던지지 않고 binding 을 사용하는 곳에서 계속해서 null safety 연산자 (`?.`) 를 사용하면 더 안전하겠지만, 실제로 이 부분이 not-null 이므로 하나하나 처리를 해야하는지는 잘 모르겠네요

두루는 모든 곳에서 `binding?.` 처럼 적용하시는 편이신가요?

2024-05-19 20:47 UTC, sh1mj1 commented on app/src/main/java/woowacourse/shopping/productList/ProductRecyclerViewAdapter.kt
> +) : RecyclerView.Adapter<ProductRecyclerViewAdapter.ViewHolder>() {
리스너 인터페이스를 만들고 xml variable 로 갖도록 해서 databinding 으로 적용해보겠습니다

2024-05-20 10:46 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/productDetail/ProductDetailFragment.kt
> +    private val binding get() = _binding!!
위에서처럼 사용을 해도 좋을 것 같습니다!!👍
사실 개인적으로 저는 DataBinding을 Base에 넣어두는 것을 그렇게 권장하지는 않기는 합니다😀
(이유는 현재와 같은 null check 에 대한 애매함도 있기는 해서 입니다!)

2024-05-20 11:07 UTC, Gyuil-Hwnag requested changes
심지 안녕하세요!
해당 미션 구현 고생 많으셨습니다!
리뷰 반영하면서 구현한 내용 수정 너무 잘 해주셨습니다 💯

고민해보시면 좋을만한 내용들 코멘트를 달았으니 확인해주시면 감사하겠습니다.
남겨주셨던, Ui 테스트의 추가와 ViewModel 에 남겨둔 코멘트들에 대해서 살펴보면 다음 단계를 진행해도 괜찮을 것 같다는 생각이 듭니다!
(Ui 테스트는 오래 걸리실 것 같으면, 다음 3, 4 단계를 진행하면서 해도 될 것 같으니 너무 부담은 느끼시지 않으셔도 됩니다!)

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏 
화이팅입니다💪

2024-05-20 11:07 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/productList/ProductListFragment.kt
> +    }
해당 내용처럼 한다면, 사실상 callback과 그렇게 큰 차이는 없다는 생각도 들긴 합니다!🤔

2024-05-20 11:07 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/productList/ProductListViewModel.kt
> +) : ViewModel() {
ViewModel 의 생성자에서 LiveData를 가지고 있어야 하는 이유가 궁금합니다!🤔

2024-05-20 11:07 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/productList/ProductListViewModel.kt
> +
`get()` 이라는 키워드로 설정을 하신 이유가 궁금합니다!
수정일 필요한 것은 아니며, 한번 생각해보면 좋을 내용인 것 같아서 코멘트 남겨두었습니다!
심지의 의견을 자유롭게 남겨주세요~💪

2024-05-20 11:07 UTC, Gyuil-Hwnag commented on app/src/main/res/layout/fragment_product_detail.xml
> +            android:textStyle="bold"
`sp`와 `dp`는 어떠한 차이점을 가지고 있을까요??
또한 어떠한 경우에 사용을 하는 것이 좋을지 심지의 의견을 자유롭게 남겨주세요!!💪

2024-05-20 11:07 UTC, Gyuil-Hwnag commented on app/src/test/java/woowacourse/shopping/TestFixture.kt
> +): List<Product> = List(count, productFixture)
TestFixture 작성 좋습니다~👍

2024-05-20 11:07 UTC, Gyuil-Hwnag commented on app/src/test/java/woowacourse/shopping/TwentyItemsPagingStrategyTest.kt
> +    }
테스트 함수 너무 잘 작성해주셨네요~👍

2024-05-20 13:42 UTC, sh1mj1 commented on app/src/main/res/layout/fragment_product_detail.xml
> +            android:textStyle="bold"
sp 로 설정했을 경우 아래 그림처럼 사용자가 기기의 폰트 크기를 늘린다면 그에 맞춰서 화면에 나타나는 텍스트 크기도 커집니다.
하지만 dp 의 경우는 폰트 크기를 늘리더라도 텍스트 크기가 커지지 않습니다.
![image](https://github.com/woowacourse/android-shopping-cart/assets/90040304/ae5fdb98-0827-45f4-9f37-f061e135c00c)

그래서 사용자가 기기의 폰트 크기를 키우더라도 화면에 나타나는 텍스트 크기가 커지지 않기를 바란다면, 글씨의 크기가 중요한 디자인 요소라면, dp 로 설정하고, 그렇지 않다면 sp 로 설정하는 것이 좋아보입니다.

제가 디자인은 잘 모르지만,  리사이클러뷰와 같은 곳에서는 dp 로 표시하는 것이 더 나아보이고, 이렇게 상세 페이지는 sp 로 표시하는 게 좋을 것 같습니다

2024-05-20 13:50 UTC, sh1mj1 commented on app/src/main/java/woowacourse/shopping/productList/ProductListViewModel.kt
> +) : ViewModel() {
액티비티가 `onDestroy` 될 때 `isFinishing` 이 내부적으로 호출됩니다.
이 때 `isFinishing` 가 `true` 이면, viewmodel 이 완전히 소멸되고, `false` 이면 viewmodel 이 메모리에 남아있게 됩니다.

`true` 가 되는 경우는 액티비티를 `finish` 등으로 종료하거나, 안드로이드 OS 가 자체적으로 부족한 메모리를 확보하기 위해 앱의 프로세스를 메모리에서 제거하는 경우입니다.

그런데 어떠한 앱에서는 이러한 경우에도 상태를 저장하고 싶을 수 있을 것 같습니다.
그럴 때 뷰모델의 생성자로 `_currentPage` 를 갖게 된다면  `SIS(SavedInstanceState)`에 저장하기 좋을 것 같습니다.

또한 `currentPage` 를 테스트할 때 생성자로 가지고 있으면 좋을 것이라고 판단했습니다.

2024-05-20 13:55 UTC, sh1mj1 commented on app/src/main/java/woowacourse/shopping/productDetail/ProductDetailFragment.kt
> +    private val binding get() = _binding!!
그렇군요!

그렇다면 
`private val binding by lazy { _binding?: throw IllegalStateException("FragmentProductListBinding is not initialized")}`
이러한 방식으로 사용하시는 건가요?

아니면 


```kotlin
// ... 
binding?.productDetailList?.adapter = adapter
        binding?.vm = viewModel
// ...
binding?.productDetailList?.adapter = adapter

```
이렇게 사용하시는 건가요??

2024-05-21 03:58 UTC, sh1mj1 commented on app/src/main/java/woowacourse/shopping/productList/ProductListViewModel.kt
> +
get() 메서드를 설정해서 currentPage 를 _currentPage 와 분리한 이유는 외부에서 _currentPage 를 임의로 변경하지 못하도록 한 것입니다.

물론 get() 메서드가 아닌 따로 함수를 만들어서 사용할 수 있습니다.
두가지 경우 동작은 거의 비슷하게 합니다. 
하지만, 커스텀 게터를 사용하는 편이 가독성이 더 좋아보이며,
Observable 한 LiveData 를 사용할 때 이런 식으로 만드는 것이 안드로이드에서 일반적인 패턴입니다.
그래서 이렇게 적용했습니다.

질문에 대한 의도하시는 방향의 대답이 맞나요?

2024-05-21 06:34 UTC, sh1mj1 commented on app/src/main/java/woowacourse/shopping/productList/ProductListFragment.kt
> +    }
```kotlin
class ProductViewModel ( .. ): ProductRecyclerViewAdapter.OnProductItemClickListener  {
		private var _detailProductDestinationId: MutableLiveData<Int> = MutableLiveData()
		val detailProductDestinationId: LiveData<Int> get() = _detailProductDestinationId

	override fun onCLick(productId: Int) {
		_detailProductDestinationId.value = productId
	}
}

class ProductListFragment: Fragment() {
		private val adapter: ProductRecyclerViewAdapter by lazy {
        ProductRecyclerViewAdapter(
            viewModel.loadedProducts.value ?: emptyList(),
            onProductItemClickListener = viewModel,
        )
    }		
    
    private fun observeDetailProductDestination() {
        viewModel.detailProductDestinationId.observe(viewLifecycleOwner) { productId ->
            navigateToProductDetail(productId)
        }
    }
}
```
처음에는 위처럼 뷰모델이 상품 상세 목적지를 갖게 해서 구현했습니다.

이렇게 하니까 productlistfragment 에 들어갈 때마다 계속 liveData 를 옵저빙해서, 자동으로 상품 디테일로 네비게이션 되는 문제가 있어 오늘 피드백 수업에서 배운 SingleLiveData 를 적용했습니다.

```kotlin
class ProductViewModel ( .. ): ProductRecyclerViewAdapter.OnProductItemClickListener  {
		private var _detailProductDestinationId: MutableLiveData<Int> = MutableLiveData()
		val detailProductDestinationId: LiveData<Int> get() = _detailProductDestinationId

	override fun onCLick(productId: Int) {
		_detailProductDestinationId.value = productId
	}
}
```

그런데 뷰모델이 과연 detailProductDestinationId 를 알고 있는게 맞는지, 이것이 뷰모델의 관심사가 맞는지 잘 모르겠네요

2024-05-21 07:14 UTC, sh1mj1 commented on app/src/main/java/woowacourse/shopping/cart/ShoppingCartViewModelFactory.kt
> +}
넵 UniversalViewModelFactory 라는 이름으로 구현하겠습니다.
```kotlin
class UniversalViewModelFactory(private val creator: () -> ViewModel) : ViewModelProvider.Factory {
    override fun <T : ViewModel> create(modelClass: Class<T>): T {
        @Suppress("UNCHECKED_CAST")
        return creator() as T
    }
}
```

그런데 이렇게 하면 `modelClass.isAssignableFrom `문장이 쓰일 수가 없는 것 같아요.
이 때 각 뷰모델에 `isAssignableFrom` 메서드로 클래스가 `modelClass` 에 할당 가능한지 확인하는 로직은 필요없는 건가요?

2024-05-21 07:16 UTC, sh1mj1 commented on app/src/main/java/woowacourse/shopping/cart/ShoppingCartViewModel.kt
> +) : ViewModel() {
아래 [ProductListViewModel ](https://github.com/woowacourse/android-shopping-cart/pull/62#discussion_r1606809684) 에서의 근거와 동일한 이유입니다!

2024-05-21 07:18 UTC, sh1mj1 commented on app/src/main/java/woowacourse/shopping/cart/CartItemRecyclerViewAdapter.kt
> +        notifyItemRangeChanged(0, itemCount)
아니요, 이 부분 제가 잘못 작성한 것 같습니다!
`notifyItemRangeRemoved` 를 사용하려고 했는데 잘못 작성했네요

2024-05-21 07:21 UTC, sh1mj1 commented on app/src/main/java/woowacourse/shopping/FiveCartItemPagingStrategy.kt
> +    override fun loadPagedData(
어떻게 페이징할 것인지도 하나의 객체가 가질 수 있는 책임이지 않을까 해서 이렇게 만들었습니다.

생각해보니, 이 전략은 장바구니에서만 사용되지 않을 수 있는데 제가 Ui 관련 사항을 네이밍에 포함시켰네요. 수정하겠습니다!

2024-05-21 07:40 UTC, sh1mj1 commented on app/src/main/java/woowacourse/shopping/FiveCartItemPagingStrategy.kt
> +    override fun loadPagedData(
추가로 `PagingStrategy` 에서 페이징하는 수를 생성자 파라미터로 넘기도록 만들고,
페이징 전략이 필요하지 않는 경우를 위해서 `NonePagingStrategy` 를 사용하도록 변경했습니다!

`class NumberPagingStrategy<T>(private val countPerLoad: Int) : PagingStrategy<T> `
`class NonePagingStrategy<T> : PagingStrategy<T> `

2024-05-21 14:16 UTC, sh1mj1 commented on app/src/main/java/woowacourse/shopping/productDetail/ProductDetailFragment.kt
> +    private var _binding: FragmentProductDetailBinding? = null
넵 알겠습니다.
뷰모델을 쓰고 있으니 액티비티에서 간단히 
```kotlin
override fun onCreate(savedInstanceState: Bundle?) {
    // ..
    if (savedInstanceState == null) {
                initFragment()
     }
}
 ```
만 해주면 될 것으로 보이네요!

2024-05-21 16:46 UTC, sh1mj1 commented on app/src/main/java/woowacourse/shopping/cart/CartItemRecyclerViewAdapter.kt
> +        notifyItemRangeChanged(0, itemCount)
이 부분을 수정하면서 문제가 발생하고 이를 수정하는데 시간이 오래 걸렸네요.

결론적으로는 CartItemRecyclerViewAdapter 에서 
```kotlin
fun updateData(newData: List<Product>) {
    val oldSize = products.size
    this.products = newData.toList()
    if (newData.isEmpty()) {
        notifyItemRangeRemoved(0, oldSize)
        return
    }

    notifyItemRangeChanged(0, itemCount)
}
```
이렇게 바꾸었습니다.

그런데 `this.products = newData.toList()` 를 `this.products = newData` 로 하면 `val oldSize = products.size` 에서 ConcurrentModificationException 이 발생하더라구요.

예외가 발생하는 후자의 코드에서 itemsInCurrentPage 를 옵저빙하는 코드는 ShoppingCartFragment 의 코드에서 아래와 같이 로그를 찍어보면
```kotlin
private fun observeItemsInCurrentPage() {
    viewModel.itemsInCurrentPage.observe(viewLifecycleOwner) { products ->
        Log.d(TAG, "observeItemsInCurrentPage: $products")
        adapter.updateData(products)
    }
}
```
로그 메시지는 변경된 itemsInCurrentPage 을 아래처럼 제대로 옵저빙합니다
```
D  observeItemsInCurrentPage: [Product(id=2, name=1 번째 상품 이름, price=100), Product(id=3, ,name=2 번째 상품 이름, price=200), Product(id=4, name=3 번째 상품 이름, price=300)]
Shutting down VM
FATAL EXCEPTION: main
      Process: woowacourse.shopping, PID: 4364
      java.util.ConcurrentModificationException
```
오래 고민해보고 원인을 찾아보았는데 결국 원인을 정확히는 찾지 못했습니다.

혹시 어떤 문제인지, 어떻게 이것에 대해 찾아봐야 하는지 알려주실 수 있으신가요?

2024-05-21 16:51 UTC, sh1mj1 commented
안녕하세요 두루! 리뷰 남겨주신 부분들 모두 반영했습니다.
여쭈어보고 싶은 내용들도 피드백주신 코멘트에 남겨두었습니다.

ui 테스트는 이후의 미션을 진행하면서 추가하려고 합니다.
프래그먼트 UI 테스트를 위해 프래그먼트의 뷰모델 레지스트리에 접근해서, 뷰모델을 테스트 케이스마다 설정해주고 싶었으나,
정확한 방법을 찾는데 너무 오래 걸리는 것 같아 먼저 PR 합니다.

프래그먼트에 생성자로 뷰모델을 넣고, FragmentFactory 를 커스텀하는 것 외에 다른 방법이 있을 것 같은데... 잘 모르겠네요.

이번에도 잘 부탁드립니다!!

2024-05-22 03:17 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/cart/CartItemRecyclerViewAdapter.kt
> +        notifyItemRangeChanged(0, itemCount)
notifyItemRangeRemoved의 내부 구현을 보면, 아래와 같이 리스트를 순회를 하게 됩니다~
<img width="745" alt="스크린샷 2024-05-22 12 12 06" src="https://github.com/woowacourse/android-shopping-cart/assets/84956038/e04ec37e-9f98-4fe5-9fcb-22d942e3c2c9">
여기서 문제가 되는 부분을 예시를 들어보도록 하겠습니다!
ex)
products 라는 리스트가 있으며 사이즈는 5입니다.
아래와 같은 구현이 있다면, 어떤 문제가 발생을 하게 될까요??
(초점은 반복문은 0 -> 5까지 도는데, 리스트의 사이즈가 변경을 하게 됩니다!)
~~~kotlin
fun main() {
    val products = mutableListOf(1, 2, 3, 4, 5)
    for (i in 0 until products.size) {
        products.removeAt(i)
    }
}
~~~

이에 대한 이슈에 대해서 참고할만한 레퍼런스가 있어서 첨부하였습니다!
https://blog.naver.com/tmondev/220393974518

2024-05-22 03:25 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/productList/ProductListViewModel.kt
> +) : ViewModel() {
@sh1mj1 
심지 안녕하세요~
설명해주신 부분들에 대해서 이해가 잘 안되는데, 제가 이해한 부분이 맞을까요?
1. Activity의 configuration change등에 대해서 값을 저장하기 위해서 설정을 해두었다.
(이게 맞다면, Android ViewModel 의 생명주기에 대해서 살펴봐주시길 바랍니다!)

2. 현재 보던 장바구니에 위치를 저장하고 싶었다.
(LiveData로 넣어둘 필요가 있었을까요?? 그럴경우 부생성자로 Int로 받거나, 내장 데이터에 넣어두고 꺼내오는 식으로 구현을 하는게 맞지 않을까 싶습니다!)

2024-05-22 03:26 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/cart/ShoppingCartViewModel.kt
> +) : ViewModel() {
@sh1mj1 
해당 코멘트 참고부탁드립니다~
[코멘트](https://github.com/woowacourse/android-shopping-cart/pull/62#discussion_r1609206506)

2024-05-22 03:30 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/cart/ShoppingCartViewModelFactory.kt
> +}
우선 해당 내용에 대해서 코멘트를 드린것은, 생성자가 있을경우에는 공통으로 묶는 것이 어려운 것을 직접 경험을 해보고 공식문서나 다른 곳에서는 어떻게 적용을 하고 있는지 살펴보고자 함이었습니다!

공식문서에는 companion object 로 ViewModelFactory()에 대해서 정의를 하고 있기는 합니다!
(해당 내용을 살펴본다면, companion object로 작성을 하는 것과 따로 파일을 구분하는 것중 심지의 생각에는 어떤 형태로 구현을 하는 것이 좋을까 여쭤보고 싶습니다!💪)
공식문서 : https://developer.android.com/topic/libraries/architecture/viewmodel/viewmodel-factories

2024-05-22 04:12 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/productDetail/ProductDetailFragment.kt
> +    private var _binding: FragmentProductDetailBinding? = null
좋습니다!!👍

2024-05-22 04:17 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/productList/ProductListFragment.kt
> +    }
해당 처럼 ViewModel 에서 작성하신 내용도 좋습니다!
추후 클릭 -> 로직 수행 -> 화면 이동의 경우라면 ViewModel 에서 처리를 하는 것이 맞다는 생각이 듭니다!
이번 코멘트를 남겨둔 것은, 이처럼 활용할 수 있으니 알아둔다면 추후 위에 처럼 로직이 포함된 경우에도 활용할 수 있어서 적용을 해봤으면 해서 남겨둔 내용이었습니다~

2024-05-22 04:29 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/productList/ProductListViewModel.kt
> +
get() 으로 작성을 하였을 하신 이유가 `단순 Android 에서 해오던 방식 이어서 이렇게 사용합니다.`도 틀린말은 아니지만, 왜 이렇게 작성을 하는지에 대해서 고민을 해보면 좋을 것 같아서 코멘트를 남겨두었습니다!
도움이 될만한 내용이 있는 것 같아서 첨부해두었습니다!
get() : https://medium.com/google-developer-experts/avoid-backing-properties-for-livedata-and-stateflow-706006c9867e
kotlin : https://youtrack.jetbrains.com/issue/KT-14663

2024-05-22 04:55 UTC, Gyuil-Hwnag approved these changes
심지 안녕하세요!
해당 미션 너무 고생 많으셨습니다! 
많이 어려우셨을텐데 정말 잘 해주셨네요💯

해당 미션은 다음 미션 진행을 위하여 머지하도록 하겠습니다.
도움이 될만한 코멘트 달았으니 확인하여 다음 미션에서 반영해주셔도 좋을 것 같습니다.
남겨주신 질문에 대해서는 코멘트 남겨두었으니, 확인 부탁드립니다~

남겨둔 코멘트에 대해서는 3, 4단계를 진행하기 전에 반영을 하고 나서 3, 4단계를 진행하는 것도 좋을 것 같다는 생각이 듭니다!💪

궁금한 점이나 논의하고 싶은 내용이 있으면 언제든 DM 주세요! 🙏
다음 미션도 화이팅입니다💪

2024-05-22 04:55 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/SingleLiveData.kt
> +    private val liveData = MutableLiveData<Event<T>>()
SingleLiveData 좋습니다~👍

2024-05-22 04:55 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/Event.kt
> +    var hasBeenHandled = false
Event 사용 좋습니다~
Utils등을 패키지를 분리한다면 추후 프로젝트 규모가 커졌을 때 유용하게 사용될 수 있겠다는 생각도 듭니다!💪
<img width="287" alt="스크린샷 2024-05-22 13 45 48" src="https://github.com/woowacourse/android-shopping-cart/assets/84956038/286ab4d0-2384-4bad-b4f0-9418b5e8b043">

2024-05-22 04:55 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/productList/ProductListViewModel.kt
> +    val currentPage: LiveData<Int> get() = _currentPage
인터페이스의 활용 좋습니다~👍

2024-05-22 04:55 UTC, Gyuil-Hwnag commented on app/src/main/res/layout/holder_product.xml
> +        >
DataBinding의 활용 좋습니다~👍

2024-05-22 04:55 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/cart/CartItemRecyclerViewAdapter.kt
> +        notifyItemRangeChanged(0, itemCount)
이전 코멘트를 참고한다면, 에러가 나는 원인에 대해서 파악이 가능할 것 같다는 생각이 듭니다! 💪
[이전 코멘트](https://github.com/woowacourse/android-shopping-cart/pull/62#discussion_r1609202773)

2024-05-22 04:55 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/NumberPagingStrategy.kt
> +    override fun loadPagedData(
실제 서버하고 통신을 한다고, 가정을 한다면 해당 네이밍은 어떻게 수정이 될 것 같은지 심지의 생각을 남겨주세요!💪

2024-05-22 04:55 UTC, merged

2024-05-22 07:34 UTC, sh1mj1 commented on app/src/main/java/woowacourse/shopping/productList/ProductListViewModel.kt
> +) : ViewModel() {
> 1. Activity의 configuration change등에 대해서 값을 저장하기 위해서 설정을 해두었다.
위 이유 때문에 값을 저장한 것이 아닙니다.
AAC ViewModel 은 configuration change 등이 일어나도 viewModelProvider 라는 레지스트리에 viewModel 을 저장해두고, 나중에 다시 필요할 때 레지스트리에 뷰모델이 있다면 꺼내 쓰는 형식으로 동작한다고 알고 있습니다.
그래서 구성 변경에 대해서 값을 저장하기 위해서 설정한 것은 아닙니다.

제가 생각한 케이스는 android OS 가 자체적으로 메모리가 부족하다고 판단해서 프로세스를 종료시키는 케이스였습니다.
이 때는 뷰모델이 메모리에 남지 않기 때문입니다.

> 2. 현재 보던 장바구니에 위치를 저장하고 싶었다. (LiveData로 넣어둘 필요가 있었을까요?? 그럴경우 부생성자로 Int로 받거나, 내장 데이터에 넣어두고 꺼내오는 식으로 구현을 하는게 맞지 않을까 싶습니다!)

말씀 들어보니, 부생성자로 Int 로 받는 것이 좋아보이네요!
이렇게 하는 게 훨씬 깔끔할 것 같아요. 감사합니다!

2024-05-22 07:53 UTC, sh1mj1 commented on app/src/main/java/woowacourse/shopping/Event.kt
> +    var hasBeenHandled = false
넵!, Utils 이라는 이름의 패키지를 되도록 쓰고 싶지 않았는데,  결국 어쩔 수 없는 부분이 생기는 군요...
적용하겠습니다

2024-05-22 07:59 UTC, sh1mj1 commented on app/src/main/java/woowacourse/shopping/NumberPagingStrategy.kt
> +    override fun loadPagedData(
앱 아키텍처 관련 안드로이드 공식 문서를 생각하면, DataSource  정도가 될 것 같아요.
그리고 실제 서버와 통신을 한다면, 실제 페이지 안의 데이터의 양만큼만 데이터를 요청해야 하므로, 메서드의 시그니처도 조금 바뀔 것도 같습니다.

2024-05-22 08:49 UTC, sh1mj1 commented on app/src/main/java/woowacourse/shopping/productList/ProductListFragment.kt
> +    }
그렇군요!

2024-05-22 09:02 UTC, sh1mj1 commented on app/src/main/java/woowacourse/shopping/cart/ShoppingCartViewModelFactory.kt
> +}
지금 당장 어떠한 기준이나 근거가 바로 세워지지가 않네요... 😢 
이 부분 잊지 않고 있다가 추후에 꼭 코멘트 달겠습니다!

2024-05-23 10:59 UTC, Gyuil-Hwnag commented on app/src/main/java/woowacourse/shopping/Event.kt
> +    var hasBeenHandled = false
@sh1mj1 
심지 안녕하세요~
Utils는 예시라서 심지가 생각하기에 좋은 방식으로 작성해주세요!!