[쇼핑 장바구니] 벼리 1, 2단계 미션 제출합니다.
woowacourse/android-shopping-cart pull request #70
Opened 2024-05-16 08:38 UTC by gaeun5744

안녕하세요! 안드로이드 6기 크루 벼리입니다 🤗
안녕하세요 제리!
블랙잭 미션 때 제리와 리뷰를 주고 받으면서 많이 배웠는데, 또 다시 이렇게 만나서 기쁘네요😄😄
이번 미션 부족한 점이 많지만 잘 부탁드립니다 🙇🏻‍♀️

2024-05-17 08:39 UTC, vagabond95 requested changes
다시 뵙게 되어 반갑습니다 벼리 :)

전반적으로 함수 단위 / 상수 선언 등에 신경을 많이써주신 것 같습니다. 가독성이 뛰어나 이해가 쉬웠어요 👍 

좀 더 고민해볼만한 포인트에 대해 몇가지 코멘트 남겼는데, 확인 후 리뷰요청 부탁드릴게요~!

2024-05-17 08:39 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productdetail/ProductDetailActivity.kt
> +        viewModel.product.observe(this) {
현 단계에서 진도가 나간부분일지 몰라서, 우선 코멘트만 남겨놓을게요~!

databinding 의 기능을 잘 활용하면 LiveData 를 xml 에서 접근 및 활용이 가능합니다.
즉, 현재 처럼 별도로 observe 하는 코드가 필요없고 일반적인 모델을 가져다 쓰는 것처럼 코드를 작성하면서 변경사항이 발생했을 때 자동으로 반영이 되는 마법(?)같은 일이 가능합니다.

databinding, liveData 키워드를 같이 묶어서 리서치하면 참고할 자료가 많으니 한번 학습해보셔도 좋겠습니다 :)

2024-05-17 08:39 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productdetail/ProductDetailActivity.kt
> +            Glide.with(this@ProductDetailActivity)
Glide 코드는 구조가 거의 유사하므로 재사용하기 용이합니다.
재사용 가능하도록 분리해보는 것은 어떨까요?

이전 미션에서 학습한 BindingAdapter 를 활용해보셔도 좋습니다.

2024-05-17 08:39 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListActivity.kt
> +            adapter.submitList(products.map { it.toProductUiModel() })
데이터를 Mapping 하는 작업이 View 에서 진행될 필요가 있을까요~?

2024-05-17 08:39 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListAdapter.kt
> +        notifyItemRangeInserted(previousCount, products.size - previousCount)
notifyItemRangeInserted 를 활용하는 시도 👍 
그런데, 현재처럼 전체 데이터를 넘기기보다 새로 추가되는 데이터만 전달하는게 좀 더 자연스럽지 않을까요~?

2024-05-17 08:39 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListViewModel.kt
> +    val totalSize: Int = repository.productsTotalSize()
해당 상태들은 현재 사용이 안되고 있는 것 같습니다 :)

2024-05-17 08:39 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/shoppingcart/ShoppingCartActivity.kt
> +            viewModel.loadCartItems(currentPage)
viewModel 의 상태를 observe 했을때, 다시 viewModel 코드를 호출하는 구조는 흐름을 파악하기 어려울 수 있어요.
또한, LiveData 를 사용했을 때 얻을 수 있는 큰 이점은 [UDF](https://medium.com/swlh/unidirectional-data-flow-in-for-android-uis-5edd1386f40d) 가 가능해진다는 점인데, 현재와 같은 구조는 양방향으로 flow 가 진행되기 때문에 그 이점을 잘 살리지 못하는 것 같습니다.

LiveData 를 학습했다고 해서 모든 flow 를 LiveData 로 구현하지 않으셔도 괜찮습니다!
+ 추가 질문 : 양방향으로 flow 가 진행됐을 때, 단방향 대비 단점은 무엇이 있을까요?

2024-05-17 08:39 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/shoppingcart/ShoppingCartActivity.kt
> +        viewModel.updatePageSize()
view 에서 viewModel 동작의 세부 흐름을 알 필요가 없을 것 같아요. 하나의 함수를 호출하고, 세부 동작은 viewModel 내부에서 처리해보는 것은 어떨까요?

2024-05-17 08:39 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/shoppingcart/ShoppingCartViewModel.kt
> +        MediatorLiveData(false).apply {
벌써 MediatorLiveData 를 학습하고 활용해주셨군요?! 👍

2024-05-17 08:39 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/shoppingcart/ShoppingCartViewModel.kt
> +        private const val PAGE_SIZE = 5
전반적으로 상수가 꼼꼼히 정의되어 있어 코드를 이해하기 쉬웠습니다 👍

2024-05-17 08:39 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/shoppingcart/ShoppingCartViewModel.kt
> +            loadCartItems(currentPage)
loadCartItems 는 currentPage 의 데이터를 불러와서 UI 에 표현하는 함수인데요.

예를들어 10개의 페이지가 있고, 7번째 페이지에서 삭제가 발생하여 loadCartItems(7) 를 호출하게 되면,
UI 에는 7번째 페이지만 노출되지 않을까요?

loadCartItems 함수 혹은 cart item 삭제 후 처리에 대해 고민이 필요할 것 같습니다!

2024-05-19 06:06 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/productdetail/ProductDetailActivity.kt
> +        viewModel.product.observe(this) {
해당 부분에 관해 질문이 있습니다..! 

### 제리의 dataBinding 적용 기준이 궁금합니다!
사실 저번 미션을 진행하면서, 혼란스러웠던 지점 중 하나가 바로 `dataBinding을 적용하는 기준`이었습니다.

제리의 말대로 xml에서 liveData를 이용해 뷰를 초기화할 수 있지만, 과연 모든 로직에 대해서 dataBinding 써도 될까 라는 의문을 가졌습니다. **왜냐하면 오히려 dataBinidng을 썼기 때문에 가독성이 떨어진다는 생각이 많이 들었기 때문입니다.** 또한, dataBinding은 업데이트가 비교적 느리고 에러가 발생했을 때 디버깅하기 어렵다는 단점이 있습니다.

그래서 저 나름대로 dataBinding을 적용하는 기준을 세워보았습니다.
dataBinding은 유저 이벤트로 인한 변화가 많이 생기는 뷰에 대해서, 업데이트를 효율적이고 간편하게 하는 것이 가장 큰 장점이라 생각했습니다. 

그래서 `변화가 자주 일어나는 뷰에 대해서는 dataBinding을 적용`하고, 뷰 초기화와 같이 단편적인 뷰에 대해서는 하지 않는게 좋겠다고 생각했습니다. 그래서 해당 뷰에서는 dataBinding을 활용하지 않았습니다..!

하지만 이에 대해서,  startActivity와 같이 context에 종속적인 로직을 제외하고는 전부 dataBinding을 적용하는 기준을 가진 크루도 있었습니다. 

혹시 제리의 dataBinding 적용 기준은 어떻게 되나요?! 제리의 생각이 궁금합니다!!

2024-05-19 08:26 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListViewModel.kt
> +    val totalSize: Int = repository.productsTotalSize()
아 해당 부분은 xml에서 
```
android:visibility="@{vm.currentSize == vm.totalSize ? View.GONE : View.VISIBLE}"
```
에서 사용되고 있습니다!!

2024-05-19 16:42 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/productdetail/ProductDetailActivity.kt
> +            Glide.with(this@ProductDetailActivity)
해당 부분에 대해서는, 위의 코멘트와 같이 아직 BindingAdapter를 적용하는 기준을 명확히 세우지 못해서 우선은 확장함수로 만들었습니다!!

2024-05-19 16:46 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListActivity.kt
> +            adapter.submitList(products.map { it.toProductUiModel() })
아차차..! viewModel로 로직을 이동시켰습니다..!!!

2024-05-19 17:11 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListAdapter.kt
> +        notifyItemRangeInserted(previousCount, products.size - previousCount)
추가된 데이터에 대해서만 전달하려고 구현하다가 의문점이 생겨서 코멘트를 남겼습니다!!

2024-05-19 17:16 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/shoppingcart/ShoppingCartActivity.kt
> +            viewModel.loadCartItems(currentPage)
1. UI와 비즈니스 로직이 단일 진입 지점을 통해 상호 작용하기 때문에 디버깅하기 쉽습니다.
2. 대부분의 로직이 viewModel에 있도록 구현되기 때문에 테스트하기 쉽습니다

덕분에 ui layer에서의 디자인 패턴에 대해 배울 수 있었습니다!! 🥰

2024-05-19 17:18 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/shoppingcart/ShoppingCartActivity.kt
> +        viewModel.updatePageSize()
아이템을 삭제한 후, onSuccess에서 updatePageSize() 및 loadCartItems()을 수행하도록 수정했습니다!!

2024-05-19 17:29 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/shoppingcart/ShoppingCartViewModel.kt
> +            loadCartItems(currentPage)
해당 코멘트에 대해 더 자세히 설명해 주실 수 있을까요..? 
7번째 페이지만 노출 되는 것이 왜 문제인지 이해가 되지 않습니다.😂😂

**혹시 delete 메서드가 호출되면, 7번째가 아닌 다른 페이지의 ui 또한 미리 갱신되어야 한다는 의미일까요..?** 

다시 영상을 찍으며 유저 사용성에 대해 고민해봤습니다..! 
3번째 페이지에서 아이템을 삭제한 후, 해당 페이지에서 갱신된 장바구니 아이템 5개를 바로 ui에 반영하도록 구현했습니다. 제가 꼼꼼하지 못한 편이라, 다른 페이지로 다시 넘어가도, ui 구조에 대한 문제점을 파악하기 힘듭니다😥 죄송하지만 더 자세히 설명해주시면 감사하겠습니다...


++) 혹시 notifyDataSetChanged()를 호출했기 때문에 발생하는 ui 교체 깜빡임 현상을 말씀하시는 걸까요?? 해당 부분에 대해서도 계속 시도해봤지만, 너무 어려운 문제라 추가로 코멘트를 남겼습니다😭

https://github.com/woowacourse/android-shopping-cart/assets/92314556/d569402d-ea02-408a-94c1-17bb9a79b868

2024-05-19 17:57 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListViewModel.kt
> +    val products: LiveData<List<ProductUiModel>> get() = _products
해당 속성은 현재 사용하고 있지 않습니다! 사용하지 않음에도 불구하고, 코드를 남겨둔 이유는 다음과 같습니다.

1. ui state holder 역할을 하는 viewModel의 데이터와, 실제 ui에 나타난 데이터 사이의 간극

현재는 `moreProduct LiveData`를 이용해 새로 추가된 데이터에 대해서만 adapter에 추가하고 있습니다. 그렇게 되면서 전체 데이터를 나타내는 `products`는 더이상 쓰지 않게 되었습니다. 
그러자 ui state holdel인 viewModel이 전체 데이터의 일부만 가지고 있어도 되는 것인가? 라는 의문이 들었습니다. 
화면 회전시에도 데이터가 유지되는 viewModel의 특성을 제대로 활용하고 있지 못할 뿐더러, 대부분의 개발자는 모든 ui data는 viewModel에서 관리하고 있다고 기대할 것이라 생각하기 때문입니다.

이에 대한 해결방안으로, 다음과 같은 코드를 생각하기도 했습니다. 
```
viewModel.products.observe(this) { products ->
      adapter.submitList(products.subList(adapter.itemCount, products.lastIndex))
}
```

다만 해당 로직은, activity가 로직을 들고 있다는 점에서 어색하게 느껴졌습니다... 
혹시 제리는 둘 중 어떠한 방법이 더 나아 보이시나요?

2024-05-19 17:57 UTC, gaeun5744 commented on app/build.gradle.kts
> +    implementation("com.squareup.leakcanary:leakcanary-android:2.14")
원래라면 `debugImplementation`을 붙여서 디버깅시에만 작동하도록 해야하지만.. 제 컴퓨터가 느려서 디버깅을 시작하면 작동이 아예 안되는 경우가 발생해 부득이하게 `implementation`을 했습니다😳

2024-05-19 17:57 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/shoppingcart/ShoppingCartAdapter.kt
> +    }
해당 메서드도 구현했지만, 현재는 사용하지 않고 있습니다.
원래 처음 의도는
1. 아이템 삭제(notifyItemRemoved 호출)
2. 다음 페이지에 아이템이 있을 경우, 다음 페이지의 아이템을 가져와서 `addItem` 메서드를 통해 아이템 추가

라는 시나리오를 구성했습니다.
다만, 재활용되는 viewHolder 특성상  
```
ibCartClose.setOnClickListener {
            onClicked.onItemRemoveBtnClicked(item.id)
}
```

위의 메서드에서, 이전에 삭제되었던 item의 id값이 고정되어 들어오는 문제가 발생했습니다.
즉, 아이템을 2번  연속으로 삭제하지 못하고 있습니다 

이 문제를 해결하기 위해 onBindViewHolder에서 초기화하거나 여러 방법을 시도했지만, 해결하기 힘들었습니다😥
혹시 해당 문제에 대한 힌트를 얻을 수 있을까요...?

2024-05-19 17:57 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/shoppingcart/ShoppingCartViewModel.kt
> +//            }
이부분도 adatper의 `deleteItemByProductId` 메서드 문제를 해결하면 바로 주석을 풀겠습니다 😂

2024-05-19 17:59 UTC, gaeun5744 commented
안녕하세요 제리! 좋은 주말 보내셨나요🥰 
우선 의도치 않게 주석처리된 코드로 리뷰요청을 보내서 죄송합니다. 
코드를 전부 다 지우고 질문을 드리기에는 이해하기 어려워 보여서, 부득이하게 남기게 되었네요.. 다음 리뷰 요청때는 꼭 삭제하겠습니다!

2024-05-19 18:19 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/shoppingcart/ShoppingCartViewModel.kt
> +    val cartItems: LiveData<List<ProductUiModel>> get() = _cartItems
추가로 질문 있습니다! 
MuteblaLiveData에서 LiveData로 값을 가져올 때, 왜 많은 사람들이 `custom getter`를 사용하는지 알 수 있을까요..?
`custom getter`를 사용하지 않더라도 LiveData에서는 항상 최신값을 불러올 수 있을 뿐더러, val 은 setter을 생성하지 않는 것으로 알고 있습니다..! 계속 서치해봐도 `custom getter`을 쓰는 이유를 알 수 없어서 이렇게 질문 드립니다🤣

2024-05-20 12:55 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productdetail/ProductDetailActivity.kt
> +        viewModel.product.observe(this) {
솔직히 고백하겠습니다.. 저는 data binding 을 선호하지 않습니다 ^^;;;
이유는
1) 현 팀의 프로젝트가 data binding 을 적용하기에 적합하지 않은 구조이기도 하고
2) data binding 을 적용했을 때, xml 에 비즈니스 로직이 들어갈 수 있는 여지를 주는게 싫었습니다.

그럼에도 불구하고 data binding 을 적용하는 기준을 생각해본다면
벼리가 얘기한 것처럼 어떤 상태의 속성 기준으로 data binding 적용한다기 보다,
data binding 을 모든 상태에 적용하되 최대한 상태를 바로 참조하여 사용할 수 있도록 신경을 썼던 것 같습니다.

예를 들어, 날짜를 표시해야한다면 날짜에 대한 포매팅은 모두 viewModel 에서 마치고 view 에서는 날짜 텍스트를 바로 참조하여 노출해주는 형태로요.

그런데, 이러한 지침은 벼리에게 그다지 도움이 되지 않을 것 같아요. 왜냐하면 벼리가 스스로 이미 너무 잘해주고 계시기 때문입니다.

그냥 형식적인 칭찬이 아니라 벼리가 생각한것처럼 정답이 없는 부분이기 때문입니다.
dataBinding 은 결국 view 와 model 을 연결하는 방법 중 하나일 뿐이고, 그동안 미션들에서 배웠던 view / model 의 의존성을 다루는 규칙만 잘 지킨다면 어떠한 방식으로 활용해도 상관이 없다고 생각합니다.

따라서 벼리가 스스로의 기준을 세우고 그대로 준수해보면서, 겪게되는 장/단점을 익히고 자신만의 논리를 세워나가는게 중요하다고 생각합니다.
그리고 협업시에는 이러한 논리로 팀원들을 잘 설득하되, 팀 전체의 방향성을 해치지 않는 선에서 맞춰나가면 제일 이상적인 모습이라고 생각됩니다 :)

한가지 궁금한 점이 있는데여, 데이터 바인딩의 업데이트가 느리다는 내용은 어떤 기준으로 산정된 것일까요?

2024-05-20 13:00 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListViewModel.kt
> +    val totalSize: Int = repository.productsTotalSize()
이 부분 다른 크루들한테도 동일하게 저질렀던 실수인데, 빌드하지 않으면 xml 에서 binding 한 상태는 IDE 에서 못잡더라구요 ^^; 혼동을 드려 죄송합니다.

2024-05-20 13:09 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/shoppingcart/ShoppingCartViewModel.kt
> +    val cartItems: LiveData<List<ProductUiModel>> get() = _cartItems
다양한 예제에서 custom getter 를 사용하고 있었나요? 
```
    val currentPage: LiveData<Int> = _currentPage
```
사실 위와 같이 표현해도 차이가 없긴한데요 ㅎㅎ;
아마 누군가 레퍼런스를 올렸고, 그것을 다같이 참조해서 그랬을수는 있을거 같네요.

크게 중요한 부분은 아닌거 같아요!

2024-05-20 13:20 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/shoppingcart/ShoppingCartAdapter.kt
> +    }
```
    fun deleteItemByProductId(productId: Long) {
        val deleteIndex = items.indexOfFirst { it.id == productId }
        items.removeAt(deleteIndex)
        notifyDataSetChanged()
    }
```
를 그대로 호출한뒤, 특정 ViewHolder 의 onBind 함수에서 삭제된 item 이 전달된다는 의미이실까요?

onBind 를 통해 전달되는 item 이 무엇인지부터 먼저 추적하고, 그 때 items 에도 제대로 값이 제거되었는지 확인을 먼저 해보면 원인을 찾는데 좁혀볼 수 있지 않을까요~?

2024-05-20 13:28 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListViewModel.kt
> +    val products: LiveData<List<ProductUiModel>> get() = _products
우선 전체 리스트를 들고있는 전략은 좋다고 생각합니다.
이것을 Adapter 에 어떻게 전달할지는 선택의 문제인데요, 우선 Activity 에서 처리하는 것은 지양해야할 것 같습니다. 데이터를 어떻게 전달하는 방식에 대한 고민은 View 의 역할이 아니니까요.

남은건 ViewModel or Adapter 둘중 하나에서 처리를 해야하는데, 저라면 ViewModel 에서 처리를 할 것 같습니다. 저는 Adapter 도 View 의 일부라서 전달받은 데이터를 업데이트하고 notify 하는 역할 외에는 수행하지 않는 것이 맞다고 생각합니다.

따라서 지금 벼리가 구현한 코드에서 크게 달라지지는 않을 것 같아요.
다만 products 가 굳이 LiveData 로 감싸지 않아도 괜찮지 않을까요? ㅎㅎ

2024-05-21 05:14 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/productdetail/ProductDetailActivity.kt
> +        viewModel.product.observe(this) {
이 부분은 [공식문서](https://developer.android.com/topic/libraries/data-binding/binding-adapters?hl=ko)의 내용을 보고 주관적으로 판단했습니다! 

문서에서는 성능 최적화를 위해서, data 변화가 감지되더라도 바로 ui에 업데이트 되지 않는 경우가 있다고 되어 있습니다. 저는 해당 내용을 통해서 데이터 바인딩의 업데이트가 비교적 느리다고 생각했습니다. 

또한, viewBinding을 적용했을 때는 성공하는 테스트가, DataBinidng을 적용하면 실패해서 테스트가 많았습니다...(예시: [hadDescendant](https://stackoverflow.com/questions/56577546/recyclerviewactions-scrollto-doesnt-work-if-we-use-android-data-binding-in-view) 
그래서 업데이트가 느리다고 생각했습니다!

2024-05-21 05:19 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListViewModel.kt
> +    val products: LiveData<List<ProductUiModel>> get() = _products
넵!! 사용하지 않는 데이터에 대해 고민이 많았었는데 덕분에  조언 얻고 갑니다!!😄😄

2024-05-21 11:10 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/shoppingcart/ShoppingCartViewModel.kt
> +    val cartItems: LiveData<List<ProductUiModel>> get() = _cartItems
android 공식 조직계정의 [sunflower 프로젝트](https://github.com/android/sunflower/blob/15898e5e5c2212cb7d174e6d182f92baee2d6cae[…]oogle/samples/apps/sunflower/viewmodels/PlantDetailViewModel.kt)와 [코드랩](https://developer.android.com/codelabs/basic-android-kotlin-training-livedata?hl=ko#5) [다른 레포](https://github.com/android/storage-samples/blob/main/MediaStore/app/src/main/java/com/android/samples/mediastore/MainActivityViewModel.kt)에서 사용중인 걸로 알고 있습니다..! 

로직상 다른 부분이 있는 줄 알았는데 아니었네요droid 공식 조직계정의 [sunflower 프로젝트](https://github.com/android/sunflower/blob/15898e5e5c2212cb7d174e6d182f92baee2d6cae[…]oogle/samples/apps/sunflower/viewmodels/PlantDetailViewModel.kt)와 [코드랩](https://developer.android.com/codelabs/basic-android-kotlin-training-livedata?hl=ko#5) [다른 레포](https://github.com/android/storage-samples/blob/main/MediaStore/app/src/main/java/com/android/samples/mediastore/MainActivityViewModel.kt)에서 사용중인 걸로 알고 있습니다..! 

로직상 다른 부분이 있는 줄 알았는데 아니었네요😂

2024-05-21 12:14 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/shoppingcart/ShoppingCartAdapter.kt
> +    }
문제를 해결했습니다! adapter 내부의 문제가 아니라 observing 객체가 중복되면서, 기존 데이터를 계속 넘기는게 문제였습니다..!! 😂😂

2024-05-21 12:15 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/DummyShoppingRepository.kt
> +object DummyShoppingRepository : ShoppingRepository {
productRepository와 shoppingRepository 이렇게 2가지로 나눠서 분리했습니다!

2024-05-21 12:16 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListActivity.kt
> +            viewModel.loadProducts(adapter.itemCount)
기존의 product 프로퍼티를 이용해서 메서드를 불러오도록 수정했습니다!

2024-05-21 12:17 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListViewModel.kt
> +    val currentSize: LiveData<Int> get() = _currentSize
이 부분도 product 프로퍼티를 이용해 관리하도록 수정했습니다!

2024-05-21 12:20 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/shoppingcart/ShoppingCartViewModel.kt
> +    val loadState: LiveData<LoadCartItemState> get() = _loadState
아 이부분은 앞에서 언급한 delete 메서드 오류를 해결하면서 활용할 liveData라 그대로 두었습니다..! 현재는 사용중입니다!!!😄

2024-05-22 01:48 UTC, vagabond95 approved these changes
단순한 감이 아니라 공식 레퍼런스 문서를 참고하여 의사결정하는 과정이 인상깊었습니다 👍 
저보다도 더 꼼꼼하게 체크해주신 것 같아요! ㅎㅎ

벼리가 참고했던 레포지토리들은 훌륭한 레퍼런스지만 코드 스타일의 경우 너무 깊게 고민을 안하셔도 될 것 같아요. 정말 이상한 규칙이 아닌 이상, 하나의 코드를 표현하는 방법은 여러가지 방식이 있기 때문에 de facto standard 가 명확하게 정해져 있다기보다 개별 팀 단위에서 규칙을 정하고 린트로 잡아내는 것이 가장 이상적인 형태인 것 같습니다!

다음단계의 원활한 진행을 위해 1,2단계는 여기서 마무리하겠습니다.  고생많으셨어요!

2024-05-22 01:51 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/shoppingcart/ShoppingCartAdapter.kt
> +    }
LiveData 혹은, 비슷한 방식으로 publish - subscribe 방식을 취하는 구현체는
중복 데이터 발행 이슈가 많은 비중을 차지하는 것 같아요 ^^;

그래도 앞으로는 비슷한 이슈가 발생했을 때 더 빠르게 원인을 파악할 수 있게 되었네요 👍

2024-05-22 01:51 UTC, merged