[쇼핑 장바구니] 누누 3,4단계 미션 제출합니다.
woowacourse/android-shopping-cart pull request #74
Opened 2024-05-22 10:23 UTC by jinuemong

안녕하세요 제리 3,4단계도 잘 부탁드립니다 !
🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️

2024-05-23 14:23 UTC, vagabond95 requested changes
빠르게 3,4단계 마무리해주셨네요 !

Repository 를 단순히 data source 의 CRUD 작업의 추상화로만 활용하는 것을 넘어서, CRUD 작업 자체를 엮어서 또하나의 비즈니스로직을 수행하도록 구성해보는 시도를 해봐도 좋을 것 같아요.

ViewModel 이 비즈니스 로직을 담당하는 역할은 맞지만, Model 계층 내에서만 수행될 수 있는 비즈니스 로직이 있다면 이를 굳이 ViewModel 까지 끌고올 필요는 없으니까요 :)

코멘트 확인 후 리뷰요청 부탁드릴게요~!

2024-05-23 14:23 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/view/MainFragmentListener.kt
> +interface MainFragmentListener {
이를 구현하고 있는 구현체가 Fragment 가 아닌 Activity 이므로 네이밍 수정이 필요할 것 같아요. 

추가로 ActivityViewModel 이라는 키워드에 대해 학습해보면, 해당 Listener 를 쓰지않고도 요구사항을 구현할 수 있어보이는데 한번 리서치해봐도 좋겠습니다 :)

2024-05-23 14:23 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/data/db/product/ProductDao.kt
>  class ProductDao {
Dao 는 보통 DB 의 접근을 돕는 객체의 의미로 많이 쓰이기 때문에, 웹 소켓을 Mocking 하는 클래스에는 적절하지 않은 이름 같아요.

2024-05-23 14:23 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/data/db/product/ProductDao.kt
> +    fun findAll(): List<Product> {
OkHTTP 자체에 대한 리뷰는 다음 미션에서 다룬다고 전달받아 깊게 보지는 않았습니다!

그래도 몇개만 코멘트를 남겨보면,
우선 여러 함수들이 비슷한 구조로 구성되어있어서 재사용이 가능하도록 리펙토링 해보면 좋을 것 같아요.

2024-05-23 14:23 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/data/db/product/ProductDao.kt
> +        private const val MOCK_SERVER_URL = "/products"
정확히는 PATH 라고 지칭하는 것이 맞습니다 :)
상수화를 한 것은 좋습니다! 그런데 해당 상수가 재사용이 잘 안되고 있는 것 같아요. 재사용할 수 있는 부분에는 해당 상수를 이용해볼 수 있을까요?

2024-05-23 14:23 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/view/products/ProductListViewModel.kt
> +    private val _errorEvent: MutableSingleLiveData<ProductListEvent.ErrorEvent> =
공유드렸던 SingleLiveData 를 도입해주셨군요!

2024-05-23 14:23 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/view/products/ProductListViewModel.kt
> +                    _errorEvent.postValue(
대부분 이벤트 전달 시, postValue 를 호출해주셨는데 이유가 있을까요?
setValue 와 구현상 차이는 무엇일까요?

2024-05-23 14:23 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/view/products/ProductListViewModel.kt
> +                    product.cartItemCounter.updateCount(cartItemResult.counter.itemCount)
product 를 접근하는 입장에서 cartItemCounter 를 노출해주지 않는게 더 좋을 것 같아요.
디미터 법칙을 상기하면서, 캡슐화 및 함수 호출 depth 를 줄여볼 수 있을까요?

2024-05-23 14:23 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/view/products/ProductListViewModel.kt
> +                        }
DB 로 부터 모델을 가져오고, 모델의 특정 상태를 업데이트하고, 해당 모델을 다시 DB 로 업데이트하는 과정이
여러 ViewModel 에서 반복적으로 구현되어 있는 것으로 보여요.

해당 과정을 하나로 묶어, Repository 에서 하나의 함수로 제공해보는 것은 어떨까요?

2024-05-23 14:23 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/data/model/RecentlyProductEntity.kt
> +        fun makeRecentlyProductEntity(recentlyProduct: RecentlyProduct): RecentlyProductEntity {
entity -> domain model Mapping 함수는 entity 내부에,
domain model -> entity Mapping 함수는 companion object function 으로 제공되고 있는데

구현 방식이 통일되면 좋을 것 같아요.

2024-05-23 14:23 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/data/model/RecentlyProductEntity.kt
> +        fun makeRecentlyProductEntity(recentlyProduct: RecentlyProduct): RecentlyProductEntity {
추가로, Mapping 함수는 exntension function 으로 제공하면 좀 더 가독성 및 유지보수 측면에서 용이합니다.

가령, RecentlyProductEntity 내부에서 mapping 함수를 제공하는 것도 단점이 존재하는데요,
Entity 에 Domain Model 의 의존성이 생기기 때문입니다.

Entity 는 기본적으로 Model 계층에서도 가장 하위, 다시 말해 무엇도 의존하지 않는 low level 의 모델에 속합니다. 도메인 모델에 의존하면 이러한 의존관계가 깨지기 때문에 추후에 확장성에 한계가 존재합니다.

이때 extension function 을 활용하면, Entity 외부에서 (=Entity 가 도메인 모델에 직접적인 의존을 하지 않으면서) Mapping 이 가능해지죠 ㅎㅎ

2024-05-23 14:23 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/data/repository/ShoppingCartRepositoryImpl.kt
> +        var cartItem: CartItem? = CartItem.defaultCartItem
default 라는 값을 두어야할 이유가 있을까요~?
값을 가져오거나 / 가져오지 못하는 상황만 존재할 것 같아서요 ㅎㅎ

2024-05-23 14:23 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/data/repository/ShoppingCartRepositoryImpl.kt
> +            }
이 부분도 NotExists / Exists 를 구분하기보다, 값을 가져올 수 있는 경우만 전달하고 나머지는 예외를 세부적으로 구별하여 던지는 방식은 어떨까요? Result 를 매번 분기하면서 검사하는 코드가 항상 필요하다는게 허들이 될 수 있어보여요.

2024-05-24 07:18 UTC, jinuemong commented on app/src/main/java/woowacourse/shopping/domain/model/CartItemCounter.kt
> +        return ChangeCartItemResultState.Success
원래는 카트에 담을 개수를 제한하려 했는데, 기능이 생각보다 많아서 처리를 못했네요 ! 삭제하였씁니다.

2024-05-24 08:09 UTC, jinuemong commented on app/src/main/java/woowacourse/shopping/domain/model/CartItemCounter.kt
> +    isSelected: Boolean = DEFAULT_ITEM_SELECTED,
네~ 해보겠습니다 !

2024-05-24 08:22 UTC, jinuemong commented on app/src/main/java/woowacourse/shopping/data/db/product/ProductDao.kt
>  class ProductDao {
MockProductService로 수정하였는데요,
테스트코드가 아닌 부분에 Mock을 사용하는 것이 조금 고민이 됩니다.
서버를 임시로 생성하여 테스트 후
나중에 서버를 연결한다고 가정한다면,
Mock이라는 이름을 테스트코드가 아닌 곳에서 사용하는게 괜찮을까요?
서버 연결을 나중에 구현한다는 가정을 하였습니다.

2024-05-25 05:26 UTC, jinuemong commented on app/src/main/java/woowacourse/shopping/data/db/product/ProductDao.kt
> +        private const val MOCK_SERVER_URL = "/products"
위 코맨트와 함께 재사용 가능하도록 리팩토링 해봤습니다 !

2024-05-25 05:33 UTC, jinuemong commented on app/src/main/java/woowacourse/shopping/view/products/ProductListViewModel.kt
> +                    _errorEvent.postValue(
setValue는 메인 스레드에서 즉시 값을 설정하고 옵저버에게 알리고, postValue는 백그라운드 스레드에서 값을 설정하고 다음 ui 스레드 사이클에서 옵저버에게 알린다고 알고 있습니다.
솔직하게 차이는 이해하였는데 적절한 사용법을 잘 모르겠습니다.
백그라운드 스레드에서 값을 설정하게 되면 안정적이고 비동기적으로 데이터를 업데이트하는 것이 아닌가? 생각하여 사용하게 되었습니다.
두 함수를 어떻게 적절하게 분배해야할 지 잘 모르겠습니다 ㅠ

2024-05-25 10:03 UTC, jinuemong commented on app/src/main/java/woowacourse/shopping/data/repository/ShoppingCartRepositoryImpl.kt
> +        var cartItem: CartItem? = CartItem.defaultCartItem
로직을 수정해보니 필요없는 부분이네요! 수정하였습니다.

2024-05-25 10:04 UTC, jinuemong commented on app/src/main/java/woowacourse/shopping/data/model/RecentlyProductEntity.kt
> +        fun makeRecentlyProductEntity(recentlyProduct: RecentlyProduct): RecentlyProductEntity {
수정 중에 궁금한 사항이 생겼습니다  !
entity -> domain, domain -> entity 매핑 함수 모두 extension function을 활용하는 것이 좋을까요?

2024-05-25 10:06 UTC, jinuemong commented on app/src/main/java/woowacourse/shopping/data/repository/ShoppingCartRepositoryImpl.kt
> +            }
위 커맨트의 리팩토링을 거치면서 삭제되었습니다 !

2024-05-25 12:21 UTC, jinuemong commented
[1차 리팩토링] 제리 리팩토링해서 보냅니다!
궁금한 점은 코맨트에 짧게 달아놨습니다.🙇‍♂️

2024-05-26 06:21 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/data/model/RecentlyProductEntity.kt
> +        fun makeRecentlyProductEntity(recentlyProduct: RecentlyProduct): RecentlyProductEntity {
저는 Mapping 함수는 대부분 extension function 을 활용하는 것을 선호합니다.
각각을 구분하는게 좋다는 생각이 드셨다면, 이유를 알 수 있을까요~?

2024-05-26 06:24 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/data/db/product/ProductDao.kt
>  class ProductDao {
개발 단계에서 서버쪽 구현 일정과 맞지 않을때, Mock 이라는 이름을 사용하기도 합니다!
다만, 이 부분은 언젠가 실제 서버 API 구현으로 대체될 부분이기 때문에 삭제가 되므로 임시로 부여하는 성격이 강합니다 ㅎㅎ

한편, 테스트시 Service 를 Mocking 할 니즈가 있을 경우에도 사용할 수 있겠죠.
만약 MockProductService 자체의 의존성이 생기는 것이 부담스럽다면, ProductService 인터페이스를 만들고 인터페이스 타입에 의존하도록 수정해보면 어떨까요?

2024-05-26 06:32 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/view/products/ProductListViewModel.kt
> +                    _errorEvent.postValue(
postValue 가 호출될 때, 어느 Thread 에서 동작하는지 한번 체크해볼 수 있을까요? :)

2024-05-26 06:45 UTC, vagabond95 commented
현재 대부분의 동작이 크래시로 인해 정상적으로 진행이 안되고 있는데요, 해결이 필요할 것 같습니다.
PR 제출전에 한번씩 전체적인 flow 도 테스트 부탁드릴게요~!

2024-05-26 06:53 UTC, vagabond95 requested changes
코멘트의 의도를 잘 파악하고 리펙토링 진행해주셨네요 👍 

하위 코멘트로 질문드린 부분도 고민 후 답변 부탁드릴게요~!
그래고 크래시 해결이 가장 최우선으로 진행이 되어야 할 것 같습니다. 😭 

마지막까지 화이팅입니다~!

2024-05-26 06:53 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/view/products/ProductListViewModel.kt
> +    private fun updateTotalCount() {
해당 함수는 파라미터를 전달하지 않으므로 어떻게 업데이트해야하는지 알 수 없어서, 모호한 함수로 보여요.

업데이트되는 대상을 인자로 받거나, 어디로부터 업데이트 되는 것인지 명시가 필요해보여요.

2024-05-26 06:53 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/view/products/ProductListViewModel.kt
> +        _productListEvent.postValue(ProductListEvent.UpdateProductEvent.Success(product.id))
try 구문내에 있어야하지않을까요? 
현 구현에서는 실패하더라도 성공 처리를 하게 될 것 같네요 ^^;

2024-05-26 06:53 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/data/db/product/MockProductService.kt
> +class MockProductService {
하위 코멘트에도 남겼지만, Repository 처럼 인터페이스를 통해 추상화한 후, 인터페이스 타입을 참조하도록 개선해봐도 좋을 것 같습니다~!

2024-05-26 06:53 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/data/repository/ShoppingCartRepositoryImpl.kt
> +        val cartItemResult = getCartItemResultFromProductId(productId)
repository 가 세부적인 Model 비즈니스 로직을 처리하도록 리펙토링 되었네요 👍 

앞으르도 viewModel 에 세부적인 Model 비즈니스 로직을 넣지 않도록 연습해보시면 좋을 것 같아요.

2024-05-26 06:53 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/data/repository/ShoppingCartRepositoryImpl.kt
> +                Log.d("sdlfsdj", updateCartItemType.count.toString())
테스트가 끝난 로그는 제거 부탁드릴게요~!

2024-05-26 06:53 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/view/cart/ShoppingCartViewModel.kt
> +                ShoppingCartEvent.UpdateProductEvent.DELETE(productId = productId)
2개의 이벤트가 항상 같이 호출되어야 한다면, 하나로 합쳐보면 어떨까요?

2024-05-26 06:53 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/view/cart/ShoppingCartViewModel.kt
> +    fun increaseCartItem(product: Product) {
increaseCartItem , decreaseCartItem 두 함수는 거의 구조가 유사한데요.
공통함수를 두고 재사용해보는 것은 어떨까요?

추후에 변경사항이 발생했을 때, 두 함수의 구현을 별개로 두면 놓치는 부분이 생기기 쉬울 것 같아요.

2024-05-26 11:13 UTC, jinuemong commented on app/src/main/java/woowacourse/shopping/view/products/ProductListViewModel.kt
> +        _productListEvent.postValue(ProductListEvent.UpdateProductEvent.Success(product.id))
앗 리팩토링 과정에서 실수했네요 ㅠ

2024-05-26 11:18 UTC, jinuemong commented on app/src/main/java/woowacourse/shopping/data/model/RecentlyProductEntity.kt
> +        fun makeRecentlyProductEntity(recentlyProduct: RecentlyProduct): RecentlyProductEntity {
도메인이 아주 많은 프로젝트에서 extension function에 모든 매핑 함수를 작성한다면 직관적이지 않다는 생각이 들어서 궁금했습니다! 
(ex> 너무 많은 extension funciton으로 구조를 파악하기 어려움? 등..)

2024-05-26 11:19 UTC, jinuemong commented on app/src/main/java/woowacourse/shopping/data/db/product/ProductDao.kt
>  class ProductDao {
좋은 방법이네요 수정해보겠습니다 !

2024-05-26 12:59 UTC, jinuemong commented on app/src/main/java/woowacourse/shopping/view/cart/ShoppingCartViewModel.kt
> +    fun increaseCartItem(product: Product) {
모든 뷰모델에 사용 된 증감 함수를 공통함수로 리팩토링 해보겠습니다 !

2024-05-26 13:08 UTC, jinuemong commented
[2차 리팩토링] 안녕하세요 제리 ! 크래시 부분 제외하고 리팩토링 진행하였습니다.
혹시나 해서 다른 기기에서 테스트해도 정상동작 하네요ㅠ 모든 flow 진행해봤습니다!

2024-05-27 13:00 UTC, vagabond95 requested changes
전반적으로 리펙토링이 꾸준히 잘 진행되어 크게 코멘트 드릴이 보이지 않네요 👍 

Exception 을 이용하여 로직을 수행하는 부분이 있어서 코멘트 남겼는데, 이 부분만 확인 부탁드릴게요~!

2024-05-28 02:38 UTC, jinuemong commented
[3차 리팩토링] 로직을 수정해봤습니다

2024-05-29 10:03 UTC, vagabond95 approved these changes
누누 미션 전반적으로 응답이 느려서 죄송했습니다 😭 
회사 업무가 참 도와주지 않네요 ^^;;

매번 가장 먼저 제출해주셨고, 피드백에 대한 의도도 잘 파악해주셨습니다 👍 
점점 비즈니스 로직이 복잡해질수록 이를 어떻게 잘 캡슐화하고, 재사용할지에 대해 계속 고민해보면 좋을 것 같아요.
마지막 미션까지 화이팅이십니다! 정말 고생 많으셨습니다. 💯

2024-05-29 10:03 UTC, merged