[쇼핑 장바구니] 차람 3,4단계 미션 제출합니다.
woowacourse/android-shopping-cart pull request #81
Opened 2024-05-26 14:48 UTC by aprilgom

안녕하세요 파이로!
3, 4단계도 리뷰 잘 부탁드립니다.

https://github.com/woowacourse/android-shopping-cart/assets/8610234/134b58cd-abcf-43fb-9491-09f9833d76de

미션에 대해 한가지 질문드릴 것이 있는데요,
상품 목록의 HTTP Client는 테스트 환경에서만 작동하면 되는건가요?
RemoteProductDataSource를 작성하긴 했는데, Mock 서버는 테스트 환경에서만 돌릴 수 있는 것 같아 질문 드립니다.

2024-05-26 22:30 UTC, ghojeong commented
> 상품 목록의 HTTP Client는 테스트 환경에서만 작동하면 되는건가요?
RemoteProductDataSource를 작성하긴 했는데, Mock 서버는 테스트 환경에서만 돌릴 수 있는 것 같아 질문 드립니다.

넵 테스트 환경에서만 작동하면 됩니다.
RemoteDataSource 의 경우에는 다음 미션에서 본격적으로 자세히 다루기 시작합니다.
그러므로 Mock 서버에는 크게 공수를 들이지 않으면 좋겠습니다.
Mock 서버 말고도 지금 할게 무척 많으니깐요!

Mock 서버 신경쓰지 마시고 보완해야할 테스트 보완해주시면 좋겠습니다.

2024-05-27 05:57 UTC, ghojeong requested changes
차람! 현재 린트와 테스트에 통과하지 않고있는데 
확인해주시고 다시 리뷰요청 해주시길 바랍니다.

2024-05-27 14:01 UTC, ghojeong requested changes
차람!
린트와 테스트 피드백만으로는 아쉬워하실 것 같아서,
추가로 피드백 남겨봅니다.

2024-06-02 08:47 UTC, aprilgom commented on app/src/main/java/woowacourse/shopping/presentation/ui/productlist/adapter/HistoryListAdapter.kt
> +    }
구현이 바빠서 그만..
item 개수가 10개밖에 안되기도 하니 나중에 고치자는 생각으로 일단 넣었습니다.
지금은 ListAdapter로 수정해주었습니다.

2024-06-02 08:47 UTC, aprilgom commented on app/src/main/java/woowacourse/shopping/presentation/ui/productlist/adapter/ProductListAdapter.kt
> +                )
enum으로 수정해주었습니다.

2024-06-02 08:48 UTC, aprilgom commented on app/src/main/java/woowacourse/shopping/presentation/ui/productlist/adapter/ProductListAdapter.kt
> +    override fun getItemCount(): Int = pagingProductUiModel.productUiModels.size + 2
ProductListViewType의 entries.size로 수정해주었습니다.

2024-06-02 08:53 UTC, aprilgom commented on app/src/main/java/woowacourse/shopping/presentation/ui/productdetail/ProductDetailViewModel.kt
> +    }
updatePrice로 바꾸어주었습니다.

2024-06-02 08:56 UTC, aprilgom commented on app/src/main/java/woowacourse/shopping/presentation/ui/productlist/adapter/HistoryListAdapter.kt
> +) : RecyclerView.Adapter<HistoryListAdapter.HistoryViewHolder>() {
HistoryAdapter에 ListAdapter를 적용해주었습니다.
1단계에 `ListAdapter, DiffUtil을 사용하지 않는다.` 라는 조건이 있어 쓰지 않았었네요.

2024-06-02 08:59 UTC, aprilgom commented on app/src/main/java/woowacourse/shopping/domain/model/History.kt
> +)
ProductBrowsingHistory라는 이름으로 바꾸어주었습니다.
조금 긴 이름이어도, 조회 기록인지, 아니면 구매 기록인지 구분을 해주는 쪽이 좋을 것 같아 좀 길게 지었습니다.
지역변수 이름으로는 history와 같이 짧게 지어주고 있는데, 길게 지어주는 쪽이 혼동 가능성은 적으나 읽기는 어려운 것 같아 고민입니다.

2024-06-02 09:32 UTC, aprilgom commented on app/src/main/java/woowacourse/shopping/presentation/ui/productdetail/ProductDetailViewModel.kt
> +        println(product.value)
표준 출력으로 나와도 확인이 되기에 돌려보면서 바로바로 확인하는 용도로 println을 썼습니다.
제가 특문을 쓰는게 좀 느려서 Log.d("~","~")를 치는데 오타가 많아 그랬습니다.
거기에 data class도 찍어보려면 toString 붙여야되고, import도 해줘야되고.. 한두개 찍어보고 지우는데도 태그지정을 해줘야하고..
로그별로 어디서 나오는지 에러인지 단순 로그인지 분류를 해야 알 수 있는 상황이 오면 모를까, 지금은 차라리 println이 편하겠다 싶어 사용했습니다.

2024-06-02 09:38 UTC, aprilgom commented on app/src/main/java/woowacourse/shopping/presentation/ui/productdetail/ProductDetailViewModel.kt
> +        println(product.value)
이렇게 로그를 하나 찍고 지우고 하면서 만드는 상황 자체가 좀 잘못된 것 같아 보이긴 하지만요.

2024-06-02 09:47 UTC, aprilgom commented on app/src/main/java/woowacourse/shopping/presentation/ui/productlist/ProductListActivity.kt
> +        menuBinding.vm = viewModel
handler를 따로 둔 건 교체 가능한 구조를 의도했었는데, 이렇게 보니 특정 viewModel에 의존적이네요. 이러면 의미가 없겠어요..

2024-06-02 09:49 UTC, aprilgom commented on app/src/main/java/woowacourse/shopping/presentation/ui/productlist/adapter/HistoryListAdapter.kt
> +    }
없애주었습니다.

2024-06-02 09:52 UTC, aprilgom commented on app/src/main/java/woowacourse/shopping/presentation/ui/productlist/adapter/ProductListAdapter.kt
> +                )
ViewType을 enum class로 따로 분리해주었습니다.

2024-06-02 09:53 UTC, aprilgom commented on app/src/main/java/woowacourse/shopping/presentation/ui/productlist/adapter/ProductListAdapter.kt
> +    override fun getItemCount(): Int = pagingProductUiModel.productUiModels.size + 2
enum type의 entries.size로 바꿔주었습니다.

2024-06-02 09:55 UTC, aprilgom commented on app/src/main/res/layout/activity_product_detail.xml
> +            tools:layout_editor_absoluteX="-196dp" />
이건.. 대체 왜 들어간건지 모르겠습니다. 아마 레이아웃 디자인 툴에서 뭔가 미스클릭이 있었던 것 같습니다.
지워주었습니다.

2024-06-03 07:30 UTC, aprilgom commented on app/src/main/java/woowacourse/shopping/presentation/ui/productlist/ProductListUiState.kt
>  )
History와 ProductList, Order를 각각의 UiState들로 분리해주었습니다. 이러면 서버 콜 로딩을 따로 받을 수 있을 것 같습니다.

2024-06-03 07:32 UTC, aprilgom commented on app/src/main/java/woowacourse/shopping/presentation/ui/productlist/ProductListViewModel.kt
> +    private fun makePagingProductUiModels() {
MediatorLiveData를 이용해 OrderUiState와 PagingProductUiState의 변경 사항이 있을 경우 이를 받아 처리할 수 있도록 변경했습니다. 이러면 변경 사항이 있을 때 마다 make~를 일일히 호출해주지 않아도 될 것 같습니다.

2024-06-03 07:43 UTC, aprilgom commented on app/src/main/java/woowacourse/shopping/presentation/ui/productlist/ProductListActivity.kt
> +    }
initPage의 메서드 명을 initViewModel로 바꿔주었습니다.

2024-06-03 07:54 UTC, aprilgom commented on app/src/main/java/woowacourse/shopping/presentation/ui/productlist/ProductListViewModel.kt
> +            }
repo쪽에서 처리를 해버리는 것도 괜찮을 것 같습니다. 주문과 상품이 이어진 무언가를 도메인에 만들어 주고 싶었지만 이름짓기가 어려워서 일단 viewModel에서 처리해주었습니다.

2024-06-03 08:26 UTC, aprilgom commented on app/src/main/java/woowacourse/shopping/presentation/ui/productlist/bindingadapter/OrderQuantityAdapter.kt
> +}
OrderState를 바로 입력받으며 hideIfCountLessThanZero를 사용할 수 없어졌습니다..
View를 보여주는 adapter와 숫자를 설정하는 adapter를 분리해주었습니다.

2024-06-03 08:39 UTC, aprilgom commented on app/src/main/res/layout/holder_counter.xml
> +    </data>
onPlusClickListener, onMinusClickListener, countNum으로 이름을 각각 바꾸어주었습니다.

2024-06-03 08:43 UTC, aprilgom commented on app/src/main/res/layout/activity_product_detail.xml
> +            hideIfRecentProduct="@{vm.product}"
hideIfRecent로 이름을 변경해주었습니다.

2024-06-03 11:51 UTC, ghojeong commented on app/src/main/java/woowacourse/shopping/presentation/ui/productdetail/ProductDetailViewModel.kt
> +        println(product.value)
어차피 다음 미션으로 넘어가야하기 때문에 굳이 수정을 요청하지 말아야지 했는데,
"잘못된 습관은 들이지 않는 것이 좋을 것 같습니다." 라고 답해주셔서 감사합니다.

저는 개발자의 성장이란 결국 피로 새겨진 경험으로부터 오는 습관이라 생각합니다.

> 거기에 data class도 찍어보려면 toString 붙여야되고, import도 해줘야되고.. 한두개 찍어보고 지우는데도 태그지정을 해줘야하고..

이건 제 개인 철학인데 번거로움을 이유로 잘못된 예외를 허용하기 시작하면,
그 스스로 허용하기 시작한 레벨이 곧 자신의 한계가 되리라 생각합니다.

빠르게 성장하고 빠르게 구현하는 것을 목표로 하는게 아니라,
더 잘하는 높은 경지를 목표로 한다면 차람이 말한대로 더 좋은 습관을 가지려 욕심을 낼 필요가 있다고 생각합니다.

제가 말씀드리기 전에 스스로 반성하신게 대견해서 언급을 해보았습니다.

2024-06-03 11:54 UTC, ghojeong approved these changes
차람!
쇼핑 주문 미션과 병행하기 무척 빡셌을 텐데,
마지막까지 성실하게 쇼핑 장바구니 미션의 피드백을 반영해셔서 감사합니다.
마지막 미션의 완주까지 화이팅입니다! 🔥

2024-06-03 11:54 UTC, merged