[쇼핑 장바구니] 벼리 3, 4단계 미션 제출합니다.
woowacourse/android-shopping-cart pull request #82
Opened 2024-05-26 15:32 UTC by gaeun5744

안녕하세요 제리! 이번 미션에 욕심을 내다가 너무 늦게 제출했네요.. 🤣🤣 
항상 좋은 코멘트 감사합니다!! 이번 3,4단계도 잘 부탁드립니다🥰

https://github.com/woowacourse/android-shopping-cart/assets/92314556/90cfc9cb-c21f-49f8-8dad-26e3c7d57cfe

2024-05-26 16:01 UTC, gaeun5744 reviewed
안녕하세요 제리! 이번 미션이 복잡한 만큼, 알아보기 힘드실까봐 구현에 집중했던 부분과 구현 이유를 코멘트에 남깁니다...!

2024-05-26 16:04 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/productdetail/ProductDetailActivity.kt
> +    }
데이터를 다시 로딩하지 않고, 새로운 activity를 실행한 이유는 anmation적인 부분 때문입니다..! 보통 마지막으로 본 상품을 클릭하면, 새로운 화면으로 이동할 것이라 기대한다고 생각하기 때문에 activity를 재활용하지 않고 새로 생성해 봤습니다!

2024-05-26 16:06 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListActivity.kt
> +            }
`PlusFail `은.. 저의 도메인 세계에서는 구매 개수 제한도 있어서 추가했습니다😎

2024-05-27 14:37 UTC, vagabond95 requested changes
그래도 기한내에 잘 미션을 마무리해주셨네요 👍 

전반적으로 상태와 이벤트를 구분하는 코멘트를 많이 남겼어요. 
이 부분에 대한 결정에 따라 코드가 많이 변경될 수 있는데, 다음 미션으로 인해 변경이 부담스러우시다면 생각을 코멘트로 남겨주셔도 좋습니다 :)

마지막까지 화이팅이십니다~!

2024-05-27 14:37 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/shoppingcart/uimodel/CartItemUiModels.kt
> +data class CartItemUiModels(
해당 클래스는 UiModel 이라고 부를 수 있을까요? ㅎㅎ
벼리가 생각하는 UiModel 의 정의는 무엇인지 궁금해요. (혼내는거 아님)

2024-05-27 14:37 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productlist/uimodel/LoadProductState.kt
> +sealed class LoadProductState() : UiState {
LoadProductState 와 하위 클래스들은 상태일까요? 이벤트일까요?

2024-05-27 14:37 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productlist/uimodel/LoadProductState.kt
> +    data class PlusFail(override val currentProducts: ProductUiModels) :
Plust 가실패를 했는데, currentProducts 를 상태로 가지고 있어요. 다음과 같은 의문이 듭니다!
- 실패를 했는데 왜 상태를 가지고 있어야할까? 실패 사유만 알고 있으면 되지 않을까?
- 설령 상태를 알고 있다고 하더라도, Plus 가 실패한 대상만 알고 있으면 되지 않을까? 전체 리스트를 알고 있어야할까?

2024-05-27 14:37 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productdetail/ProductDetailViewModel.kt
> +            val price = _countState.value?.countResult?.price ?: it.price
loadProductDetail 는 onCreate 에서 호출되므로, _countState 값이 없는 것이 자명하므로 MINIMUM_COUNT, it.price 를 바로      할당해줘도 되지 않을까요?

2024-05-27 14:37 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productdetail/ProductDetailViewModel.kt
> +            _countState.value =
_countState 는 상태일까요? 이벤트일까요?

2024-05-27 14:37 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productdetail/ProductDetailViewModel.kt
> +                is GetLastProduct.Success,
`,` 는 의도하신걸까요? ㅎㅎ

2024-05-27 14:37 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListActivity.kt
> +                if (isRecentChanged) viewModel.loadRecentProduct()
2가지 고민해볼 포인트가 보여요.

1. 각 Result 는 별개의 Activity 에서 전달이 되므로, Activity 타입으로 구별하여 처리하는게 좋지 않을까요?
2. Activity Result 에 대한 Intent 를 ProductListActivity 에서 책임지고 있는데, Result 는 실제로 Result 를 리턴한 곳에서 책임을 지는게 더 자연스럽지 않을까요? 가령, CHANGED_PRODUCT_ID 를 다른 Activity 에게 보내고 싶은 경우가 있더라도, 현재는 전혀 연관이 없는 ProductListActivity 와의 의존성이 생기게되는데 부자연스러운 구조인 것 같아요.

2024-05-27 14:37 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListViewModel.kt
> +            _loadState.value =
조금 지겨우시겠지만 ^^; 해당 loadState 는 상태일까요? 이벤트일까요?

2024-05-27 14:37 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListViewModel.kt
> +            val products = productIds.map { productRepository.productById(it) }
`productRepository.productById` 를 통해 products 를 또 불러올 필요가 있을까요?
해당 함수는 결과적으로  cartItems 가 변경되어 호출되는 함수이기에 cartItems 만으로 충분하고, 
uiModel 로도 Mapping 이 가능하도록 구현해주신 것 같아서요 ㅎㅎ

2024-05-27 14:37 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/domain/RecentProducts.kt
> +    fun lastRecentProduct(): GetLastProduct =
전반적으로 자주 보이는 패턴인데요,
코틀린에서 제공하는 Result API 를 활용하는게 아닌이상 예외 상황에서는 실패 상태를 전달하기보다 예외를 전달하는게 더 낫다고 생각해요. 상태의 경우 꼭 상태의 타입을 체크하지 않으면 실패했는지 알 수 없지만, 예외를 던지면 처리를 강제할 수 있니까요 :)

혹 Fail 이 예외상황이 아니라 요구사항 중 하나라면 네이밍이 변경되면 좋을 것 같습니다 ㅎㅎ

2024-05-27 14:37 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/util/SingleLiveData.kt
> +abstract class SingleLiveData<T> {
SingleLiveData 를 잘 찾아서 적용해주셨네요 👍 

그런데 활용되면 좋을 부분이 적용이 많이 안된 것 같습니다 ㅜ,ㅜ

SingleLiveData 는 MutableLiveData 에 비해 어떤 이점이 있고 어느상황에 활용하면 좋을까요?

2024-05-30 13:13 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListActivity.kt
> +            }
제가 코멘트를 모두 확인했다고 생각했는데 벼리가 남겨주셨던 내용이 따로 있었군요. 놓쳐서 죄송합니다 😿 

UDF 는 화면과 상태가 복잡해질 수록 더 빛을 발한다고 생각합니다. 👍 

현재는 의도대로 잘 구현해주신 것 같아요!

2024-05-30 13:18 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productdetail/ProductDetailActivity.kt
> +    }
이런 부분은 보통 프로젝트를 기획하는 부분에서 정의해주겠지만,
스스로 사용성을 고려하여 작업해주시는 것 좋습니다 👍

2024-05-30 13:28 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/shoppingcart/uimodel/CartItemUiModels.kt
> +data class CartItemUiModels(
안녕하세요 제리! 저도 구현하면서 애매했던 부분을 정확히 짚어주셨네요..

우선 `model`에 대한 저의 생각을 말씀드리자면, 미션을 하면서 저는 `model`이 너무나 다양한 범주에 속한다고 생각했습니다. 

![image](https://github.com/woowacourse/android-movie-theater/assets/92314556/b268fecc-0d6b-435c-bcbd-05943c908ff7)

해당 정의를 보았을 때, 저는 `maintaining data`가 3가지가 떠올랐습니다. 
1. RoomDB의 `Entity`
2. Ui 계층의 `UiModel` 
3. domain 계층의 `model` 

이렇게 3가지가 떠올랐습니다.

저는 3가지 다 `model` 이라고 생각하며, 데이터의 모습을 한 계층에 한정지어서 정의하는 것은 어렵다고 생각합니다..
그래서 `uiModel` 은 말 그대로 `UI 계층의 데이터 모습` 이라고 생각합니다!

이와 관련해서 다른 리뷰어와 생각을 주고받았던 코멘트가 있어서 [링크](https://github.com/woowacourse/android-movie-theater/pull/90#discussion_r1597620830)를 걸어둡니다

2024-05-30 13:56 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/productlist/uimodel/LoadProductState.kt
> +sealed class LoadProductState() : UiState {
### 질문 : **혹시 제리는 밑의 3가지 중 어떤 방법이 더 좋아 보이시나요? 밑의 구현 방법이 아니라 다른 선호하는 구현 방법이 있으신지도 궁금합니다!!**

사실 `uiModel`이 `Ui의 상태`와 직접적으로 연관이 있는 만큼, `Event`와 `State`에 대한 개념이 혼종되어 있다고 개인적으로 생각합니다. 그래서 이 부분은... 제가 명확히 어떤 것이다! 라고 정의를 내리기 어려운 부분이네요 😭

`LoadProductState`에서 `UiState`를 상속받은 이유는... 만약 로딩이 되고 있는 상태라면, 해당 `LiveData`를 `observing` 하고있는 `View`에게  **현재는 `Loading` 상태이다**. 를 전달하기 위해서 였습니다!

만약 앱에서 Loading 뷰가 추가될 경우, 구현 방식은 저에게 3가지가 생각났습니다.

1. 화면 전체 로딩  X, 특정 뷰에 대해 로딩 - `LoadProductState`에 `Loading`을 추가하는 경우
```
sealed class LoadProductState() : UiState {
    abstract val currentProducts: ProductUiModels

    data class ShowProducts( ...)

    data class Loading(....)
}

```

2. 화면 전체 로딩 X, 특정 뷰에 대해 로딩 -  isLoading 파라미터를 추가하는 경우
```
sealed class LoadProductState() : UiState {
    abstract val currentProducts: ProductUiModels
    abstract val isLoading = true

    data class ShowProducts(
        override val result: ProductUiModels,
        override val currentProducts: ProductUiModels,
         override val isLoading 
    ) : LoadProductState(),
        UiState.CompleteWithResult<ProductUiModels>


}

```

3. 로딩에 대한 뷰가, 특정 위젯이 아닌 **화면 전체**에 대한 로딩 뷰일 경우
   - uiState 상속 삭제
   - 해당 viewModel에 `isLoading LiveData` 구현



상품 리스트 뷰에서는, DB에서 가져오는 데이터가 많은 만큼, 3번은 아니라는 확신이 들었습니다.
그리고 1번과 2번 둘중 하나를 고르자면, 저는 1번이 가독성이 좋아서 1번을 선택했었습니다!

**혹시 제리는 위의 3가지 중 어떤 방법이 더 좋아 보이시나요? 위의 구현 방법이 아니라 다른 선호하는 구현 방법이 있으신지도 궁금합니다!!**

2024-06-02 05:49 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/shoppingcart/uimodel/CartItemUiModels.kt
> +data class CartItemUiModels(
두 방법의 차이점을 발견하고자 `viewModel` 내부에서 확장함수를 추가하여 구현해 보았습니다! 

제가 생각하는 해당 구현 방법의 장단점은

장점: Ui에 대한 비즈니스 로직이 `ViewModel`에 모여져 있으니 한 눈에 보기 편하다. 상세 로직을 보기 위해 `UiModel`에 이동할 필요가 없다.
단점: `ViewModel`에 내부에 메서드가 많아서 기능이 확장된다면 보기 불편할 것 같다.

라는 생각이 들었습니다..! 혹시 제리가 생각하는 해당 방법의 장단점은 무엇을까요?? 제리의 생각이 궁금합니다!!!😊😊

2024-06-02 08:18 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/productlist/uimodel/LoadProductState.kt
> +sealed class LoadProductState() : UiState {
3가지 모두 일시적인 사건에 해당하며, 이전의 결과값이 필요없기 때문에 이벤트라고 생각합니다..! 
해당 리뷰를 반영해서, Product가 바뀐 Event인 `ProductChangeEvent` 와 Product가 바뀌는 것에 실패한 Event인 `ProductChangeFailEvent`를 구현해보았습니다!!

2024-06-02 08:19 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/productlist/uimodel/LoadProductState.kt
> +    data class PlusFail(override val currentProducts: ProductUiModels) :
위의 코멘트와 같이, `Plus`가 현재 상태를 알 필요 없기 때문에 `ProductChangeFailEvent`를 따로 구현했습니다!

2024-06-02 12:56 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/productdetail/ProductDetailViewModel.kt
> +            val price = _countState.value?.countResult?.price ?: it.price
아 이부분은 `ProductListActivity`의 `initProduct`처럼,  configureation Change에서는 기존의 상태를 할당하기 위해 저렇게 만들었습니다..! 
다시 보니 그러면 불필요한 서버 통신을 하게 되네요ㅠㅠ MINIMUM_COUNT, it.price는 바로 할당하게 만들고, _count가 null 일 경우에만 서버통신을 하도록 코드를 수정했습니다!

2024-06-02 12:58 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/productdetail/ProductDetailViewModel.kt
> +            _countState.value =
바뀐 Count의 경우, 일회성이 아니라 계속 유지되어야 하는 상태이기 때문에 `State`라고 생각합니다!!

2024-06-02 12:59 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/productdetail/ProductDetailViewModel.kt
> +                is GetLastProduct.Success,
아ㅠㅠ 쉼표가 들어간줄 몰랐네요..! 바로 지웠습니다!!!

2024-06-02 14:50 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListActivity.kt
> +                if (isRecentChanged) viewModel.loadRecentProduct()
이를 구현하기 위해 `ResultActivity`라는 enum class를 만들어서, 각 Activity 타입별로 `registerForActivityResult`에 대한 분기처리를 했습니다! 

다만 구현을 해보니 다음과 같은 장단점이 보였습니다...!

---
**- 단점**

**1. startActivity의 `intent`와 registerForActivityResult의 `intent`처리 차이에서 발생하는에 혼란스러움** 


`startActivity`에서는 intent에 대한 책임을 리턴받는 곳에서 가지고 있습니다. 이와 반대로 `registerForActivityResult`에서는 intent에 대한 책임을 리턴하는 곳에서 가지고 있기 때문에 일관성이 없어서 개인적으로 혼란스러웠습니다! (**혹시 제리는 startActivity에 대한 intent의 책임도 리턴하는 곳에서 가지고 있나요....?**)

또한 개인적인 생각이지만,, 저는 `registerForActivityResult`를 구현하는 이유는, 리턴 받는  곳인 `ProductListActivity`의 뷰 업데이트 때문이기에  intent는 `ProductListActivity`의 책임이라 생각했습니다!


**2. 공통되는 로직의 반복**

변경된 product들의 id들을 `ProductListActivity`에 넘기는 로직은 `Cart`와 `Detail`에서 둘 다 사용되기 때문에, 반복되는 로직을 묶을 수 없다는 단점이 있습니다.


**- 장점**

**1. 기능 확장성**

기능이 확장됨에 따라 더 많은 update 로직과 화면이 증가할 때, 이러한 구현 방식은 유연하게 대처할 수 있어서 편리해 보였습니다!

2024-06-02 14:53 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListActivity.kt
> +                if (isRecentChanged) viewModel.loadRecentProduct()
만약 공통되는 로직이 없다면 저는 제리가 제안해주신 방법대로 구현 했을 것 같습니다!  이와 별개로 궁금한 점이 있습니다

### 혹시 제리는 어떠한 장점 때문에 1. Activity 타입별로 분기 처리와  2. 리턴 하는 곳에서 intent에 대한 책임을 가지도록 구현하는 방법을 생각하셨나요? 제리의 생각이 궁금합니다!!!

2024-06-02 14:57 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListViewModel.kt
> +            _loadState.value =
_loadState 내부를 보면 상태와 이벤트가 혼종되어 있기 때문에,,,  이 부분도 위의 코멘트와 같이 State와 Event를 분리했습니다!

2024-06-02 15:20 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListViewModel.kt
> +            val products = productIds.map { productRepository.productById(it) }
아 `productRepository.productById` 는 장바구니 뷰에서 삭제된 아이템에 대해 처리하기 위해 추가했습니다!!

예를 들어서, 장바구니 상품을 삭제하면 `shoppingRepository.cartItemsByProductIds(productIds.toList())` 에는 삭제된 장바구니를 제외하고 불려옵니다!

하지만 모든 products를 불러오는 것은 불필요하다는 생각이 들어서, 이미 불려온 CartItem에 대한 id는 제외하고 Product를 불러오도록 코드를 수정했습니다!!

```

runCatching {
            val cartItems = shoppingRepository.cartItemsByProductIds(productIds.toList())
            val products = productIds.filterNot { productId ->
                cartItems.map { it.product.id }.contains(productId)
            }.map { productRepository.productById(it) }

            products.map { product ->
                product.toProductUiModel(productOfCartQuantity(cartItems, product))
            }
        }.onSuccess 
```

2024-06-02 16:07 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/domain/RecentProducts.kt
> +    fun lastRecentProduct(): GetLastProduct =
이 부분은 [이펙티브 코틀린의 7장](https://augustin26.tistory.com/30)의 내용을 저 나름대로 적용해본 결과물 입니다...!

Failure 클래스는 총 3군데 사용했는데, 사용 이유는 각각 다음과 같습니다.

1. lastRecentProduct

최근에 가입한 유저는 최근 본 상품이 없을 수 있기 때문에, 비즈니스 로직에 해당하다고 생각해서  Failure을 반환했습니다! 다만 의미가 불명확 하다는 생각이 들어서 `NoRecentProduct`로 이름을 수정했습니다.

2. CartItem

해당 Failure는, 만약 cartItem이 없는 경우 분기처리를 하기 위해 추가했습니다! 만약 cartItem이 없으면 장바구니를 추가하고, cartItem이 있으면 수량을 수정하도록 로직을 만들었습니다!

다만,,, 해당 부분을 제외하고는, cartItem이 없을 때 에러를 터뜨리기 때문에... 적용이 너무 애매해서 해당 부분의 Failure를 삭제했습니다.

```
override fun addCartItem(shoppingCartItem: ShoppingCartItem) {
        val cartItem = cartItemDataSource.cartItemById(shoppingCartItem.product.id)
        if (cartItem == null) {
            cartItemDataSource.insert(
                ShoppingCartItemEntity(
                    shoppingCartItem.product.id,
                    shoppingCartItem.totalQuantity,
                ),
            )
        } else {
            cartItemDataSource.increaseCount(
                shoppingCartItem.product.id,
                shoppingCartItem.totalQuantity,
            )
        }
    }

```

3. QuantityUpdate

저는 상품마다 최소 구매 수량이 다르다고 생각했기 때문에, 1일 때 최소 수량 토스트 메시지를 보내는게 아니라 Fail 일 때 토스트 메시지를 보내도록 구현했습니다

다만 이 부분도 의미가 불명확하다는 생각이 들어서.. 더이상 수량을 변경할 수 없다는 의미로 `CantChange`로 네이밍을 수정했습니다!

2024-06-02 16:10 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/util/SingleLiveData.kt
> +abstract class SingleLiveData<T> {
DM으로도 말씀드렸지만... 제가 적용하는 기준을 제대로 세우지 못했었네요ㅠㅠㅠ 
LiveData는 onStart 시에 추적을 다시 시작하기 때문에 State 에서는 활용하기 좋지만, Event에서는 event가 중복되어 뷰에 전달됩니다

그래서 Event를 View에 전달할 때 주로 `SingleLiveData`사용한다고 생각합니다!!

2024-06-02 16:39 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListActivity.kt
>      }
로직에 대해 대략적으로 설명드리겠습니다..!

1. onCreate 에서 viewModel.initProducts() 메서드 호출 -> state가 init으로 변경 
2. 상품 더 불러오기, 상품 수량 변경 등의  Event 발생 -> state가 change로 변경
3. configuration Change 발생 
4. onCreate 콜백 호출 -> 다시 viewModel.initProducts() 메서드 호출 -> initProducts는, 기존 state가 null 이 아니면 서버통신을 안함 -> state가 init으로 변경 
5. 기존 상태로 adapter의 모든 item들이 replace 된다


........ configuration Change 때문에 `Change`와 `Init `상태를 추가했습니다 이 방법밖에 생각이 안 나네요 😂😂 
처음 보는 입장에서는 Change 상태일 때는 아무것도 안 하기 때문에 의문스러운 구조인 것 같습니다...

혹시... 여기서 어떻게 더 리팩터링을 하면 좋을지 힌트를 얻을 수 있을까요...?

2024-06-02 16:39 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/productdetail/ProductDetailViewModel.kt
> +    val isAddSuccess: SingleLiveData<Boolean> get() = _isAddSuccess
제리는 해당 `_isAddSuccess`에 대해 어떻게 생각하시나요?

이 부분에 대해서도 다른 크루들과 이야기를 나눴었는데, 서로의 생각이 달랐어서 제리에게 질문 드립니다..!

1. 벼리의 생각

`isAddSuccess`의 value가 true가 된다면, `ProductListActivity`로 이동하기 위해 구현했습니다!
저는 서버통신의 결과를 뷰에 반영하는 것은 오로지 View의 책임이라 생각했습니다. 장바구니에 상품을 담은 후, 토스트 메시지를 띄우든, 장바구니 뷰로 이동하든, 상품 목록 뷰로 이동하든 그것은 View의 책임이라 생각했습니다. 그래서 `isAddSuccess`를 추가했습니다. 또한 그래야 다른 뷰에서 해당 `ViewModel`을 활용하기 좋다고 생각했습니다.


2. 다른 크루들

반대로, 다른 크루들은 이러한 로직 또한 `ViewModel`의 책임이라 여겼습니다. 그래서 만약 장바구니 담기 로직이 성공하면, `navigateTo` 와 같은 `SingleLiveData`를 추가해서, sealed class를 이용해 어떤 뷰로 이동할 지를 정의할 것이라 생각했습니다.

혹시 제리는 서버 통신의 결과를 뷰에 업데이트 하는 것을 `View`의 책임이라 생각하시나요 아니면 `ViewModel`의 책임이라 생각하시나요?

2024-06-02 16:39 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListViewModel.kt
> +
이 부분도 보충 설명이 부족한듯 하여 코멘트로 남깁니다!!

uiModel을 업데이트하는 로직을 추가한 이유는, 서버통신을 최소화하여 뷰에 반영하기 위해서입니다!

원래의 정석적인 로직은 다음과 같다고 생각합니다

1. product 삭제 혹은 수량 변경 Event 발생
2. productId를 이용해 서버 통신을 하여, 변경된 결과물을 가져온다.
3. 뷰에 반영한다.

저의 로직은 2번의 과정을 생략했습니다! 만약 1번 서버통신이 통과된다면, 서버에 믿음을 가지고(?) 뷰에 업데이트 하기 위해 해당 로직을 추가했습니다

2024-06-02 16:59 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListActivity.kt
>      }
그리고 추가로 든 의문이 있습니다. **혹시 RecyclerView을 적용했을 때 더 이점인 상황이 있을까요?**

RecyclerView에 item을 효율적으로 업데이트 하기 위해 Product의 `Event`와 `State`를 나누고, 그 과정에서 수많은 로직이 추가되고 SSOT에서 멀어지는 것을 보면서 ListAdapter의 필요성을 더욱 느낄 수 있었습니다. 
아마 이번 미션을 마지막으로 저는 웬만한 상황에서는 ListAdapter를 적용할 것이라 생각합니다.. 
혹시 ListAdapter 대비 RecyclerView만의 장점이 있을까요? ListAdapter가 기본적으로 RecyclerView.Adapter를 확장한 클래스라서 큰 불편함을 느끼지 못하고 있기에 이렇게 질문 드립니다ㅠ

2024-06-02 17:03 UTC, gaeun5744 commented
안녕하세요 제리! 아마 원칙상 이번 리뷰요청에서 merge 될 것 같네요😭😭 개인적으로 제리한테 너무나 많이 배웠어서, 정말 감사했었습니다. 덕분에 가장 기본적인 부분을 짚고 넘어갈 수 있게 되었어요.. DM으로 자세히 설명해 주셔서 정말 감사했었습니다!!


마지막으로, 질문이 많은 만큼 보기 힘드실까봐 질문들을 링크로 모아 이렇게 코멘트를 남깁니다.

https://github.com/woowacourse/android-shopping-cart/pull/82#discussion_r1623331870
https://github.com/woowacourse/android-shopping-cart/pull/82#discussion_r1623465941
https://github.com/woowacourse/android-shopping-cart/pull/82#discussion_r1623523559
https://github.com/woowacourse/android-shopping-cart/pull/82#discussion_r1623567443
https://github.com/woowacourse/android-shopping-cart/pull/82#discussion_r1623525447

2024-06-03 14:00 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/shoppingcart/uimodel/CartItemUiModels.kt
> +data class CartItemUiModels(
너무 좋은 방법 같은데요?!

단점은 딱히 안보이는 것 같아요.
다만, 저라면 extension function 을 viewModel 의 외부, 다시말해 ShoppingCartViewModel 파일내에는 있지만 ViewModel class 의 외부 영역에 선언해줬을 것 같아요. 이렇게해도 ShoppingCartViewModel 파일 내에서만 접근이 가능하고 ViewModel 코드에 더 집중하기 쉬워지니까요 :)

2024-06-03 14:12 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListActivity.kt
> +                if (isRecentChanged) viewModel.loadRecentProduct()
우선 용어가 헷갈리니 먼저 정리를 해야할 것 같네요 ㅎㅎ;
Intent 는 StartActivity - Intent, ActivityResult - Intent 2가지가 있고 각각을
S(tart) Intent, R(esult) Intent 라고 부를게요.

저는
S Intent 에 대한 책임은 startActivity 를 호출하는 Acitivty, 
R Intent 에 대한 책임은 result 를 세팅하는 Activity 에 있다고 생각합니다.

이렇게 생각하는 이유는 `Activity 는 본인이 start 를 시킬 Activity 는 알 수 있지만, 어떤 Activity 가 본인을 start 시킬지는 알 수 없기 때문` 입니다.

따라서 A -> B 로 acitivty 를 start 를 한다고 했을 때, A 가 B activity 에 대해 의존성을 가지는 것은 자연스럽습니다. 그렇기 때문에 R Intent 에 대한 key 를 A 가 가지고 있더라도 자연스러운 것이구요.

반면, 벼리의 코드는 구현 형태만 바뀌었을 뿐 초기 구현과 방향성이 똑같은 것 같아요.
A -> B 구조일 때, B 가 A 의 존재를 미리 알고 있습니다.

이것이 현재는 문제가 되지 않을 수 있는데, 만약 B 를 start 하는 activity 가 50개라면 B 는 50개의 Activity 에 대한 의존성이 생기게 됩니다.

따라서 S Intent 에 대한 책임과 R Intent 에 대한 책임을 각각 직접 액션을 수행하는 쪽에서 가진다고 가이드를 드리고 싶었습니다. :)

2024-06-03 14:14 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListActivity.kt
>      }
ProductUiState 는 별도 코멘트로 남겨보겠습니다~!

2024-06-03 14:16 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListActivity.kt
>      }
ListAdapter 와 RecyclerView 는 비교대상이 잘못된 것 같아요.

RecyclerView 는 UI 요소이고, Adapter 는 RecyclerView 의 데이터를 관리하는 클래스입니다. 그리고 Adapter 내에서 
- 기본 Adapter
- ConcatAdapter
- ListAdapter

등이 갈리는 것이구요.

혹, 기본 Adapter 대비 ListAdapter 가 단점이 있냐고 물으신 것이라면 없습니다. ListAdapter 가 애초에 기본 Adapter 의 단점을 보완하여 나온 것이기 때문입니다.

다만, ListAdapter 를 미션차원에서 금지한 것은 왜 ListAdapter 가 나왔고 ListAdapter 없이 효율적인 notify 를 처리하는 것이 얼마나 어려운지를 경험하기 위한 의도였다고 생각됩니다 ^^;

2024-06-03 14:29 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productdetail/ProductDetailViewModel.kt
> +    val isAddSuccess: SingleLiveData<Boolean> get() = _isAddSuccess
해당 코드가 논쟁의 여지가 생기는 것은 `업데이트 결과를 뷰에 반영`하는 행위가 모호하기 때문인데요. 사실 정답이 없는 부분입니다. 저희팀에서도 여러번 논쟁했던 부분이구요 ^^;

팀 정책을 따라가는게 제일 좋지만, 저의 논리를 펼쳐볼테니 벼리가 설득이 되는지 한번 들어주세요!

이전 미션에서도 들어보셨을지 모르겠지만, 저는 View 가 멍청할 수록 좋다고 생각합니다.
이유는 많은 책에서도 그렇게 얘기하고 있고, 실제 경험으로도 그것이 유지보수하기 좋았습니다. 

View 가 멍청하다는 것은 다시 얘기하면, `정말 View 에서 할수밖에 없는 일들만 하자!` 라는 것을 의미합니다.

```
                viewModel.updateRecentProduct(productId)
                val intent =
                    Intent(this, ProductListActivity::class.java).apply {
                        putExtra(CHANGED_PRODUCT_ID, longArrayOf(productId))
                        putExtra(IS_RECENT_CHANGED, true)
                        putExtra(ACTIVITY_TYPE, ProductListActivity.ResultActivity.DETAIL.ordinal)
                    }

                setResult(RESULT_OK, intent)
                finish()
```

벼리의 코드를 예로들자면 isSuccess 가 true 일 경우 2가지 일을 수행하고 있습니다.

1. updateRecentProduct 호출
2. startActivity

1번은 view 가 아니어도 할 수 있습니다.
2번은 view 혹은 Acitivity 에서만 가능한 일이죠.

물론 벼리가 작성한 코드도 문제가 있는 것은 아닙니다. 그런데 저는 (개인적으로) 다음과 같은 상황을 싫어합니다.

벼리가 같은 팀원이고 `ProductDetailActivity` 화면을 새로 작성하여 코드 리뷰를 진행했습니다. 그런데 저는 해당 화면에 대한 구현을 알지 못하므로 어떻게 로직이 진행되는지 알기 위해 ViewModel 을 살펴보았습니다. 그런데 살펴보니, Recent product 가 어떻게 갱신되는지를 찾지 못했습니다. 알고보니 Activity 에서 updateRecentProduct 을 제어하고 있었습니다.

즉, 코드를 이해하는 컨텍스트가 끊기는 상황인데요. 이런 경우가 하나면 상관이 없지만 복잡한 화면의 경우 금방 flow 가 스파게티가 되곤합니다. vm -> activity -> vm -> activity ...

정리하면,
1. activity 가 (혹은 view 가) activity 에서만 할 수 있는 일 외의 일을 하기 시작하면 코드의 흐름을 이해하기 어렵다.
2. 코드 흐름의 컨텍스트가 끊기는 것은 코드를 이해하기 어렵게 만든다.
입니다.

벼리가 어느정도 설득이 되었을지 모르겠네요 ㅎㅎ

2024-06-03 14:31 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListViewModel.kt
> +
이부분은 세부 요구사항에 따라 달라질 것 같아요.

최신성이 중요하다면 매번 API 에 의존하도록 할 것이고, 비용 관리가 더 중요하다면 벼리가 작성한 것처럼 로컬기반으로 동작하도록 구현하겠죠 ㅎㅎ

2024-06-03 14:46 UTC, vagabond95 approved these changes
두가지 미션 진행이 쉽지 않았을 텐데 정말 고생 많으셨어요!

많은 고민 후 질문들을 남겨주신 것 같아, 저도 열심히 고민후 답변을 남겼습니다 :)

해당 미션에서 조금이라도 얻어간 것이 있으셨길 바라며 마지막까지 화이팅이십니다~!

2024-06-03 14:46 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/shoppingcart/ShoppingCartActivity.kt
> +        if (viewModel.changedProductIds.isEmpty()) {
https://github.com/woowacourse/android-shopping-cart/pull/82#discussion_r1624563173
코멘트와 같은 맥락으로 activity 에서 인텐트를 생성하고, data 를 가져올 수는 있지만
무엇인가를 판단하기 시작하면 비즈니스 로직이 view 에 섞여 view 와 viewModel 모두를 항상 확인해야하는 일이 생길 것 같아요.

2024-06-03 14:46 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productlist/uimodel/ProductUiState.kt
> +sealed interface ProductUiState {
우선 해당 interface 는 상태와 event 가 섞인 것 같아요. 그래서 벼리가 헷갈려하는 것 같구요.

event 라고 판단한 이유는 사실상 Init 을 제외한 나머지는 `currentProducts` 를 활용하고 있지 않기 때문이에요.
상태라고 판단한 이유는 viewModel 에서 currentProducts 를 참조하고 있기 때문인거구요.

두가지 속성이 애매하게 섞여있어서, currentProducts 가 필요없는 Error 나 Loading 도 currentProducts 를 가지고 있게 되고 
Change 라는 이벤트에 대응되는 동작이 없는 현상이 발생하는 것 아닐까요?

마지막인만큼 힌트를 드려보면,
currentProducts LiveData 와
productLoadEvent SingleLiveData 로 분리되는게 더 적절해보입니다!

2024-06-03 14:46 UTC, vagabond95 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListViewModel.kt
> +    private fun List<ProductUiModel>.updateProducts(updatedProducts: List<ProductUiModel>): List<ProductUiModel> =
extension function 을 도입한 시도는 좋았어요! 
그런데 실제로 함수 내부에서 `this` 를 사용하지 않기 때문에 사실상 일반 함수로 정의해도 될 것 같아요 ^^;

2024-06-03 14:46 UTC, merged

2024-06-13 13:00 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/productlist/ProductListActivity.kt
>      }
아!! 제가 용어를 헷갈렸네요.. 제가 질문했던 부분은 기본Adapter과 ListAdapter의 차이입니다!!

2024-06-13 13:02 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/productdetail/ProductDetailViewModel.kt
> +    val isAddSuccess: SingleLiveData<Boolean> get() = _isAddSuccess
결국 UDF와 관련된 부분이었군요..! 😂😂
1번의 로직을 viewModel 내부에서 수행할 수 있도록 수정하겠습니다!!!