[쇼핑 장바구니] 채채 3, 4단계 미션 제출합니다.
woowacourse/android-shopping-cart pull request #84
Opened 2024-05-26 19:48 UTC by chaehyuns

### 안녕하세요 제이든 👋🏻
이번 3, 4 단계 미션을 하면서 기능 요구사항이 저에게는 굉장히 까다롭게 느껴져서 이제서야 리뷰 요청을 드리네요 🥹

shoppingItem Repository 와 cart Repository가 비슷한 일을 많이 하게 되고 통합이 되도록 로직을 이리저리 수정하다보니,
중복되거나 불필요한 로직이 생겨나진 않았을까 하는 생각에 걱정이 드네요..! 

### 위에서 말씀드렸다싶이 제가 고민되는 부분들을 말씀드리도록 하겠습니다!
1. shoppingItem와 cart의 역할 분리가 잘되고 있는지 궁금합니다.
2. ShoppingAcitivity나 다른 Activity의 viewmodel이 repository를 많이 가지고 있게 설계되었는데, 그에 따라 viewmodel의 책임이 많아 지게되었고 가독성이 점점 떨어진다는 생각이 들게 되었습니다. 
3. 재활용은 어디까지 해야하는지 궁금합니다. 현재는 카트의 수량을 조절하는 똑같은 view가 3개 존재하고 있습니다. 
    그런데, shopping과 detail activity에서는 같은 ProductWithQuantity 객체를 사용하지만 cart activity 에서는 Cartitem을 사용하고 있습 
   니다. 상품을 보여주기 위한 갯수와 카트에 담긴 아이템을 조절하는 것dl 다르게 설계되어있어 cart activity에서는 재활용을 하고 있지 않게 구현했습니다. 이런 경우에도 일관적으로 ProductWithQuantity 객체를 사용하여 카트 아이템들을 보여주는 것이 더 나은 방안일까요?

### 시연 영상
https://github.com/woowacourse/android-shopping-cart/assets/80222352/7eff1a4e-a07c-457d-a66b-bdc6a9f34c57

### 유의 사항
현재 미션 시간이 임박해서 mock server을 사용한 detail view model test 코드가 정상적으로 돌아가고 있지 않습니다. 추후 test 코드를 보완하겠습니다!

2024-05-27 04:01 UTC, chaehyuns commented on app/src/main/java/woowacourse/shopping/data/repository/DummyShoppingItemsRepository.kt
> +    }
이런식으로 작성한다면 DummyShoppingItemsRepository에서 인스턴스를 생성할때 마다 더미 shopping item의  insert를 매번 해주는 문제가 발생하는 것 같습니다. DataBase에서 생성될때 insert해주는 방법도 시도해봤는데, 동작하지 않아서 위와 같이 코드를 작성했습니다. 혹시 바꿀 수 있는 방안을 추천해주실 수 있으실까요? 😵‍💫

2024-05-27 04:39 UTC, chaehyuns commented on app/src/main/java/woowacourse/shopping/data/repository/DummyShoppingItemsRepository.kt
> +    }
애플리케이션 수준에서 싱글톤으로 관리하는 식으로 변경하는 방법으로 변경하겠습니다! 

```
companion object {
        @Volatile private var instance: DummyShoppingItemsRepository? = null

        fun getInstance(context: Context): DummyShoppingItemsRepository =
            instance ?: synchronized(this) {
                instance ?: DummyShoppingItemsRepository(AppDatabase.getInstance(context)).also { instance = it }
            }
    }
```

```
class ShoppingApplication : Application() {
    val appDatabase: AppDatabase by lazy { AppDatabase.getInstance(this) }
    val shoppingItemsRepository: DummyShoppingItemsRepository by lazy { DummyShoppingItemsRepository.getInstance(this) }

```

2024-05-27 08:38 UTC, KwonDae requested changes
3,4 단계 구현을 잘 해주셨습니다!
한번 더 수정해보고 피드백을 드릴 수 있도록 빠르게 코멘트를 남겨드렸습니다.
확인 후 요청 부탁드립니다!

2024-05-27 08:38 UTC, KwonDae commented on app/src/main/java/woowacourse/shopping/data/repository/DummyShoppingItemsRepository.kt
> +    }
Database를 Build하는 곳에서 callback을 통해 사전에 데이터를 채울 수 있는데요,
Activity처럼 Database에도 [onCreate](https://developer.android.com/reference/androidx/room/RoomDatabase.Callback#onCreate(androidx.sqlite.SQLiteConnection))가 존재합니다.

이 [예제](https://hanyeop.tistory.com/221)를 참고해보셔도 좋을 것 같아요!

2024-05-27 08:38 UTC, KwonDae commented on app/src/main/java/woowacourse/shopping/data/repository/DummyShoppingItemsRepository.kt
> +class DummyShoppingItemsRepository(database: AppDatabase) : ShoppingItemsRepository {
repository를 local, remote 성격에 맞게 패키지를 구분하여 잘 해주셨습니다.
다만, 조금 더 나아가면 repository 는 안드로이드의 Data Layer에서 앱에게 데이터를 제공하는 역할을 합니다.
지금처럼 앱에서 데이터가 필요하면 반드시 repository를 거쳐서 가져와야만 하죠.

![image](https://github.com/woowacourse/android-shopping-cart/assets/33443660/a4e052d5-7bb8-4880-b0bf-e6e018bb39f8)
[공식문서](https://developer.android.com/topic/architecture/data-layer?hl=ko#architecture)에서의 데이터 레이어의 모습은 이렇습니다.

[네이밍 가이드](https://developer.android.com/topic/architecture/data-layer#naming-conventions)는 
data + Repository = ProductRepository
source + DataSource = ProductRemoteDatasource or ProductLocalDataSource

와 같이 내용을 보면 repository는 하나의 데이터 타입에 대한 정보를 제공을 하고, 어떻게 가져올건지는 DataSource를 통해 결정되게 됩니다.
위 내용을 참고하여 개선해볼 수 있을까요?

사실 이 관점에서 보면 repository 입장에서는 ProductRepository 하나만 존재해도 될 것 같다는 생각이 듭니다.

또는, ProductRepository 하나만으론 너무 복잡할 것 같다면
[Multiple levels of repositories](https://developer.android.com/topic/architecture/data-layer#multiple-levels) 를 읽어보셔도 감을 잡는데 도움이 될겁니다.

2024-05-27 08:38 UTC, KwonDae commented on app/src/main/java/woowacourse/shopping/presentation/ui/shopping/adapter/ShoppingAdapter.kt
> +) : RecyclerView.Adapter<RecyclerView.ViewHolder>() {
이제 화면간 데이터 싱크를 맞추기 위해 이동할 때 데이터 갱신을 해야하는 일이 빈번하게 발생할겁니다.
그렇다면 변경이 있는 아이템에 대해서만 업데이트를 할 수 있다면 좋을텐데요.
이번 기회에 [ListAdapter](https://developer.android.com/reference/androidx/recyclerview/widget/ListAdapter)를 활용해보고, 어떤 차이점이 있는지 알아볼까요?

2024-05-27 08:38 UTC, KwonDae commented on app/src/main/java/woowacourse/shopping/presentation/ui/shopping/ShoppingActivity.kt
> +                        ?: emptyList()
장바구니 화면을 다녀온 뒤 최근 본 상품 목록은 무조건 갱신하지만,
`EXTRA_KEY_MODIFIED_PRODUCT_IDS` 이라는건  아무래도 수량을 업데이트 하는 로직이겠죠?

지금은 전달해야 하는 데이터의 양이 적고 종류도 얼마 안돼서 괜찮지만,
데이터의 양이 크고 복잡하다면 관리하기가 힘들어질거에요.
사실 이런경우엔 어떤 화면을 갔다 왔는지에 따라서 데이터 타입에 해당하는 API/DB를 다시 조회하는게 더 정확하기도 하죠.

어떤 데이터를 수정해야 하는지 담아서 보내는것도 방법 중 하나겠지만,

화면들간에 연계가 되어 있어 데이터 sync를 위해서 여러 방법들이 있습니다.

1. 화면들간 intent 의 bundle에 업데이트된 데이터 넘기기
2. 화면 전환 콜백으로 해당되는 데이터를 재호출하여 갱신하기

1번은 데이터의 종류가 다양해지고 양이 커질수록 관리하기가 힘들어 집니다.
그렇다면 2번은 데이터가 변하지도 않았는데 호출하면 낭비가 될 수 있지 않을까요? 라고 생각하실 수 있습니다.
실제로 그정도의 리소스는 얼마든지 투자할 수 있고 감당할 수 있는 부분이라고 현업에서도 많이들 다루곤 합니다.
또는, 어떤 종류의 데이터가 변했으니 해당 데이터 갱신이 필요하다 정도의 type만 넘겨받아도 좋겠네요.

2024-05-27 08:38 UTC, KwonDae commented on app/src/main/java/woowacourse/shopping/data/repository/InMemoryCartRepository.kt
> +class InMemoryCartRepository(database: AppDatabase) : CartRepository {
[inMemoryDatabaseBuilder](https://developer.android.com/reference/android/arch/persistence/room/Room#inmemorydatabasebuilder) 와 비슷한 역할인줄 기대했으나 아닌거 같네요..?

남겨드린 repository의 내용과 네이밍에 대해서 읽어보시고 개선해도 좋을 것 같습니다!

2024-05-27 08:38 UTC, KwonDae commented on app/src/test/java/woowacourse/shopping/presentation/ui/shopping/ShoppingViewModelTest.kt
> +//    fun `처음 상품 목록을 부를 때 오류가 있다면 Error 상태로 변경한다`() {
덕분에 디버깅을 하게 되었는데요 ㅎㅎ.. 
위 이슈를 해결하기 위해 어떻게 디버깅을 할 수 있을지 고민해보시는걸 추가 과제로 드릴게요.
디버깅은 안드로이드 개발하는데 있어 굉장히 중요합니다.

일단 힌트는 `findProductWithQuantityItemsByPage` 의 구현체에 있습니다.
Test 에서 shoppingRepository에 어떤 구현체를 주입해주었고,
해당 구현체의 `findProductWithQuantityItemsByPage`은 어떻게 구현되어 있었는지 살펴보시면 바로 이유를 아실거에요.

2024-05-27 15:40 UTC, KwonDae commented on app/src/main/java/woowacourse/shopping/presentation/ui/shopping/ShoppingViewModel.kt
> +    private val recentlyViewedProductsRepository: RecentlyViewedProductsRepository,
> ShoppingAcitivity나 다른 Activity의 viewmodel이 repository를 많이 가지고 있게 설계되었는데, 그에 따라 viewmodel의 책임이 많아 지게되었고 가독성이 점점 떨어진다는 생각이 들게 되었습니다.

우려하고 계신 부분을 저도 공감합니다.
어떤 이유로 위와 같은 고민을 하게 되었을까요?
아마도 비슷한 기능을 하는 repository의 존재라고 생각하는데요, 제가 남겨드린 공식문서의 repository 가이드를 보면
`type of data + Repository` 로 가이드하고 있습니다.

어떤 이유일까요? 위의 예시를 들어보면 사실 ShoppingViewModel은 관심사는 크게 아래와 같습니다.
1. 상품리스트 호출
2. 최근 본 상품
3. 장바구니에 담긴 상품 개수

모두 '상품' 이라는 data type과 '장바구니에 담긴 상품' 라는 data type을 둘 수 있겠네요.
전시되는 상품과 장바구니 상품을 다르게 본다면 말이죠.

그렇다면 ShoppingViewModel 에서는 ProductRepository, CartRepository 두가지를 갖고 비즈니스 로직을 구성할 수 있을 것 같아요.

2024-05-27 15:47 UTC, KwonDae commented on app/src/main/java/woowacourse/shopping/presentation/ui/shopping/ShoppingViewModel.kt
> +        }
통신 또는 db를 조회하는 로직을 수행할 때 repository 반환값을 Result로 사용해보는건 어떨까요?
그렇다면 
```kotlin
shoppingRepository.productWithQuantityItem(productId)
   .onSuccess { _updatedProduct.postValue(UiState.Success(..)) }
   .onFailure {  _updatedProduct.postValue(UiState.Error(it) }
```

ViewModel 내부에서 Exception을 발생시키기 보다, Repository의 반환값을 Result로 설정함으로써 어떤 값을 기대할 수 있는지 가시성이 좋게 구조를 만들 수 있습니다.

2024-05-27 15:48 UTC, KwonDae commented on app/src/main/java/woowacourse/shopping/presentation/ui/shopping/ShoppingViewModel.kt
> +    private val recentlyViewedProductsRepository: RecentlyViewedProductsRepository,
또한, 비대해졌다고 느낄 수 있는 부분은 `UiState`에 관련된 데이터들이 각각 분리되었던 점을 볼 수 있습니다.
`_isProductListEmpty`, 
`_isRecentlyViewedEmpty`, 
위 두개는 `Activity`에서 observe로 내려오는 List의 empty 상태에 따라 recyclerview를 보여줄 것인지, 아니면 빈 화면을 보여줄 것인지 결정할 수 있기에 상태로 갖고 있지 않아도 된다고 생각해요.

`_totalCartItemsCount`, 는 UiState에서 함께 관리해보는건 어떨까요? 장바구니 상품 개수라는게 Ui에 표시하기 위함이니까요.

이런식으로 UiState에 관련된 값들은 UiState에서 함께 관리하고, 과연 이 모두를 LiveData로 관찰해야 하는가? 에 대해서도 고민해보시면 좋겠네요 👍

2024-05-27 16:17 UTC, KwonDae commented on app/src/main/java/woowacourse/shopping/domain/model/ProductWithQuantity.kt
> +data class ProductWithQuantity(
> 재활용은 어디까지 해야하는지 궁금합니다. 현재는 카트의 수량을 조절하는 똑같은 view가 3개 존재하고 있습니다.
> 그런데, shopping과 detail activity에서는 같은 ProductWithQuantity 객체를 사용하지만 cart activity 에서는 Cartitem을 사용하고 있습니다. 상품을 보여주기 위한 갯수와 카트에 담긴 아이템을 조절하는 것dl 다르게 설계되어있어 cart activity에서는 재활용을 하고 있지 않게 구현했습니다. 이런 경우에도 일관적으로 ProductWithQuantity 객체를 사용하여 카트 아이템들을 보여주는 것이 더 나은 방안일까요?

Shopping, DetailActivity, CartActivity 3군데에서 상품을 취급하는게 다를까요?
현재 고민이 되는 부분은 '상품 + 개수' 일거에요.
상품에 개수가 포함되는 값은 아니니까요. 다만 Cart에서는 포함될거에요.

그렇다면, ProductUiModel 이라는걸 활용해보면 어떨까요?
ShoppingActivity, DetailActivity에서 ProductWithQuantity 도메인 모델이 필요하게 된건 결국 '개수' 때문입니다.

개수는 사실 Ui에 보여주기 위한 값일 뿐 API에서 내려오거나 저장하기 위한 용도는 아니었을거에요.
그렇다면 예를 들어, 모두 API에서 호출을 하게 된다면 ProductRepository, CartRepository 에서 호출하는 결과값을 조합하여 ProductWithQuantity 를 만들어 ShoppingViewModel 과 DetaiViewModel 에게 보내게 되겠죠.

**결국엔 ProductWithQuantity이 UiModel 역할을 하고 있었을 뿐 다른점은 없는데요, 굳이 필요하지 않은데 UiModel(ProductWithQuantity) 을 만들어 사용할 필요는 없다고 개인적으로 생각합니다 :)**

2024-05-27 16:20 UTC, KwonDae commented on app/src/main/java/woowacourse/shopping/presentation/ui/shopping/viewholder/ShoppingItem.kt
> +sealed class ShoppingItem {
> shoppingItem와 cart의 역할 분리가 잘되고 있는지 궁금합니다

지금은 상품리스트 화면과 장바구니 에서 보여주는 데이터가 크게 다르지 않아 혼동이 오신거 같아요.
만약 상품리스트의 상품들에게 보여주어야 하는 스티커 혹은 다른 Ui가 있다면 장바구니와는 전혀 다른 역할을 하는 모델이 될겁니다.
지금은 ShoppingViewModel의 로직들만 정리가 되고 repository가 data type별로 분리가 된다면 보다 명확해질거라고 생각합니다 👍

2024-05-27 16:21 UTC, KwonDae commented on app/src/main/java/woowacourse/shopping/data/repository/DummyShoppingItemsRepository.kt
> +        }
참고로 thread를 repository에서 처리해주신건 정말 잘해주셨습니다 💯

2024-05-27 21:14 UTC, chaehyuns commented on app/src/test/java/woowacourse/shopping/presentation/ui/shopping/ShoppingViewModelTest.kt
> +//    fun `처음 상품 목록을 부를 때 오류가 있다면 Error 상태로 변경한다`() {
아...!! 감사합니다! 원인을 바로 찾았습니다! mock server 관련해서 setResponseCode에 따른 추가 구현이 필요한줄 알았는데, 제가 null을 반환하고 있었군요,,,,,,,,,,,,,,,,,,,,,,,

2024-05-27 21:22 UTC, chaehyuns commented on app/src/main/java/woowacourse/shopping/data/repository/DummyShoppingItemsRepository.kt
> +    }
헉 그렇군요!! 예제 감사드립니다! 
onCreate 에서 insert하는 형식으로 변경하였습니다!

아래와 같이 코드를 변경하였습니다!
```
Room.databaseBuilder(
                    context.applicationContext,
                    AppDatabase::class.java,
                    "shopping_database",
                ).addCallback(
                    object : RoomDatabase.Callback() {
                        override fun onCreate(db: SupportSQLiteDatabase) {
                            super.onCreate(db)
                            thread {
                                getInstance(context).productDao().insertProducts(DummyShoppingItems.items)
                            }
                        }
                    },
                ).build().also { instance = it }
```

2024-05-27 21:28 UTC, chaehyuns commented on app/src/main/java/woowacourse/shopping/presentation/ui/shopping/ShoppingActivity.kt
> +                        ?: emptyList()
화면 전환 콜백으로 해당되는 데이터들을 모두 호출해야한다는 것이 비효율적으로 느껴져서 위와 같이 상품들의 id값을 통해서 변경을 업데이트 하려했습니다!
하지만, 어떤 종류의 데이터가 변했으니 해당 데이터 갱신이 필요하다 정도의 type만 넘겨받아서 필요한 경우에 호출을 한다면 어느 정도의 효율성을 보장할 수 있고 데이터의 종류가 다양해거나 요구사항이 변동되었을 때 충분하게 대응할 수 있는 방안이 될 수 있군요!! 좋은 인사이트 감사합니다 😊

2024-05-27 21:31 UTC, chaehyuns commented on app/src/main/java/woowacourse/shopping/presentation/ui/shopping/adapter/ShoppingAdapter.kt
> +) : RecyclerView.Adapter<RecyclerView.ViewHolder>() {
ListAdapter는 RecyclerView.Adapter를 확장하여 보다 효율적인 데이터 업데이트를 가능하게 하는 클래스이군요!
ListAdapter는 데이터 변경을 감지하고, 변경된 부분만 업데이트하여 제가 따로 구현을 하지 않아도 성능상의 이점을 가지기 때문에 더 효율적이라는 생각이 드네요! list adapter로 변경하겠습니다. 감사합니다!

2024-05-28 12:32 UTC, chaehyuns commented on app/src/main/java/woowacourse/shopping/presentation/ui/shopping/ShoppingViewModel.kt
> +        }
리포지토리 반환 값에 Result를 사용한다는 생각은 못했는데, 예외 없이 성공 및 실패 상태를 보다 명확하게 처리할 수 있을 것 같습니다! 
코드를 수정했습니다. 감사합니다!

2024-05-28 12:39 UTC, chaehyuns commented on app/src/main/java/woowacourse/shopping/presentation/ui/shopping/ShoppingViewModel.kt
> +    private val recentlyViewedProductsRepository: RecentlyViewedProductsRepository,
`_isProductListEmpty,`
`_isRecentlyViewedEmpty,`
와 같이 visible을 설정하는데 데이터 바인딩을 꼭 사용해야한다는 강박이 생겼던 것 같습니다! 
그래서 그런지 LiveData 변수들이 너무 많아져서 코드가 복잡해보이는 것을 피할 수 없었습니다.
`Acivity`에서 설정을 해줘도 괜찮은 거였군요! 상태 관리를 더 단순화하고 코드의 일관성을 유지하는 데 도움이 될 것 같습니다 😊
모두를 LiveData로 관찰해야하는가에 대한 고민이 꼭 필요할 것 같습니다! 
Event 클래스를 사용하면 일회성 이벤트를 처리도(현재 저의 기능에서는 페이지 이동이나 토스트 메시지) 고민해 볼 수 있을 것 같습니다!

2024-05-28 12:42 UTC, chaehyuns commented on app/src/main/java/woowacourse/shopping/presentation/ui/shopping/ShoppingViewModel.kt
> +    private val recentlyViewedProductsRepository: RecentlyViewedProductsRepository,
> 그렇다면 ShoppingViewModel 에서는 ProductRepository, CartRepository 두가지를 갖고 비즈니스 로직을 구성할 수 있을 것 같아요.

저도 최근 본 상품을 다른 repository로 설정해야하는지 아니면 상품 repository로 합쳐야하는지에 대한 고민을 계속 하게 되었는데요. 제이든의 `type of data + Repository` 코멘트로 인해서 저에게 좀 더 명확한 기준이 생기게 된 것 같습니다! 정말 감사합니다

2024-05-31 07:35 UTC, chaehyuns commented on app/src/main/java/woowacourse/shopping/domain/model/ProductWithQuantity.kt
> +data class ProductWithQuantity(
UiModel을 활용하는 것도 다양한 데이터를 한번에 처리할 수 있는 방법이  될 것 같습니다...!
저도 리팩토링을 진행하면서 Ui model로 변환을 하려고 했는데, 이미 repository에 로직이 너무 많은 시간이 필요해서 수정하지 못했습니다. 제이든께서 긴 글 남겨주신 덕분에 저의 의견 확립에도 도움이 된 것 같습니다! 감사합니다 제이든!

2024-05-31 07:38 UTC, chaehyuns commented
### 안녕하세요 제이든! 👋🏻
오랜만에 인사드립니다. 최대한 오늘 끝낸다고 디엠을 드렸는데, 새로운 미션을 진행하면서 시간이 너무 너무 부족했네요 🥹
UiModel을 따로 두거나 repository를 대대적으로 수정하고 싶었는데, datasource 를 분리하는 것으로도 시간이 꽤나 걸려서 여기까지 마무리하고 리뷰 요청 드립니다..! 

제이든이 repository 에 대한 내용을 길게 적어주신 덕분에 앞으로 안드로이드에서 repository를 만들때 어떠한 기준을 잡고 개발을 해야할지에 대한 기준이 생긴 것 같습니다! 꼼꼼하게 리뷰해주셔서 정말 감사합니다!

2024-05-31 13:25 UTC, KwonDae approved these changes
끝까지 피드백 반영을 잘 해주셨습니다.
현재 진행중인 미션에서도 여러개의 repository와 retrofit, 직렬화 등 많은 개념들이 나타나게 되는데요 그 가운데서 본인만의 명확한 기준을 갖는게 중요합니다.
그러한 의미로 이번 미션이 도움이 됐었으면 했네요. 이번 미션 고생 많으셨고
마지막 미션도 파이팅입니다!

2024-05-31 13:25 UTC, merged