[쇼핑 장바구니] 채드 3, 4단계 미션 제출합니다.
woowacourse/android-shopping-cart pull request #88
Opened 2024-05-27 08:10 UTC by dpcks0509

파이로, 안녕하세요! 이번 미션이 어렵고 할게 많아서 시간이 오래걸렸네요..🥲
첫 홈화면에서 장바구니에 담긴 개수를 처음에 한번만 데이터베이스에서 가져오고,
상품상세 화면이나 장바구니에서 수량을 조절하고 다시 홈화면으로 복귀했을때에도 장바구니에 담긴 개수를 다시 데이터베이스에서 가져오지 않고 어플안에서 처리하도록 하고싶었습니다.
홈화면 내에서 수량 조절을하는 것은 데이터베이스에서 장바구니에 담긴 개수를 다시 가져오지 않아도 해결할 수 있었는데,
상품 상세화면이나 장바구니 화면에서 수량을 조절하고 다시 홈화면으로 돌아왔을때 수량이 업데이트 되지 않아
홈화면에서 onRestart함수에서 viewModel에 데이터베이스를 통해 수량을 업데이트 하는 함수를 호출해서 다시 업데이트 해주고 있습니다.
이것을 해결할 수 있는 방법이 있을까요? activityResultLauncher를 활용해서 해결해보려고 했는데1:1로 화면을 왔다갔다 하는 경우에는 가능했는데 여러화면을 거치는 경우 (홈->장바구니->상세화면->홈) 에는 제대로 정보가 업데이트가 되지않았습니다.
홈화면에서 onRestart함수에서 viewModel에 데이터베이스를 통해 수량을 업데이트 하는 함수를 호출하는 방법을 사용해도 문제가 없는것인지 궁금합니다!

2024-05-27 13:52 UTC, ghojeong requested changes
채드!
정말 구현할 내용들도 많고 요구사항도 많았는데 
포기하지 않고 미션 제출해주셔서 감사합니다.
시간이 많진 않지만 생각해볼만한 내용들 리뷰 남깁니다.

2024-05-28 17:28 UTC, dpcks0509 commented on app/src/main/java/woowacourse/shopping/data/db/recent/RecentProductRepositoryImpl.kt
> +    }
DateTimeFormatter을 이용해서 문자열 foramt 처리하였습니다!

2024-05-28 17:31 UTC, dpcks0509 commented on app/src/main/java/woowacourse/shopping/data/db/recent/RecentProductRepositoryImpl.kt
> +    }
threadAction을 삭제하고 start()를 삭제하고 join() 처리만 하도록 수정하였습니다!

2024-05-28 17:34 UTC, dpcks0509 commented on app/src/main/java/woowacourse/shopping/view/cart/CartActivity.kt
> +        adapter = CartAdapter(viewModel, viewModel)
adapter에 viewModel을 넘겨주는 것이 조금 어색하다고 느껴져서 저렇게 구현을 하였는데 adapter에 viewModel을 넘겨줘도 상관이 없군요! 수정하였습니다!

2024-05-28 17:35 UTC, dpcks0509 commented on app/src/main/java/woowacourse/shopping/view/cart/adapter/CartAdapter.kt
> +    private val quantityClickListener: QuantityClickListener,
위와 마찬가지로 viewModel을 binding하도록 수정하였습니다!

2024-05-28 17:37 UTC, dpcks0509 commented on app/src/main/java/woowacourse/shopping/view/cart/adapter/CartAdapter.kt
> +            (cartItems as MutableList)[position] = cartItem
cartItems.toMutableList()[position] = cartItem 로 수정하였습니다!

2024-05-28 17:41 UTC, dpcks0509 commented on app/src/main/java/woowacourse/shopping/view/detail/DetailViewModel.kt
> +        get() = _detailUiState
첫번째 방법은 매번 detailUiState에 접근할 때마다 _detailUiState 값을 반환하고, 두번째 방법은 detailUiState가 선언될 때 즉시 _detailUiState로 초기화됩니다.

2024-05-28 17:43 UTC, dpcks0509 commented on app/src/main/java/woowacourse/shopping/view/detail/DetailActivity.kt
> +        viewModel.updateRecentProductVisible(isMostRecentProductClicked)
버그가 존재해서 여쭤본 것은 아니었고 다른 Activity에서 HomeActivty로 돌아올때마다 onRestart()함수를 통해서 데이터베이스에 있는 정보들을 불러와서 viewModel의 값을 업데이트 해주는 방법을 사용해도 괜찮은 것인지 아니면 안좋은 방법인지 궁금해서 여쭤봤습니다! 제가 질문을 조금 이해하시기 힘들게 적어놨네용,,

2024-05-28 17:45 UTC, dpcks0509 commented on app/src/main/java/woowacourse/shopping/view/cart/adapter/CartAdapter.kt
>  ) : RecyclerView.Adapter<CartViewHolder>() {
Recyclerview 어댑터를 ListAdapter로 구현하면 데이터가 어떻게 바뀌든간에 submitList로 전체 리스트를 넘겨주기만 하면 어댑터가 알아서 백그라운드 스레드를 사용해 리스트 차이를 계산하여 화면을 갱신해줍니다. 그렇게 되면 복잡하게 어떤 아이템이 변경되었는지 계산하는 로직이 빠져서 코드가 간결해질것 같습니다! 다음 미션에는 ListAdapter를 사용해서 리팩토링 해보도록 하겠습니다!

2024-05-29 00:04 UTC, ghojeong approved these changes
채드!
저와 함께 미션 진행하시느라 고생 많으셨습니다.
다음이 벌써 레벨2의 마지막 미션인데,
완주까지 화이팅입니다! 🔥

2024-05-29 00:05 UTC, merged

2024-05-29 00:30 UTC, ghojeong commented on app/src/main/java/woowacourse/shopping/view/detail/DetailActivity.kt
> +        viewModel.updateRecentProductVisible(isMostRecentProductClicked)
> onRestart()함수를 통해서 데이터베이스에 있는 정보들을 불러와서 viewModel의 값을 업데이트 해주는 방법을 사용해도 괜찮은 것인지 아니면 안좋은 방법인지 궁금해서 여쭤봤습니다!

저는 생명주기에 대한 이해가 충분하다면 크게 문제되지는 않을 것 같다고 생각이 드는데,
혹시 채드가 안 좋을 수 있다고 생각하신 부분이 있을까요?
개선에 욕심을 내시고 계신 것 같아서, 어떤 부분을 개선하고 싶으셨던 건지 궁금하여 여쭈어봅니다.

2024-05-29 00:42 UTC, ghojeong commented on app/src/main/java/woowacourse/shopping/view/detail/DetailActivity.kt
> +        viewModel.updateRecentProductVisible(isMostRecentProductClicked)
> 장바구니에 담긴 개수를 다시 데이터베이스에서 가져오지 않고 어플안에서 처리하도록 하고싶었습니다.

혹시 onRestart 가 문제가 아니라,
데이터베이스를 통하지 않도록 개선을 하고 싶으셨던 것 일까요?