[핑구] 1, 2단계 쇼핑 장바구니 제출합니다.
woowacourse/android-shopping-cart pull request #9
Opened 2023-05-11 08:48 UTC by pingu244

안녕하세요 말리빈!
1, 2단계 쇼핑 장바구니 제출합니다.

아직 구현하지 못한 기능이 남아있습니다.
- 장바구니 화면 하단 페이지 이동 버튼 비활성화
- 장바구니 상품을 삭제했을 경우 다음 페이지의 상품을 가져오는 기능

감사합니다!

2023-05-12 00:16 UTC, malibinYun requested changes
1, 2단계 미션 고생 많으셨어요!
아직 구현하지 못한 기능들은 꼭 피드백과 함께 반영해보셨으면 좋겠어요 :)
피드백 반영 후 다시 리뷰 요청 부탁드려요!

2023-05-12 00:16 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/shopping/ShoppingActivity.kt
> +    }
기기에 따라서는 화면이 뜨기도 전에 상품 목록이 보일지도 모르겠어요.
상품 상세만 보고 앱을 종료할 수도 있을테니, 미리 그려놓는 것은 비효율적이겠지요.
모두 본 뒤 돌아왔을 때 갱신해주는 건 어떨까요?

2023-05-12 00:16 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/shopping/ShoppingPresenter.kt
> +    )
최근 본 상품 목록 데이터를 다루는 것도 Presenter에서 하고 있네요.
직접 데이터를 다루는 것은 Presenter의 일일까요?

또, 최근 본 상품목록이 하나의 모델로 묶여있어야하는 지도 고민해보세요.
데이터를 꺼낼 때는 최근 상품 목록을 꺼내지만, 꺼내온 데이터 자체는 List\<Product> 이면 어떤 장단점이 생길까요?

2023-05-12 00:16 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/shopping/ShoppingPresenter.kt
> +
메서드에는 add를 했는데, 변수에 removedProduct 라고 적혀있어서 읽는 데 혼란스러웠어요.
적절한 이름으로 변경해보세요 :)

2023-05-12 00:16 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/shopping/ShoppingRecyclerAdapter.kt
> +    fun refreshRecentViewedItems(toRemove: ProductUiModel?, toAdd: ProductUiModel) {
notifyDataSetChanged에 경고가 나타나는 이유는 무엇일까요?

2023-05-12 00:16 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/shopping/ShoppingRecyclerItemViewType.kt
> +    RECENT_VIEWED, PRODUCT;
ViewType에 대한 정보는 다른 적절한 객체에 응집도 있게 합쳐볼 수 있겠네요 :)

2023-05-12 00:16 UTC, malibinYun commented on app/src/test/java/woowacourse/shopping/ProductDetailPresenterTest.kt
> +        every { repository.insertToShoppingCart(capture(slot)) } just Runs
slot 없이도 충분히 구현할 수 있어요.
slot을 활용하지 않고 테스트 코드를 구성해보세요 :)

2023-05-12 00:17 UTC, malibinYun commented
지금 앱을 켜면 아무런 상품 정보도 불러오지 않고 빈 화면이네요!
원인이 무엇인지 고민해보고, 꼭 고쳐서 리뷰 요청해주세요 :)

2023-05-15 16:07 UTC, pingu244 commented on app/src/main/java/woowacourse/shopping/database/ShoppingDBAdapter.kt
> +    }
`setUpDB()`라는 함수는 임의로 만들어 놓은 상품 데이터를 SQLite에 저장하는 코드입니다. 최초 실행시에만 함수를 실행시켜 에뮬레이터에서 테스트를 진행하고 있습니다!

2023-05-15 16:13 UTC, pingu244 commented on app/src/main/java/woowacourse/shopping/shopping/RecentViewedLayoutViewHolder.kt
> +    }
중첩된 recyclerview의 단점은 하나씩 viewType으로 지정해줘야하기에 구현하는데 concatAdapter에 비해 복잡합니다.
반면 장점은 viewType을 사용하는 만큼 지난 영화관 미션처럼 원하는 위치에 반복적으로 화면을 바꿔 띄울 수 있습니다.
ConcatAdapter를 사용한다면 viewType을 사용하는 것에 비해서는 빠르고 간편하게 구현할 수 있지만 내부 동작이 복잡하여 이를 이해하지 못하고 사용한다면 예상치 못한 부수효과가 발생할 수 있습니다!

2023-05-15 16:14 UTC, pingu244 commented on app/src/main/java/woowacourse/shopping/shopping/ShoppingActivity.kt
> +    }
ActivityResultLauncher 를 사용하여 돌아왔을 때 갱신시켜주었습니다!

2023-05-15 16:23 UTC, pingu244 commented on app/src/main/java/woowacourse/shopping/shopping/ShoppingRecyclerAdapter.kt
> +    fun refreshRecentViewedItems(toRemove: ProductUiModel?, toAdd: ProductUiModel) {
notifyDataSetChanged는 recyclerView의 모든 데이터가(크기와 아이템 모두가) 변하는 상황에서 사용하는 함수입니다.
그렇기에 이 함수를 사용하면 모든 화면을 새로 그리는 작업을 하기 때문에 데이터의 일부만 변하는 상황이라면 지양하는 것이 좋습니다!
상황에 맞는 함수를 사용하도록 수정했습니다.

2023-05-16 15:03 UTC, malibinYun approved these changes
1, 2단계 미션 고생 많으셨어요!
다음 미션 진행을 위해 머지할게요.
피드백은 다음 미션에 반영해주세요!

2023-05-16 15:03 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/shoppingcart/ShoppingCartRecyclerAdapter.kt
> +    }
목록을 보여주는 View에서
다음 장, 이전 장 같은 도메인에 대한 관심을 가질 필요가 있을까요?
원하는 목록을 보여주기만 하게끔 변경해보는 건 어떨까요?

2023-05-16 15:03 UTC, malibinYun commented on app/src/test/java/woowacourse/shopping/ShoppingCartPresenterTest.kt
> +
기대 값을 로직으로 만들어내기보다, 하드코딩으로 만들어내서 비교해보는 것은 어떨까요?

2023-05-16 15:03 UTC, malibinYun commented on app/src/test/java/woowacourse/shopping/ShoppingPresenterTest.kt
> +        } just Runs
slot 없이 충분히 구현해볼 수 있어 보이네요!

2023-05-16 15:03 UTC, merged

2023-05-16 15:06 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/shopping/ShoppingPresenter.kt
> +    )
네 맞아요!! `최근 본 상품목록을 하나의 모델로 만들 필요성이 사라져서` 해당 내용도 해결이 된 것으로 보여요.
repository.selectRecentViewedProducts()의 반환이 List\< RecentViewedProduct> 가 아니라 List\<Product> 였으면 좋겠다는 의견이었어요 :)

2023-05-22 08:20 UTC, pingu244 commented on app/src/main/java/woowacourse/shopping/shoppingcart/ShoppingCartPresenter.kt
> +        val productsSize = repository.getShoppingCartProductsSize()
위의 코드는 한 페이지에 해당하는 상품들만 가지고 있는 변수이고 아래의 코드는 다음 페이지가 있나 없나를 검색하기 위하여 size는 쇼핑 카트에 있는 모든 상품의 개수를 반환합니다!

2023-05-22 08:21 UTC, pingu244 commented on app/src/main/java/woowacourse/shopping/shopping/ShoppingPresenter.kt
> +
repository 측에서 이 로직까지 포함하여 상품데이터를 반환하게 하였습니다.