[쇼핑 장바구니] 알송 3, 4단계 미션 제출합니다.
woowacourse/android-shopping-cart pull request #90
Opened 2024-05-27 08:16 UTC by songpink

오랜만이에요 말리빈! 3,4단계가 너무 어려워서 시간이 굉장히 오래걸렸습니다.. 😭 게다가 구현이 완벽하지 않은 부분이 몇 군데 있습니다. 상품 목록 화면에서 장바구니에 담긴 총 개수 숫자의 녹색 동그라미, 0이면 보이지 않게 하기, 마지막으로 본 상품을 선택했을 때는 마지막으로 본 상품이 보이지 않는 기능을 구현하지 못했네요.. 😥 그리고 HTTP Client도 거의 이해하지 못한 채로 사용했습니다. 리뷰에 참고 부탁드립니다!

2024-05-28 02:07 UTC, malibinYun requested changes
3, 4단계 미션 고생 많으셨어요.
원활한 다음 미션 진행을 위해 이번 미션은 이슈 위주로 다시 살펴보세요!
PR은 화~수 사이에 머지하도록 할게요 :)

2024-05-28 02:07 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/util/CommonBindingAdapters.kt
> +        }
visibility를 바인딩 어뎁터를 활용해주셨네요! 👍

2024-05-28 02:07 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/ui/cart/CartViewHolder.kt
> +    ) {
뷰홀더에 뷰모델이 꼭 필요할지 고민해보시면 좋겠네요!

2024-05-28 02:07 UTC, malibinYun commented on app/src/main/java/woowacourse/shopping/ui/cart/CartViewModel.kt
> +    private val allProducts = productDao.findAll()
지금은 dao가 메모리에서 데이터를 가져오고 있어서 이런 구조가 가능하겠지만,
나중에는 멀티 스레드환경을 꼭 고려해보세요!

2024-05-28 05:46 UTC, songpink commented on app/src/main/java/woowacourse/shopping/ui/detail/ProductDetailViewModel.kt
> +    val recentProductVisibility: LiveData<Boolean> get() = _recentProductVisibility
recentProduct를 구독하게 하면 같은 동작을 하게 할 수 있었습니다! 따로 분리한 이유는 recentProduct가 null이면 invisible, null이 아니면 visible로 설정하는것 보다 이 방법이 더욱 명시적인 것 같아서였습니다. 수정했습니다!

2024-05-28 11:52 UTC, songpink commented on app/src/main/java/woowacourse/shopping/ui/cart/CartViewModel.kt
> +        ordersRepository.insert(OrderEntity(id, _orderCounts.value!![id]!!))
시간이 부족해서.. 😅 수정했습니다! 하지만 결론적으로 Map을 사용하지 말았어야 했다는 생각이 드네요.. 😥

2024-05-29 02:19 UTC, malibinYun approved these changes
미션 수행하시느라 정말 고생 많으셨어요!
다음 레벨 2 마지막 미션도 잘 수행하시길 응원할게요 💪

2024-05-29 02:19 UTC, merged